### ISSUE TITLE
Downloading a large file needs a more prominent indication

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#101]
Try grabbing the audio from gemini://konpeito.media/konpeito-05-a.mp3  and there's no indication if the download is still happening  or not.  All you can do is try "Save" until it eventually works.

**Comment by skyjake** [comment]
The current indications are:

- the progress bar fills up and disappears
- the download size counter in the URL bar changes color
- the 🌐 changes into 🔃

<img width="743" alt="Screen Shot 2020-12-15 at 7 05 18" src="https://user-images.githubusercontent.com/1225742/102174235-a002dc00-3ea5-11eb-8a6c-c9167dbc33ce.png">
<img width="741" alt="Screen Shot 2020-12-15 at 7 05 29" src="https://user-images.githubusercontent.com/1225742/102174238-a1340900-3ea5-11eb-98f8-395412d269a7.png">

Granted, in light mode these are less noticeable changes. Are you using light mode?

Possible changes are using the URL bar background as the progress bar so it's much thicker, and doing a small animation in the stop/reload button while the request is ongoing.

**Comment by johnwcowan** [comment]
I do indeed use light mode: black print on white paper, like God and Gutenberg intended.  :-)

The progress bar and the number of bytes received use (nearly) the same color as the light-mode background of the tab, so invisible.  They should be some other color, preferably black.  I never looked at the globe before.

**Comment by skyjake** [comment]
Thicker progress bar (on retina) and an "ongoing request" spinner were added in v0.13.2.
