### ISSUE TITLE
Subscribed bookmarks in remote bookmarks don't work

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#104]
Using this file as a remote bookmark (sourceremote tagged):
```
# My remote bookmarks

## headings
=> about:version Release notes

## subscribed
=> about:version Release notes
```
Lagrange segfaults when refreshing remote bookmarks via the menu entry, and the subscribed bookmark is not marked as such in the bookmarks panel.

**Comment by skyjake** [comment]
a736f4e00d57a54f4ec1f061d8b1e284207c50b1 might fix the crash, let me know.

Remote bookmarks will have a couple of limitations in this initial implementation. For example, you can't subscribe to a remote bookmark without first making a local copy of it. I'll document these in the Help.

**Comment by jcromero** [comment]
Working fine, now. I'm also subscribing locally to my remote subscribed bookmarks, and working fine, too. Thanks.
