### ISSUE TITLE
Importing user certificates

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#105]
Hello, I wanted to try motm with lagrange:

gemini://illegaldrugs.net/cgi-bin/motm/boards

But when registering, it generates and outputs a certificate for me, that I have to use as client certificate after. It’s not clear how to do this with lagrange.

**Comment by skyjake** [comment]
Currently adding existing certificates requires some manual work. It's explained in the Help document ("Importing existing certificates").

You'll need to copy and paste the certificate and the private key into two new files. The certificate file should be named "something.crt" and the key file is "something.key". When you launch Lagrange, it checks for new files in the idents directory and adds them as Identities.

It would be great to have an automated import feature, though, for this kind of provided certificates.

**Comment by skyjake** [comment]
In v1.1 it will be as easy as pressing ⇧⌘I or Shift+Ctrl+I on the page where the certificate and key are shown. The new Import Identity dialog can also handle crt/key pasted from clipboard and drag-and-dropped files.
