### ISSUE TITLE
Patch to support finger protocol

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#106]
This patch can be applied to a7b8aa0f4fca5d42abae228430cf14b2a9feb0b6 to provide support for finger URLs (format:  finger://cosmic.voyage/latest)  There is no finger proxy support, however.

[lagrange-finger-diff.txt](https://github.com/skyjake/lagrange/files/5758636/lagrange-finger-diff.txt)

**Comment by skyjake** [comment]
Wow Finger is that simple? I'll apply some cleanup and commit this for v1.1. Thanks!

**Comment by johnwcowan** [comment]
Happy New Year!
