### ISSUE TITLE
Excessive use of memory - over 1GB of serialized state

### ISSUE THREAD

**Issue by bortzmeyer** [skyjake/lagrange#109]
On one of my Debian/Linux machines, with a Lagrange just compiled after a `git pull `:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
stephane 20323  2.8 37.0 1215832 1146444 ?     Sl   17:01   0:06 lagrange
stephane  3292  2.7  6.8 738116 211084 ?       Sl   08:36  13:57 /usr/lib/firefox-esr/firefox-esr -contentproc
```
It's a bit better on another Linux box, using Ubuntu.

```
% lagrange --version
Lagrange: A Beautiful Gemini Client
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: fr_FR.utf8
SDL init failed: No available video device

% gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% uname -a
Linux XXXX 4.19.0-13-686-pae #1 SMP Debian 4.19.160-2 (2020-11-28) i686 GNU/Linux
```

**Comment by skyjake** [comment]
The expected memory usage of Lagrange is around 60-80 MB, plus GPU textures if those is being used (total could be up to 200 MB).

Things that currently are unrestricted when it comes to memory:

* The navigation history with full gemtext sources is kept in memory. It's limited to 50 pages, but those can be arbitrarily large.
* Opened images are copied to raw RGBA textures, so they may use up plenty of memory especially if they are large. Images are not cached persistently, though.
* Audio data is also kept in memory.

Some things to check:

* What is your desktop resolution and Lagrange window size? This will affect UI buffering.
* How large are the various files in ~/.config/lagrange? (E.g., an "ls -l" of the directory.)
* CMAKE_BUILD_TYPE is Debug or Release?

**Comment by bortzmeyer** [comment]
* Resolution: 1920x1080. I typically keep Lagrange between a third and a half of the screen.
* I removed `~/.config/lagrange` and, indeed, the memory usage is *much* lower now
* I did not set `CMAKE_BUILD_TYPE` so it has the default value.

Otherwise, former content of `~/.config/lagrange`:

```
~/.config % ls -lth lagrange.old 
total 1.1G
-rw-r--r-- 1 stephane stephane 6.1K Jan  5 08:40 visited.txt
-rw-r--r-- 1 stephane stephane    8 Jan  4 22:15 idents.binary
-rw-r--r-- 1 stephane stephane    0 Jan  4 22:15 bookmarks.txt
-rw-r--r-- 1 stephane stephane  233 Jan  4 22:15 bindings.txt
-rw-r--r-- 1 stephane stephane  704 Jan  4 22:15 prefs.cfg
-rw-r--r-- 1 stephane stephane 1.1G Jan  4 22:15 state.binary
-rw-r--r-- 1 stephane stephane 2.0K Jan  2 20:36 trusted.txt
drwxr-xr-x 2 stephane stephane 4.0K Dec  7 13:22 idents
```

I assume the large `state.binary` is responsible. Lack of garbage collecting?

**Comment by skyjake** [comment]
> I assume the large state.binary is responsible.

Yeah that's the culprit here. I'll add some diagnostics to "about:debug" to track what's going into state.binary and see what kind of limits are required here.

Did you have a large number of tabs open? Each tab has its own navigation history, so that may have contributed to the issue.

> Resolution: 1920x1080. I typically keep Lagrange between a third and a half of the screen.

This rules out any issues with large view buffers.

> CMAKE_BUILD_TYPE

I believe the default for a git checkout is Debug; you should check that. Although running a debug build will mostly affect performance and not memory use.

**Comment by bortzmeyer** [comment]
I had typically three or four tabs open, not more.

**Comment by skyjake** [comment]
I will add a preference for limiting the cache size.
