### ISSUE TITLE
Lagrange window rendering flaky when switching viewports

### ISSUE THREAD

**Issue by karthanistyr** [skyjake/lagrange#11]
**Issue:**
When the lagrange window is exposed, the window manager only shows the decoration, not the contents of the window.

In this video (https://video.barbed.fr/videos/watch/491a9b10-b3db-4107-aa61-5ff07272a28a), I jump between viewports 3 and 4 (Lagrange is on viewport 3). When the correct viewport is displayed, the Lagrange window does not render until I hover the mouse cursor over its location.

**Expected behaviour:**
I would expect the Lagrange window to always render when the viewport it resides in is displayed.

**Platform:**
Arch Linux x64
window manager: dwm (https://dwm.suckless.org/)

**Lagrange version:**
Self-compiled, 0.6 (commit: bcca576f0463df67378ece8712dc0941c67f0c9e)

**Comment by skyjake** [comment]
As with #10, this is SDL behavior. When it determines that the window is exposed and visible the window will be drawn. I'm actually not sure if there is anything that can be done here... I'll have to install dwm myself and run some tests.

**Comment by karthanistyr** [comment]
Also replicated on openbox (non tiling wm)
https://video.barbed.fr/videos/watch/58df4716-b6e3-4797-9036-f331834e5e78

The window does not render when the viewport it resides in is displayed -- only when the mouse hovers over the window.

**Comment by skyjake** [comment]
Does it make a difference if you launch lagrange with the `--sw` option? That would force the use of SDL's software rendering, but it may already be defaulting to that depending on your video driver situation.

**Comment by karthanistyr** [comment]
I narrowed it down to this bit, which is disabled by a precomp switch: 
https://github.com/skyjake/lagrange/blob/0057c015316e4adf79ae6864fb0db0c335372a61/src/ui/window.c#L629-L638
When going back to the viewport where the lagrange window lives, it receives at the very minimum a `SDL_WINDOWEVENT_EXPOSED` event, which is its opportunity to handle and redraw as needed.

For example, this very naive patch fixed the redrawing problem by calling a redraw upon `SDL_WINDOWEVENT_EXPOSED`
```patch
From 2147c197cc5fa8939dfaf4524e679e68d592086b Mon Sep 17 00:00:00 2001
From: Antoine Mazeas <antoine@karthanis.net>
Date: Sun, 25 Oct 2020 16:50:08 +0100
Subject: [PATCH] Handle SDL_WINDOWEVENT_EXPOSED to redraw upon viewport switch

Signed-off-by: Antoine Mazeas <antoine@karthanis.net>
---
 src/ui/window.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/src/ui/window.c b/src/ui/window.c
index c5194ea..343ebd9 100644
--- a/src/ui/window.c
+++ b/src/ui/window.c
@@ -663,6 +663,9 @@ static iBool handleWindowEvent_Window_(iWindow *d, const SDL_WindowEvent *ev) {
             d->isMouseInside = iTrue;
             postCommand_App("window.mouse.entered");
             return iTrue;
+        case SDL_WINDOWEVENT_EXPOSED:
+            draw_Window(d);
+            return iTrue;
         default:
             break;
     }
--
2.29.0
```
I'm not familiar with the reason why this event was chosen to be left unhandled, or if there is a chance that it is patched in to allow redrawing as needed?

**Comment by karthanistyr** [comment]
> Does it make a difference if you launch lagrange with the `--sw` option? That would force the use of SDL's software rendering, but it may already be defaulting to that depending on your video driver situation.

**Comment by skyjake** [comment]
I believe you have found the culprit. The expose event should be followed up with a redraw, and it is an oversight that it doesn't happen currently. I think that on many other platforms/window managers the compositor has a buffered copy of the window contents so they can be restored from memory automatically, but in the case of dwm/openbox the application is responsible for redrawing the missing parts.

Thanks for investigating! I'll commit a suitable fix.

**Comment by karthanistyr** [comment]
Happy to help
