### ISSUE TITLE
Build failure in linux

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#110]
Failed to build:
```
$ cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local
... <snipped> ...
/home/jcromero/src/lagrange/res/bincat.sh: 13: Syntax error: "(" unexpected (expecting "fi")
... <snipped> ...
```

**Comment by skyjake** [comment]
This is my new bincat.sh script that isn't as portable as it should. I'll disable it by default, but you can do so manually with CMake option `-DENABLE_BINCAT_SH=NO`.

**Comment by jcromero** [comment]
OK, will do.

Thanks.

**Comment by jcromero** [comment]
Working now.

**Comment by jcromero** [comment]
I'm using debian bullseye, and `sh` points to `/usr/bin/dash`

Nevertheless, if I use `bash` instead, I get the same error.

**Comment by skyjake** [comment]
It tries to use an array of values, but there's probably another way to extract the fifth field on a line (e.g., sed).

**Comment by jcromero** [comment]
Yes, I know your are trying to use an array. But it surprised me that `bash` also produces an error, and I was blowing my mind trying to guess what's wrong. I, still, don't understand what's happening in `bash`.

**Comment by skyjake** [comment]
There's an updated version of bincat.sh in the dev branch, using /bin/bash now. It works for me on Ubuntu at least.

**Comment by jcromero** [comment]
It works also in Debian. Thanks.
