### ISSUE TITLE
Two links assigned to letter U, and unfollow-able links

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#111]
When I open a page with a lot of links (e.g. gopher://republic.circumlunar.space:70/1/~katolaz/phlog/) and hit `f` to follow a link, there are some links that are not follow-able, because there are more links than letters. And, the letter `U` is assigned to two links, instead of one.

**Comment by skyjake** [comment]
Some sort of extension system is needed when it runs out of letters. Perhaps the easiest to implement would be to use the final letter to renumber the links starting after the last previously numbered link.
