### ISSUE TITLE
Percent-encoding when copying URL to clipboard

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#112]
As spaces are shown as spaces in the address bar, if I copy paste from my address bar to a gemini post I’m doing, I get a broken link.

I’m not sure if it should be the default behavior to copy with %20 instead of spaces or if that should be an option.

**Comment by skyjake** [comment]
I'll make it so that it converts spaces to %20 when copying from navbar to the clipboard. (in v1.0.3)

I'll also add an option to fully percent-encode the URL when copying to clipboard (off by default).

**Comment by MCMic** [comment]
Thanks!

I just checked, Firefox does this, it shows spaces but copies to %20.

**Comment by skyjake** [comment]
v1.0.3 wil include fix for percent-encoding spaces when copying to clipboard.
