### ISSUE TITLE
Strips brackets from feed title

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#114]
I think this is some kind of heuristic gone wrong, but my last gemlog post from gemini://gemlog.lanterne.chilliet.eu/ named "[gams-en]GAMS-board-system.en.gmi" appears in the feed panel as "gams-en]GAMS-board-system.en.gmi".

**Comment by skyjake** [comment]
Here's the problem: https://github.com/skyjake/lagrange/blob/4c92e0c975fbb6df7cf3a560b43e7f0d0728dec7/src/feeds.c#L173

Any punctuation is currently considered strippable. I suppose parentheses and brackets should be excluded here.
