### ISSUE TITLE
F5 to reload, middle click to close

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#115]
Hello,

There are two shortcuts which I’m really used to from web browsers and missing in lagrange:
- F5 reloads the page (same as ctrl+R)
- Middle click to close tabs

**Comment by skyjake** [comment]
> Middle click to close tabs

Where do you middle click for this? (I don't use regular mice that much myself.)

**Comment by MCMic** [comment]
On the tab «header». The same place you left-click to switch to a tab.
