### ISSUE TITLE
Reload certain gemini pages on a schedule

### ISSUE THREAD

**Issue by lupine** [skyjake/lagrange#116]
Hi,

I love lagrange - it's my main browser on desktop. There is one feature I'd love to have though, which is to automatically refresh a given tab every (minute, hour, day). 

The use case for this is any "live"-style page, where the content changes regularly. gemini://astrobotany.mozz.us/app/plant is an obvious candidate, but it would be just as useful for utilitarian status views, CI/CD radiators, river level gauges (I'm watching https://riverlevels.uk/brompton-beck-brompton closely over HTTP at the moment, and manually refreshing that is a pain in firefox ^^), etc.

Is this something you see as fitting within lagrange?

**Comment by skyjake** [comment]
Yeah I agree this could be a useful feature.

One way to implement this would be to add a special bookmark tag that specifies the refresh interval. That way it wouldn't be necessary to introduce any new tab-specific options, and the refresh setting would be automatically persistent.

Does that sound acceptable? I could still add a context menu option for easily applying the tag.

The downside is that there would be more bookmarks, one for each auto-refreshed page, but the bookmark list UI is due some revising anyway.

**Comment by lupine** [comment]
Thanks for the reply!

Personally, I tend not to use bookmarks normally, but it sounds workable. In my head, I had a general idea of adding a subcontext menu to the current "Reload page" option that would allow you to select "now", a repeating interval, or to cancel the reload, but I'd use whatever it ended up being gladly :).

**Comment by skyjake** [comment]
I decided against using bookmark tagging for this. Now there's a "Set Auto-Reload..." item in the page context menu, and the setting is remembered for the tab while it remains open. Each tab has its own auto-reload interval. The intervals are saved persistently with the rest of the tab state.
