### ISSUE TITLE
Null pointer dereferencing when processing invalid Unicode sequence

### ISSUE THREAD

**Issue by Br0000k** [skyjake/lagrange#117]
lagrange deferences a null pointer when attempting to process an invalid Unicode sequence (such as \xff\xff\x00\x00) on a Gemini page, thus crashing.

This is the GDB output.

`Thread 1 "lagrange" received signal SIGSEGV, Segmentation fault.`
`0x000055555560644b in trimEnd_Rangecc (d=0x7fffffffd2e0)`
`        at /home/[omitted]/lagrange/lib/the_Foundation/src/string.c:317`
`317                      if (d->end[-1] == 0) {`

u8_prev seems to return NULL when there's an invalid Unicode sequence.

I have made a fix that can go after the isSpace_Char function on line 323 of lib/the_Foundation/src/string.c
    `if (pos == NULL)`
    `    d->end--; else`

I decrement d->end because the last Unicode char is the last ASCII char when an invalid sequence is present.

**Comment by skyjake** [comment]
Could you attach a test .gmi file that shows the problem? I couldn't reproduce the crash.

**Comment by Br0000k** [comment]
You just need to do `echo -e -n '\xff\xff\x00\x00' > test.gmi` or something like that. But my concerns is that someone could use this to crash a user's client (which we don't want obviously). Thank you for patching it btw :)

**Comment by skyjake** [comment]
Thanks that does reproduce the crash.

I suppose it would be good to just refuse to show any UTF-8 content that contains invalid sequences... Could just show an error page instead.

**Comment by Br0000k** [comment]
I think it's perfect how it is :) The Gemini spec mandates that clients be able to handle UTF-8 text but it doesn't say how to handle invalid sequences. Hopefully it will in the future - might comment on this in the project's mailing list.
