### ISSUE TITLE
lagrange aborts when typing non-Latin characters in address bar

### ISSUE THREAD

**Issue by Br0000k** [skyjake/lagrange#119]
When I go to type non-Latin characters in the address bar with another keyboard layout (Hebrew, Russian, etc), lagrange seems to just abort.

Here's the GDB output.
`lagrange: /home/[omitted]/lagrange/src/ui/lookupwidget.c:338: worker_LookupWidget_: Assertion '!isEmpty_String(pattern)' failed.`
`Thread 8 "lagrange" received signal SIGABRT, Aborted.`
`[Switching to Thread 0x7fffc7fff700 (LWP 4119)]`
`__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50`
`50 ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.`

Btw I've never contributed to open source before so apologies if I make any annoying mistakes. This is the first project I've contributed to! :)

**Comment by Br0000k** [comment]
Thank you for checking out my issues. Btw, is Codeberg where I can do pull requests to the_Foundation?

**Comment by skyjake** [comment]
Yes, Codeberg is the only place where PRs are open for the_Foundation at the moment.

If it's a small change you can just email me the Git commit, though.

**Comment by skyjake** [comment]
I just checked and the PRs actually weren't enabled on Codeberg, sorry. Now they are: https://codeberg.org/skyjake/the_Foundation/pulls

**Comment by Br0000k** [comment]
Thank you :) I might check out Codeberg in the future.
