### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [skyjake/lagrange#120]
### Preamble
Several days ago I first discovered [Gemini](https://gemini.circumlunar.space/) [protocol](https://en.wikipedia.org/wiki/Gemini_(protocol)) and even though I was not at home on my computer and could not do some tests at the moment I had a look at [Gemini clients](https://gemini.circumlunar.space/clients.html) on my phone and [Lagrange](https://gmi.skyjake.fi/lagrange/) client immediately caught my attention- neat, light and clean website, cross platform, open source  and native program in active development, written in nice language (C), helpful and responsive developer (I had a look at [Issues](https://github.com/skyjake/lagrange/issues)) so I bookmarked it for testing. A couple of days ago I found time to test the program and my expectations were confirmed- tiny executable (as of [version](https://github.com/skyjake/lagrange/releases) [1.0.3](https://github.com/skyjake/lagrange/releases/tag/v1.0.3) it is only 898 KB), clean, nice, skinnable GUI, moderate resource usage, decent set of configuration options. Although I am not a programmer I can appreciate well-written programs and [Lagrange](https://github.com/skyjake/lagrange) turned out to be a niece piece of software. Although that for the time being I don't have a great use of Gemini protocol (I don't own a Gemini site) I will keep using and testing **Lagrange** and I may open several new issues aimed at further improvement of this promising Gemini client. My first suggestion will be a request for option to run the program in portable mode.

### Request
Currently (as of version [1.0.3](https://github.com/skyjake/lagrange/releases/tag/v1.0.3)) **Lagrange** saves its configuration and data files (<code>idents.binary</code>, <code>state.binary</code>, <code>prefs.cfg</code>, <code>bindings.txt</code>, <code>bookmarks.txt</code>, <code>trusted.txt</code>, <code>visited.txt</code> files plus <code>idents</code> sub-folder) in AppData:

<code>C:\Users\User\AppData\Roaming\fi.skyjake.Lagrange</code>

I would appreciate if there is a way to save all program data in program folder (next to the executable- <code>lagrange.exe</code>), which will mean that the user would be able to move the program from machine to machine witb all its data saved in its program folder without the need to copy data from AppData.

Portability can be implemented in different ways, I will provide several examples below:

1. **command-line argument** - if **lagrange.exe** is started with a specific parameter, for example `lagrange.exe -portable`, data is saved in program folder, not in AppData;
2. **portable version** - separate portable version- the program is packed in archive, the user extracts the archive and runs the executable, data is saved in in program folder, not in AppData;
3. **portable flag** - specific file in program folder (for example `portable` without extension or `portable.txt`) triggers portable mode, when **Lagrange** starts it checks program folder for such file and if it is there data is saved in program folder, not in AppData;
4. **configuration file** - when **Lagrange** starts it checks program folder for a configuration file (<code>prefs.cfg</code>) and if it is there the program saves data in program folder, not in AppData;
5. **special sub-folder** - when **Lagrange** starts it checks program folder for a special sub-folder (for example `Data` or `Settings` or <code>Lagrange</code>) and if it is there it saves data in this sub-folder, not in AppData;
6. **executable name** - if the executable is renamed from `lagrange.exe` to `lagrange.-portable.exe` the program starts in portable mode, data is saved in program folder, not in Appdata;
7. **option in preferences** - new check box- `Portable Mode`, which, if selected, forces the program to save data in program folder, not in AppData;
8. **portable installation** - when the program is installed beside normal installation it offers also portable installation (extraction), which just extracts the files to a folder specified by the user and data is saved in program folder, not in AppData;

There may be other ways of triggering portable mode but I suppose the ones I suggested above are the most common ones. I prefer methods **2**, **3**, **4** and **5** but any of them would do once **Lagrange** can save data to program folder and load data from program folder.

### Advantage
I think that portable programs (or programs that can be run in portable mode) have several advantages:

- **mobility** - portable programs can be easily transferred from machine to machine with all their data;
- **backup** - portable programs are easy to back up to external drives or to cloud services (in case one needs to re-install OS);
- **testing** - portable programs facilitate testing- one can test different versions (stable, alpha, beta) with different settings;

So I will be glad if you consider implementing portable mode for **Lagrange** in future releases. I believe that if there is portable version of **Lagrange** (or it can run in portable mode) that would add more flexibility to this already quite promising Gemini client.

### Postamble
I can see that **Lagrange** is being developed with aesthetics, elegance, usability and clean programming in mind and for someone who is tottaly fed up with Java, .NET and especially JavaScript/Electron monstrisities your Gemini client is a real gem. So I would be glad if I can contribute to the development of **Lagrange** with ideas for possible enhancements in future releases.

**Comment by skyjake** [comment]
Thanks for the well-written feature request! I think this could indeed be a useful feature. I'm leaning towards option 5, the special subfolder, since that seems simple to implement and also easy for the user to set up.

I think a separate "portable ZIP" distribution package with the special subfolder already included would be the best option.

**Comment by smaragdus** [comment]
@skyjake 

Thank you for your extremely quick response! Actually I didn't install the program, I just extracted it (using [Universal Extractor 2](https://bioruebe.com/dev/uniextract/), [GitHub](https://github.com/Bioruebe/UniExtract2)) as I am a bit allergic to installers.

> I think a separate "portable ZIP" distribution package with the special subfolder already included would be the best option.

I totally agree.

Keep up your excellent work! I may come up with some more ideas in the future.

Best regards

**Comment by smaragdus** [comment]
@skyjake 

I tested version [1.1.2](https://github.com/skyjake/lagrange/releases/tag/v1.1.2) and contrary to this statement:

> The portable ZIP can be extracted anywhere and run as-is — user files are stored under the userdata subdirectory.

it still insists on using AppData (`C:\Users\User\AppData\Roaming\fi.skyjake.Lagrange`). Moving the data from AppData to `userdata` and deleting AppData folder results in re-creation of AppData folder and `userdata` sub-folder  is not used at all.

I suppose that you are aware of this yet I decided to report the problem.

Anyway, thank you for the new version ([1.1.2](https://github.com/skyjake/lagrange/releases/tag/v1.1.2)) and for all your great work in maintaining and improving this great project!

**Comment by skyjake** [comment]
Apologies, I forgot to include the commit that actually implements the _userdata_ check in the release branch. 😬

I removed the incorrect description from the release page and will do a another build with this feature included.

**Comment by smaragdus** [comment]
No problem at all, thanks for the express response!

**Comment by skyjake** [comment]
Available now: https://github.com/skyjake/lagrange/releases/tag/v1.1.3

**Comment by smaragdus** [comment]
@skyjake 

I have just checked version [1.1.3](https://github.com/skyjake/lagrange/releases/tag/v1.1.3) and I can confirm that the portable version of [Lagrange](https://gmi.skyjake.fi/lagrange/) is fully and truly portable as it does not write any data outside its own program folder. Cutting the data files from `AppData` folder into `userdata` sub-folder was just enough to have all my data in program folder, I am emphasizing this because it is a common misbehaviour of some portable programs which, although saving program data in program folder also create an empty folder in `AppData`, this is not the case with [Lagrange](https://github.com/skyjake/lagrange). So I am very pleased to conlude- with version [1.1.3](https://github.com/skyjake/lagrange/releases/tag/v1.1.3) **Lagrange is beautifully portable!**

Many thanks for your excellent work!
