### ISSUE TITLE
Binding key to 'close tab'

### ISSUE THREAD

**Issue by jonhiggs** [skyjake/lagrange#121]
I would like to bind a keystroke to close a tab but that option seems to be missing.

**Comment by Br0000k** [comment]
Do you want keystroke binding in general or just 'close tab'?

**Comment by Br0000k** [comment]
I have included a commit in my pull request that adds this option.

**Comment by jonhiggs** [comment]
I don't need anything special. If I can make cmd-d close a tab, I'll be super happy. :)

**Comment by skyjake** [comment]
> I don't need anything special. If I can make cmd-d close a tab, I'll be super happy. :)

You'll first need to unbind Cmd-D from "Add bookmark", but this is now possible in the dev branch.
