### ISSUE TITLE
Set recommended TLS cipher suites

### ISSUE THREAD

**Issue by Br0000k** [skyjake/lagrange#122]
Project Gemimi's best practices for implementations seems to recommend (for TLS 1.2) using only Ephemeral Diffie-Hellman (DHE) or Ephemeral Elliptic Curve Diffie-Hellman (ECDHE) for key agreement, AES or Chacha20 as bulk ciphers (which is already the default), and SHA2 or SHA3 hash functions.

I've also restricted the cipher suites to GCM only as the IANA TLS Parameters doesn't seem to recommend CBC ciphers.

The following code might be worth adding in the init_Context function on lib/the_Foundation/src/tlsrequest.c after line 64 or 65.

`SSL_CTX_set_cipher_list(d->ctx, "ECDHE-ECDSA-AES256-GCM-SHA384:"`
`                                                      "ECDHE-ECDSA-CHACHA20-POLY1305:"`
`                                                      "ECDHE-ECDSA-AES128-GCM-SHA256:"`
`                                                      "ECDHE-RSA-AES256-GCM-SHA384:"`
`                                                      "ECDHE-RSA-CHACHA20-POLY1305:"`
`                                                      "ECDHE-RSA-AES128-GCM-SHA256");`

**Comment by skyjake** [comment]
I don't think hardcoding these to TlsRequest is the best way to go, but I can add a `setCiphers_TlsRequest()` method to set these from the application side.

**Comment by Br0000k** [comment]
I think they should be the defaults. Perhaps there should be a option to let the user choose if they want to accept weak or insecure cipher suites? It's very easy for configuration to go wrong (I think that's why we have TLS 1.3), and most Gemini servers probably won't use the outdated ciphers.
