### ISSUE TITLE
Full Screen Mode

### ISSUE THREAD

**Issue by smaragdus** [skyjake/lagrange#130]
I checked `Preferences - Keys` and I didn't find keyboard shortcut for full screen mode so I presume that as of version [1.1.0](https://github.com/skyjake/lagrange/releases/tag/v1.1.0) [Lagrange](https://gmi.skyjake.fi/lagrange/) does not support full screen mode, which is a common feature for browsers and text editors. Since Gemini protocol is mostly text-oriented I suppose that if full screen mode is implemented it will facilitate distraction-free reading. I think that `F11` is a common shortcut key for toggling full csreen mode on/off.

**Comment by skyjake** [comment]
This is correct, there is no fullscreen feature at the moment.

On macOS, though, SDL implements the Ctrl-Cmd-F shortcut, so fullscreen mode can be toggled on. The fullscreen state will not get restored on relaunch since it isn't saved at any point.

**Comment by smaragdus** [comment]
@skyjake 

> The fullscreen state will not get restored on relaunch since it isn't saved at any point.

To my knowledge beside games there are only some text editors that operate exclusively in full screen mode that are intended to start in full screen mode. I don't see a real use of a browser starting in full screen mode. Also, terminating a program running in full screen mode requires invoking a task manager. So for me there is no need at all for Lagrange to remember full screen mode state after restart.

**Comment by skyjake** [comment]
> I don't see a real use of a browser starting in full screen mode.

Yeah you're right, restoring back to fullscreen mode doesn't seem all that useful.

I've added a keybinding for toggling fullscreen mode. The fullscreen state is not saved at exit. Still have to test that it doesn't conflict with the window pos/size retaining feature.

**Comment by smaragdus** [comment]
By the way I noticed that **Lagrange** supports keyboard shortcut for exit (`CTRL+Q`), initially I was looking in `Preferences - Keys` but I found out that the shortcut was listed under the hamburger menu. This means that the user would be able to quit the program directly from full screen mode without the use of task manager.

**Comment by skyjake** [comment]
> This means that the user would be able to quit the program directly from full screen mode without the use of task manager.

I think the user should always be able to quit the app with the appropriate keyboard shortcut. Are you suggesting there should be a "kiosk" fullscreen mode that would disable quitting altogether?

**Comment by smaragdus** [comment]
> Are you suggesting there should be a "kiosk" fullscreen mode that would disable quitting altogether?

In short- no. I don't see any point in this. It is just that I failed to notice the exit keyboard shortcut initially because I was checking the keys in preferences, not the hamburger menu (which obviously replaces the menu bar and all its commands).

**Comment by smaragdus** [comment]
Thanks for adding full screen mode.

However I think that there may be a bug in using full screen mode (at least on Windows).

Steps to reproduce:

1. Start **Lagrange** in non-maximized state;
2. Click **Maximize** button in the title bar;
3. Enter **Full Screen Mode** (**F11**);
4. Exit **Full Screen Mode** (**F11**);
5. Click **Restore Down** button in the title bar;
6. The previous not-maximized state (with which **Lagrange** has started) is not restored;

Can you confirm this?

When full screen mode is invoked from non-maximized state of the program window the problem does not appear.

**Comment by skyjake** [comment]
Have you enabled the Custom Frame setting? The behavior is different depending on this option.

**Comment by smaragdus** [comment]
`Custom window frame` was set to `NO`.

**Comment by skyjake** [comment]
I've spent little time in Windows recently, but after a brief test I could not reproduce this behavior according to your steps (Windows 10).

Do you happen to use multiple monitors, or a laptop with an external monitor?

**Comment by smaragdus** [comment]
@skyjake 

> Do you happen to use multiple monitors, or a laptop with an external monitor?

No, I use single monitor.
