### ISSUE TITLE
Identity: invalid expiration date

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#131]
### Steps to reproduce
1. `New identity...`
2. Set `Valid until` to "2021-06-30 00:00:00"
3. Set `Common name`
4. `Create identity`

![scr0](https://user-images.githubusercontent.com/688044/106526520-d5679580-64f6-11eb-9b59-04822fe59376.jpg)

### Actual behaviour
`Expiration date must be in the future`:
![scr1](https://user-images.githubusercontent.com/688044/106526529-d7c9ef80-64f6-11eb-950f-c469e1b95cfa.jpg)

### Configuration
Lagrange 1.1.0

**Comment by skyjake** [comment]
I cannot reproduce this. Which OS are you running? Does `2021-06-30` work as expected?

**Comment by sikmir** [comment]
> Which OS are you running?

Linux (NixOS).

> Does 2021-06-30 work as expected?

No, the same issue.

And I've just tried to enter "2019-06-30" and I got:
`Please check the "Valid until" date. Examples: ...`
instead of
`Expiration date must be in the future`.

**Comment by skyjake** [comment]
Hmm, I made a few changes to the input widget that may affect this issue. If possible, please test with 6d885dee5e3a9fc7316c901542eec21e39ae1f12 or later (the_Foundation submodule updated as well).

**Comment by sikmir** [comment]
It works now, thanks!
