### ISSUE TITLE
Submit this app to FlatHub

### ISSUE THREAD

**Issue by rany2** [skyjake/lagrange#132]
Hi, I've made a flatpak package for this app. Is it fine for me to submit this package to flathub?

The app ID would be `fi.skyjake.lagrange` which is more appropriate. https://github.com/rany2/flathub/tree/com.github.skyjake.lagrange

**Comment by skyjake** [comment]
Already working on it: https://github.com/flathub/flathub/pull/2090 😊

There are a few minor tweaks to apply to comply with Flathub rules.

**Comment by rany2** [comment]
Perfect. Sorry I didn't check :)
