### ISSUE TITLE
Advanced text selection

### ISSUE THREAD

**Issue by Zwatotem** [skyjake/lagrange#134]
Many existing programs including web browsers incorporate this selection model:

- [x] Click and hold, then drag around to select text from the exact point of your first click.
- [x] Double click to select a single word. Hold your second click and drag around to select whole words at once. Some programs pick trailing spaces, but let you unselect them, by draging back.
- [x] Triple click to select a paragraph. Hold your third click and drag around to select whole paragraphs. For preformatted blocks it could be just lines.

Lagrange currently implements just the first one, but I think it would be cool, if it did all three. I use this fairly often, to follow the text better, but obvously the primary usecase is time-efficient copy-pasting 😄

**Comment by skyjake** [comment]
I agree on the usefulness, and actually have this on my to-do list. It has fallen pretty far down the list, though, with more important things having taken priority. Maybe it's now time to implement this..
