### ISSUE TITLE
Opening Help & Release Notes

### ISSUE THREAD

**Issue by smaragdus** [skyjake/lagrange#136]
I noticed that when I open `Help` and `Release Notes` from hamburger menu **Lagrange** opens them in the currently active tab. I think that it would be more logical if `Help` and `Release Notes` open in new tabs, this way the possibility of losing an open tab by user's negligence would be diminished. What do you think?

**Comment by skyjake** [comment]
Hmm, this could be a nice little usability improvement, although I think it requires a minor tweak so only one Help tab is opened if you press F1 multiple times.

**Comment by smaragdus** [comment]
@skyjake 

> I think it requires a minor tweak so only one Help tab is opened if you press F1 multiple times.

For me it won't be an issue if I open several instances of `Help`. Yet if it is worth the effort to make such a tweak I suggest the following:

- if one instance of `Help` is already open but it is not the active tab  hitting F1 again would result in bringing the already open `Help` tab to front;

If such a tweak is not worth the effort just discard it.

**Comment by skyjake** [comment]
This has been implemented in a recent release.
