### ISSUE TITLE
Launching lagrange messes up latte dock

### ISSUE THREAD

**Issue by dquark** [skyjake/lagrange#137]
I'm using latte dock with manjaro kde, when I run lagrange 1.1.0-1 from AUR, the transparency of dock changes and makes it look like some sort of wood texture (screenshots below). Even after changing an icon of lagrange, the issue still exists.

Screenshots of how it looks like:
![Zrzut ekranu z 2021-02-03 23 18 12](https://user-images.githubusercontent.com/30926205/106816972-7cbf0680-6676-11eb-8dad-1a7e36bd0de4.png)
![Zrzut ekranu z 2021-02-03 23 18 26](https://user-images.githubusercontent.com/30926205/106816979-7e88ca00-6676-11eb-96ca-b3939a7c349f.png)

**Comment by skyjake** [comment]
Does launching Lagrange with the `--sw` option affect this? That will force the UI to use software rendering only.

**Comment by dquark** [comment]
> Does launching Lagrange with the `--sw` option affect this? That will force the UI to use software rendering only.

It doesn't appear to change anything.

**Comment by skyjake** [comment]
Hmm, I can't really think of anything that Lagrange does that could cause an issue like this.

Have you noticed a similar issue with other SDL based apps, perhaps a game of some kind?

**Comment by dquark** [comment]
> Hmm, I can't really think of anything that Lagrange does that could cause an issue like this.
> 
> Have you noticed a similar issue with other SDL based apps, perhaps a game of some kind?

Unfortunately I'm not aware what SDL is, could you tell me it's full name or give me an example of an app I can use to answer your question? I don't play any games on this computer, at least so far I didn't.

**Comment by skyjake** [comment]
Here is a list of games that use the SDL library (Simple DirectMedia Layer): https://en.wikipedia.org/wiki/List_of_games_using_SDL

To keep things light and portable, Lagrange has been implemented on top of SDL without the use of any existing UI toolkits like GTK (GNOME) or Qt (KDE). This makes it akin to a game from a software implementation point of view.

It is conceivable that glitches in graphics drivers underpinning the window system may result in image content of other apps being messed up when one app is drawing low-level graphics.

Unfortunately there isn't much more I can do here to help you, so I'm closing this issue. We can revisit this if other people report similar problems.

**Comment by skyjake** [comment]
This could help: https://github.com/skyjake/lagrange/issues/160#issuecomment-784965285
