### ISSUE TITLE
Everything is VERY BIG with this commit: 5dac1beb

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#139]
![Screenshot_20210206_002424](https://user-images.githubusercontent.com/984714/107099391-d0b22280-6811-11eb-95d9-0fb1d495d0fa.png)
Reverting the 5dac1beb7bd29604142988961d69ac2c17be1f86 commit I get again a "decent" size.

**Comment by skyjake** [comment]
How's your "UI scale factor" value in Preferences > Window? I think the default has been 1.1, but now with this DPI check looks like you can reduce that to 0.8 or thereabouts. The best value depends on both the monitor DPI and your average viewing distance.

You'll need to restart Lagrange for a new UI scale factor to take effect.

Checking the DPI is necessary to support monitors with different pixel densities.

**Comment by jcromero** [comment]
My UI scale factor was 1.1, I haven't changed it.  I have reduced it to 0.7, and now the size is ok again. FWIW, my screen has a 1920x1080 resolution (it's a typical 15.6 inches laptop screen) . I tried previously to modify this scale factor, but I didn't restart the application, so I didn't observe any change.

Thanks for the instructions.

**Comment by skyjake** [comment]
I don't think there is anything to fix here as the behavior is intended, so I'm closing this. Of course, if the DPI value is for any reason incorrectly reported by the system you may get unexpected scaling as result, but I'm trusting SDL's ability to determine the DPI reliably.

**Comment by jcromero** [comment]
Yes @skyjake , you are right. I closed the issue by error, so I reopened it for you to close.

Thanks.
