### ISSUE TITLE
Possibility to change the home page

### ISSUE THREAD

**Issue by yannicka** [skyjake/lagrange#141]
Currently the home page is "about:lagrange", and I don't see any way to change that. It would be nice to have an option to change that.

**Comment by skyjake** [comment]
Check out the Help document:

> 1.4.3 Special tags
>
> * Set a "homepage" tag on a bookmark to make it one of the pages that will be opened when pressing the 🏠 button. If multiple bookmarks are tagged as homepages, a random one is selected.

**Comment by skyjake** [comment]
You can also right-click on a bookmark in the Bookmarks list to do this.
