### ISSUE TITLE
Input query string applied to current tab when opening a new tab

### ISSUE THREAD

**Issue by 0v3rCl0kEd** [skyjake/lagrange#142]
If you open a new tab from your bookmarks and you need to provide input the query is going to be applied to your current tab, not the new tab.

Example: If I am on gemini://gemini.circumlunar.space/ and I open gemini://vault.tansjovian.org/(wikipedia) in a new tab with Ctrl+Click inside the bookmark bar I get a query prompt and whatever I type is applied to the current tab(you can see it in the url) instead of the tab you just opened.

**Comment by skyjake** [comment]
Indeed, the way it's dealing with input prompts is a bit buggy. I'm also getting big black bars (invalidated document content) on the current page when I'm opening a search prompt via bookmarks.

Will fix.
