### ISSUE TITLE
Re-arranging tabs via drag&drop

### ISSUE THREAD

**Issue by smaragdus** [skyjake/lagrange#143]
As all modern web browsers support re-arrangement of tabs via drag&drop I suppose that it would be handy if Lagrange supports this common feature.

**Comment by skyjake** [comment]
We have issue #59 for tab reordering.

Although I have to say, I can't recall any situation where I would've needed to reorder tabs. Do you have a use case where you commonly do this?

**Comment by smaragdus** [comment]
@skyjake 

First I need to apologize for opening a duplicate issue (of #59) as I didn't check the already open ones.

> Although I have to say, I can't recall any situation where I would've needed to reorder tabs. Do you have a use case where you commonly do this?

I can only speak of my habits while using browsers- I prefer to have a single window with many tabs in stead of multiple windows and as I open many tabs I oftentimes re-arrange these tabs according to research topic for example- tabs from 1 to 10- history, tabs from 10 to 15- literature, etc so when I save multiple tabs via a session manager everything is organized according to topic or reading priority. As Lagrange can save currently loaded tabs on exit I would like to be able to re-arrange tabs according to topic.

Off-topic, testing software was a hobby for me but as I don't have much time now I am keeping watch on several short-listed programs which I find promising. Lagrange has all the prerequisites of becoming a gem of a program- written in a good programming language, cross-platform, mindful developer. So I may open some more issues which in fact may be considered as fancy ones. I am aware that most of them might be rejected outright but this does not matter. Even if some of my suggestions make it to the bottom of the developer's to do list it would be fine- it may happen that in the future there might be a day that you won't have anything better to do than implementing some fancy feature requests.

**Comment by skyjake** [comment]
>  I open many tabs I oftentimes re-arrange these tabs according to research topic 

I see, this does sound sensible.

As a first step, it should be quite easy to use keyboard shortcuts for moving tabs around (one spot left or right). Drag-and-drop with the mouse is more difficult to implement but that should be doable eventually.

**Comment by skyjake** [comment]
>  Lagrange has all the prerequisites of becoming a gem of a program

Thanks! :) Looking forward to your improvement ideas. I of course only have so much time in a day to work on this project, but good ideas are always welcome.

**Comment by skyjake** [comment]
@smaragdus Progress: https://github.com/skyjake/lagrange/issues/59#issuecomment-1380387687
