### ISSUE TITLE
Links without a label are not correctly recognised in remote bookmarks

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#147]
Links starting with // without scheme are not recognised as gemini links and get the wrong icon.
They still works when clicking them, but it does not work for bookmark autoimporting.
And I guess they may not work in gemlog feeds either?

I discovered this while attempting to use gemini://français.lanterne.chilliet.eu/ as a bookmark source.

**Comment by skyjake** [comment]
I can confirm that //-links don't get picked up from `remotesource` pages and that seems like a bug.

Not seeing any incorrect icons, though. Could you attach a screenshot of one of these links?

**Comment by skyjake** [comment]
492e8257afa8f1e2183f1c7031fd7340a66cbc6e fixes the bookmark source problem.

**Comment by MCMic** [comment]
Maybe I misunderstood the icons, I had a blue world globe while on an other site I opened I had arrows, but maybe that's local vs external ?

**Comment by skyjake** [comment]
The (blue) globe means that the link goes to a different Gemini domain. The arrows are for links within the same domain as the originating page.
