### ISSUE TITLE
Network/TLS Failure when connecting to localhost

### ISSUE THREAD

**Issue by Tau5** [skyjake/lagrange#151]
What the title says, I also tested with Kristall and Amfora and they connected succesfully

**Comment by skyjake** [comment]
Which operating system are you using, and which server?

Maybe related to #43 ?

**Comment by Tau5** [comment]
I'm using Arch Linux and the [Jetforce server](https://github.com/michael-lazar/jetforce)

**Comment by skyjake** [comment]
Could be fixed now in the dev branch, with the updated the_Foundation submodule.

**Comment by Tau5** [comment]
Yes! It works now!

**Comment by skyjake** [comment]
Fixed in v1.1.2.
