### ISSUE TITLE
Issue: Illegal instruction

### ISSUE THREAD

**Issue by danrobi11** [skyjake/lagrange#155]
Thats the error I get

```
./Lagrange-1.1.2-x86_64.AppImage
Lagrange: A Beautiful Gemini Client
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: en_US.UTF-8
Illegal instruction
```

OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm

**Comment by skyjake** [comment]
Currently the AppImage is built with SSE 4.1 CPU instructions enabled. I'll disable that for the next build, which should help.

Thanks for reporting!

**Comment by skyjake** [comment]
v1.1.3 is available, please test.

https://github.com/skyjake/lagrange/releases/tag/v1.1.3

**Comment by danrobi11** [comment]
@skyjake v1.1.3 is working fine here. Thank you!
