### ISSUE TITLE
Windows 10 Pro Lenovo TrackPoint middle button scrolling not working

### ISSUE THREAD

**Issue by johanbove** [skyjake/lagrange#158]
Using a Lenovo TrackPoint enable keyboard and wanted to scroll a page in Lagrange v1.1.1, the icon changes into the "scrolling vertically" view, but nothing happens. The viewport does not scroll.

**Comment by skyjake** [comment]
That's interesting. A quick web search suggests that the TrackPoint generates mouse wheel events, but they may not be quite the same as normal wheel events. It's unclear whether they are coming through as usual via SDL.

Are there any system settings for the TrackPoint with regard to scrolling/wheel emulation modes?

Not sure how to go about fixing this... The last time I personally saw a TrackPoint was circa 2004 when I had a ThinkPad as a work laptop. 🙂 I suppose we could try logging all the events received by the app and see what the TrackPoint is sending. Such a logging mode doesn't currently exist, though.

**Comment by johanbove** [comment]
Found a work-around / solution. Disabling the "Thinkpad Preferred Scrolling" makes the TrackPoint scrolling using the middle button work again.

So this issue can be closed as the effort is probably not worth the time.

![Screenshot 2021-02-15 222817](https://user-images.githubusercontent.com/922765/107994717-7701e300-6fdd-11eb-8e06-e61e021b4cbd.png)
