### ISSUE TITLE
Using address bar for adding bookmarks

### ISSUE THREAD

**Issue by smaragdus** [skyjake/lagrange#161]
Almost all modern browsers have a button in address bar (URL bar) for adding a bookmark. This feature is available in another Gemini client - **Kristall** ([Website](https://kristall.random-projects.net/), [GitHub](https://github.com/MasterQ32/kristall)), screen:

![Kristall 0 3 - 2021-02-14 - 002](https://user-images.githubusercontent.com/9025757/107885648-37b39380-6f04-11eb-8f12-79c288d3dfb2.png)

As of version [1.1.3](https://github.com/skyjake/lagrange/releases/tag/v1.1.3) [Lagrange](https://github.com/skyjake/lagrange) allows bookmarks to be added only via context menu, screen:

![Lagrange 1 1 3 - 2021-02-14 - 002](https://user-images.githubusercontent.com/9025757/107885922-9f1e1300-6f05-11eb-81b2-0d263db25691.png)

My suggestion:

- A bookmark button in address bar (URL bar), which, when clicked, calls `Bookmark Page` command;

Besides adding an alternative way of bookmarking pages (which I find convenient and visually pleasing) [Lagrange](https://gmi.skyjake.fi/lagrange/) may use different icons for the bookmark button as a visual indicator whether a page has already been added to bookmarks or not, for example:

- yellow star for a page that has been bookmarked;
- grey star for a page that has not been bookmarked;

Such dynamic bookmark button will help the users avoid to bookmark already bookmarked pages (which has happened to me).

I suppose that implementing this feature (which is mostly eye candy) may require some work.

**Comment by skyjake** [comment]
This is feasible to implement, although I'm unlikely to add more "regular" buttons in the navbar as it already has quite a few. The bookmark "Star" button could be embedded inside the URL input field as a frameless icon, like in Firefox at least.

**Comment by skyjake** [comment]
The toolbar buttons can be modified to include the "Add Bookmark" button, and in v1.13 there is an indicator that shows whether the current page has already been bookmarked.

**Comment by smaragdus** [comment]
@skyjake 

I cannot find this [version](https://github.com/skyjake/lagrange/releases) **1.13**, the latest one I see is [1.12.2](https://github.com/skyjake/lagrange/releases/tag/v1.12.2). Is **1.13** unpublished or beta or published on other repository?

**Comment by skyjake** [comment]
v1.13 is in the "dev" branch and currently unreleased.

**Comment by smaragdus** [comment]
@skyjake 

> v1.13 is in the "dev" branch and currently unreleased.

Thanks for the explanation.

When **1.13** Is available I will have a look.

I don't find the GUI flexible and pleasant to use (as of version [1.12.0](https://github.com/skyjake/lagrange/releases/tag/v1.12.0)) because the tool bar icons are hard-coded and cannot be re-organized, The same applies for tabs- no way to re-organize them. At least I need to be able to populate the tool bar with the buttons which I need to be there, using the context menu to access commands means more useless click, the the tool bars exist just for this reason- to provide access to common commands.

**Comment by skyjake** [comment]
> When 1.13 Is available I will have a look.

Shoud be sometime this week.

> I don't find the GUI flexible and pleasant to use

Well, the tool and tab bars certainly aren't very flexible currently. 🙂 They are pretty much still at the "minimum viable" level, and other features have taken precedence. At the moment, you only get four customizable buttons (right-click on one and select a new action).

Reorganizing tabs (by mouse drag) has been requested before I'm planning to do that eventually. Changing the number of buttons in the toolbar seems like a reasonable thing to do for mouse-first users.

**Comment by smaragdus** [comment]
@skyjake 

I saw that there are several new versions released today. I will have a look perhaps tomorrow.

I want to tell you that I appreciate your work, I follow the project from version [1.0.3](https://github.com/skyjake/lagrange/releases/tag/v1.0.3) and although I haven't tested all versions I still check the latest ones from time to time. The program has improved immensely yet I still think it could be improved even further (mostly in the GUI department).

Off-topic, if only Chromium and Firefox developers were as reasonable as you, but unfortunately they do their best to make browsing the web unbearable pain and I suppose that this is one of the reasons more and more people are turning to protocols like Gopher and Gemini. Now all web browsers are terrible (Chromium has always been junk but it is a shame that Firefox was destroyed by its developers) and there is neither hope nor solution.
