### ISSUE TITLE
Inconsistent bookmarks when running multiple instances

### ISSUE THREAD

**Issue by datenbrei** [skyjake/lagrange#163]
When having multiple instances of Lagrange 1.1.2 running and there is a change in bookmarks in one instance, the change is not reflected in the other running instances.

For example, if I delete one bookmark or add one and close the Lagrange process, the change is overwritten by the last running instance.

A possible solution could be to have enforced always just one instance running. This would also mean, that opened links from external, e.g. from firefox, would result in another tab in the running instance and would not start a whole new process.
Another fix, and maybe the easiest, could be to use a transactional database like sqlite for all bookmarks, like Firefox does.
A third solution could be some kind of having an own thread for each window, but just one process - and then making use of inter-thread-communication.

**Comment by skyjake** [comment]
This is related to issue #37.

A previous comment on the subject: https://github.com/skyjake/lagrange/issues/37#issuecomment-727186557

**Comment by skyjake** [comment]
b97462993b00ecc5cd04051b4fc2abd164fefb04 prevents multiple instances from using the same user directory.
