### ISSUE TITLE
PSK support

### ISSUE THREAD

**Issue by eko234** [skyjake/lagrange#164]
Hi, i was wondering if you plan on implementing some sort of pre shared keys support for lagrange, it would be very cool.
Nice browser, keep the amazing work on.

**Comment by skyjake** [comment]
Thanks!

Could you elaborate a little on what the pre-shared keys would be used for, please? I'm not sure what the use case is.

**Comment by eko234** [comment]
i'm developing a gemini based program, and for authentication i'm using a url based authentication system, which indeed works, but i think PSK would be a better choice.

**Comment by skyjake** [comment]
Sorry, I'm still not quite following what exactly you are trying to accomplish. You are not using client certificates for authentication?
