### ISSUE TITLE
Should blockquotes include a closing double quotation mark?

### ISSUE THREAD

**Issue by SirBossJam** [skyjake/lagrange#165]
I find it odd that blockquotes only have the beginning double quote on rendered pages. Is this by design? I thought at first it was a problem with my formatting until I noticed this on other sites as well.

![Screenshot_2021-02-15_14-54-00](https://user-images.githubusercontent.com/66538223/107992355-6b5bef80-6fd0-11eb-8069-51c84a6a9230.png)

**Comment by skyjake** [comment]
Yes this is by design. 🙂  Check out the quote line indicator option in Preferences > Style for an alternative quote presentation.
