### ISSUE TITLE
gopher links with spaces in them are parsing incorrectly

### ISSUE THREAD

**Issue by jamestomasino** [skyjake/lagrange#168]
If you visit the log listings page on cosmic.voyage in gopher you can see the issue: gopher://cosmic.voyage:70/1/log

If the path segment has a space in it the link is clipped incorrectly. For example:

```
0430 >> Isla Ristol - Peta-millones     /Isla Ristol/a11.txt    cosmic.voyage   70
```
The link for this should be the `/Isla Ristol/a11.txt` path, but instead the link is just `/Isla`. Likewise the text label of the links is parsing at the wrong location. It's probably convoluting the gopher-link logic with the gemini space seperator.

**Comment by skyjake** [comment]
The problem was that paths on Gopher menus weren't being URL-encoded in the generated gemtext output.
