### ISSUE TITLE
Ogg/Opus audio crashes the browser

### ISSUE THREAD

**Issue by ajroach42** [skyjake/lagrange#169]
For example, there is an opus file linked here: gemini://ofmanytrades.com/

The browser recognizes it as an ogg file, sorta, but it won't play back and if you click on the menu item the browser crashes.

**Comment by skyjake** [comment]
Yeah it goes to the Vorbis decoder since that also uses Ogg containers, but Opus decoding is currently not supported.

The crash needs fixing, but I could also consider adding an Opus decoder. It would be an additional optional dependency.

**Comment by skyjake** [comment]
This was the cause for the crash: c632c97667ea3ae55ef614c6e23fad7dfb1a61bf

Fixed for v1.2.
