### ISSUE TITLE
Enhancement Idea: Add a "View Source" option

### ISSUE THREAD

**Issue by mdesjardins** [skyjake/lagrange#170]
Congrats and thank you on making an amazing Gemini browser - the rendering is gorgeous, well done!

I was thinking what would be super-cool is a "View Source" entry under the View menu... when I was first learning HTML in the 1990s (yikes!) this is what inspired me to learn how to try to make my own pages. I recognize that Gemini markup is vastly simpler than HTML but it still might be nice to show people how easy it is. I searched through the Issues and was surprised that I didn't find someone else requesting this.

Hopefully the option isn't already there somewhere and I'm just not finding it! 😬

**Comment by mdesjardins** [comment]
Argh! I just found "Copy Source" under the context menu. Doh! Ignore me. 🤦

**Comment by skyjake** [comment]
I agree that gemtext is so simple that viewing the source is a bit pointless, but implementing an option to force all pages to show up as "text/plain" would be pretty trivial.

Note that pressing Ctrl+C or ⌘C without any text selected will do "Copy Source" on the entire page. Also, you can use "Save to Downloads" (Ctrl+S / ⌘S) on any page to save the page source to your downloads directory.
