### ISSUE TITLE
Sorting order of unread feed entries

### ISSUE THREAD

**Issue by vascocosta** [skyjake/lagrange#173]
The ability to subscribe to pages using the YYYY-MM-DD format is one of the features I like the most in Lagrange. However, I'm experiencing a sorting issue which I'm not sure whether it's a bug or by design.

As the day progresses and new feed entries show on the feed entries list, they're inserted at seemingly random positions, intertwined with old and already visited entries. That's not a big deal if you subscribe to only a few feeds or feeds that have low traffic, but in situations with more traffic, I end up needing to scroll down quite a bit to find the new/unread entries, which get buried below old/visited ones.

I understand YYYY-MM-DD doesn't allow for sorting by time within a single day, since there's no time info, nevertheless, the code is aware of entries that are new and haven't yet been clicked. In my opinion, it would be interesting to always place the newly found entries at the very top of the list, instead of placing them at random locations.

Thank you so much for this amazing browser. If you get some spare time and this isn't too complicated to implement, please consider having this as an option or default behaviour.

**Comment by skyjake** [comment]
Default behavior in v1.2 is to sort secondarily by feed entry fetch time.
