### ISSUE TITLE
Improved command line behavior: unknown command line options, --help

### ISSUE THREAD

**Issue by bortzmeyer** [skyjake/lagrange#174]
```
lagrange --does-not-exist gemini://gemeaux.bortzmeyer.org
```
does not output an error message, which I find problematic: typos in options are silently ignored.

**Comment by Br0000k** [comment]
I've made a pull request for this :) need to do some work on getting both URLs and options to work with each other.

**Comment by skyjake** [comment]
I've been quite focused on GUI usage thus far, but there are certainly a bunch of things that could be done better for the command line:

- [x] `--help`
- [x] errors when encountering unknown options (that don't appear to be existing files)
- [x] long and short variants of the options

**Comment by skyjake** [comment]
Moved the man page to #190.
