### ISSUE TITLE
Copy/cut/paste via application/context menus

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#175]
Whenever the mouse pointer is in a text box, it should be possible to paste by mouse.  Currently you have to use a system-dependent keyboard shortcut.

This comes up when I copy a gemini-protocol URL from Chrome, which does not recognize them properly.  So I select the URL with the mouse, choose Copy using the right-click menu, switch to Lagrange, and then I have to return to the keyboard to type Command-V or Control-V.  Some suggestions:

1. Add Edit/Cut before Edit/Copy and Edit/Paste after Edit/Copy to the menu bar with appropriate keyboard shortcuts. These would be grayed out when the focus is not in a text box.
2. Add popup menus with Cut, Copy, and Paste to all text boxes.
3. Do both (ideal).

**Comment by skyjake** [comment]
There is currently pasting with middle mouse button but a context menu would be a very useful thing to have, too.

**Comment by johnwcowan** [comment]
Ah.  I'm on a trackpad, and accurately triple-fingering is too hard for me.

On reflection I think option 1 would be the simplest and easiest.

**Comment by skyjake** [comment]
Implemented for v1.3.
