### ISSUE TITLE
Segfault when a non resolvable URL/text is entered

### ISSUE THREAD

**Issue by DrZingo** [skyjake/lagrange#177]
Lagrange segfaults on bad url's.

How to reproduce: 
Enter anything that doesn't resolve in the address bar. 
Wait 5-10 seconds. 
Segfault

Lagrange version: 1.1.4, 1.1.3, maybe earlier versions
System: Linux

**Comment by skyjake** [comment]
At least on macOS I get:

> Network/TLS Failure
> Failed to communicate with the host. Here is the error message:
> Operation timed out

I'll need to try on Linux, maybe the socket connection timeout behaves differently.

**Comment by skyjake** [comment]
> System: Linux

Could you elaborate on the version etc.? I just tried on Ubuntu 20.04.2 and it gave me an error page as expected, no crashes.

**Comment by DrZingo** [comment]
Arch Linux, 
kernel: 5.10.16
gnutls 3.7.0
openssl 1.1.1.j

**Comment by DrZingo** [comment]
I have also tried v1.1.2 on endeavourOS now, same problem.

**Comment by skyjake** [comment]
This could be the same problem as here: https://github.com/skyjake/lagrange/issues/43#issuecomment-779701281

That crashing bug has been fixed in the dev branch, or you can get it in the release branch if you manually pull the latest commits from the_Foundation's master branch to `lib/the_Foundation/`.

**Comment by DrZingo** [comment]
Great, this worked, and I got the expected TLS error message: 
```
git clone --recursive --branch dev https://github.com/skyjake/lagrange.git
cd lagrange && mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
cmake --build . --target install
```

**Comment by skyjake** [comment]
Version 1.2 will include the fix.
