### ISSUE TITLE
Listing open tabs via a programmatic interface

### ISSUE THREAD

**Issue by mernisse** [skyjake/lagrange#178]
I'd be interested in Lagrange providing a way for external scripts to determine a list of open tabs.  I currently get this on macOS from Safari via applescript but just writing a text file out periodically would be fine as well.

**Comment by skyjake** [comment]
This could tie into #37. One way could be to keep some sort of lock file that can be used both for determining if an instance of Lagrange is already running and which tabs are currently open. The file could contain the PID and a list of URLs.

Would this be the URLs only, or should titles be available, too?

**Comment by mernisse** [comment]
In my use case all I use is URLs.  As long as they can be reasonably parsed out using normal shell tooling I don't have any argument against titles being available though.

**Comment by skyjake** [comment]
This is now implemented via a new command line option: `--list-tab-urls`

If there is a Lagrange instance running, its open URLs will be printed to stdout, one per line.

I'll still need to add an option to prevent an instance from being started if Lagrange is _not_ currently running. Or perhaps `--list-tab-urls` should always quit at launch, regardless of whether instances are running.

**Comment by skyjake** [comment]
> --list-tab-urls should always quit at launch

That is how it now works.

The option `--list-tab-urls` (`-L`) prints the tabs open in the currently running instance of Lagrange, or prints nothing and just exits if Lagrange isn't running.

On macOS, one can do this by calling _Lagrange.app/Contents/MacOS/Lagrange_ directly in a script.
