### ISSUE TITLE
Window not rendering until mouse hover

### ISSUE THREAD

**Issue by gramosg** [skyjake/lagrange#18]
I'm using xmonad as WM, and whenever I arrive to the workspace in which Lagrange is running, in the space where Lagrange should be displayed there still appears whatever was being displayed on that space of the screen on the previous workspace. After moving the mouse over it, it is refreshed and Lagrange appears as it should.

Interestingly, focusing the window with the keyboard does not trigger the rendering, only hovering with the cursor.

I'm not sure how to reproduce this, and the console shows nothing suspicious. If you have any clue how to trace this issue I'm happy to help.

Happens on Lagrange 0.6.0 w/ libsdl2-2.0.12 on Gentoo amd64.

**Comment by skyjake** [comment]
This sounds like #11 that has been fixed in the dev branch. The problem there was the window expose events weren't triggering a window redraw as they should've been.

Could you try a build of the dev branch to see if the problem persists there for you?

**Comment by gramosg** [comment]
Oh snap, yes, it is fixed in dev :man_facepalming: . Nevermind then, thanks for the quick response!
