### ISSUE TITLE
Add option to collapse preformatted blocks, configuration option to set default

### ISSUE THREAD

**Issue by jamestomasino** [skyjake/lagrange#180]
The preformatted text blocks have an alt text property following the three backticks which is designed to be a human-readable representation or indication of what is in the block. This feature gains value for blind users when our clients embrace it and allow it to be displayed instead of the wall of text common in ascii art or even code samples.

[Davin Prater's post on the mailing list](https://lists.orbitalfox.eu/archives/gemini/2021/005631.html) explains this from the POV of a blind user quite well.

As a feature request I would ask for two additions to Lagrange to improve it for blind users:

1. Allow preformatted blocks to toggle visibility, labeled with their alt-text representation or a generic fallback
2. Allow the collapsed state to be set as the default in a configuration option

**Comment by skyjake** [comment]
I have been wondering what to do with the alt texts beyond the obvious tooltips (that haven't been implemented either)...

Your suggestion sounds like a pretty good approach.

**Comment by ghost** [comment]
@jamestomasino mentioned on IRC that they've not specified the generic fallback, in the case that no alt-text is given.  I suggest(ed) that a simple 'missing alt-text' or 'no alt-text provided' message be used.

**Comment by skyjake** [comment]
> 1. Allow preformatted blocks to toggle visibility, labeled with their alt-text representation or a generic fallback
> 2. Allow the collapsed state to be set as the default in a configuration option

Both done for v1.3.

> additions to Lagrange to improve it for blind users

Mind you, Lagrange is currently completely unusable to blind users because there is no integration whatsoever with screen readers. (This is a separate issue #186.) However, this feature encourages use of alt text in preformatted blocks, so it should still be beneficial overall.
