### ISSUE TITLE
download progress for common file formats

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#185]
Hello,

When downloading a large file it’s quite annoying to have to progress bar.
I do know that Gemini protocol does not advertise the file size, but I was wondering, doesn’t most file formats contain a header with some kind of size information at the beginning?

The case I had was downloading a video in webm format here: gemini://artorinix.space/gemlog/first-video-of-a-martian-landing-released.gmi

I am no expert on file formats but I expect a video file format must have information on its duration in the first bytes? This would I think allow to show some kind of progress bar for the supported format. I think archive formats also have this kind of header information.

**Comment by skyjake** [comment]
While it is true that technically it would be possible to parse the first couple of kilobytes for header information, there are so many different file and video container formats that trying to handle them all in a reliable way becomes a considerable challenge, or requires adding a dozen new 3rd party libraries to the build. Weighing this against the gained benefit of just displaying a progress bar seems like a misallocation of resources IMO.

It would be much easier if the author of the Gemini page would simply include the size in the human-readable link label, for instance `(10 GB)`.
