### ISSUE TITLE
Lagrange crashes with STATUS_ILLEGAL_INSTRUCTION exception on Windows 10

### ISSUE THREAD

**Issue by dnsppv** [skyjake/lagrange#187]
Hi! Lagrange crashes immidiately after start on Windows 10 20H2 (build 19042.804)
Stack dump: https://gist.github.com/armanzor/f2d64fa090831d6f96564d8e7cd2391a
Portable and setup versions, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2 are affected

**Comment by skyjake** [comment]
> STATUS_ILLEGAL_INSTRUCTION

This could be related to SSE 4.1 instructions being enabled in the build. I'll disable it and let's see if that helps (after the next build).

**Comment by dnsppv** [comment]
I asked my friend with new computer and processor, supporting instructions SSE 4.1 and SSE 4.2 to check this. He has successfully run the program. Unfortunately, my processor doesn't support this.

**Comment by skyjake** [comment]
[v1.2.2](https://github.com/skyjake/lagrange/releases/tag/v1.2.2) is available.

**Comment by dnsppv** [comment]
Works perfect, thanx!
