### ISSUE TITLE
README.md doesnt say how to reset lagrange

### ISSUE THREAD

**Issue by kylagit** [skyjake/lagrange#188]
i deleted the app image (downloaded from releases) and redownloaded it and the settinsg and tabs before are still there, please say in README.md where the data/settings for lagrange are located so i can delete it and start fresh

**Comment by skyjake** [comment]
Sure, I'll add a note about that.

The user files are in `~/.config/lagrange/`, or if you've customized your XDG directories, wherever the XDG_CONFIG_HOME is.
