### ISSUE TITLE
Middle clicking sidebar entries to open them in a new tab

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#189]
I can use middle click to open a link in a new tab, but it does not work on bookmarks. (I did not try history and such)

**Comment by skyjake** [comment]
I don't think the sidebar uses middle clicks for anything yet... For consistency this should be added, though.

**Comment by skyjake** [comment]
Just as an update, the middle button currently has this functionality:

* Pasting text from clipboard.
* Closing a tab when clicking on the tab title button.
* Opening link in a new tab.

Missing:

* Opening bookmarks, feed entries, and history items in a new tab.
* Scrolling (potentially): #448
