### ISSUE TITLE
Compilation of the_Foundation fails on OpenBSD

### ISSUE THREAD

**Issue by wluckin** [skyjake/lagrange#19]
Compilation of `the_Foundation` fails on OpenBSD with the following error:

```
/home/wl/build/lagrange/lib/the_Foundation/src/platform/posix/address.c:66:27: error: 
      use of undeclared identifier 'AI_V4MAPPED_CFG'
    const int hintFlags = AI_V4MAPPED_CFG | AI_ADDRCONFIG | (isEmpty_String(...
```

I'm compiling with OpenBSD clang version 10.0.1 on OpenBSD-current, though the issue also exists on 6.8.

I tried messing around with the `ifdef` above

```
     60 #if defined (iPlatformLinux) || defined (iPlatformMsys) || defined (iPlatformCygwin)
     61 #   define AI_V4MAPPED_CFG  AI_V4MAPPED
     62 #endif
```

with no real success.

**Comment by skyjake** [comment]
This is with the release branch? A couple of changes were required for OpenBSD, they are currently in the dev branch.

I'll probably put these in 0.7.1 with some other fixes.

**Comment by wluckin** [comment]
Oh cool, thanks! That's great.

I'm actually pretty interested in what you needed to change from OpenSSL/LibreSSL, because there's a few other programs I tried to compile recently failing with similar errors. I'll be sure to check it out.

**Comment by wluckin** [comment]
Actually, even with the most recent version a change is needed in `lib/the_Foundation/CMakeFiles/the_Foundation.dir/src/tlsrequest.c` getting a non-constant reference with `X509_getm_notAfter(d->cert)` instead of `X509_get0_notAfter(d->cert)` on line 270.

However, after that, it does compile, thanks to the recent changes in `address.c`.

**Comment by skyjake** [comment]
Which SSL library/version are you using? I haven't seen that error with OpenSSL 1.1.1h on OpenBSD 6.8, where I did my debugging.

**Comment by wluckin** [comment]
I am using the default in OpenBSD 6.8, which is LibreSSL 3.2.2.

**Comment by skyjake** [comment]
> However, after that, it does compile

I'm not seeing a `ASN1_TIME_to_tm()` in LibreSSL 3.2.2, and that is called on tlsrequest.c:270. Did you change something with regard to that?

**Comment by wluckin** [comment]
Sorry, previous message wasn't so clear. Had to switch to `X509_getm_notAfter(d->cert)` because I needed a mutable reference for `ASN1_TIME_set_tm`, which LibreSSL does have.

```
diff --git a/src/tlsrequest.c b/src/tlsrequest.c
index 919eb9f..de2a49d 100644
--- a/src/tlsrequest.c
+++ b/src/tlsrequest.c
@@ -267,7 +267,8 @@ void validUntil_TlsCertificate(const iTlsCertificate *d, iDate *untilDate_out) {
     iZap(*untilDate_out);
     if (d->cert) {
         struct tm time;
-        ASN1_TIME_to_tm(X509_get0_notAfter(d->cert), &time);
+       ASN1_TIME* temp = X509_getm_notAfter(d->cert);
+        ASN1_TIME_set_tm(temp, &time);
         initStdTime_Date(untilDate_out, &time);
     }
 }
```

**Comment by skyjake** [comment]
Nice, I'll adapt this so it works with both libraries.

**Comment by wluckin** [comment]
Thanks! Lagrange is great. I may look in to packaging it for OpenBSD's ports, if I'm still using it in a few weeks.

**Comment by skyjake** [comment]
FYI, I ended up with [this code](https://codeberg.org/skyjake/the_Foundation/commit/52fc0ee9c948ddfbd5918ce1449ab32b910c005d) because `ASN1_TIME_set_tm()` actually does the inverse of what is expected here.

**Comment by wluckin** [comment]
That's what I get for just guessing, I guess... thanks!
