### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by skyjake** [skyjake/lagrange#191]
Now that #37 is done, and Lagrange prevents multiple instances from running on the same user directory, it makes sense to look at multiple window support.

The good news is that the `Window` class largely does not assume that only a single window exists. `App` must be made aware of multiple windows and track their state, and process events in each window. There could even be a thread-per-window parallel processing mode.

One drawback is that rendering contexts are not shareable, so the font glyph cache and other resources must be separately allocated and managed for each window. `Text` is a singleton currently, so that does need refactoring.

A big advantage of supporting multiple windows is that Preferences and other popups (including menus) could be done as windows, too (perhaps borderless), so they are not confined inside the main windows.

**Comment by sirnewton01** [comment]
:+1: This will be super useful when running in mobile Linux devices in phosh because tab management can be done more easily in the shell than within the application. The browser is already very nice and usable there right now, with the exception of the dialogs.

**Comment by skyjake** [comment]
Multi-window support was added in v1.11.
