### ISSUE TITLE
User interface localization

### ISSUE THREAD

**Issue by skyjake** [skyjake/lagrange#192]
All user-visible strings should be looked up via a translation table so the UI can be localized to different languages.

In practice, wherever there is a user-visible string, it should be replaced with a lookup key. The keys could start with a special symbol, for instance `$menu.tab.new`. Widgets could then perform the lookup from the translation table and keep a pointer to the user-visible string. When the language is changed at runtime, widgets can then just redo the lookup and everything will instantly update.

Dynamically formatted text is a challenge of its own, but one solution is to translate the format string and use numbered arguments so the order can be changed in the translation (like in Qt).

EDIT: There is now a Weblate server where you can contribute translations: https://weblate.skyjake.fi/projects/lagrange/ui/. Contact me if you want to start translating a new language.

**Comment by sikmir** [comment]
I would like to help with translating to Russian and Finnish.

**Comment by skyjake** [comment]
Thanks for the offer! Although I'll probably do Finnish myself, being a native speaker. 🙂 (for dev purposes, too)

**Comment by sikmir** [comment]
I suggest to use [Weblate](https://hosted.weblate.org/), it's free for open source projects.

**Comment by skyjake** [comment]
That's a good idea. I'll look into the supported file formats on Weblate and see what would work best for Lagrange.

**Comment by laosb** [comment]
Want to see this happening! I would like to help with Chinese translation.

**Comment by skyjake** [comment]
@sikmir @laosb I've set up a self-hosted Weblate at [weblate.skyjake.fi](https://weblate.skyjake.fi/projects/lagrange/ui/). You're most welcome to create an account and start translating! 🙂 

Let me know if you run into any issues with the site. It seems to be working for me at least.

**Comment by laosb** [comment]
@skyjake Hi I've set up my account, but there's no option for translating to Chinese. Could you add it?

**Comment by skyjake** [comment]
Which one would you like:

  Chinese (Min Nan) (nan)
  Chinese (Pinyin) (zh_Latn)
  Chinese (Simplified) (zh_Hans)
  Chinese (Simplified, Singapore) (zh_Hans_SG)
  Chinese (Traditional) (zh_Hant)
  Chinese (Traditional, Hong Kong) (zh_Hant_HK)

**Comment by laosb** [comment]
I believe Chinese (Pinyin) is not really Chinese, just the pronunciation assisting symbols. I'm native in Simplified Chinese, and can help with Traditional Chinese.

**Comment by skyjake** [comment]
All right, added!

**Comment by skyjake** [comment]
@laosb I added you to the Translators group so you should be able to save the translations directly now.

**Comment by laosb** [comment]
Oh, OK, thank you!

**Comment by sikmir** [comment]
@skyjake "Save" button is disabled, I can only "Suggest" translation. Is it some restriction?

**Comment by skyjake** [comment]
@sikmir I've added you to the Translators, too. By default, users can suggest only.

**Comment by Carmina16** [comment]
Please add Interlingue (code: ie).

**Comment by Carmina16** [comment]
Is it possible to give me ("OIS") the translator rights for Interlingua [ia] and Interlingue [ie]?

**Comment by skyjake** [comment]
@Carmina16 I've added you as a translator.

**Comment by laosb** [comment]
Just finished translating to zh-Hans. Will work on translating to zh-Hant later.

Any chance getting some test build to see the real world performance?

**Comment by laosb** [comment]
Btw, I'm a little concerned about the font used in Lagrange. Currently it renders Chinese badly with characters changing sizes along the line. I would suggest use system font or [Noto Sans CJK](https://www.google.com/get/noto/help/cjk/) if possible.

**Comment by skyjake** [comment]
Nice! I was just testing this a moment ago.

I'll see about doing a test build. Which operating system do you use?

> Currently it renders Chinese badly with characters changing sizes along the line. 

Yes that is a problem at the moment, and it's also missing a few glyphs. I will update the UI font.
<img width="191" alt="Screen Shot 2021-03-25 at 9 20 26" src="https://user-images.githubusercontent.com/1225742/112434253-07091a00-8d4c-11eb-87f5-a2a4a8d22092.png">

**Comment by laosb** [comment]
I'm using macOS on Apple Silicon. Also on iOS.

**Comment by skyjake** [comment]
OK, I'll do the font update and make a test build for macOS.

**Comment by skyjake** [comment]
@Carmina16 

> Interlingua [ia] and Interlingue [ie]?

Ah, earlier I missed `ie` in Weblate because it's called "Occidental (ie)" and not Interlingue there. (Perhaps to avoid confusing it with Interlingua.) It's now added to the project, so please go ahead. 🙂

**Comment by sikmir** [comment]
Status:
<a href="https://weblate.skyjake.fi/engage/lagrange/">
<img src="https://weblate.skyjake.fi/widgets/lagrange/-/ui/multi-auto.svg" alt="Translation status" />
</a>

**Comment by skyjake** [comment]
Nice, although I just noticed there are 6 untranslated strings in the quick lookup results popup... I'll commit those shortly.

**Comment by skyjake** [comment]
@laosb Test build for you: https://media.skyjake.fi/lagrange_v1.3.0_macos11.0-arm64.tbz

This build adds Noto Sans CJK (SC) weighing in as an additional 10 MB. Previously, glyphs have been picked from different fonts where available, so that's one possible reason for inconsistent appearance. Now they should all be coming from Noto Sans. Let me know if you spot errors in text rendering.

Some known issues:

- Must restart the app to update the macOS menu items.
- Layout of the Preferences dialog is incorrect immediately after a language change.

**Comment by sikmir** [comment]
@skyjake It looks like plural forms are not properly extracted for Russian:
https://github.com/skyjake/lagrange/blob/94f45c0fe81f7f18d65a3d701da1c8448027d8b7/po/ru.po#L532-L536
Compare:
https://github.com/skyjake/lagrange/blob/94f45c0fe81f7f18d65a3d701da1c8448027d8b7/po/fi.po#L535-L538

**Comment by skyjake** [comment]
@sikmir This seems to be a Weblate issue. The strings originally didn't have plurals, and the export is somehow stuck on the original non-plural strings. I had to manually edit the fi.po and re-upload it to Weblate to fix this... Would you like me to do the same for ru.po?

**Comment by sikmir** [comment]
> Would you like me to do the same for ru.po?

Yes, please.

**Comment by skyjake** [comment]
Done. Hopefully they are now correctly exported.

I should check German as well, I'm pretty sure it has the same problem.

EDIT: Nope, they aren't translated yet in German.

**Comment by skyjake** [comment]
Auto-refresh intervals didn't have strings yet, so those were added (fa746aa0766b957acbb36800d4a410c768392d4a).

**Comment by laosb** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/2545261/112742337-4dff4580-8fc0-11eb-9e66-0284378e3064.png">

The test build works mostly fine. Noticed two problems:

* When the field name is too long, the pref window have some overflow as the screenshot shows (maybe I can try to shorten the translation by not explaining what CA is in this case?)
* The menu on macOS doesn't update. Restarting Lagrange is required to get the menu updated to selected language.

**Comment by skyjake** [comment]
Yeah, those problems are occurring for me too. I'll need to debug the Preferences layout a bit. There should be no need to alter the translations.

The macOS menus not retranslating on the fly is a known issue.

**Comment by laosb** [comment]
Fixed some date translation in Chinese (S). Also roughly finished Chinese (T), with machine translation from S to T and manual inspection. Hope native Chinese (T) speaker from Taiwan can help correct my mistakes.

**Comment by skyjake** [comment]
@laosb I think the exported .po file has a couple of problems with the plurals, like I had with Finnish and @sikmir had with Russian. I'll apply a fix...

**Comment by skyjake** [comment]
We've reached string freeze for v1.3. You still have a couple of days to finalize the translations for v1.3.0.

**Comment by laosb** [comment]
Received the notice. Just updated both Chinese (S) and (T) to keep it at 100%!

**Comment by skyjake** [comment]
Aha, of course there's still one more string missing, the menu item for Chinese (T). I'll still add that...

**Comment by sikmir** [comment]
Russian is 100% ready and looks good for me, looking forward 1.3.0 release.

**Comment by sikmir** [comment]
One note, as far as this issue will be closed on 1.3.0 release, it makes sense to enable "Start new translation" button on Weblate for registered users (it can be configured to require approval) to make it easy to request new language.

**Comment by skyjake** [comment]
I think I'll leave this issue open for now, but I will look into the access rights for the translation button.

**Comment by sikmir** [comment]
@skyjake "Translate" button is out of frame:
![scr1](https://user-images.githubusercontent.com/688044/112866387-68b9e300-90c2-11eb-9230-e73cd620d3af.jpg)

**Comment by sikmir** [comment]
@skyjake Another untranslated strings:
* https://github.com/skyjake/lagrange/blob/dev/src/audio/player.c#L786-L802
* https://github.com/skyjake/lagrange/blob/dev/src/ui/documentwidget.c#L3165

**Comment by skyjake** [comment]
@sikmir Fixed the dialog layouts being sometimes too narrow.

I suppose the remaining strings can wait for a patch. Maybe the keyboard key names should also be translated?https://github.com/skyjake/lagrange/blob/dev/src/ui/util.c#L104

There's a set of `about:` pages that could also be translated:

* https://github.com/skyjake/lagrange/blob/dev/src/bookmarks.c#L327
* https://github.com/skyjake/lagrange/blob/dev/src/feeds.c#L651
* https://github.com/skyjake/lagrange/blob/dev/res/about/about.gmi

**Comment by sikmir** [comment]
> Maybe the keyboard key names should also be translated?

I think it's better to leave it as-is, translating "Ctrl/Alt/Shift/Meta/Caps/Space/Esc" seems weird.

**Comment by Carmina16** [comment]
Yes, keyboard keys should be translatable.

Also, it possible to embed English strings for missing entries in translation files instead of the identifiers?

**Comment by skyjake** [comment]
> embed English strings for missing entries in translation files instead of the identifiers?

That is not possible at the moment. I could enable this for selected things like the keyboard key names, which mostly come from SDL.

**Comment by laosb** [comment]
I'm not sure about how to do that, but to ensure quality, it's better to include both TC and SC variants of Noto Sans CJK, and switch to the corresponding one accordingly.

Also it might be a good idea to switch for content according to the Gemini header `lang={}`.

**Comment by MCMic** [comment]
@skyjake Hello, can I be added to translators for French? (MCMic account on the weblate)

Also I’d love to see an esperanto translation, but I’m not good enough to do it.

**Comment by skyjake** [comment]
@MCMic You should now have translator rights, please go ahead.

I’ve added Esperanto, too. Let’s see if someone volunteers to do it...

**Comment by sikmir** [comment]
> Also I’d love to see an esperanto translation, but I’m not good enough to do it.

+1, I also learned Esperanto and can help with it a bit.

**Comment by skyjake** [comment]
@laosb 

> I'm not sure about how to do that, but to ensure quality, it's better to include both TC and SC variants of Noto Sans CJK, and switch to the corresponding one accordingly.

I'm planning to implement #195 (downloadable fonts) so there can be a larger variety of fonts available, and every update doesn't have to include the full set of fonts. Switching based on the UI language shouldn't be a big issue.
 
> Also it might be a good idea to switch for content according to the Gemini header `lang={}`.

This is doable, although requires the server to send the correct the language parameter. I wonder how often this is present in practice?

**Comment by skyjake** [comment]
@Carmina16 Is it appropriate to label `ie` as "Occidental" also in the Lagrange UI, or should I use "Interlingue"? Keeping in mind that "Interlingua" could also be included when finished.

EDIT: Going with "Interlingue" for now as "Occidental" seems obsolete according to Wikipedia.

**Comment by Carmina16** [comment]
`Interlingue` is OK.

**Comment by balazsbotond** [comment]
I would like to translate Lagrange into Hungarian. Could you please start the new translation on Weblate?

**Comment by skyjake** [comment]
I've now added Hungarian. Did you already register a user account on Weblate? Let me know the username and I'll give you translator access rights, otherwise you can only suggest strings.

**Comment by balazsbotond** [comment]
Thank you! I've just registered, my username is balazsbotond.

**Comment by skyjake** [comment]
You now have the access rights. 🙂

**Comment by balazsbotond** [comment]
I finished the translation. Thanks for your help!

**Comment by skyjake** [comment]
Wonderful! This will be included in v1.8.1.

One more string, though: I added `lang.hu` for the language dropdown menu.

**Comment by balazsbotond** [comment]
Great, I'm looking forward to the new version!

I've translated `lang.hu` too.

**Comment by balazsbotond** [comment]
I built the project and checked the translated UI. I made some minor corrections to the strings in Weblate based on what I saw, but now the Hungarian translation can be considered complete.

I also discovered that translated strings aren't being applied to a tiny part of the UI, even though they are present in Weblate ("Normal" and "Fill", keys `prefs.linewidth.normal` and `prefs.linewidth.fill`):
![2021-11-04-152052_1073x305_scrot](https://user-images.githubusercontent.com/2791280/140336134-a2b5fc2e-dea6-4671-bc1a-ba5558961898.png)

**Comment by skyjake** [comment]
If you close and reopen the dialog, those should get translated as well?

There are also other minor glitches with language switches, I'll make a note about this one.

**Comment by balazsbotond** [comment]
You're right, closing and reopening the dialog solves it.

**Comment by ghost** [comment]
Hi @skyjake Can you add arabic language `ar`. Will try to contribute. I'm ButterflyOfFire on Weblate. Thanks.

**Comment by skyjake** [comment]
@BoFFire I've added "Arabic (ar)". I'll probably need to rearrange some UI elements for a more appropriate RTL layout, but having the UI strings first would be great. 👍 Also, you now have Translator access rights.

**Comment by sikmir** [comment]
> I’ve added Esperanto, too. Let’s see if someone volunteers to do it...

@skyjake Could you please add Esperanto Glossary as well? I have no permissions for that.

**Comment by skyjake** [comment]
@sikmir Ok, added.
