### ISSUE TITLE
Right click on selected text in address bar not working

### ISSUE THREAD

**Issue by shtirlic** [skyjake/lagrange#194]
Hi, there is no context menu when right clicking on selected address text in address bar, right click on selected is okay. Also it's not possible to select single word in text by double click or whole text via next double click.
Version: 1.2.1
Platform: Windows 10 PRO

**Comment by skyjake** [comment]
Both of these features are unimplemented at the moment. The existing issues should cover this: #175 and #134.

**Comment by shtirlic** [comment]
Sorry for duplicates, I've tried search before with no luck, thank you for great software.

**Comment by skyjake** [comment]
No problem! 🙂
