### ISSUE TITLE
Build Fail: `setCiphers_TlsRequest` not found

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#197]
Hello!  Lagrange (last few commits on `release`) is failing to build because the function `setCiphers_TlsRequest` seems to be missing:

```
[ 56%] Built target the_Foundation
[ 57%] Building C object CMakeFiles/app.dir/src/main.c.o
.../lagrange/src/main.c: In function ‘main’:
.../lagrange/src/main.c:63:5: error: implicit declaration of function ‘setCiphers_TlsRequest’; did you mean ‘setContent_TlsRequest’? [-Werror=implicit-function-declaration]
   63 |     setCiphers_TlsRequest("ECDHE-ECDSA-AES256-GCM-SHA384:"
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     setContent_TlsRequest
cc1: some warnings being treated as errors
make[2]: *** [CMakeFiles/app.dir/build.make:82: CMakeFiles/app.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/app.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
It looks like `setCiphers_TlsRequest` is supposed to be defined in `the_Foundation`, but the commit that is being included (as a submodule) in the Git repository doesn't seem to have it.  However, `the_Foundation` has it on `master`, so it looks like the commit specified for the submodule needs to be updated.  Maybe include this build process (i.e. directly from the Git repo) in any CI builds?

**Comment by skyjake** [comment]
The release branch is using the_Foundation commit `4b542128` that does have `setCiphers_TlsRequest`. Perhaps you need to run `git submodule update`?

My release build scripts always do a full checkout, so they would fail if the right version of the submodule is not available in the branch.

> Maybe include this build process (i.e. directly from the Git repo) in any CI builds?

I can look into adding a check in Lagrange's CMakeLists to verify that if the build is happening from a checked out repo, the correct version of the submodule is also checked out.

**Comment by ghost** [comment]
> The release branch is using the_Foundation commit `4b542128` that does
> have `setCiphers_TlsRequest`. Perhaps you need to run `git submodule
> update`?

... huh.  I thought `git pull` was updating submodules too, but
apparently I was wrong.  Sorry about that.

> I can look into adding a check in Lagrange's CMakeLists to verify that
> if the build is happening from a checked out repo, the correct version
> of the submodule is also checked out.

Unless someone else runs into this issue as well, I don't think there's
any point checking for it.

Thanks!

**Comment by skyjake** [comment]
No problem! :)

> Unless someone else runs into this issue as well, I don't think there's any point checking for it.

Unfortunately there does appear to be questions about this somewhat frequently, so an automated check could be helpful.
