### ISSUE TITLE
Weird mouse behaviour on Lagrange 1.2.2 (macOS 11.2.3)

### ISSUE THREAD

**Issue by arturh** [skyjake/lagrange#198]
Focus doesn't follow mouse. See attached video.

https://user-images.githubusercontent.com/81313/110868541-12c6fc00-82c9-11eb-8cb6-5c7ffe64eb2c.mov

**Comment by skyjake** [comment]
Do you use multiple monitors? Looks like it's confused about the display pixel ratio for some reason.

**Comment by arturh** [comment]
Yes, actually I noticed it only happens on my second monitor.

**Comment by skyjake** [comment]
All right, I'll investigate...

**Comment by arturh** [comment]
Thanks a million

**Comment by skyjake** [comment]
This could actually just be the same as issue #83, which has been implemented for the upcoming v1.3.

Let's revisit once that version is out?

**Comment by arturh** [comment]
Sure!

**Comment by skyjake** [comment]
@arturh Does v1.3.1 improve things for you?

**Comment by skyjake** [comment]
#239 is a related issue, although it doesn't change the pixel ratio behavior on macOS.
