### ISSUE TITLE
Window size limited to a maximum of approx. 1024 * 768

### ISSUE THREAD

**Issue by AndreasSchuette** [skyjake/lagrange#199]
On one of my systems the window size of Lagrange 1.2.2 is limited to about 1024 * 768 pixels. I use the 64bit variant on Windows 8.1. The window cannot be enlarged or maximized beyond this size. The behavior already occurred in version 1.2.1 (same "flavor").
I have not tested previous versions. The system is a Panasonic Toughbook CF-19 MK5 (native screen 1024 * 768 with four additional full HD displays on DisplayLink adapters).

**Comment by skyjake** [comment]
This is likely happening because Lagrange is not fully aware of multiple monitors and uses the wrong monitor's size information. The fixes made in #83 should help a lot here.

Does it (mis)behave in the same way with the _Custom window frame_ option enabled and disabled? (Quit and relaunch the app after toggling the option.)

**Comment by AndreasSchuette** [comment]
It does (mis)behave in the same way no matter if Custom windows frame option is enabled or disabled.

**Comment by skyjake** [comment]
@AndreasSchuette Does v1.3.1 work any better?

**Comment by AndreasSchuette** [comment]
**@skyjake** Unfortunately no change - Lagrange still shows the same behavior.

**Comment by skyjake** [comment]
I am now able to reproduce this. Let's see what's the problem...

**Comment by skyjake** [comment]
Fixed for v1.3.2.

**Comment by AndreasSchuette** [comment]
**@skyjake:** as soon as v1.3.2 has been released, i'll test and report here. Thank You!

**Comment by AndreasSchuette** [comment]
Everything works as expected now! Thank You very much! (Tested on Windows 8.1 Professional x64)

**Comment by skyjake** [comment]
No problem! Let me know if you notice any other issues with window behavior.

**Comment by AndreasSchuette** [comment]
Of course - I do!
