### ISSUE TITLE
Option to open tab in background when pressing Ctrl+Click

### ISSUE THREAD

**Issue by waweic** [skyjake/lagrange#20]
The title basically says what this is about. I will have a look into the code and see if I can implement it myself

**Comment by skyjake** [comment]
Quick check with Firefox/Safari shows that (on a Mac) Cmd+Click should be "open tab in background" and Shift+Cmd+Click should be "open tab in foreground". I'll implement the same behavior in Lagrange, it's pretty much a one-liner. 🙂
