### ISSUE TITLE
Incorrect text wrapping of ellipses and decimal points

### ISSUE THREAD

**Issue by printfn** [skyjake/lagrange#201]
I've noticed that text containing ellipses or decimal numbers (... or e.g. 1.2) sometimes incorrectly gets wrapped onto the next line. For example, this is on gemini://gemini.circumlunar.space/~solderpunk/gemlog/tls-musings.gmi:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1643883/111012892-70ab2f00-8402-11eb-98e3-c75b3bee50b9.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1643883/111012994-c253b980-8402-11eb-88ae-2c2329869cd4.png">

I'm running Lagrange 1.2.2 on macOS 11.2.3.

**Comment by skyjake** [comment]
I've been eyeing the same issue for a while now. The word wrapping needs some tuning when it comes to punctuation.
