### ISSUE TITLE
Network/TLS Failure

### ISSUE THREAD

**Issue by stemy2** [skyjake/lagrange#202]
Hello,

I can't access to any gemini website because of this error.

```
🖧 Network/TLS Failure
Failed to communicate with the host. Here is the error message:

>TLS/SSL handshake failed
```

Did i missed something in the parameters ?

**Comment by skyjake** [comment]
Could you provide some details about your setup:

* Which operating system do you use?
* Did you compile Lagrange manually?
* If so, which version of OpenSSL or a compatible SSL library do you have?

**Comment by stemy2** [comment]
Debian stable
I did not compiled it myself, i'm using the appimage.

**Comment by skyjake** [comment]
Sorry, not really sure what's going on here. It is possible that the AppImage is somehow incompatible with your system. It might be useful to try compiling Lagrange from a source tarball and testing if it works any better when it's using the local versions of all the system libraries.

**Comment by ghost** [comment]
I'm having the same issue on Kubuntu with the Flatpak and AppImage. I tried compiling from both the release and dev branch to no avail.

Edit: OpenSSL version is 1.1.1f

**Comment by Mr-Andersen** [comment]
Same
OS: Fedora 32 / Linux 5.11.11-100.fc32.x86_64
Lagrange: compiled manually
OpenSSL: openssl-1.1.1k-1.fc32

**Comment by skyjake** [comment]
I suspect this has something to do with how sockets are used in `TlsRequest`. OpenSSL is probably not to blame here.

@Cliveptr @Mr-Andersen do you have IPv6 configured on your systems?

Could you do a fully-enabled debug build (CMAKE_BUILD_TYPE=Debug, TFDN_ENABLE_DEBUG_OUTPUT=YES) and send me the output (with `-E` option when running), please?

**Comment by Mr-Andersen** [comment]
`lagrange -E gemini://gemini.circumlunar.space/users/solderpunk/gemlog/`
Here is log: https://gist.github.com/Mr-Andersen/70f45af18ba9362437fcd0f7d3c96bc5
P.S.: Lagrange IS beautiful, thank you for it.

**Comment by Mr-Andersen** [comment]
On IPv6: WiFi connection shows an ipv6 address, so I assume, yes

**Comment by ghost** [comment]
Yes, I have IPv6 enabled.

**Comment by skyjake** [comment]
@Mr-Andersen The log says it tried to use the IPv4 address (168.235.111.58) to make the connection, but a route was not found. Is your system IPv6-only? That would certainly be a configuration that I've never tested.

**Comment by Mr-Andersen** [comment]
Nope, IPv4 is on too

**Comment by skyjake** [comment]
That's strange then... Are you able to use the OpenSSL command line tool to make a successful request?

```
echo "gemini://gemini.circumlunar.space/\r" | openssl s_client -servername gemini.circumlunar.space -ign_eof -host 168.235.111.58 -port 1965
```

**Comment by ghost** [comment]
Now that's weird... mine works now. Nothing I did should effect it.
Unfortunately I didn't capture an unsuccessful log, but [here are the successful ones](https://archive.cliveptr.cc/github.com/skyjake/lagrange/issues/202/).

**Comment by skyjake** [comment]
@Mr-Andersen Any improvement with 7dd1cdf9d5587e7ebc2a5c6203ad5d69e0d4e5d0? I reviewed the connection code and it is possible that it terminated the attempt too early if there are multiple IP addresses found matching a host.

@Cliveptr Not sure what could be the underlying reason, apart from there being multiple IP addresses that are sometimes discovered in a different order so it doesn't stop trying too early? Could be something unrelated, of course.

**Comment by Mr-Andersen** [comment]
```
> echo "gemini://gemini.circumlunar.space/\r" | openssl s_client -servername gemini.circumlunar.space -ign_eof -host 168.235.111.58 -port 1965
139793884137280:error:02002071:system library:connect:No route to host:crypto/bio/b_sock2.c:110:
139793884137280:error:2008A067:BIO routines:BIO_connect:connect error:crypto/bio/b_sock2.c:111:
connect:errno=113
```
Checked out last commit, here is `lagrange -E gemini://gemini.circumlunar.space/users/solderpunk/gemlog/` log: https://gist.github.com/Mr-Andersen/b0c3eb424589605e3328c2ee3aab88f8

**Comment by skyjake** [comment]
> 139793884137280:error:02002071:system library:connect:No route to host:crypto/bio/b_sock2.c:110:

Well at least this is consistent, OpenSSL is having the same problem connecting to an IPv4 address. Which also means it isn't a problem unique to my code.

Now Lagrange attempts a second time with the IPv6 address as expected, but that doesn't seem to work either:

```
[Socket] connecting async to [2604:180:f3::185]:1965 (addrSize:28 index:0)
[Socket] family:10 type:1 protocol:6
[Socket] result from connect: rc=-1 errno=101 (Network is unreachable)
```

I actually don't know if gemini.circumlunar.space supports IPv6, but the fact that both Lagrange and `openssl` fail to connect via a plain IPv4 address suggests a network configuration issue, a firewall blocking 1965, or some other problem of this kind.

Are you able to connect to gemini.circumlunar.space with another Gemini client?

**Comment by Mr-Andersen** [comment]
Oops. No, I cannot. Sorry about all this then

**Comment by Mr-Andersen** [comment]
Yep. `torify lagrange ...` works as expected. At least I can browse geminispace now :)

**Comment by skyjake** [comment]
No worries, at least one bug got fixed.

**Comment by skyjake** [comment]
@stemy2 Not sure if any of this helps with your issue, but I suggest checking the connectivity with `openssl` like in my [comment above](https://github.com/skyjake/lagrange/issues/202#issuecomment-815136941).
