### ISSUE TITLE
page freezes on atom feed (numeric XML character entity)

### ISSUE THREAD

**Issue by t-900-a** [skyjake/lagrange#205]
using appimage on ubuntu
Not sure how to collect detailed logs to determine why the page freezes.

The atom feed that freezes is one generated by flounder.

gemini://t-900.flounder.online/gemlog/atom.xml

**Comment by skyjake** [comment]
Thanks for reporting! This is a bug in Lagrange's XML parser. It doesn't yet understand `&#nnnn;` entities.

Will fix.

**Comment by skyjake** [comment]
Fixed in https://git.skyjake.fi/skyjake/the_Foundation/commit/c2885defff5d04d0839a9f1369493b8760b031fe.
