### ISSUE TITLE
Lagrange doesn't display a git:// URI at all

### ISSUE THREAD

**Issue by ElonSatoshi** [skyjake/lagrange#208]
How to reproduce: 

1. Go to gopher://bitreich.org:70/1/lawn in Lagrange. Scroll down to the bottom, where it says:

```
If you want to save the moderators time, check out
and add a file with categories and keywords to the »db« directory. There
are many example files in there for how the format looks like.
```

2. Go to gopher://bitreich.org:70/1/lawn in another Gopher client, such as `sacc`. Scroll down to the bottom, where it says:

```
If you want to save the moderators time, check out
git://bitreich.org/gopher-lawn
and add a file with categories and keywords to the »db« directory. There
are many example files in there for how the format looks like.
```

3. Compare the difference.

Here are some screenshots.
![Screenshot from 2021-03-13 13-09-49](https://user-images.githubusercontent.com/24940510/111079365-b54cce00-84c7-11eb-8c32-c1cabf597096.png)
![Windowshot-2021-03-13-20:03:14](https://user-images.githubusercontent.com/24940510/111079369-b7169180-84c7-11eb-80f1-19409303c914.png)

**Comment by skyjake** [comment]
Fixed for next release.
