### ISSUE TITLE
Bitcoin URIs don't display correctly

### ISSUE THREAD

**Issue by t-900-a** [skyjake/lagrange#215]
Reference: https://en.bitcoin.it/wiki/BIP_0021

- What the link should be

`bitcoin:1fadfaiuhfiausffaefdsf`

- What the link displays as

`bitcoin://<currentdomainname>/1fadfaiuhfiausffaefdsf`

**Comment by skyjake** [comment]
Yeah I don't think "bitcoin" is a recognized scheme at the moment in the app.
