### ISSUE TITLE
Offer zsync files with appimages

### ISSUE THREAD

**Issue by adnan360** [skyjake/lagrange#216]
Thanks for creating this project. It makes browsing Gemini websites close to a normal web browser - simple and easy.

I use appimage version of Lagrange, which makes it easy to use on any distro. One problem is that it takes manual steps to update. One way to fix this is to use [AppImageUpdate](https://github.com/AppImage/AppImageUpdate). To utilize this however, the project needs to [include a .zsync file](https://docs.appimage.org/packaging-guide/optional/updates.html?highlight=zsync) with each release.

Please include this so that updates can be easier.

**Comment by skyjake** [comment]
OK, I'll look into it. I should be able to integrate that into my AppImage build scripts.

**Comment by skyjake** [comment]
Starting with v1.3.3, .zsync files are now included in releases using GitHub as the update URL.
