### ISSUE TITLE
Rendering/download stops prematurely on some sites

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#22]
Linux / x86_64 / Lagrange v0.7.1

One site is rendering incompletely in Lagrange. I tried a few refreshes, same result. No idea how to tell if this is a server issue or client issue (no logs in the terminal). It's working fine in another browser.

gemini://bleyble.com

![Screenshot_2020-11-03_09-25-36](https://user-images.githubusercontent.com/270504/97997323-c03c7700-1de0-11eb-993b-32cc388ce91a.png)

Same site in Kristall Browser:

![Screenshot_2020-11-03_09-26-13](https://user-images.githubusercontent.com/270504/97997407-d4807400-1de0-11eb-90f4-6f970bc7c284.png)

gemini://bleyble.com/users/quokka/

![Screenshot_2020-11-03_09-27-00](https://user-images.githubusercontent.com/270504/97997444-dcd8af00-1de0-11eb-9101-eac49feec7ee.png)

![Screenshot_2020-11-03_09-26-30](https://user-images.githubusercontent.com/270504/97997490-e82bda80-1de0-11eb-81ea-11e3d45e1c2b.png)

Lagrange is absolutely amazing. Thank you so much for your hard work!

**Comment by skyjake** [comment]
Hmm, a quick test on the Mac shows that `bleyble.com` gives this error page:

> Network/TLS Failure
> Failed to communicate with the host. Here is the error message:
> "error while decrypting incoming data"

OpenSSL has some flags and options to tweak that might help in cases like this, but there's no guarantee those will work. Another possibility is that there's some glitch in the handling of incoming data related to the socket being closed by the peer. I'll investigate...

> Lagrange is absolutely amazing. Thank you so much for your hard work!

You're welcome! 🙂

**Comment by ghost** [comment]
Maybe it has to do with `bleyble.com` having an expired certificate (notice the yellow lock in my screenshot)...

**Comment by skyjake** [comment]
Being expired shouldn't cause an error like this, if the certificate is otherwise valid.

**Comment by skyjake** [comment]
Well, this works:

```bash
echo -e "gemini://bleyble.com/\r\n" | openssl s_client -servername bleyble.com -connect bleyble.com:1965 -ign_eof
```

So the problem is definitely a bug in my code.

**Comment by skyjake** [comment]
I think 5c0f9d0c8cd38b5534c920a61cbb4c99f789d31e fixed the issue.

**Comment by ghost** [comment]
Working for me! :+1:
