### ISSUE TITLE
Pressing Continue after saving page

### ISSUE THREAD

**Issue by lifelike** [skyjake/lagrange#221]
I would prefer if the information dialog saying that the page had been saved could just be a small notice in the corner somewhere that disappeared by itself. Maybe have a setting to choose to have the dialog waiting for the user to press the continue button if that is something someone finds useful.

**Comment by skyjake** [comment]
Yeah I agree that the file save dialog is a bit clunky. It is among the parts of the UI that could use refinement.

Note that currently you can dismiss it also by pressing Space, Enter, or Escape on the keyboard.
