### ISSUE TITLE
Add support for XF86Back and XF86Forward

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#223]
XF86Back and Forward are keys on some keyboards (like on old thinkpads) that go back/forward in history in normal browser.
SDL scancodes for those keys are 270 and 271 for Back and Forward respectively. Would you mind adding them to go back/forward in history for more convenience please?

**Comment by skyjake** [comment]
I think it makes sense to add all of these as built-in bindings for the corresponding commands:

```
    SDLK_AC_SEARCH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH),
    SDLK_AC_HOME = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME),
    SDLK_AC_BACK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK),
    SDLK_AC_FORWARD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD),
    SDLK_AC_STOP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP),
    SDLK_AC_REFRESH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH),
    SDLK_AC_BOOKMARKS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS),
```
