### ISSUE TITLE
Ctrl+Q and some other Ctrl shortcuts stop working

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#224]
I can't quit Lagrange with `Ctrl+Q`, while there is no such problem with other Qt/GTK based apps.

OS: Linux/X11

**Comment by skyjake** [comment]
I assume you are running the dev branch? I have noticed recently that on X11 the Ctrl modifier stops being recognized some time after running the app.

Does it work for you immediately after launching?

**Comment by sikmir** [comment]
> I assume you are running the dev branch?

Yes.

> I have noticed recently that on X11 the Ctrl modifier stops being recognized some time after running the app.

Indeed, but for example `Ctrl+T`, `Ctrl+=`, `Ctrl+-` still works. And the same issue with `F1`.

> Does it work for you immediately after launching?

Yes.

**Comment by skyjake** [comment]
This must be a regression of some kind, I'll need to investigate a bit.
