### ISSUE TITLE
Non-ASCII input doesn't work

### ISSUE THREAD

**Issue by Carmina16** [skyjake/lagrange#227]
It is impossible to type any non-ASCII characters into the text fields.

**Comment by skyjake** [comment]
Could you provide some information about your system, please? (OS, desktop environment, locale settings; environment variables from Lagrange's "about:debug")

Without any context, my first guess is that the version of SDL on your system has a problem dealing with UTF-8 text input.

Unicode input works on all the systems I've tried (Mac, Windows, Linux, Raspi at least), and there are no other reports of this problem occurring.

**Comment by Carmina16** [comment]
It seems it caused by using obsolete locale functions in X, like `XLookupString`. I suppose it is SDL bug then.
