### ISSUE TITLE
Window title garbled

### ISSUE THREAD

**Issue by Carmina16** [skyjake/lagrange#228]
At least in the Mate DE, the non-ASCII characters in the title of Lagrange's window are garbled - UTF-8 is displayed as a sequence of Latin-1 characters.

**Comment by skyjake** [comment]
The window title is set using [SDL_SetWindowTitle()](http://wiki.libsdl.org/SDL_SetWindowTitle) where the title string is in UTF-8. What happens after that depends on SDL's internals and the window system. I would therefore consider this mostly an SDL bug.

I could add a build option (off by default) to force the window title to 7-bit ASCII?

**Comment by Carmina16** [comment]
It seems SDL is lagging behind the modern toolkits. I managed to work it around by changing X locale settings.
