### ISSUE TITLE
User preference for bold links

### ISSUE THREAD

**Issue by alyssarosenzweig** [skyjake/lagrange#233]
I just updated Lagrange, see links are now bolded. I'm a bit overwhelmed by this visually, and am curious what the rationale was. The commit message says to make them stand out, but with the icons, different spacing, lighter colour, links already stood out. Adding bold on top feels 'too much', especially for pages that link heavy like CAPCOM.

I patched it out of my local build, but as others might feel similarly, I thought it was worth mentioning.

**Comment by alyssarosenzweig** [comment]
(I notice gmi.skyjake doesn't bold links either. It looks great, by the way! I don't suppose you have your gmi->html and lagrange-style css available / FOSS anywhere? :P)

**Comment by skyjake** [comment]
Adding an option for this is certainly doable. Some of the font weights could also be adjusted (i.e., semibold).

The rationale (from gemini://skyjake.fi/gemlog/2021-04_lagrange-1.3.gmi):
> There are issues with relying on color, though. In Colorful Dark, where body text is usually colored, I've found it harder to read the bright-white link lines compared to the rest of the text. Also, on bright backgrounds, links and body text have been drawn in the same color, leaving the icon as the only differentiator.
>
> To improve on both of these problems, links are now displayed using a bold font. This allows them to be distinct on light backgrounds, too, and they can be clearly tinted with the theme color for consistency. 

The gmi.skyjake.fi stylesheet was written to match v1.0 and hasn't been updated since...

The source is in a private repo currently because it's very specific to gmi.skyjake.fi. You can view the Python source here: https://media.skyjake.fi/gmi-hatch.py

The license (not mentioned in the .py file) is BSD 2-clause like with Lagrange.

**Comment by skyjake** [comment]
Also, forgot to mention in the release post that the distinctiveness of the link icons and the link text greatly depends on the color theme and its random parameters. Bold text has a much greater chance to look distinct in all themes.

**Comment by alyssarosenzweig** [comment]
I see, I'm experimenting with different themes now.

On light themes (white, sepia, high contrast), the bold works for my
eyes. Colorful Light doesn't work for my eyes regardless of bold.

For dark themes (grey, black, colorful dark), the bold is overwhelming
for me. Colorful Dark likewise is a bit much for me regardless of bold.

The standard on the web is underlining instead of bold, I'm not sure if
that's better or worse here. Mostly I'm not sure why links need to be
emphasized so heavily, when the icon already serves for this. Might just
be me.

>    The source is in a private repo currently because it's very specific to
>    gmi.skyjake.fi. You can view the Python source here:
>    https://media.skyjake.fi/gmi-hatch.py

Nice, thank you 😃

**Comment by alyssarosenzweig** [comment]
Relatedly, mixing a dark interface theme with a light content theme
creates severe contrast problems on accent colours (e.g. when hovering
over a link). I don't know if this is a supported use case or not.

**Comment by skyjake** [comment]
> severe contrast problems on accent colours (e.g. when hovering over a link)

That should be considered a bug... All the possible color combinations should yield legible results.

**Comment by skyjake** [comment]
Closing this as the original issue has a user preference in v1.3.1.

The color contrast problems should be moved to another issue.
