### ISSUE TITLE
Thanks for Lagrange!

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#238]
Hi, I wanted to drop by and leave a note that this software is amazing. I've been playing around with the new release and...

- Replacing link icons w/ emojis is really elegant
- The new translation tool is straight up magic
- Everything works seamlessly across desktop and mobile
- gopher:// and finger:// both work great

The amount of built-in functionality in Lagrange is insane! You rock!

**Comment by skyjake** [comment]
Thanks for the feedback, I really appreciate it!

**Comment by alyssarosenzweig** [comment]
Seconding Michael <3
