### ISSUE TITLE
Incorrect scaling with HiDPI + Wayland (sway)

### ISSUE THREAD

**Issue by DawidLoubser** [skyjake/lagrange#239]
Good day,
When running `lagrange` on a HiDPI monitor under `sway` WM, not only does the UI and rendered content not honour the scaling, it in fact seems unbearably small in the "opposite" direction, i.e. if I scale my monitor by 2, it seems to run at _less than 1.0_ scale.

Also, the usual problems such as the right-click context menu appearing in completely the wrong position etc.

As `lagrange` (and Gemini in general) aligns so well with the minimalist aesthetic of running `swaywm`, it would be really useful if I could use lagrange on my HiDPI hardware under `sway`.

# Screenshot

Launched with default settings, and a 1.5 scale on my monitor: `lagrange` to the left, `amfora` running in my terminal at a comfortable font size, to the right.

![lagrange-amfora](https://user-images.githubusercontent.com/506878/113689236-64955300-96ca-11eb-962c-166fe79d3e3a.png)

**Comment by skyjake** [comment]
This problem could be rooted in SDL's DPI detection. I'm not sure how well it works under Wayland.

You should still be able to manually scale Lagrange's UI in Preferences > Interface > UI Scale Factor? If the UI is too small to access that, it's also in ~/.config/lagrange/prefs.cfg:

```
uiscale arg:1.00000
```

Try changing that to `arg:1.5` or `arg:2.0`.

**Comment by skyjake** [comment]
If you have recommendations/suggestions as to how to detect the correct DPI under Wayland, I'm all ears. :)

**Comment by DawidLoubser** [comment]
Thanks for the fast reply! Manually scaling in the config file did the trick.
It's interesting that I had to put in a factor much larger than what the rest of my desktop environment is using, so something is definitely working "against" the default scaling here.

And - off-hand, I'm not sure about detecting the scaling, but I'm going to look into it and see if I can send a merge request. I'm a server-side engineer (Go, Rust, Node...) and have very little experience in C-based GUI apps, but I'd love to dig in and help if I can. I feel this is something that usually doesn't have to be done, most UI toolkits have it baked in, but of course if you're coding at a low level I can see why you'd need to detect it yourself.

Kudos for an excellent piece of software, and for the fast and friendly reply. I wish more maintainers were like you!

**Comment by DawidLoubser** [comment]
P.S. Even with the scaling parameter, the right-click context menu is still way our of whack, so that's another interesting problem to solve. I really hope I can get some time to dig into your code, I'd love to contribute.

**Comment by DawidLoubser** [comment]
I'm afraid that with the scaling set in the config file, it *appears* correct, but like with the context menu, thinks like clicking of links is broken; links not at all under the mouse cursor are being activated etc.

At the moment, definitely not usable under scaled wayland.

**Comment by skyjake** [comment]
There is another place in the code that scales incoming mouse event coordinates. It sounds like the incorrect DPI value coming from SDL is affecting that. Should be fixable, perhaps by adding an option to ignore the DPI queries and just set whatever DPI value the user wants to use (e.g., by adding an environment variable for this).

**Comment by skyjake** [comment]
I suspect things would work correctly for you if you change `pixelRatio_Window_()` to use the last branch of the ifdef:

```
    int dx, x;
    SDL_GetRendererOutputSize(d->render, &dx, NULL);
    SDL_GetWindowSize(d->win, &x, NULL);
    return (float) dx / (float) x;
```

(I.e., it determines the pixel ratio by looking at the difference between render pixels and logical window coordinates.)

Then, `coord_Window()` would need to use this branch:

```
    /* Coordinates are in points. */
    return mulf_I2(init_I2(x, y), d->pixelRatio);
```

If this helps, I should make it an actual build config option so it can be enabled instead of the X11-friendly behavior.

**Comment by skyjake** [comment]
Now that I think about it, there's a bug here in that the pixel ratio is conflated with the display DPI factor. The pixel ratio is always required for correct conversions between window coordinates and actual pixels, and the DPI factor is supposed to affect what UI scale factor 1.0 looks like, regardless of how many pixels there are. It should be possible to simpify this by making these separate values.

**Comment by skyjake** [comment]
The recent commits should help with this issue. The points-to-pixels ratio is now independently applied as appropriate.

I don't have a Wayland setup to test this with, so feedback is welcome. I'm a bit unsure whether it's OK to have both the pixel ratio _and_ the DPI affect UI sizing at the same time, but at least mouse events should now be correctly positioned.

**Comment by DawidLoubser** [comment]
Awesome! I'm going to build from source a bit later and provide feedback from a wayland setup.

**Comment by DawidLoubser** [comment]
Built latest `master` from source, it's certainly a lot better now! Your fixes have addressed the issues with not being able to click on links, or the context menu appearing at the wrong location.

Strangely, the UI is now too massive by default. I removed my `~/.config/lagrange` directory to ensure I'm running on defaults, and the UI is rather large - this is on `sway` running with a default scale of `1.0` on a `1920x1080` monitor, with `amfora` for scale on the right running in my terminal at a default font size (`13px` in my case).

![lagrange-amfora-post-fix](https://user-images.githubusercontent.com/506878/113924637-56d6ef00-97ea-11eb-806c-ed1bd9eda70d.png)

Nothing I can't fix by tweaking `lagrange`'s scale factor manually (`0.7` seems pretty good), so thank you so much for the fix!

**Comment by skyjake** [comment]
Great! My guess is that the display DPI value doesn't reflect the pixel ratio being larger than 1.0 (perhaps because SDL is unable to query it under Wayland?), so everything is larger than one would assume. But this is why the UI scale factor setting is there I guess...
