### ISSUE TITLE
IPFS Support

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#240]
Perhaps you can implement IPFS Support? https://ipfs.io
It's a bit complicated I am guessing but I think you can do it somehow

**Comment by ghost** [comment]
It would be pretty cool to see Distributed Gemini Capsules on the dweb

**Comment by skyjake** [comment]
Peer-to-peer networks are pretty cool, but this seems too far removed from "standard Gemini" to be in the scope of the project at this time.

I would also imagine that serverside peer-to-peer content distribution would be generally more useful so it would work with all clients.

**Comment by ghost** [comment]
Makes sense

**Comment by ninedraft** [comment]
Hello!

I think it makes sense to not implement a full IPFS stack, but just proxy-like interaction with `ipfs://$HASH` links. Lagrange just needs to fetch `http[s]://$GATEWAY_DOMAIN/ipfs/$HASH` content and render it.

User can choose local or remote IPFS gateway to access such pages.
