### ISSUE TITLE
RPi install fails

### ISSUE THREAD

**Issue by mroberts1** [skyjake/lagrange#242]
I've been trying to install Lagrange on a Raspberry Pi 4 running the current version of Raspian, using flatpak. When I run the install command:

  flatpak install flathub fi.skyjake.Lagrange

I get

  Nothing matches fi.skyjake.Lagrange in remote flathub

Any idea why that might be? The RPi flatpak set up appeared to succeed.

**Comment by skyjake** [comment]
I'll investigate. The Flathub builds are likely missing the arm architecture for Raspberry Pi.

I have been running Lagrange on my Raspberry Pi 400 and it works great there.

**Comment by skyjake** [comment]
[There's a note on flatpak.org about Raspberry Pi](https://flatpak.org/setup/Raspberry%20Pi%20OS/):

> **Important note:** As of March 2021, Raspberry Pi computers still ship with the 32-bit version of Raspberry Pi OS. However Flathub started phasing out support for that architecture. If you consider Flathub as an important source of applications, it is recommended to use Raspberry Pi OS 64-bit as newer applications are more likely to be available for that platform.

I understand this means that recent versions of Flatpak runtimes will not include support for ARM 32-bit.

However, Lagrange does not require a very recent version of the runtime, so I've downgraded it to Freedesktop 19.08. You should now be able to install Lagrange from Flathub on 32-bit Rasperry Pi 4. (Just tested on my Pi 400.)
