### ISSUE TITLE
Incorrect scaling on vertically oriented monitor

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#246]
One of my monitors is oriented vertically, so its vertical resolution is greater than its horizontal resolution. This seems to mess with a DPI calculation or something, as when I open Lagrange on it, the scaling is far too big. I haven't looked at the code but it seems like it might be as simple as doing a calculation based on the minimum between display width and height instead of just basing it on display height.

**Comment by skyjake** [comment]
Lagrange queries DPI information via [SDL](https://libsdl.org) so I'm guessing there's either a bug in SDL or the monitors are reporting an incorrect DPI value.

I've received another report of a similar issue. As a workaround, there will be an environment variable that lets you override Lagrange's DPI detection with an arbitrary value for all monitors. Hopefully this will work with your setup, too.

As a future enhancement, I could consider adding per-display UI scale factors.

**Comment by skyjake** [comment]
An environment variable for setting the DPI value is now available in the dev branch, if you want to try compiling yourself. Documentation: https://github.com/skyjake/lagrange/blob/9fd5f867ae1a3d5ed8278359582cd99ca89a0318/res/about/help.gmi#L452

**Comment by skyjake** [comment]
v1.3.3 is out, let me know if this is a sufficient fix...

**Comment by ghost** [comment]
> v1.3.3 is out, let me know if this is a sufficient fix...

Now, when opening Lagrange on my second monitor its DPI is correct, but when it gets resized the DPI changes and everything is too big again.

**Comment by skyjake** [comment]
Did I understand this right: you manually resize the Lagrange window when it's on the second monitor, and the UI gets rescaled to a different size? 

* Have you set the new `LAGRANGE_OVERRIDE_DPI` environment variable to force a specific DPI value to be used?
* Does the window span two monitors?
