### ISSUE TITLE
xdg-open can't open a new gemini site if lagrange is already open (Flatpak)

### ISSUE THREAD

**Issue by fdr** [skyjake/lagrange#248]
Works: clicking a gemini link if lagrange is not yet open.

Doesn't work: navigating to a new site (in a tab, window, or whatever) if lagrange is already open.

Perhaps related: "New Window" in the GNOME dropdown menu also appears to be a no-op.

I am on Fedora 33, using the flatpak installation, from flathub.

**Comment by skyjake** [comment]
This is most likely caused by #245. The Flatpak version needs a little more work to support this use case.

**Comment by fdr** [comment]
Thanks, should we close this as a dupe? I think that'd be alright, even if I have to come back again later.
