### ISSUE TITLE
Unable to play audio (play button), or to see content of audio hamburger menu

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#249]
I am running Lagrange 1.3.2 from Flathub on Fedora 33 and I am unable to play audio (play button), or to see content of audio hamburger menu.
![image](https://user-images.githubusercontent.com/66519591/115147362-f9009d80-a05a-11eb-88ab-7503efd3d31f.png
I tested on gemini://gem.chriswere.uk/aprilcast/ or gemini://gem.chriswere.uk/aprilcast/

**Comment by skyjake** [comment]
The problem was that the audio player's MIME type check didn't account for possible additional parameters that follow the type. Narrowly missed the v1.3.3 patch but fix is in the dev branch now.

**Comment by skyjake** [comment]
Fixed in v1.3.4.
