### ISSUE TITLE
UX: improved handling of http resources

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#25]
I like to browse the SmallWeb (where I spend a lot of time) with Lagrange + duckling_proxy, but often a Gemini site links to a BigWeb site, and then I get gibberish instead of being thrown into a web browser.

So I would like to have a button and/or keystroke to easily enable/disable the proxy without having to go through the dialog box and wipe it out and then re-enter it later.  That way, SmallWeb browsing remains straightforward, but when I see that a link is BigWeb, I can disable the proxy, click on the link, and re-enable the proxy when I come back to Lagrange.  (There is no need to do this for the gopher proxy, for Lagrange + agena is as capable as any Gopher client.)

I realize that screen space is precious and creeping featurism is bad, but I'd really like to make Lagrange my main browser for the SmallWeb.

**Comment by skyjake** [comment]
Hmm, how about a context menu item “Open without proxy” when right-clicking an HTTP link?

**Comment by johnwcowan** [comment]
LGTM.
