### ISSUE TITLE
Gopher URLs mangled when called via URL handler

### ISSUE THREAD

**Issue by nikdoof** [skyjake/lagrange#250]
If Lagrange is already open and another application calls its URL handler for a Gopher URL, Lagrange tries to parse it as a file:/// URL.

![mac-url-handling](https://user-images.githubusercontent.com/170514/115271476-4d784b80-a135-11eb-8a28-72ca24f3e48b.gif)

Gemini URLs work as expected.

macOS 11.2.3
Lagrange 1.3.0

**Comment by skyjake** [comment]
Could you test this with v1.3.2? I believe this should be fixed there.

The relevant commit is 033050c5077ebcb02dd9f03ee2747284e1a0c5cf.

**Comment by nikdoof** [comment]
Yep, works in v1.3.3, thank you.
