### ISSUE TITLE
Certificate domain vaildation fails with CN=*.com

### ISSUE THREAD

**Issue by rodolphoeck** [skyjake/lagrange#251]
Sourcehut's Gemini hosting service (gemini://srht.site/) uses certificates with wildcards and just the TLD in the common name (to be as generic as possible), for example CN=*.com and CN=*.site.

The domain validation in Lagrange fails and an error message is displayed: "UNTRUSTED CERTIFICATE".

I found the comment at https://github.com/skyjake/lagrange/blob/1e5dfdc840824723dfa142707aca1f0fca4c0056/src/gmcerts.c#L396 and I'm wondering (sorry, not much time to read the code further) if this is expecting common names to have at least two non wildcard labels.

**Comment by skyjake** [comment]
The wildcard check is done by OpenSSL and I’m pretty sure it has no concept of a certificate that covers an entire TLD.

I think in the context of Gemini it’s fine to use more lenient wildcard checking, although it needs to be done manually.

The referenced line is related to implicit wildcards where a “site.tld” certificate is automatically allowed for “subdomain.site.tld”.

**Comment by skyjake** [comment]
`TlsRequest` in the_Foundation now supports this kind of wildcards.

**Comment by skyjake** [comment]
Fixed in v1.3.4.
