### ISSUE TITLE
HTTP/HTTPS Links with Query Strings

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#252]
When I try opening an http link with a query string, the URL passed to the default web browser is missing the query string.
Copying the link from the gemini capsule will copy the full link, which means the problem is when it passes the link to the default web browser to handle.

**Comment by skyjake** [comment]
You didn't mention which operating system you're using, but I can reproduce this problem on Windows 10 (Mac and Ubuntu work correctly).

On Windows this can be fixed by upgrading to SDL 2.0.14. I will do so for the next build.

**Comment by skyjake** [comment]
Possibly fixed in v1.3.4, please test.

**Comment by ghost** [comment]
> You didn't mention which operating system you're using

Oh, sorry.

Ok, I will test as soon as I can. Thanks for the fix!

**Comment by ghost** [comment]
Yep, it is fixed for me. Thanks!
