### ISSUE TITLE
Gempub support: rendering the cover page and basic content viewing

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#255]
There is a new gempub (gemini eBook) spec that someone has created that is basically a zip file of gemini files along with a metadata file. Since lagrange can already open zip files, I thought it would be cool if you could also support this gempub spec too, at least for local gempub files.

Spec: https://codeberg.org/oppenlab/gempub

**Comment by ghost** [comment]
Apparently you've already implemented rudimentary support for gempubs (https://codeberg.org/oppenlab/gempub/issues/2)! I *just* found this out, lol. Sorry.

**Comment by skyjake** [comment]
I like the idea of Gempub a lot and will be following this closely.

What I'd really want to see here is a paged book reading mode in Lagrange, especially on iPad or other tablets. Such a reading mode might be cool for "normal" Gemini content as well.

**Comment by ghost** [comment]
Gempub has a few changes recently: there's no longer a mimetype file, and the metadata file's name has changed to metadata.txt. Finally, the metadata file is now required to be UTF-8.

I also have created a gpub file since there's not many example gpub files to test with. On the *first* gemini link, the changes above have not been taken into account.  I have provided an updated gpub with the second link that *does* take the above changes into account.

gemini://pon.ix.tc/poetry.gpub
~~gemini://pon.ix.tc/poetry_updated.gpub~~

Edit: The poetry.gpub was replaced by poetry_updated.gpub since lagrange has now implemented everything for the metadata up to the current spec.
