### ISSUE TITLE
Scrollbar in "Keys" settings tab appears only after I change language or mouse wheel scrolling the list

### ISSUE THREAD

**Issue by CyberTailor** [skyjake/lagrange#257]
I don't know why it happens. Also there's no "Tab" key navigation to work around this.
![screenshot](https://user-images.githubusercontent.com/6988243/116776862-744e5000-aa5a-11eb-89e3-bb88178f1808.png)

**Comment by skyjake** [comment]
Yeah, the Keys scrollbar is a bit broken.

Another way to make it appear is to scroll the list with the mousewheel/trackpad.

**Comment by CyberTailor** [comment]
> Another way to make it appear is to scroll the list with the mousewheel/trackpad.

Yeah, there's nothing resembling mousewheel on a graphics tablet.

Possible solution would be resizing a popup to fit the whole list.

**Comment by skyjake** [comment]
I agree there is no reason to limit the size of the list when the window is large enough, but of course the scrollbar bug needs fixing regardless.
