### ISSUE TITLE
gopher "h" type isn't displayed

### ISSUE THREAD

**Issue by rapenne-s** [skyjake/lagrange#258]
On the gopher resource gopher://bitreich.org:70/1/usr/solene/park_rennes.cgi there should be a few lines which are of h type to openstreetmap, they are correctly rendered in sacc and bombadillo clients but hidden in Lagrange. I tried a few other gopher content and the http links are all hiddens.

I'm using Lagrange 1.3.4 on OpenBSD amd64

**Comment by skyjake** [comment]
According to [RFC 1436](https://tools.ietf.org/html/rfc1436), Gopher lines are terminated by `\r\n` but park_renner.cgi only uses `\n`. That is why Lagrange disregards the content.

Do you have a reference that specifies Gopher lines terminated by `\n` should also be allowed, or is this just common convention among clients? (I don't have much experience with this myself.)

**Comment by rapenne-s** [comment]
Indeed, thanks for pointing me out the missing `\r`, I forgot about this one.

However, on this page: `gopher://bitreich.org:70/1/usr/solene/linuxfr/` there should be a link at the top, I confirm that the line ends with `\r\n` but isn't displayed in Lagrange.

**Comment by skyjake** [comment]
I'm getting this response from the Gopher server, and it has only a `\n` terminating the line (same for preceding line)?

```
000000c0  30 0a 68 4c 69 65 6e 20  76 65 72 73 20 6c 65 20  |0.hLien vers le |
             ^^
000000d0  66 6c 75 78 20 41 54 4f  4d 09 55 52 4c 3d 68 74  |flux ATOM.URL=ht|
000000e0  74 70 73 3a 2f 2f 6c 69  6e 75 78 66 72 2e 6f 72  |tps://linuxfr.or|
000000f0  67 2f 6e 65 77 73 2e 61  74 6f 6d 09 62 69 74 72  |g/news.atom.bitr|
00000100  65 69 63 68 2e 6f 72 67  09 37 30 0a 69 09 45 72  |eich.org.70.i.Er|
                                            ^^
```

Do you know if it's possible that the server is doing some sort of automatic line ending conversion here?

**EDIT:** This may have been a problem on my end...

**Comment by skyjake** [comment]
Ah, I noticed that the line is:
```
hLien vers le flux ATOM	URL=https://linuxfr.org/news.atom	bitreich.org	70
```

While (according to Wikipedia) the URL selectors should use a colon (`URL:`) and not an equal sign. That's why the parser ignores it...

**Comment by rapenne-s** [comment]
Sorry for the noise then, it's my fault all along. Gophermap format is tricky.
I replaced `=` by `:` and it displays fine in Lagrange.

**Comment by panicsteve** [comment]
Hi, sorry to bump a closed issue, but I'm also seeing this behavior, and I can't seem to figure it out.

At gopher://[redacted]:70/1/ there should be an https link to Lagrange at the bottom.  It's visible in Bombadillo, but not Lagrange.  Server is pygopherd so I _assume_ it's doing line endings correctly, but maybe not?

**Comment by panicsteve** [comment]
Never mind, I think I just figured this out, and it appears to be a bug in pygopherd.

For 'h' lines, pygopherd prepends a '/' before the 'URL:', which I don't think is correct per the spec.

I was able to fix this by editing `gopherentry.py` and adding lines 191 and 192 below:

```
 188     def getselector(self, default = None):                                                                                         
 189         if self.selector == None:
 190             return default
 191         if self.type == 'h' and self.selector[0] == '/':
 192             return self.selector[1:]
 193         return self.selector
```
