### ISSUE TITLE
Issue Compiling on Latest Dev Commit

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#259]
I am getting this issue when compiling. My system has SDL version 2.0.10 (I can see where the error is, there's a #if check for the SDL version).

![image](https://user-images.githubusercontent.com/4098042/116827384-566a1380-ab5e-11eb-97ad-a8d95dd2bc3f.png)

**Comment by skyjake** [comment]
Yep that needs updating to use the current UI root, I'll fix it.
