### ISSUE TITLE
UX: Mouse wheel scrolls by one pixel

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#26]
That makes it horribly horribly slow to scroll the page with the wheel.

**Comment by skyjake** [comment]
Which OS are you using?

**Comment by johnwcowan** [comment]
Sorry about that.  Mac OS Catalina.

**Comment by skyjake** [comment]
There should be a way to detect which device emitted the events, I'll take a look...

...the issue being that only the trackpad device should do single-pixel scrolling.

**Comment by rnkn** [comment]
I'm also on OS X Catshit and came here to report this.

I just have a cheap USB mouse with a step-style scroll wheel (not a magic mouse) and each wheel step is about a pixel.

Two-finger scrolling via the trackpad works beautifully.

**Comment by skyjake** [comment]
I've found a solution by hacking SDL a bit more. It seems the current version does not make any distinction between mouse devices, so I check if the event has precise scrolling deltas and use that to determine if it's a trackpad or a mouse.

The next build will use this improved event handling.

**Comment by skyjake** [comment]
[0.8.1 is out](https://git.skyjake.fi/skyjake/lagrange/releases) with this fix. At least works for me on a Logitech G502.

**Comment by johnwcowan** [comment]
Thanks!
