### ISSUE TITLE
shelling out to xdg-open leaving zombie process on Linux

### ISSUE THREAD

**Issue by mukappa** [skyjake/lagrange#260]
Each time Lagrange (ver 1.3.2) shells out to xdg-open (ver. 1.1.2) on Linux (Ubuntu 18.04), a zombie process
shows up in the process list.

mukappa@lassie:~$ ps -ef | grep defunct
mukappa  10663 10651  0 03:13 ?        00:00:00 [xdg-user-dir] <defunct>
mukappa  10909 10651  0 03:23 ?        00:00:00 [xdg-open] <defunct>
mukappa  10995 10411  0 03:23 pts/2    00:00:00 grep --color=auto defunct

**Comment by skyjake** [comment]
I can reproduce this. Looks like the processes aren't cleared up after they terminate, only after the parent process (lagrange itself) exits.

**Comment by skyjake** [comment]
32c9c9eda7750422049fa62b35b39838ee4dd679 should fix it. Also applies to the `xdg-user-dir` process.
