### ISSUE TITLE
Customize UI colors

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#263]
I love Lagrange and I think the ability to customize the UI colors would make it an almost perfect small-internet-browsing experience. Is this on the roadmap? :)

**Comment by skyjake** [comment]
I don't have concrete plans for this but it's not a big feature so it could be done at some point for sure.

To clarify, there are two kinds of color palettes in Lagrange: one for the UI, and another for the page content. The first has currently 4 variants (black, dark, light, white) + one accent color, and the page content theme is procedural with a couple of different variations.

I could add a config file where the user's dark/light mode UI theme colors are defined, along with custom accent colors. Those would then apply to everything except the page content.

Sounds good?

**Comment by ghost** [comment]
That would be a perfect solution to this!

**Comment by skyjake** [comment]
A preview: https://skyjake.fi/@jk/106425000842320188
