### ISSUE TITLE
SDL_VIDEODRIVER=wayland breaks lagrange: no window expose event, no window redraw after move/resize

### ISSUE THREAD

**Issue by sseneca** [skyjake/lagrange#264]
Hiya, I tried forcing lagrange to run under Wayland by setting `SDL_VIDEODRIVER=wayland` (from the [arch wiki](https://wiki.archlinux.org/title/Wayland#SDL2)). When run under Wayland, Lagrange acts kinda strange, as demonstrated in this video:

https://user-images.githubusercontent.com/25619071/116986334-2e44f680-acbd-11eb-8f12-659f8d6a4cc4.mp4

It doesn't render pages properly, doesn't resize/move properly, etc. I'm running Sway WM on [Parabola](https://parabola.nu).

Setting `SDL_VIDEODRIVER=x11` (aka running under XWayland) makes it act completely fine again.

Not sure how I can help debug this, let me know!

**Comment by skyjake** [comment]
I wonder if this is mostly an SDL bug? I haven't used Wayland myself so not sure what could be done here...

**Comment by skyjake** [comment]
One thing that does come to mind is that maybe the window isn't receiving any SDL window expose events. You could try setting `d->isExposed = iTrue;` in `init_Window()` where it currently is initialized to `iFalse`.

**Comment by sseneca** [comment]
I compiled it with `d->isExposed = iTrue;` but unfortunately the problem persists. I'm not very familiar with SDL unfortunately.

**Comment by atisharma** [comment]
It works under wayland as packaged in FreeBSD 13.0-RELEASE (lagrange 1.2.2.1).

**Comment by Jonnobrow** [comment]
> It works under wayland as packaged in FreeBSD 13.0-RELEASE (lagrange 1.2.2.1).

Lagrage 1.2.2 works for me aswell, but Lagrage [1.3.4 (Latest Release)](https://github.com/skyjake/lagrange/releases/tag/v1.3.4)
does not work with this environment variable and displays the same behaviour shown by @sseneca 

> I compiled it with d->isExposed = iTrue; but unfortunately the problem persists. I'm not very familiar with SDL unfortunately.

When I tried this with the latest release v1.3.4 it seems to work. I haven't tried with the master branch though.

**Comment by skyjake** [comment]
@Jonnobrow That confirms it's a problem with Lagrange and not SDL. This may require a build option that disables the wait for the window expose event, but I'll see if a workaround can be applied.

**Comment by skyjake** [comment]
I tested this under Weston and sure enough it's very reproducible. 75df73293c3ff154699c30e7756d271b93938492 is a workaround for marking the window as exposed, fixing the draw issue.

I'll include this in v1.4.1.

**Comment by skyjake** [comment]
v1.4.1 is out, let me know if it improves things.

**Comment by Jonnobrow** [comment]
v1.4.1 is better for me under wayland and works with both:
- `SDL_VIDEODRIVER=wayland` and
- `SDL_VIDEODRIVER=x11`

**Comment by skyjake** [comment]
@sseneca Please close the issue if it works for you, too.

**Comment by sseneca** [comment]
It's a lot better than before, but there are still issues described below. If they require their own separate issue let me know.

Resizing doesn't work properly under Wayland (works fine under X11):

https://user-images.githubusercontent.com/25619071/118201327-bd34da00-b446-11eb-9c49-2548b92531ae.mp4

When the window is moved/resized, it doesn't render properly until either it's full-screened (shown first at 8 seconds) or the mouse is dragged into it (shown second at 11 seconds). In addition, generally each time it's moved & resized running natively under Wayland, it's a lot more sluggish in comparison to X11.

**Comment by skyjake** [comment]
Ok, the redrawing issue should still be fixed in the context of this issue, so let's keep it open.

When it comes to sluggishness, I recently upgraded to Ubuntu 21.04 (XFCE) and for some reason window resizing has become extremely sluggish. While dragging the frame, it updates only 1-2 times per second. This may be an SDL problem, but I'll need to take a closer look that nothing untoward is happening during the resize. In any case, it could be related to what's happening under Wayland.

**Comment by skyjake** [comment]
This should be tested again with SDL 2.0.16, where they have made Wayland related improvements. It's still not fully done yet, though.

Also see #321.

**Comment by sseneca** [comment]
Just tested against SDL 2.0.16 and the issue is completely gone, thanks :-)
