### ISSUE TITLE
Lagrange misidentifing links. Relevant to gempubs.

### ISSUE THREAD

**Issue by Lord-Guckavin** [skyjake/lagrange#269]
This issue might be with Gemini Text or Gempub's respective specs and not with your implementation, this definitely is a edge case.

While translating a book txt of "Public Opinion" into a gempub I ran into this chapter name: "The Old Image in a New Form: Guild Socialism" which when linked to in a index.gmi as 
`=> 19_The_Old_Image_in_a_New_Form:_Guild_Socialism.gmi XIX. The Old Image in a New Form: Guild Socialism`
Lagrange interprets as a link with the protocol of `19_The_Old_Image_in_a_New_Form:`, not allowing a reader to open the file. When a link is appended with `file://` this stops being a issue. 

Due to colons being used commonly in chapter titles, a work around might be desired as this will come up again.
Excerpt from Gemini Text's spec, describing relative links.
```
=> foo/bar/baz.txt	A relative link
```

A couple solutions I can think of: If one is within a gempub's index, ignore protocols. But then you would need to be able to figure out if a gempub is a archive or a book. Or you could can look for local files before calling out for a protocol while dealing with local files. Changes to the specs could definitely clear this up in a cleaner way, `protolcol://` could be used for relative files as well or just ban the use of colons in relative links. Either would work on a Gemini text or Gempub level. If you believe this would be a issue better suited for the specs, tell me and create issues on their projects.

Thank you for reading this and thank you making such a nice to use browser.

**Comment by Lord-Guckavin** [comment]
Considering this more, I believe it's a spec issue.

**Comment by ghost** [comment]
It's not an issue with the gemini spec. It's an issue with URLs and how they are interpreted. Assuming URLs allow a schema without the slashes after the colon, then either the colon will have to be encoded to point to a filename with the colon, or the colon would have to be removed from the filename.

**Comment by skyjake** [comment]
I think Lagrange’s URI parser is too lax when parsing the scheme, the underscores should disqualify it in this case, leading to the whole thing being treated as a relative path.

**Comment by skyjake** [comment]
Please check if this is still an issue in v1.4.
