### ISSUE TITLE
UX: Way to disable smooth scrolling

### ISSUE THREAD

**Issue by Arteneko** [skyjake/lagrange#27]
I have "smooth" and animation effects disabled on my whole system due to it making me sick; seeing it enabled (going against my system configuration) and without a way to disable it is pretty surprising.

Would it be possible to disable it, e.g. through a configuration option?

Edit: I found the behaviour to be implemented in `src/ui/documentwidget.c`, but I'm having trouble seeing how to implement it myself, so I'll put it on the side for now.

**Comment by skyjake** [comment]
No problem, I'll add a setting for disabling smooth scrolling in Preferences.

**Comment by Arteneko** [comment]
Thanks for the fast answer!

If you implement it, could you put the link to the PR / patchset here, so I can try to see how you implemented it? Thanks

**Comment by skyjake** [comment]
Will do.

**Comment by skyjake** [comment]
It's implemented now in 6ffe005a8ad62fb5ecdd5fc6d63f914b9c45142c. Most of the changes were wiring for the UI. It should've been enough to just force `duration` to zero in `smoothScroll_DocumentWidget_()`, but there was a timing glitch with `setValueEased_Anim()` so I added the extra condition.

**Comment by Arteneko** [comment]
Thanks!
