### ISSUE TITLE
Build failes on arch linux with `error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]`

### ISSUE THREAD

**Issue by Minnerlas** [skyjake/lagrange#270]
As I wrote in the title, on gcc 10.2.0 fails with
> error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]

The simple fix is to disable `-Wformat-security` where `-Wformat` is disabled.

**Comment by skyjake** [comment]
There's some related discussion here: https://codeberg.org/skyjake/the_Foundation/issues/6

The implemented workaround was to add the build option TFDN_ENABLE_WARN_ERROR. It seems like a good idea to use `-Wno-format-security` here, although it may require checking specifically for GCC version 10.2 (?).

**Comment by Minnerlas** [comment]
I guess that would work, I am just not very experienced with cmake so I can't change that myself

**Comment by skyjake** [comment]
I've applied the `-Wno-format-security` flag for future builds, let's see if that's enough.

When you run CMake to configure the Lagrange build, just add `-DTFDN_ENABLE_WARN_ERROR=NO` to the command line.

**Comment by Minnerlas** [comment]
I guess that would work, I am just not very experienced with cmake so I can't change that myself

**Comment by dmerejkowsky** [comment]
Hi, reporter of https://codeberg.org/skyjake/the_Foundation/issues/6 here

> When you run CMake to configure the Lagrange build, just add -DTFDN_ENABLE_WARN_ERROR=NO to the command line.

That's already what the PKGBUILD does, unfortunately, that was not enough. Sorry, my bad, I assumed disabling Werror was enough.

> I've applied the -Wno-format-security flag for future builds, let's see if that's enough.

We'll see at the next Lagrange release I guess ;)

**Comment by Minnerlas** [comment]
Should we close the issue or wait for the next release then

**Comment by dmerejkowsky** [comment]
I think so. The commit 91f8f22708a3814e0c7ef63e398fb87330665b65 update the Foundation submodule to the [correct revision](https://git.skyjake.fi/skyjake/the_Foundation/commit/32f3566a800cc8c0ded136abe54450b4eb24951c), but we' ll know for sure when we try and package the next release.

**Comment by skyjake** [comment]
Let's reopen the issue if the problem persists.
