### ISSUE TITLE
Addressbar glitching

### ISSUE THREAD

**Issue by drskrzyk** [skyjake/lagrange#271]
I have a clean build on ubuntu studio 20.04, on release branch (1.4.0) built with the following uptions: cmake ../lagrange -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=$HOME/.local/share -DENABLE_MPG123=YES -DENABLE_WINDOWPOS_FIX=YES

![image](https://user-images.githubusercontent.com/57383204/117493579-c8fd3980-af38-11eb-872c-9d0f59b268d9.png)

When switching between tabs occasionally the address bar will show "snow" like artifacts as shown above. 

I am going to try building with SW render to rule out some bad interaction with the native render.

**Comment by drskrzyk** [comment]
Compiling with -DENABLE_X11_SWRENDER=YES enabled via cmake corrected this issue. 

Please let me know if you'd like further investigation/testing/information from me!

**Comment by skyjake** [comment]
I haven’t seen this myself, but it’s definitely related to buffering the input field contents on a texture for faster drawing. Looks like the texture wasn’t cleared properly.

I’ll check if I can spot anything that could cause this.

**Comment by skyjake** [comment]
Could you check which version of SDL you’re building with?

**Comment by drskrzyk** [comment]
Sure! 
libsdl2-dev/focal,now 2.0.10+dfsg1-3 amd64

**Comment by skyjake** [comment]
I'll try compiling with SDL 2.0.10 myself and see what kind of workaround is needed. I believe more recent versions of SDL do not have this problem.

**Comment by skyjake** [comment]
So far I've been unable to reproduce this glitch.

**Comment by drskrzyk** [comment]
I'm not horribly concerned as I was able to work around it with the software rendering. The workstation that exhibits this behavior is an Intel NUC with integrated intel video. The appimage doesn't act like this, so my build environment could be suspect too. 

I'll close this up and dig around further on my end. Thank you for looking into it.
