### ISSUE TITLE
Changing visited link from semibold to unweighted breaks monospace body

### ISSUE THREAD

**Issue by nytpu** [skyjake/lagrange#274]
I like to browse Gopher with a monospaced body sometimes, and the new link font styling where unvisted links are bolded and visted links are normal weight is broken when the body is set to monospace. Unvisted links look like the standard monospace that they were before (including being unbolded), but when a link is visited the link is changed to the variable-width thin font.

Broken links (top two are visited, the rest are unvisited):  
![Broken links, where unvisted links are monospaced and visited links are not](https://user-images.githubusercontent.com/17458512/117686310-f97ce780-b173-11eb-9c21-4cac954af719.png)

Links working properly when monospace body is disabled:  
![Normal bold/thin links when the entire body is variable-width](https://user-images.githubusercontent.com/17458512/117686394-0f8aa800-b174-11eb-9f89-9c94654c15d0.png)

**Comment by skyjake** [comment]
Fixed for v1.4.1.
