### ISSUE TITLE
Black window on the first run

### ISSUE THREAD

**Issue by Carmina16** [skyjake/lagrange#275]
On the first run, the UI and text parts of the window are completely black. Only after the second run it looks normal.

**Comment by skyjake** [comment]
I’ll check it out. Which release/commit are you running?

**Comment by Carmina16** [comment]
1.4.1

**Comment by skyjake** [comment]
Found the problem. This may affect other platforms as well... Fixed for the next patch.

**Comment by eqn-grp** [comment]
Affects fully updated windows 10 as well,
