### ISSUE TITLE
Propose swapping keys for split vertical/horizontal

### ISSUE THREAD

**Issue by rnkn** [skyjake/lagrange#278]
I'm amazed at all the work you've been doing on Lagrange. It's such a wonderful experience to use and a joy to see each new update. Thank you for your dedication to the project :)

From what I can tell, the keys for window splitting are not (yet?) customizable, so may I suggest swapping the keys for vertical/horizontal to `mod-j 2` for horizontal and `mod-j 3` for vertical? The reason is I'm a long-time Emacs user and the key bindings for splitting windows are `C-x 2` for horizontal and `C-x 3` for vertical, so for anyone coming from Emacs has long been conditioned to think 2 for horizontal and 3 for vertical.

(Or if you wanted to go the tmux route, there's `mod-j "` for horizontal and `mod-j %` for vertical.)

**Comment by skyjake** [comment]
I agree following the Emacs convention by default makes more sense here. I'll see about adding bindings for these as well.

**Comment by rnkn** [comment]
Sweet!
