### ISSUE TITLE
Add support for Titan protocol to upload data

### ISSUE THREAD

**Issue by skyjake** [skyjake/lagrange#279]
Uploading a larger amount of data to a server is sometimes useful, but the Gemini protocol doesn't directly support it. Another protocol such as Titan could be used for this purposes.

It could work like this:

- When clicking on a `titan://` URL, show a file selection dialog. Initially this could be done via drag-and-drop since native file open dialogs are not supported yet.
- Open the connection and write the URL and data.
- Show a progress bar in the UI until the data has been uploaded.

Another use case is uploading a new version of a page. In this case, there may be no `titan://` link provided, but instead the current URL's `gemini` scheme is changed to `titan`. The client has no way to know whether a particular server/URL supports Titan uploads, but maybe just providing a menu item to attempt the upload on any Gemini URL would be sufficient, letting the user figure out when it's appropriate.

~~Open question: Is there any response sent by the server to know what happens after the upload? A redirect to a new URL? Reload the page where the `titan://` URL was clicked on? One option is to just sit at the "100% completed" state until the user navigates to a different page.~~

For reference: 

- https://communitywiki.org/wiki/Titan
- https://alexschroeder.ch/cgit/gemini-titan/about/

**Comment by Armen138** [comment]
It is my understanding that a server may respond with any valid gemini response to a titan request. Personally I send a redirect response to navigate to the newly uploaded content.

**Comment by skyjake** [comment]
@Armen138 That is correct. Titan is basically just Gemini plus a user payload and a couple of URL parameters with specific semantics.

**Comment by skyjake** [comment]
Titan uploads have been implemented for v1.6, where you upload text or files for any URL, or by clicking on a `titan://` link.
