### ISSUE TITLE
Display server-returned errormsg for temporary (4x) and permanent (5x) failures

### ISSUE THREAD

**Issue by raphm** [skyjake/lagrange#280]
The Gemini protocol specification states that for temporary and permanent failures, "[t]he optional message MAY provide additional information on the failure and if given, a client SHOULD display it to the user." 

Lagrange displays a generic error message for 4x and 5x return codes, and does not have a way for the user to view the details of the returned error message.

I should be able to put together a PR to have Lagrange display the server-provided error response, if one exists.

**Comment by skyjake** [comment]
> does not have a way for the user to view the details of the returned error message.

I think the server's error message can be viewed via Page Information (Ctrl+I or ⌘I) or clicking the lock icon. That's quite well hidden, of course.

I'll merge the PR.
