### ISSUE TITLE
Blank screen on macOS

### ISSUE THREAD

**Issue by yackx** [skyjake/lagrange#284]
Lagrange opens on a blank screen on macOS 11.3.1.

Same for the Debug screen. The About box appears correctly.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1193689/119373589-dd6f5f00-bcb8-11eb-8a2d-02bd633830cf.png">

- version 1.4.2 (installed from releases and from homebrew)
- version 1.4.1
- version 1.3.4

**Comment by skyjake** [comment]
Has any version of the app worked on this Mac?

Which Mac model is it? (i.e., what GPU does it have?)

Is this the Intel build of Lagrange?
