### ISSUE TITLE
a suggestion... in Preferences change the  txt  of the button from "dismiss esc" to "Close"

### ISSUE THREAD

**Issue by jazei-AR** [skyjake/lagrange#285]
a suggestion... in Preferences change the  txt  of the button from "dismiss esc" to "Close"
because if anyone changes an option like language for example we wait to see OK and Close... the changes are OK but If we see dismiss esc we think that the changes will be discarded, so if we see only the button "Close" we can turn off Preferences quietly.
ps.: in spanish the button will be "Cerrar" o "Salir" salir= "go out"
![preferences](https://user-images.githubusercontent.com/72522918/119491891-db4ae600-bd34-11eb-8223-0e5d922008d3.jpg)

**Comment by skyjake** [comment]
I agree, "Close" does seem less ambiguous in this context.
