### ISSUE TITLE
Help me.. ¿how to learn the use of gemini and browsing using lagrange? 

### ISSUE THREAD

**Issue by jazei-AR** [skyjake/lagrange#286]
I'm lost... this is basic chinese for me (i'm using an online translator to write this post) i don't know how to continue... i would like to see web portals from lagrange, web pages using lagrange, the basics, the abc.. the kinder for basic like me... sorry if this post is out of place you can delete it if it doesn't correspond, thank you very much!
greetings from argentina

**Comment by skyjake** [comment]
Sorry, I'm not entirely sure what you're asking... I recommend you check out [Lagrange's Help page](https://raw.githubusercontent.com/skyjake/lagrange/dev/res/about/help.gmi) for information about how to use the application.

> see web portals from lagrange, web pages using lagrange

If you're referring to browsing actual websites (via HTTP/HTTPS), that can be achieved via a HTTP proxy server. However, I don't now if anyone is running a public proxy. You'll likely need to run one yourself. For example, you could try [Duckling Proxy](https://github.com/LukeEmmet/duckling-proxy). Once you have it running, you would set its IP address in Lagrange Preferences > Network > HTTP Proxy, and then when you open an HTTP/HTTPS URL, it'll be fetched via your proxy.

Hope this helps!

**Comment by jazei-AR** [comment]
thanks, I'm refering to surfing geminispace... with lagrange but i'm walking thanks again cheers jose
