### ISSUE TITLE
All menus and buttons are completely black on first run, solved on restart

### ISSUE THREAD

**Issue by rzetterberg** [skyjake/lagrange#287]
# Description

When starting `lagrange` the first time all menus and buttons are completely black, like this (note that some parts of the actual content also are black):

![2021-05-26-093402_1919x702_scrot](https://user-images.githubusercontent.com/766350/119620915-cf7b2480-be05-11eb-88d0-031320d2b3cf.png)

This problem is resolved when `lagrange` is started a second time: 

![2021-05-26-093419_1919x701_scrot](https://user-images.githubusercontent.com/766350/119621075-fc2f3c00-be05-11eb-820b-dec15bd95801.png)

I can reproduce this problem 100% of the time by deleting `~/.config/lagrange` and starting `lagrange`. 

Upon closer inspection, I can reproduce this problem 100% by deleting these lines from `~/.config/lagrange`: 

```
theme.set arg:1 auto:1
accent.set arg:0
```

I also note that these lines are automatically added back to `~/.config/lagrange` when I close `lagrange`, which seems to be why the issue does not appear after a restart. 

I mainly created this issue in case someone else encounters the same problem and searches for clues on GitHub. Since it solves itself after a restart I feel like it's a low priority issue. 

# Environment

- **OS**: NixOS 20.09.3970.c6f0d282ae4 (Nightingale)
- **Lagrange**: 1.4.0 (NixOS hash `sha256-l8k81w+ilkOk8iQTc46+HK40JQZ0dCYVAvkGTrEpZSQ=`)

**Comment by skyjake** [comment]
Thanks for reporting. I believe this issue has been fixed in the latest v1.4.2 release.

**Comment by rzetterberg** [comment]
I just installed `1.4.2` and I can confirm that the problem is indeed fixed. Sorry for the noise in case this already had been reported!

Also, thank *you* for a really cool project! :+1:

**Comment by skyjake** [comment]
No problem, and you're welcome! 😊
