### ISSUE TITLE
Translations not showing

### ISSUE THREAD

**Issue by Strahinja** [skyjake/lagrange#288]
I'm trying to compile Lagrange from the latest source (branch release), and the compiled version doesn't seem to include the updated translations from few days back.

For example,

https://github.com/skyjake/lagrange/blob/5321da5c48a5b9f7285785351d836b90a7aaae83/po/sr.po#L1656-L1657

translation for "More..." (among others) isn't showing:

![2021-06-03-160420-lagrange](https://user-images.githubusercontent.com/981077/120795684-54162300-c529-11eb-96c1-56b457b61da1.jpg)

I even tried to remove the cloned lagrange directory and start from scratch:
```
$ rm -fr lagrange
$ git clone --recursive --branch release https://git.skyjake.fi/gemini/release
$ cd lagrange
$ mkdir build && cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
$ su
# cmake --build . --target install
```
but still the translations for new strings aren't showing. Am I missing something?

**Comment by skyjake** [comment]
I added this explanation to https://gmi.skyjake.fi/lagrange/compiling.gmi:

Weblate has a separate working copy of the Lagrange repository. New and updated .po files have to be manually merged to the main repository.

At runtime, the app does not directly use the .po files. The Python script "compile.py" (under "po/") must be run to convert the strings into a format that gets loaded at runtime. After running "compile.py", the strings are stored in "res/lang/". When you run CMake, these will be combined with all other resources into the "resources.lgr" file.

Summarizing, the steps to update UI translations are:

* Merge latest .po files from Weblate.
* Run "compile.py" under "po/".
* Run CMake to regenerate "resources.lgr".
* Rebuild the app to update the embedded resource metadata.

**Comment by Strahinja** [comment]
Thanks, I'll close the issue.
