### ISSUE TITLE
Feature Request: header title as link to site root

### ISSUE THREAD

**Issue by karthanistyr** [skyjake/lagrange#29]
**Use case:**
As a Lagrange user, I would like to be able to browse back to the root of the gemsite by clicking on the Header Band Title (cf. screenshot)
![Capture_2020-11-09_17-45-59 815913787_highliht](https://user-images.githubusercontent.com/7722196/98571129-81ad2d80-22b4-11eb-9514-91c410614e83.png)
I think this would help the "browsability" of gemsites.

**Comment by skyjake** [comment]
Sounds useful, I'll make the banner clickable.

**Comment by skyjake** [comment]
Also added keyboard shortcuts to navigate to root or the parent directory.
