### ISSUE TITLE
Keybindings vs. switching keyboard layouts

### ISSUE THREAD

**Issue by lua-rocks** [skyjake/lagrange#290]
When I switch from English to Russian layout, keybindings stops working.

**Comment by skyjake** [comment]
I believe that since the keybindings are not scancode-based, they will be affected by the current keyboard layout. If you rebind keys via Preferences when using the Russian layout, do those re-bound keys then work?

**Comment by lua-rocks** [comment]
Sorry, it looks like the bug is not with `lagrange`, but with another program I use, called `easystroke`. I just realized that when I press a key physically, everything works fine in any layout! But if I make a mouse gesture, then the keystrokes sent from `easystroke` are not processed through `lagrange`. Well, I think this issue can be closed, although it is very strange that in no other program `easystroke` does not behave this way.
