### ISSUE TITLE
a general issue about Gemini.... how do you see words with tilde for ex. letter á

### ISSUE THREAD

**Issue by jazei-AR** [skyjake/lagrange#292]
what is the sintaxis for see well words with tilde and other symbols in languages whithout tilde and of course in keyboard without tilde: without á. é, í ñ or Ñ or Á É Í....?
IN HTML  is well necesary using &amp;aacute; for letter á and &amp;ntilde; for ñ, why? because using keyboard without tilde and ñ you will see another letter or a square in its place... rare symbols instead!
in gemini sintax, is it the same matter?
another symbols using ascii:
Ö | &amp;Ouml; | &amp;#214; | &amp;#xD6;
× | &amp;times; | &amp;#215; | &amp;#xD7;
Ø | &amp;Oslash; | &amp;#216; | &amp;#xD8;
Ù | &amp;Ugrave; | &amp;#217; | &amp;#xD9;
Ú | &amp;Uacute; | &amp;#218; | &amp;#xDA;
Û | &amp;Ucirc; | &amp;#219; | &amp;#xDB;
Ü | &amp;Uuml; | &amp;#220; | &amp;#xDC;
Ý | &amp;Yacute; | &amp;#221; | &amp;#xDD;
Þ | &amp;THORN; | &amp;#222; | &amp;#xDE;
ß | &amp;szlig; | &amp;#223; | &amp;#xDF;
à | &amp;agrave; | &amp;#224; | &amp;#xE0;
á | &amp;aacute; | &amp;#225; | &amp;#xE1;
â | &amp;acirc; | &amp;#226; | &amp;#xE2;
ã | &amp;atilde; | &amp;#227; | &amp;#xE3;
ä | &amp;auml; | &amp;#228; | &amp;#xE4;
å | &amp;aring

regards, 
jose

**Comment by skyjake** [comment]
The Gemini text format uses Unicode (UTF-8) encoding, and there are no HTML-like character entities. To get an å you will need to insert that Unicode character in the document somehow.

In Unicode, there are multiple ways to represent symbols. For example, there is a single codepoint for å but one can also write it as two codepoints: `a` followed by `combiningRingAbove`. Whether these work in a particular client depend on how they render text. There are differences between terminal apps and GUI apps. Lagrange particularly has a problem currently drawing the combining diacritics; they will not be displayed correctly.
