### ISSUE TITLE
flathub version crashes on x86

### ISSUE THREAD

**Issue by nebocamin** [skyjake/lagrange#293]
Hi, the current flathub version crashes for me using ubuntu on x86 

```
flatpak run fi.skyjake.Lagrange
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  109
  Current serial number in output stream:  110
```

**Comment by skyjake** [comment]
You mean x86 as in a 32-bit build?

Based on the error message, my initial guess is that this is an [SDL](https://libsdl.org) / OpenGL related problem but I haven't seen this before. Could you tell me some details about your system? (type of CPU, video card, any customizations to X11 config, etc.)

It's worth trying to launch with the `--sw` command line option:
```
flatpak run fi.skyjake.Lagrange --sw
```

**Comment by nebocamin** [comment]
```
flatpak run fi.skyjake.Lagrange --sw
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  109
  Current serial number in output stream:  110
```
I see no difference. I am using an AMD ryzen in a thinkpad X13. So the x86 64bit version. It's the same error using wayland or a X11 session. Its current ubuntu hirsute hippo.

**Comment by nebocamin** [comment]
just tested hirsute hippo on arm64, there it works.

**Comment by nebocamin** [comment]
now i installed former versions using flatpak update --commit=
and the same error is on older versions too, that worked last week. so something is odd on my machine.

**Comment by skyjake** [comment]
All right, closing the issue as I don't think there's much I can do here.

Have you tried a good old reboot? Sometimes I've been X Errors after the video drivers have been updated but I haven't rebooted the machine.

Good luck. :slightly_smiling_face:
