### ISSUE TITLE
Missing letters/characters after running for a longer time

### ISSUE THREAD

**Issue by ghostglyph** [skyjake/lagrange#294]
I hadn't properly closed and restarted the browser for a few days, and random letters started disappearing on pages and menus.

Restarting restored all the letters. I'm just not sure why they disappeared.

Running Lagrange 1.5.0, Mac 11.2.3

<img width="165" alt="Screenshot 2021-06-12 at 22 20 55" src="https://user-images.githubusercontent.com/51196808/121888236-a7e5f080-cd0f-11eb-9ba0-ebe4563d5d4b.png">
<img width="255" alt="Screenshot 2021-06-12 at 22 20 47" src="https://user-images.githubusercontent.com/51196808/121888239-a87e8700-cd0f-11eb-8d44-95cc66ae9e07.png">
<img width="222" alt="Screenshot 2021-06-14 at 12 55 03" src="https://user-images.githubusercontent.com/51196808/121888437-e54a7e00-cd0f-11eb-966c-5fc262d96c7c.png">

**Comment by skyjake** [comment]
I have noticed the same. Not sure if this macOS specific, but this has happened to me too occasionally.

My guess is that the font glyph cache texture gets released by the operating system whlie the app is in the background, and the text renderer does not notice, proceeding to draw text as if it had glyphs cached when it actually does not.

**Comment by skyjake** [comment]
Could be the same issue as #311.

**Comment by skyjake** [comment]
There are changes related to this in v1.6.2. Please report if the issue persists.

**Comment by ghostglyph** [comment]
I'm not noticing this any more, with v1.6.2. All appears to be working well.

**Comment by skyjake** [comment]
I have not noticed any missing glyphs either. Closing as fixed.
