### ISSUE TITLE
Audio Autoplaying and Crash on Rewind Issues

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#295]
Someone is having a problem with the audio files at the following link not auto-playing: gemini://kwiecien.us/gemcast/index.gmi
Additionally, when they click the rewind "|<<" button, lagrange will sometimes crash.

They are on voidlinux (with glibc)

**Comment by skyjake** [comment]
Well the first step is to reproduce the crash somewhere and get a stack trace. I haven’t seen any Vorbis or SDL audio related issues on my systems…

**Comment by ghost** [comment]
Yeah, I myself haven't been able to reproduce it, actually. But at least one person has this problem, that I know of. It might be possible they don't have a necessary dependency installed, I'm not sure.

**Comment by skyjake** [comment]
Closed due to not being able to reproduce.
