### ISSUE TITLE
Navigating backwards to page with prompt locks up app

### ISSUE THREAD

**Issue by karthanistyr** [skyjake/lagrange#30]
**Issue:**
While navigating GUS (gemini://gus.guru), Lagrange frequently locks up when using the "backwards" navigation action (both by clicking the toolbar button or using the Alt+LeftArrow binding).
It seems the app locks up when the navigation brings back a page where there should be a prompt (on GUS, it would be the search box), so it would probably not just impact browsing on GUS.

There is no relevant debug trace when this issue hits.

**Expected behaviour:**
I could see two scenarios to choose from here:
* Either navigating back to a prompt page brings back the prompt, for the user to put a new entry
* Navigating back brings the user to the page _before_ the prompt, where there is effectively no prompt

**Reproducing the issue:**

1. Navigate to gemini://gus.guru/
2. Click "Search GUS" => this brings up a prompt
3. Type a query and press enter => the results appear
4. Navigate back (left arrow on the tool bar, or Alt+LeftWarrow on the keyboard)
5. Lagrange becomes unresponsive -- can't click anything, can't SIGTERM -- I have to SIGKILL

**Version info:**
Lagrange 0.8 ( edc5194)
Arch Linux x64 (`Linux karth-dev-book 5.9.3-arch1-1 #1 SMP PREEMPT Sun, 01 Nov 2020 12:58:59 +0000 x86_64 GNU/Linux`)

**Comment by skyjake** [comment]
>  frequently locks up

"frequently" as in "not always"? This looks like a race condition related to thread exiting, I'll do some debugging in the_Foundation...

**Comment by karthanistyr** [comment]
Sorry, i went back to poke it some more and it does seem to lock up always.

**Comment by skyjake** [comment]
Please test with f2df52c755e4211fea50afbecf552bd99a8d5fe5. I updated the `the_Foundation` submodule with a potential fix.

**Comment by karthanistyr** [comment]
Yes, on GUS, it brings me back and opens the search prompt. I couldn't get the UI to lock up anymore. It looks good from a user POV. Thanks!

**Comment by skyjake** [comment]
Closing for now (0.8.1 is out), let me know if the issue still occurs in the future.

**Comment by karthanistyr** [comment]
Thank you, I appreciate how reactive you are with this project. :bow:
