### ISSUE TITLE
Gopher: Auto-collapsing preformatted text renders some content strangely

### ISSUE THREAD

**Issue by jamestomasino** [skyjake/lagrange#300]
I have preformatted blocks default to collapsed. I just navigated to this gopher hole:

    gopher://mozz.us/1/phlog

Half the content is getting sorted into preformatted blocks in unexpected and incorrect ways.

I believe you said previously that Lagrange converts gopher into gemtext to render it. Perhaps it would benefit from disabling the preformatted block collapsing when doing so. Since gopher is entirely preformatted blocks anyway it's not much help.

**Comment by skyjake** [comment]
You are correct, this option should not apply to Gopher pages.
