### ISSUE TITLE
ipad magic keyboard cannot be used

### ISSUE THREAD

**Issue by disschnarch** [skyjake/lagrange#301]
I am using the testdrive on ipados 14.6 and the magic keyboard or any external device is not working for that matter. Would be great to see that feature.

**Comment by skyjake** [comment]
Hmm, I've been using a Magic Keyboard (via Bluetooth) on my iPad and it works fine in Lagrange. Although, I'm running iPadOS 15 Beta.

> any external device is not working

Which external device(s) did you try using?

**Comment by disschnarch** [comment]
Magic Keyboard and Touchpad. But strangely enough. I justed tested it and it does work now. Hmm

**Comment by skyjake** [comment]
Well, if you find the circumstances under which it doesn't work, we can reopen the issue.
