### ISSUE TITLE
Unicode symbol 2e0d not properly rendered

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#304]
I make an extensive use of Unicode, and I found that  ⸍, which I type with code 2e0d (or U+2e0d), does not display as expected. I just see a box. 

I am using XUbuntu 20.04 with Lagrange-1.5.2-x86_64.AppImage

The same symbol is correctly shown in Bombadillo, Amfora and Ariane (the ones I tested).

The symbol is called "right raised omission bracket", although I am using it as the superscript version of the forward slash.

Any help would be appreciated.

**Comment by skyjake** [comment]
Currently Lagrange only uses fonts bundled with the app (so the same ones are available everywhere), and there's an option to configure one additional local TrueType font for additional symbols.

The fonts bundled with v1.5.2 don't contain U+2E0D. You'll need to go to _Preferences > Style > Symbol font_ and enter the path of a TrueType font file with the glyphs you need.

Future releases may include the ability to automatically use system-provided fonts (#195).
