### ISSUE TITLE
Failed server trust check should abort the connection

### ISSUE THREAD

**Issue by nervuri** [skyjake/lagrange#308]
Hi,

Lagrange allows requests and responses to go through even when the server's certificate does not match the fingerprint in `trusted.txt`.  The "untrusted certificate" warning is shown together with the response.  This defeats the purpose of TOFU to some extent.  The point is to block the connection before any (potentially sensitive) data is revealed to the man-in-the-middle.

To test this, modify one of the fingerprints in `trusted.txt`, then restart Lagrange and visit the corresponding domain.

**Comment by skyjake** [comment]
The current version of the Gemini protocol specification does not mandate aborting the request when a TOFU check fails, only that a warning is displayed.

But sure, I can see how this errs a bit much on the side of user convenience at the cost of diluting the trust-based security model. It would be good to add a user preference here that prevents the request from proceeding should the trust check fail.

In practice, it will likely require adding an OpenSSL verify callback that aborts the low-level request if the check fails.

**Comment by nervuri** [comment]
> The current version of the Gemini protocol specification does not mandate aborting the request when a TOFU check fails, only that a warning is displayed.

Not even that; the spec says _Clients can validate TLS connections however they like (including not at all)_.

But further on, when describing TOFU, it makes reference to OpenSSH and web browsers.  So I would argue that you're looking at the letter of the spec rather than its spirit.  Lagrange is the only piece of software I know of that doesn't stop requests on certificate authentication failure.  I don't think Solderpunk anticipated that anyone would do it this way; I certainly didn't.  If he had, I think he would have been explicit about blocking the request.  I can open a ticket for this over at GitLab, for clarification.

But aside from the spec discussion: since Lagrange is one of the most popular Gemini clients, the security of its users is particularly important.  So please follow the example of... all software that does certificate authentication, TOFU or otherwise.  Having this merely as a (non-default) setting would reliably fail users who are subjected to MITM attacks.

**Comment by skyjake** [comment]
That should take care of it. I didn't add a preference because it isn't a great inconvenience to update the trust via GUI if the user so chooses, but it is not so easy that the user would do it accidentally.
