### ISSUE TITLE
Text input fields: when caret over a percentage symbol `%`, crashes program

### ISSUE THREAD

**Issue by karthanistyr** [skyjake/lagrange#31]
**Issue:**
When there is a percentage symbol `%` in any text input field, if the caret highlights it, the program segfaults. This can be observed in all text input fields in the UI, like address bar, input prompt (like in `gemini://gus.guru/search` for example).

Note that this issue only involves the caret being _directly_ over the percentage symbol; text selection does not pose a problem.
I could not find any other character impacted by this, however I probably haven't tested _all_ the printable characters... I did try to go over typically reserved URL characters like `?`, `&`, `#` and `:` but they look safe, unlike `%` as explained in the present issue.

**Expected behaviour:**
The program would not segfault, whatever character is highlighted by the caret in a text input.

**Reproducing:**
1. Write a single percentage symbol `%` in the address bar
![Capture_2020-11-11_14-45-37 298893906](https://user-images.githubusercontent.com/7722196/98819008-9f9d9e00-242c-11eb-872f-34338f99f8da.png)

2. Bring the caret over this character (either click with the mouse, or use arrows to move the caret over it)
3. Program segfaults

Can be reproduced in other text input fields, e.g. the prompt at `gemini://gus.guru/search` or the proxy address fields in Settings
![Capture_2020-11-11_14-44-02 136446649](https://user-images.githubusercontent.com/7722196/98819026-a5937f00-242c-11eb-9884-a83dd3e6e44b.png)

**Version info:**
Lagrange 0.8.1 (f99df67)
```
Lagrange: A Beautiful Gemini Client
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: fr_FR.utf8
[window] renderer: opengl (accelerated)
```

**Comment by skyjake** [comment]
Sounds like a classic `printf` bug, let me take a look.

**Comment by skyjake** [comment]
Should be fixed in the dev branch now.

**Comment by skyjake** [comment]
Exemplary bug report, BTW :+1:
