### ISSUE TITLE
Use the public key fingerprint

### ISSUE THREAD

**Issue by nervuri** [skyjake/lagrange#310]
Since fixing #309 requires modifying the format of `trusted.txt`, you can take this opportunity to add one more improvement: rather than using the entire certificate's fingerprint, use a hash of its public key (SubjectPublicKeyInfo), like Amfora does.  This change would mean potentially less unnecessary warning messages for users, because a cert can be renewed without changing its public key.  Some capsules are already doing this to get TOFU-friendly Let's Encrypt certs.

Here's how to get the hash of a certificate's public key using OpenSSL:

```
openssl s_client -connect skyjake.fi:1965 </dev/null 2>/dev/null | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256
```

**Comment by skyjake** [comment]
Good idea. The domain name checks remain in place, although there's an argument to be made to only care about the keys when dealing with self-signed certificates.
