### ISSUE TITLE
Better handling of mailto: links that start with 📧 (U+1F4E7 E-MAIL SYMBOL)

### ISSUE THREAD

**Issue by dalz** [skyjake/lagrange#312]
As of now,

```
=> mailto:example@example.com label
=> mailto:example@example.com 📧 label with icon
```

is rendered as

![image](https://user-images.githubusercontent.com/25228125/126035978-ca754300-8767-4248-97a9-0c8ad7008171.png)

Would it be possible to look at the first character of mailto: links, and if it is 📧 then trim it? The current behaviour looks bad in cases like this:

![image](https://user-images.githubusercontent.com/25228125/126036050-b5bcfe82-cbc2-42c1-a11e-9af37f857185.png)

**Comment by skyjake** [comment]
I agree, repeating the icon in this case is not useful.

Done for v1.6.

**Comment by dalz** [comment]
Thank you :)
