### ISSUE TITLE
MacOS: App doesn't open normally

### ISSUE THREAD

**Issue by kbkaiser** [skyjake/lagrange#314]
Clicking on Lagrange in Applications doesn't completely launch the app.  Dragging the icon to the dock and trying to launch from there gives same result.

Right click on Applications/Lagrange and select Show Package Contents, then click on Contents/MacOS/Lagrange launches App successfully.  Can't drag that entry to the dock, though.

Catalina 10.15.7
lagrange 1.5.2 installed with brew 19July2021

**Comment by skyjake** [comment]
Not sure what's going on here, but something is definitely wrong. My first guess is that the check to see whether the app is already running is causing this "not launching" behavior. Have you tried the following:

* Check if there are any "Lagrange" processes running via Activity Monitor and kill them.
* Go to ~/Library/Application Support/fi.skyjake.Lagrange/ and delete all the hidden files starting with a period (like `.run.*.cfg`).
* Delete the app, reinstall, reboot?
