### ISSUE TITLE
Windows crash when entering cert common name

### ISSUE THREAD

**Issue by brian8267** [skyjake/lagrange#315]
Using Lagrange 1.5.2 browse gemini://gemini.thegonz.net/sggs/, click the hyperlink to `Enter`, at the bottom center of the browser click the `New Identity...` button, in the `NEW IDENTITY` pop-up enter any date then begin to type any common name and the crash occurs.

**Comment by skyjake** [comment]
I cannot reproduce this. I'm using Windows 10 (19043.1110), Lagrange v1.5.2.

Does the crash occur every time for you or is there some randomness to it?

**Comment by brian8267** [comment]
The day this happened to me I replicated it at least 5 or 6 times but I can't anymore. Perhaps the problem was on the server end and it was resolved?

**Comment by skyjake** [comment]
Please reopen if the issue persists.
