### ISSUE TITLE
[Feature Request] Add a --current-tab cli argument

### ISSUE THREAD

**Issue by bacardi55** [skyjake/lagrange#319]
First, thanks a lot for the awesome work on lagrange :)

I was wondering if, based on `--list-tab-urls` and `--close-tab` CLI arguments, it could be possible to add another argument to get the current open tab like `--current-tab`?

Goal for me is to be able to retrieve the URL in the open tab and send it to my wallabag instance (with a gemini/http proxy in the middle).

**Comment by skyjake** [comment]
You're welcome ☺️, and yes adding an option like that should be doable.
