### ISSUE TITLE
v0.8.0+ segfault

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#32]
When hitting refresh on any tab or entering and address and pressing the return key, it immediately segfaults in v0.8.0+ on Linux/amd64.

Hopefully this stack trace help, as it's currently the best I know how until I learn more about gdb and core dumps. If there's something I can do to help reproduce or track this down, let me know!

![Screenshot_2020-11-11_10-24-01](https://user-images.githubusercontent.com/270504/98835831-d2e62a00-2438-11eb-897e-fd8e04fe3ee9.png)

**Comment by skyjake** [comment]
Have you updated git submodules? As of the_Foundation commit 98441320dba07, this case of a NULL proxy is handled appropriately.

**Comment by ghost** [comment]
Hmm... I saw git say something about the_Foundation, but alas a pull may not have happened. Sorry about that.
