### ISSUE TITLE
SegFault on titan request (response is a redirect)

### ISSUE THREAD

**Issue by f0086** [skyjake/lagrange#320]
How to reproduce:
1. titan://alexschroeder.ch:1965/raw/Test
2. Text: "n1", Upload token: "hello"
3. Hit Upload
4. SegFault

```
└─ $ ▶ lagrange
Lagrange: A Beautiful Gemini Client
[window] renderer: opengl (accelerated)
Segmentation fault (core dumped)
```

Not sure how to get better debug output.

**Comment by skyjake** [comment]
Will be fixed in 1.6.2. The problem was that the site responded with a redirect, and Lagrange had a bug where that would cause a null pointer access.
