### ISSUE TITLE
Broken window on Gnu/Linux Flatpak: top bar missing

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#321]
On my Fedora 34 with gnome desktop, I am using the Lagrange flatpak from Flathub version 1.6.1 and the top bar is missing: therefor there is no way to move the window arround or to minizise, maximize or close it from the top bar.

**Comment by skyjake** [comment]
Do you happen to be using Wayland? There's a known issue in SDL where the window frame is missing on Wayland. It is supposed to be fixed in the next patch of SDL (2.0.16), to be released ~soon.

**Comment by Altonss** [comment]
Yes I am using Wayland !

**Comment by skyjake** [comment]
SDL 2.0.16 is now available, but I have no idea whether the Flatpak runtimes will start using it anytime soon.

One option would be to build it manually and link statically, which would also allow tailoring its build options to exclude any unused features/dependencies. I may look into that in the future.

**Comment by slanderous-mambo** [comment]
[The new Freedesktop SDK (21.08)](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/release/21.08) was just tagged and it includes SDL 2.0.16!

**Comment by jle64** [comment]
I still have the issue, even when running with the 21.08 Freedesktop SDK with `flatpak run --runtime-version=21.08 fi.skyjake.Lagrange`.

However as a stopgap solution removing the Flatpak permission to run through Wayland (using Flatseal) forces it to run in an X11 window which circumvents the issue.

**Comment by Altonss** [comment]
> However as a stopgap solution removing the Flatpak permission to run through Wayland (using Flatseal) forces it to run in an X11 window which circumvents the issue.

This could indeed be a could patch until it runs well on Wayland! Would it be complicated to implement this patch for a next version?

**Comment by skyjake** [comment]
@Altonss In #303 there is a report of Lagrange working better under Wayland with the current set of Flatpak permissions.

Unfortunately, I have no frame of reference here to determine which set of options would work best for most Flatpak users.

The Freedesktop runtime used by the app does need upgrading, too. I'll do that first.

**Comment by Altonss** [comment]
Maybe we should add the _bug_ label as Lagrange is currently unusable on Wayland

**Comment by skyjake** [comment]
I've modified the permissions in the v1.7.0 build with the intent to always either use X11 or the X11 fallback. Hopefully this works better both on Wayland and X11 itself.

Please report back how it goes.

**Comment by Altonss** [comment]
Just updated, the workaround works great thanks!

**Comment by skyjake** [comment]
Closing the issue. Ultimately it's up to SDL to implement full support for Wayland windowing.

**Comment by slanderous-mambo** [comment]
SDL does actually support Wayland windowing as of 2.0.16 ([works for me](https://user-images.githubusercontent.com/64353947/135206552-84718124-189d-495c-87ba-1fca74e8eaf4.png) if I compile Lagrange myself), but this does depend on libdecor, [which is not in the freedesktop SDK yet](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1300), or, as far as I know, any distros other than Fedora.

**Comment by skyjake** [comment]
Interesting. Given enough time and SDK updates, the situation should then improve and Wayland can be enabled in the Flatpak builds.
