### ISSUE TITLE
freeze & crash when directed to open an invalid gopher:// URL

### ISSUE THREAD

**Issue by marek-lach** [skyjake/lagrange#323]
I am running Lagrange natively on _Arch Linux_:

When a `gopher` address that has been entered into the address bar doesn't really exist, and it tries to load it for some time, the entire client (browser) often completely freezes, rendering the UI unresponsive:

![Lagrange_freezes_if_incorrect_gopher_address](https://user-images.githubusercontent.com/45913977/129073921-25709c8e-5c1f-43f9-bd5f-5277468ae6e5.png)

I have not observed the same behavior with non-existant Gemini addresses, which properly result in a not-found error.

**Possible solution...?**
When the UI becomes unresponsive, and the app is force quit, it should clear its address bar and not try to load the same non-existant address as it does now, because that results in an infinite loop of freeze.

**Comment by skyjake** [comment]
I wonder if this is related to #302... I'll need to try to reproduce this on the systems available to me. I can run Arch Linux in a VM, but it's not a given that the problem can be reproduced inside a virtual machine.

**Comment by marek-lach** [comment]
> I can run Arch Linux in a VM, but it's not a given that the problem can be reproduced inside a virtual machine.

I would be surprised if this was Arch Linux specific.

Mostly I think a non-existent `gopher` URL (such as the one in the screenshot) is the problem, in that `Lagrange` tries to reach it for an infinite time maybe?, and then freezes if that fails, instead of giving up, and stopping its attempt to load the address altogether, if it say, takes longer than 5-6 seconds?

**Comment by skyjake** [comment]
Please test with the [https://github.com/skyjake/lagrange/releases/tag/v1.6.3](v1.6.3) release.

**Comment by marek-lach** [comment]
> Please test with the [https://github.com/skyjake/lagrange/releases/tag/v1.6.3](v1.6.3) release.

With me testing this today, it seems to be fixed (i.e freezing, while loading an incorrect address no longer happens, instead the correct `Network/TLS Failure` displayed, and the app's been fully responsive all the while. Awesome. I'll continue testing, and I will close this issue now as resolved.

Thanks!
