### ISSUE TITLE
Error launching lagrange

### ISSUE THREAD

**Issue by victorhck** [skyjake/lagrange#325]
Hello.

When I launch lagange in a Terminal, I get this message:
```SDL init failed: Audio target 'pulse' not available```

Running openSUSE Tumbleweed and installed from repos...

EDIT:
Seems that there's a bug with Pulseaudio:
- https://bugzilla.opensuse.org/show_bug.cgi?id=1189778
- https://github.com/libsdl-org/SDL/pull/4693

Greetings

**Comment by skyjake** [comment]
Since audio playback is not a requirement for using the app, I've changed the init so that audio errors are logged but otherwise ignored.

Thanks for reporting!

**Comment by victorhck** [comment]
A pleasure...
Thanks to you for your time and code!!
've phun!
