### ISSUE TITLE
Nothing rendered at gemini://rwv.io/2020-11-11.gmi

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#33]
`gemini://rwv.io/2020-11-11.gmi` renders nothing, no header, just a blank tab in v0.7.2.

Sorry if this is fixed in v0.8.0+, it's segfaulting for me (see #32).

**Comment by skyjake** [comment]
Hmm, the site loads correctly for me on Ubuntu, macOS, and Windows 10.

**Comment by ghost** [comment]
Now that I got v0.8+ compiled, it's working. :+1:
