### ISSUE TITLE
Freeze on opening URL (simple text renderer hangs)

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#330]
Lagrange failed (freezes and does not respond anymore) to open the following url:
`gemini://lapacz-kornel.dev/git/gmnigit/commits/6104fffa30382eac461668cd3e3334aeb9be5898.patch`
Amfora and gemget opens it without problem, but Ariane failed too.
Even if it's some server side problem, I guess Lagrange should not freeze on it.

**Comment by skyjake** [comment]
Problem isn't occurring any more? Or at least for me the URL seems to load fine.

**Comment by sikmir** [comment]
No, the problem still exists, Lagrange starts using 100% CPU opening this url. I'm using NixOS, Lagrange 1.6.5.

**Comment by skyjake** [comment]
To diagnose I'll either need to find a system where the problem occurs (maybe OpenBSD?), or you could try to stop the app in a debugger while it's hanging and get a backtrace?

**Comment by sikmir** [comment]
> you could try to stop the app in a debugger while it's hanging and get a backtrace?

```
(gdb) bt
#0  0x00007ffff764577d in __memmove_avx_unaligned_erms () from /nix/store/9bh3986bpragfjmr32gay8p95k91q4gy-glibc-2.33-47/lib/libc.so.6
#1  0x00000000004bc530 in insertN_Array ()
#2  0x0000000000418386 in typesetOneLine_RunTypesetter_ ()
#3  0x00000000004727b5 in runSimple_Font_ ()
#4  0x00000000004752ca in measure_WrapText ()
#5  0x000000000041cc5e in doLayout_GmDocument_ ()
#6  0x0000000000446d87 in setSource_DocumentWidget ()
#7  0x000000000044773b in updateDocument_DocumentWidget_.part.0 ()
#8  0x00000000004483c7 in checkResponse_DocumentWidget_ ()
#9  0x000000000044e43c in processEvent_DocumentWidget_ ()
#10 0x00000000004b1481 in dispatchEvent_Widget ()
#11 0x00000000004b141f in dispatchEvent_Widget ()
#12 0x00000000004b141f in dispatchEvent_Widget ()
#13 0x00000000004b141f in dispatchEvent_Widget ()
#14 0x00000000004b141f in dispatchEvent_Widget ()
#15 0x00000000004b141f in dispatchEvent_Widget ()
#16 0x00000000004b141f in dispatchEvent_Widget ()
#17 0x00000000004abb88 in dispatchEvent_Window ()
#18 0x00000000004acabf in processEvent_Window ()
#19 0x000000000040fbe5 in processEvents_App ()
#20 0x0000000000410bf7 in run_App ()
#21 0x0000000000409a40 in main ()
```

**Comment by skyjake** [comment]
```
#3  0x00000000004727b5 in runSimple_Font_ ()
```

Thanks, I can now reproduce the problem by disabling HarfBuzz. Will fix...

**Comment by skyjake** [comment]
11bf1f9 should do the trick.

**Comment by sikmir** [comment]
Thanks, it works now.
