### ISSUE TITLE
Don't list internal tags as a section in `about:bookmarks?tags`

### ISSUE THREAD

**Issue by GoodClover** [skyjake/lagrange#331]
The `usericon`, `subscribed` e.t.c., tags are used by Lagrange internally, and not added by the user for categorisation.

Listing them as a section in `about:bookmarks?tags` seems a bit odd to me, so I suggest that they should be hidden.

`subscribed` is the only (current) one that would make sense to keep on the page IMO.

**Comment by skyjake** [comment]
You're right that there should be some sort of distinction made between user tags and internal tags. I'll need to do some thinking around this topic...

**Comment by skyjake** [comment]
I think this has been implemented already.
