### ISSUE TITLE
Remote bookmarks on mobile version of Lagrange

### ISSUE THREAD

**Issue by szczja** [skyjake/lagrange#332]
Is "1.4.2 Remote bookmarks" function is working in mobile version of Lagrange (iOS)? I've seen "Use as Bookmark Source" option at "Edit bookmark" dialog. But I don't know where is "Refresh Remote Sources" menu item in mobile version. New items seem to be unsynchronised.

**Comment by skyjake** [comment]
Yeah it should be working, although you need to trigger refreshes manually. The menu item can be found in the bookmarks list context menu (long-press on any bookmark).
