### ISSUE TITLE
Freedesktop SDK seems outdated on Flatpak version

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#335]
When trying to update my flatpaks:
`flatpak update`

I get this message:

`Looking for updates…
Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Applications using this runtime:
   fi.skyjake.Lagrange
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Nothing to do.
`
The Freedesktop SDK seems outdated and this problem is probably also related to this issue: https://github.com/skyjake/lagrange/issues/321

Would it be complicated to use the stable version which seems to be the 20.08.1? https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases

Thanks for the help :)

**Comment by skyjake** [comment]
It should be pretty simple, although I've understood this will mean the end of 32-bit Raspberry Pi Flatpak compatibility. Oh well... I will upgrade the SDK since it's now end-of-lifed.

**Comment by skyjake** [comment]
SDK upgraded and new build published.
