### ISSUE TITLE
Menu misbehaves after vertical split (XUbuntu 12.04)

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#337]
After vertical split, clicking the menu icon results in **unexpected behaviour:** instead of using the available space to display as many menu items as fit, and scrolling as necessary, Lagrange displays the bottommost menu items.

My initial misunderstanding was that the menu somehow changed and the options to split disappeared, causing me to frantically search the documentation about how to unsplit the screen.  It was not obvious to me, until today (several days later) that I could scroll up to see the top options.

Worse yet, **the bottom pane menu is buggy**.  It is not possible to scroll the bottom menu at all, and only the lowest selections are available.

**Comment by skyjake** [comment]
While the current split view mode implementation sets some restrictions on the placement and sizing of menus, it is certainly a bug that the bottom one can't be scrolled properly.

Ultimately the problem here is that popup menus shouldn't be confined inside the window, and there are two ways to solve that: use native menus (on Mac/Windows), or create new frameless windows for menus.

**Comment by stacksmith** [comment]
From the usability/onboarding standpoint, I humbly suggest that you prioritize fixing it.  I almost gave up on Lagrange within the first minute - the first thing I did was split the window, then could neither unsplit nor make sense of the (unfamiliar to me) menu fragments...

**Comment by skyjake** [comment]
I'm looking into improving this.

Note that split view mode can be ended by closing all tabs in one of the splits (e.g., Ctrl+W or ⌘W). Of course, the tab buttons lack the typical [x] buttons so there's another thing that a new user might be confused about...

**Comment by stacksmith** [comment]
I was about to mention the x, but did not want to dilute the issue...  I am on day 2 of using Lagrange, and definitely found it hard to close tabs.  The *de rigeur* 'x' in the tab is probably even better than the (missing) 'close tab' menu.

I also miss dragging links (from the document) into the bookmark pane to create bookmarks.  Also, freeform (not alphabetical) bookmarks, and folders of bookmarks... I imagine that is hard to do in plain SDL without some damned widget kit...

On the positive note, I love the look of Lagrange.  Thank you so much for your hard work!

**Comment by skyjake** [comment]
Free-floating menus coming in v1.7: https://skyjake.fi/@jk/106963120790473296
