### ISSUE TITLE
Feature Request: Customizable key binding for opening links using the keyboard

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#34]
Could it be possible to redefine the key used to navigate with the keyboard?

The current <kbd>ALT</kbd> key assigned to this functionality collides with the ubiquitous <kbd>ALT</kbd>+<kbd>TAB</kbd> combination used to cycle through windows. When I press <kbd>ALT</kbd>+<kbd>TAB</kbd> in Lagrange, it captures the <kbd>ALT</kbd> key, shows the numbered/lettered links and focus the URL input field. My new window is selected and when I do <kbd>ALT</kbd>+<kbd>TAB</kbd> again to return to Lagrange I always have to press <kbd>ESC</kbd> to unfocus the URL bar. That's really awkward.

I would like to be able to follow links with the keyboard à la qutebrowser: I press and release the <kbd>f</kbd> key, the numbers/letters for the links are shown, and then I press the wanted key to follow the link.

Thanks for this wonderful gemini client.

**Comment by skyjake** [comment]
Sure, I'll add a keybinding for toggling the keyboard navigation mode on.

**Comment by jcromero** [comment]
I also think the <kbd>f</kbd> key is a better default setting for toggling the keyboard navigation because it is there in the home row, very accesible. I also think that for keyboard navigation it is better to label the links first with the letters in the home row. Your fingers don't need to become contorted to do an action as common as following a link.

**Comment by skyjake** [comment]
>  also think that for keyboard navigation is better to label the links first with the letters in the home row. 

You mean they should start with A, S, D, ... L ? Or where should it start on the home row? That could potentially be an option in Preferences.

**Comment by jcromero** [comment]
You can see an example here. The central letters in the home row are the better ones to use first:

![Screenshot_20201111_195620](https://user-images.githubusercontent.com/984714/98852438-f8366080-2457-11eb-8276-8616dc19932d.png)

**Comment by skyjake** [comment]
I see. What does the (lowercase) "L" prefix mean?

**Comment by jcromero** [comment]
It does not mean anything. You have to press and release <kbd>l</kbd> and then press and release <kbd>d</kbd>, <kbd>f</kbd> or <kbd>g</kbd> to follow those links. It is really fast to browse that way with the keyboard. A lot faster than move all your hand to the top row where the numbers are (specially when you have small fingers :smile: )

**Comment by skyjake** [comment]
Ah, thanks for explaining! This does seem to make a lot of sense. 👍

**Comment by jcromero** [comment]
Nevertheless, gemini pages are not full of links, like web pages are. Perhaps it is not needed to use two letters to follow a link and only one letter in the home row is enough.

**Comment by jcromero** [comment]
Only one remark, independent of the link numbering/lettering method :

<kbd>ALT</kbd> and <kbd>TAB</kbd> keys should not be captured by the application, because of the reasons explained in the feature request: when cycling through windows using the <kbd>ALT</kbd>+<kbd>TAB</kbd> shortcut, the mode for following links is enabled and, at he same time, the URL bar is focused, so you have to press <kbd>ESC</kbd> twice, one to disable the follow link mode and one to unfocus the URL bar. It's very awkward to navigate with the keyboard that way.

**Comment by jcromero** [comment]
Well, reading the code I see maybe I can save one <kbd>ESC</kbd>, because when scrolling, the follow link mode is disabled. Nevertheless, I think it is ugly to enable the follow link mode when you only wanted to change forward and backward in your windows history. Besides, if the piece of document visualized has a link that can be followed with my defined scroll-up or scroll-down keys, I can not save pressing the <kbd>ESC</kbd> key.

**Comment by skyjake** [comment]
> When I press <kbd>ALT</kbd>+<kbd>TAB</kbd> in Lagrange, it captures the <kbd>ALT</kbd> key, shows the numbered/lettered links and focus the URL input field

> <kbd>ALT</kbd> and <kbd>TAB</kbd> keys should not be captured by the application

I agree. I'll need to add some special exceptions to the handling of this key combination. The current situation exists because SDL apps receive all key events as raw events.

**Comment by jcromero** [comment]
> I agree. I'll need to add some special exceptions to the handling of this key combination. The current situation exists because SDL apps receive all key events as raw events.

I see. It worries me, then, how are you going to manage all the global keyboard shortcuts of every desktop? If you add exceptions, that's not going to be scalable.

How are other SDL applications managing all this stuff?

**Comment by skyjake** [comment]
> how are you going to manage all the global keyboard shortcuts of every desktop?

My approach is to have a reasonably safe/sane set of default keys for Windows, Mac, and X11/Unix/Linux, and then allow the user to change via keybindings any keys that might clash with their global keyboard shortcuts. At present time, keybindings haven't yet been added for everything that is reasonable to customize.

> How are other SDL applications managing all this stuff?

SDL apps are usually games so they use a limited set of keys, and also have configurable keybindings. SDL can also completely disable system shortcuts from being activated, as it can handle the raw events before the system gets them. However, for a windowed desktop app that isn't appropriate behavior.
