### ISSUE TITLE
fribidi on ubuntu/debian needed

### ISSUE THREAD

**Issue by juniberry** [skyjake/lagrange#344]
README.MD
"Ubuntu: sudo apt install cmake libsdl2-dev libssl-dev libpcre3-dev zlib1g-dev libunistring-dev"

I suggest adding "libfribidi-dev" to that list to help newcomers~

**Comment by skyjake** [comment]
That probably is the best choice.

I need to double-check the source build UX here. The original idea with having fribidi as a git submodule was that it would get built if not already available via pkg-config. Did you run into an issue regarding that? (perhaps Meson related?)

**Comment by juniberry** [comment]
Yeah, I did .. On a fresh install of Linux Mint Cinnamon 20.2 .. So, I figured I'd just let ya know ~
