### ISSUE TITLE
Showing blank page for atom.xml feed

### ISSUE THREAD

**Issue by RexMorgan** [skyjake/lagrange#348]
When I attempt to load this atom feed, it doesn't list anything. When I download the feed, it has contents and looks correct at first glance.

gemini://idiomdrottning.org/atom.xml

![image](https://user-images.githubusercontent.com/178752/135523794-0f5df517-3265-4802-b5f1-b288d8e954f9.png)

**Comment by skyjake** [comment]
Thanks for reporting!

Fixed for 1.7.1.
