### ISSUE TITLE
Make time format independant of selected language

### ISSUE THREAD

**Issue by Kodden585** [skyjake/lagrange#349]
Currently the time format used for the message at the bottom of each page, telling when the page was received, is set by language. This is kind of annoying since that means the only way to get 24-hour time is to set it to Interlingua or other languages I don't speak.

**Comment by skyjake** [comment]
Hmm, I could add a 12/24 hour option here, or even a custom format string for the timestamp. 

The page footer area needs a bit of improving in general, too.

**Comment by skyjake** [comment]
24-hour time preference added for 1.9.1.
