### ISSUE TITLE
Clicking links and touch scrolling fail on mobile

### ISSUE THREAD

**Issue by justjosias** [skyjake/lagrange#351]
After updating from 1.6.6 master to current master, scrolling by swiping and clicking links doesn't work. I compiled it with and without the mobile cmake option and with and without setting the build type to Release.

Scrolling with the scrollbar still works.

Hardware: PinePhone
OS: Mobian with Phosh

**Comment by skyjake** [comment]
There were a couple of tweaks in mouse/touch event processing in v1.7, so something must now be incompatible with the touch events on PinePhone/Mobian. I'll poke around a little and see if I can detect anything on my end, but unfortunately I don't have a PinePhone to debug with so success is not guaranteed...

**Comment by skyjake** [comment]
@justjosias Have you checked if this is fixed for you in v1.8?

**Comment by justjosias** [comment]
It works quite well now. Thank you! All the touch events appear to be operational.
