### ISSUE TITLE
Having trouble viewing dithered image in Lagrange

### ISSUE THREAD

**Issue by mntn-xyz** [skyjake/lagrange#353]
I used didder (https://github.com/makeworld-the-better-one/didder) to dither an image using a reduced palette, and it refuses to render when deployed to my Gemini site (tested both locally and in production). Not sure what's going on here, I can view it locally in other programs just fine. This really sent me on a wild goose chase since Ariane also has trouble with it.

![test](https://user-images.githubusercontent.com/85877297/136220479-54770864-a2a3-460e-8d96-d11c0343e511.gif)

This was generated with the following didder options: `-f gif -x 600 -p 'tomato orange gold lightseagreen cornflowerblue mediumpurple black ivory' edm --serpentine Simple2D`

Maybe it has something to do with the reduced palette? I rerendered as png and now I have no trouble with it.

**Comment by skyjake** [comment]
It could be a GIF variant that is not widely supported. The error message from [stb_image](https://github.com/nothings/stb) (used by Lagrange) is "no clear code", "Corrupt GIF".

GraphicsMagick manages to fix it, though:

```
gm convert broken.gif -colors 8 fixed.gif
```

The generated `fixed.gif` is 48 bytes larger, so the encoding is somehow different. It then loads fine with stb_image in Lagrange.

This doesn't seem like a bug in Lagrange, so closing the issue.

**Comment by mntn-xyz** [comment]
Thanks, could be an issue with didder. I'll report it there.
