### ISSUE TITLE
lagrange crashes on debian buster/X11 or armhf.

### ISSUE THREAD

**Issue by norayr** [skyjake/lagrange#355]
hello,

thank you for writing lagrange, it's my default browser.

because i use linux mobile devices running maemo-leste (the system is very close to debian 10), i built it and generated a deb package by modifying your build system only a little bit; to add maemo specific icon, shortcut, etc.

however it crashes on my 32bit ARM systems - I didn't check on other machine. 

the crash happens when i am trying to scroll.

you can find the strace logs here:

gemini://norayr.am/lagrange/

hope those will be helpful.

any advice would be appreciated.

**Comment by skyjake** [comment]
> the crash happens when i am trying to scroll.

To me the strace looks like a controlled/normal shutdown. I couldn't pinpoint exactly where the error occurs.

Running a debug build and seeing if any assertions are failing could be informative.

One potential problem could be limited texture memory. Could you try launching the app with the `--sw` option to disable all hardware rendering?

**Comment by skyjake** [comment]
You may be interested to test the new armhf AppImage, available from v1.8.1 onwards.
