### ISSUE TITLE
[Gopher] Support p item type (PNG) (Floodgap)

### ISSUE THREAD

**Issue by Testsr** [skyjake/lagrange#356]
This gopher site, gopher://gopher.floodgap.com:70/1/fun/xkcd/comics/2520/2526 has a p item type in its listing. Floodgap apparently uses this type to load PNG images. This should be supported, as floodgap is one of the major portals into gopher.

**Comment by skyjake** [comment]
Ok, should be easy enough to do.

**Comment by skyjake** [comment]
Done for v1.7.2.
