### ISSUE TITLE
Leftward text selection dragging seems broken

### ISSUE THREAD

**Issue by GreenBeard** [skyjake/lagrange#357]
When one attempts to drag leftward it first selects the proper starting character, but then it bugs out, and jumps left one. For example if one attempts to select "bar" by placing their character directly after the "r" then clicking, and finally dragging leftward it will initially select the "r", but after moving past the "a" it will only retain the "a". Finally once one passes the "b" it will have "ba". If one starts dragging rightward initially, and then after selecting a few characters one drags leftward it appears to work properly. I'm on Devuan Beowulf using XFCE 4.12.5 if that is helpful and/or relevant.

As an aside I have to say that this project seems really cool, and it was really quick to build the `.deb` package :D

**Comment by skyjake** [comment]
Thanks!

Yeah, that is not the intended selection behavior... I'll fix it.

**Comment by skyjake** [comment]
Fixed for v1.7.2.
