### ISSUE TITLE
Creating bookmarks into folders

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#358]
Running on Xubuntu 20.04, Lagrange 1.7.2

An almost perfect user experience!  

Not being able to drag links (or current URL) into bookmarks makes life hard. 

Bookmarking by pressing Ctrl-D (why?), followed by confirming and dragging the new bookmark from the bottom to a folder at the top of the list (because things I like are at the top) is a complete pain.

Compare to a quick drag of a link to exactly where it belongs in the bookmarks.

Feels nitpicky, but I find myself muttering terrible curses every time it happens.

Many thanks

**Comment by skyjake** [comment]
I agree that dragging links and URLs to the bookmarks list would be useful for sure. I'll make a note to implement that at some point.

> Bookmarking by pressing Ctrl-D (why?)

The default keybinding was chosen to match Firefox and Safari. It can be changed in Preferences > Keys.

> things I like are at the top

Dragging links is a relatively big feature, but what about an option to add new bookmarks to the top of the list? That would be pretty simple to do and maybe alleviates the annoyance.

**Comment by stacksmith** [comment]
Inserting bookmarks at the top is definitely better.

Another option is to insert into the **most-recently-used bookmark folder, if it is open**, otherwise, top.  That gives the user some control over the destination.

As a last resort, an 'unsorted' folder?

**Comment by stacksmith** [comment]
After a week of suffering, any of these would help:
* If an 'unsorted' folder exists, drop bookmarks there;
* Allow user to specify folder upon creation of each bookmark a-la Firefox (a little cumbersome);
* Create bookmarks at the top of bookmarks list (not much better, but would force me to organize);
* Create into the most-recently-opened folder (still my favorite)
* Have some way of selecting the incoming folder (right-click?)

Any of these would be a help, compared to dragging bookmarks from the bottom each time

**Comment by skyjake** [comment]
Thanks for the suggestions. Some of those are definitely doable.

v1.7.3 has the option to add bookmarks to top, available now.

**Comment by stacksmith** [comment]
I am using 1.8 and can't see that option (add bookmark to top).  has it been removed?

Thank you for implementing drag-drop within the bookmark sidebar, very helpful.

Dragging from URL-bar into the correct place in bookmarks is _the only way I can keep bookmarks organized_ ... This is putting a real dent into my browsing experience.

**Comment by skyjake** [comment]
It's here:
<img width="415" alt="Screen Shot 2021-11-07 at 22 01 05" src="https://user-images.githubusercontent.com/1225742/140660075-918759ee-9b1a-4656-b3f6-2805322da4f3.png">
If that is "NO" then newly added items go to the top of the list.

> the only way I can keep bookmarks organized

I can't really relate to this, but I suppose everyone has their own browsing style. I admit I'm not a heavy bookmarker or tabs user. It sounds like you're creating bookmarks quite often?

**Comment by stacksmith** [comment]
I create bookmarks all the time, right into folders.  Often before reading the content, I will through a link into a folder to read later; other times I like the site I am at, and I drag the url bar link into a folder... This allows me to easily chose which folder to drop the mark, and I generally have a few open folders in full view (with subfolders for subtopics closed, for dropping into).  This sounds a bit complicated, but it works really well.  

I generally prefer command-line/keyboard applications, but when I browse in a GUI (doing research mostly), with the mouse in my hand, I don't want to type at all, when possible.  So I don't want to choose target folders with keyboard commands or searches.  I need to stay visual, and drag and drop, occasionally creating a new folder and typing in the name.

I understand it is not a high priority for you if you don't browse that way, but all web browsers allow link drag/drop, and without that feature LaGrange is reduced to a shiny toy (and the oddly pink font does not help!).  Gemini is getting to a size where my bookmarks and link management are beginning to drag me down - as browser writers are not paying enough attention to this most important job of a browser.  Ariane, for instance, is a great browser, but is nearly useless after an hour of browsing because of its horrible bookmark management - the only way to arrange bookmarks is to move them up or down one space, and no folders.  

Thank you for considering this seriously, and sorry if I sound like an a-hole.

**Comment by skyjake** [comment]
Thanks for elaborating! The point about performing actions only with the mouse is well taken. That can be as important as the inverse of using only the keyboard, which isn't fully possible either. I will endeavor to address both ends of the spectrum.

**Comment by stacksmith** [comment]
Yeah, I despise the mouse and was dragged in kicking and screaming, so it's ironic to see myself championing it.  But from usability standpoint, for browsing (mainweb) it is not realistic to choose links with the keyboard... Once the mouse is in hand, I want to do as much as possible before coming back to typing.

I've been experimenting with 4- and 5- character labels for links (which are databased and site-persistent).  Typing 4-5 characters when your fingers are on the keyboard is faster than moving to the mouse and figuring out where the pointer is, then clicking.  These labels also act as shortcuts/bookmarks, as it's easy enough to remember 4 or 5 character labels you use often, and you can even assign meaningful-to-you 2- and 3-character labels to 'speed-dial' commonly-used links...  

I like your ALT-key link-label scheme.  Persistent labels concept is a logical extension of that (and maybe of URL shorteners)...It works particularly well in a modular browser (which you should perhaps consider - breaking out the requestor from the UI/renderer).

**Comment by skyjake** [comment]
> * Allow user to specify folder upon creation of each bookmark a-la Firefox (a little cumbersome);
> * Create into the most-recently-opened folder (still my favorite)

These have been implemented for v1.9.

**Comment by stacksmith** [comment]
Thank you so much.
I do hope you get drag/drop of links working throughout Lagrange at some point.
