### ISSUE TITLE
Document how to build iOS

### ISSUE THREAD

**Issue by arafangion** [skyjake/lagrange#361]
Hey, hope this is a minor one.

I'm familiar with iOS dev, and have an apple developer account and all that, however I'm not familiar with cmake or that sort of thing.

I have checked out the project, including submodules.

I've attempted to do this by creating a build directory inside the git repo, and have run:
```
arahael@Johns-MacBook-M1 ~/s/l/build (dev)> cmake -GXcode -DCMAKE_SYSTEM_NAME=iOS ..
-- The C compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- iOS dependency directory:
CMake Error at Depends-iOS.cmake:3 (find_package):
  By not providing "Findthe_Foundation.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "the_Foundation", but CMake did not find one.

  Could not find a package configuration file provided by "the_Foundation"
  with any of the following names:

    the_FoundationConfig.cmake
    the_foundation-config.cmake

  Add the installation prefix of "the_Foundation" to CMAKE_PREFIX_PATH or set
  "the_Foundation_DIR" to a directory containing one of the above files.  If
  "the_Foundation" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Depends.cmake:2 (include)
  CMakeLists.txt:62 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/arahael/src/lagrange/build/CMakeFiles/CMakeOutput.log".
```

Where can I find this 'the_foundation' stuff?

Other interesting details:
1. Yes, it's an M1 Mac running big sur.
2. I do have Xcode 13, but happy to use Xcode 12 if required.
3. cmake version 3.19.4
4. I use macports, not home-brew, but I don't think this should affect anything.
5. I've been able to successfully build, and compile, the Mac version. I deleted the build directory and then tried again for iOS.
6. My overall motivation, is to hopefully see if this works on my iPad 2, which is like, 10 years old now.  It's too old for TestFlight, and too old for the App Store to work at all.  Compiling and side loading the apps is the only thing that works now!

**Comment by skyjake** [comment]
The iOS build is not that simple, but I've added some instructions and example scripts in [this commit](https://github.com/skyjake/lagrange/commit/2d29615b9e7ebce07b4d8b3745e3515b32c199c0). It's in the work branch for now but the instructions are not version-specific.

Good luck!

**Comment by arafangion** [comment]
I'll check them out.  At a glance, they look like a great pointer in the right direction. Thanks for that!

**Comment by skyjake** [comment]
One more thing: you'll also need to build [SDL](https://github.com/libsdl-org/SDL) for iOS, but it comes with a proper Xcode project in the repository and the only thing to check is the target OS version.

**Comment by arafangion** [comment]
Thanks for that tip!

**Comment by arafangion** [comment]
(I probably won't get a chance again until later in the week, but I do appreciate these!)
