### ISSUE TITLE
Memory leak when drawing text

### ISSUE THREAD

**Issue by jasongrlicky** [skyjake/lagrange#362]
Hi there! First of all, thanks so much for creating Lagrange, it's really cool!

I left Lagrange running overnight and saw that it had eaten up all my memory in the morning, so I figured there had to be a memory leak in the draw loop somewhere. After a some of experimentation, I found that I can reproduce the leak just by clicking into the URL bar and letting the cursor blink.

I am not the most confident C dev, but I got the project building locally for debugging and set the proper code-signing entitlements so I could use Apple's Instruments to check for memory leaks by marking generations and seeing what allocations stuck around.

This is a brand-new codebase to me, but it seems like the leak might stem from forgetting to deinit the `buffers` array in the `run_Font_` function in `text.c`. The leak seems to be fixed if I add the following [after the `GlyphBuffer`s are de-inited](https://github.com/skyjake/lagrange/blob/dece9b7406eb2c6eff768ff8a1badb7ef7076082/src/ui/text.c#L1811):

```c
deinit_Array(&buffers);
```

Hopefully that's helpful!

This was observed in Lagrange 1.7.2 arm64 on macOS 11.6 on a M1 Mac Mini.

**Comment by skyjake** [comment]
Thanks! And yes, well spotted. As it turns out I just noticed it myself yesterday: 164de748cdd

I'll make a patch with at least this fix today.

**Comment by skyjake** [comment]
Patch released.
