### ISSUE TITLE
Multiline headlines overwrite themselves with background color.

### ISSUE THREAD

**Issue by grzegorz-kraszewski** [skyjake/lagrange#364]
I use Literata font for headlines. When a headline is long and takes more than one line, the next line overwrites bottom of the previous one, damaging letters like [gjpqy]. Can be "fixed" by increasing line spacing (1.1 does the job), however I guess text rendering should only place foreground pixels.
![lagrange_overwrite](https://user-images.githubusercontent.com/6670176/138485188-65d9947b-a948-4fca-b85a-9ab8374adf72.png)

**Comment by skyjake** [comment]
Ah yes, I've been meaning to do something about this. The problem is that headings use a slightly shorter line height, so the background clearing of a text line overwrites the previous line.

**Comment by skyjake** [comment]
Workaround slated for v1.8.1.
