### ISSUE TITLE
Separate feeds from bookmarks 

### ISSUE THREAD

**Issue by aelspire** [skyjake/lagrange#366]
Let's say, I would like to have `gemini://<capsule-domain>` in bookmakrs but gemlog is placed in `gemini://<capsule-domain>/gemlog/` and I want to have this one in feeds.

Currently there are 2 options:
1. Add both, one as bookmark with tag `subscribe` and one without, so there are 2 bookmarks to the same capsule
2. Add only gemlog as bookmark and have to always click back button to go to root

I would like to sugest to add separate place for bookmarks and feeds.

**Comment by skyjake** [comment]
In my opinion, the cost of implementing a bespoke feed management UI far exceeds any benefits gained from it. With bookmark folders added in v1.7, you can now move any subscription-only bookmarks into a folder and keep them out of sight. So I recommend option 1.

I am planning to do a bookmark filtering feature at some point that could further aid here in visually separating subscriptions and other bookmarks.

**Comment by aelspire** [comment]
> you can now move any subscription-only bookmarks into a folder and keep them out of sight.

Ah, I literally haven't thought about it. It works too. Thanks!
