### ISSUE TITLE
Finer glyph subpixel positioning for small pixel sizes (otherwise causes uneven font spacing)

### ISSUE THREAD

**Issue by nyanpasu64** [skyjake/lagrange#367]
Lagrange 1.7.3 (flatpak, Arch Linux) only renders each character at 1 of 2 possible subpixel positions  (at least in the address bar):

![Screenshot_20211025_212816_](https://user-images.githubusercontent.com/913957/138808930-20936fac-03b1-470a-87ce-8e65c71d6cb4.png)

Note that each "l" is either black with a slight gray line to the left, or blurry (spread across 2 pixels) with a somewhat lighter line on the right. There are only 2 renderings of the character.

I also noticed poor positioning/kerning of running text, where some characters appear cramped or too far away. If body text's glyphs are only rendered at half-pixel offsets, that would explain the poor spacing.

![lagrange gemini spacing](https://user-images.githubusercontent.com/913957/138809065-489bffbc-b7ab-43c8-9114-b50affaa51e8.png)

The "vig" in "navigation" looks especially bad, but "bar" looks slightly off as well.

I think 4 possible positions is "good enough" (GTK4 uses 4 horizontal positions per character), and I know some people have gotten away with 3 (though I myself don't trust that it will look good enough).

**Comment by skyjake** [comment]
You are correct in that only 2 subpixel positions are used currently, and that it is not quite enough with small pixel sizes. I will look into increasing it to 4 where needed.

> poor positioning/kerning of running text

Yes, most likely this is due to the currently used offsets. You could try changing the UI scaling factor slightly (1.01, for example), and see if the glyphs shift around visibly to verify that.

**Comment by nyanpasu64** [comment]
I'm currently on UI scale 1.1, and when I type `llllllll...` into the address bar, sharp/blurry glyphs alternate every 8 or 9 characters.. Changing the UI scale to 1.2 makes them alternate every 1 or 2 characters instead.

**Comment by skyjake** [comment]
Normal density displays will have 4 subpixel positions for glyphs in v1.12.
