### ISSUE TITLE
Cannot compile the current dev branch

### ISSUE THREAD

**Issue by Strahinja** [skyjake/lagrange#369]
Fresh git clone from the current dev branch cannot compile on my system (regularly updated Artix Linux, gcc version 11.1.0 (GCC)). I executed:

```
$ git clone --recursive --branch dev https://git.skyjake.fi/gemini/lagrange
$ cd lagrange
$ mkdir build && cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- Compiling bincat for merging resource files...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/strajder/src/lagrange/build/res
Consolidate compiler generated dependencies of target bincat
[100%] Built target bincat
-- CPU supports SSE 4.1
-- Checking for module 'eopenssl11'
--   Package 'eopenssl11', required by 'virtual:world', not found
-- Checking for module 'openssl'
--   Found openssl, version 1.1.1l
-- Preparing resources...
--   res/default.fontpack
CMake Error at res/Embed.cmake:133 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:119 (embed_make)

...

-- Configuring incomplete, errors occurred!
See also "/home/strajder/src/lagrange/build/CMakeFiles/CMakeOutput.log".
See also "/home/strajder/src/lagrange/build/CMakeFiles/CMakeError.log".
```

Attached files:
[CMakeError.log](https://github.com/skyjake/lagrange/files/7446475/CMakeError.log)
[CMakeOutput.log](https://github.com/skyjake/lagrange/files/7446476/CMakeOutput.log)

**Comment by skyjake** [comment]
The Debian CI build here on GitHub seems to have the same error, although none of my local systems do. I'll investigate what's going on, shouldn't be too difficult to fix.

**Comment by etam** [comment]
I have the same on current 1.8.0 release.

**Comment by skyjake** [comment]
Looks like this error occurs when the `zip` command line utility isn't installed.

At least for me installing it fixes the problem.

**Comment by FerociousStrike** [comment]
I was running into the same issue trying to compile it on my Raspberry Pi and can confirm that installing `zip` resolved it for me as well. Thanks!

**Comment by etam** [comment]
I confirm that installing `zip` resolves the problem. There should be some check in cmake for it, to make an explicit error message.

**Comment by skyjake** [comment]
16c308157ebb54cf4fc3e0897c7419eb12849b7a should take care of that.

**Comment by Strahinja** [comment]
Confirmed, installing zip solved the issue, so I will close it.

@skyjake I think that a sentence about zip being a build requirement should be added to README.md.

**Comment by skyjake** [comment]
Yeah, I'll add that to the README.
