### ISSUE TITLE
Crash at X_SetInputFocus

### ISSUE THREAD

**Issue by etam** [skyjake/lagrange#370]
Lagrange version: 1.8.0
OS: openSUSE Tumbleweed

Happened once (so far); Steps to reproduce: unknown

Application crashed with message:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  2647
  Current serial number in output stream:  2648
```

**Comment by skyjake** [comment]
Lagrange does not directly call X11 APIs. It's all done by [SDL](https://libsdl.org) so I would assume this is either a glitch in SDL or some driver-related issue.

Please keep an eye out and see if there are any patterns to triggering it.
