### ISSUE TITLE
Show error messages for failed Titan uploads

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#371]
I got a question from a [Phoebe](https://github.com/kensanata/phoebe) user who was unable to upload a file using Lagrange. When I tried to do the same, I also failed a few times and was unable to say why it was failing. Now that I have access to my log files, I see that the answer would have been obvious if I had seen them. Thus, when a status 40 is received, can we show it to users? Otherwise, these are the strings I currently use:

- 40 An error occured, unfortunately
- 40 The wiki is locked; try again in a few seconds
- 59 Unable to write index
- 59 Unable to write log
- 59 Unable to save …
- 59 Received more than the promised … bytes
- 59 The path … is malformed
- 59 The URL lacks a page name
- 59 Page names must not contain any control characters
- 59 Uploads require a token
- 59 Your token is the wrong token
- 59 Uploads require a MIME type
- 59 This wiki does not allow …
- 59 You need to send along the number of bytes, not '…'
- 59 This wiki does not allow more than … bytes per page

I'd be happy to return more useful status codes or some token indicating the error condition for those cases where the user is able to influence the situation.

For the record, I ran into "This wiki does not allow more than … bytes per page" and "The path … is malformed" (when I tried a different path).

I think the most likely candidates would be:

- 59 This wiki does not allow more than … bytes per page → size limits should always be in place, I think
- 59 The path … is malformed → upload in the wrong place
- 59 The URL lacks a page name → see above
- 59 Page names must not contain any control characters → see above
- 59 Uploads require a token
- 59 Your token is the wrong token
- 59 This wiki does not allow … → not all MIME types are allowed
- 40 The wiki is locked; try again in a few seconds → hopefully super rare!

**Comment by skyjake** [comment]
This seems to be related to the issue where Lagrange does nothing when the server closes the connection earlier than expected. I'll investigate a bit and fix this.

**Comment by skyjake** [comment]
6054819 seems to fix the problem for me at least. It will be included in v1.8.1. We can close this issue after appropriate testing has been done.

**Comment by skyjake** [comment]
@kensanata I'm assuming this is now fixed, but please reopen if there are still problems with the error messages.
