### ISSUE TITLE
Add View Source feature

### ISSUE THREAD

**Issue by balazsbotond** [skyjake/lagrange#374]
As a relatively new gemini user I often look at the source code of pages. My current workflow is to click on Copy Page Source in the menu, open vim and paste it. This feels like too much work for just looking at how something is formatted. It would be great if I could view the source on a tab inside Lagrange and skip the copying and pasting.

**Comment by skyjake** [comment]
I agree, and that's why there's #359. ☺️

Closing as duplicate.

**Comment by balazsbotond** [comment]
Oh I see. Thank you.
