### ISSUE TITLE
Gopher Page that does not render in Lagrange, but renders in other browsers.

### ISSUE THREAD

**Issue by Testsr** [skyjake/lagrange#377]
This is the page: gopher://declanhoare.id.au:70/1/TempleOS_Gopher

**Comment by skyjake** [comment]
The problem was that the page uses LF characters as line endings. At least some versions of the Gopher specification require CRLF, so that's what Lagrange expected. I've now allowed both LF and CRLF to be recognized.

**Comment by skyjake** [comment]
Fix will be in v1.8.1.
