### ISSUE TITLE
Split view: no easy GUI way to close splits

### ISSUE THREAD

**Issue by TadaCZE** [skyjake/lagrange#378]
You have to use CTRL + W to close a split, that would be manually, tab by tab. There is literally no way to close the split without a keyboard without closing Lagrange outright. The solution, at least to me would be to always display tabs when in split view or by adding a close button.

**Comment by skyjake** [comment]
You're right there should be some sort of a quick button for getting out of split mode.

However, there are two ways that need to be handled: closing the last tab of a split, and unsplitting without closing any tabs (i.e., "Merge tabs" in the split view menu). I'll need to think about the most appropriate design here...

**Comment by TadaCZE** [comment]
Anyways, to the issue of the UI, I made a quick mock-up:
![jake](https://user-images.githubusercontent.com/33400123/143405506-ffd11a1f-0044-4e7c-b31c-f3e11e191971.png)

- You could add tabs on either side using the buttons and drag-and-drop them from one side to another.
- That colorful button in the center could just close the split and the tabs would merge. I think it looks intuitive.

Also, found a related issue, for me in split view mode links on both sides always open on the right hand side.

Also, another related issue, when in split view mode, Lagrange somehow managed to use 100% of a CPU core.

**Comment by skyjake** [comment]
Thanks for the mockup! Unfortunately, my UI toolkit can't quite implement that as is, but using the tab bar could be useful for this purpose in the future. I'm probably not going to always show the tab bar, though, as it takes away some vertical space. (Not a fan of tall bars...)

> for me in split view mode links on both sides always open on the right hand side.

This is called "split view pinning". It is explained on the Help page and you can control the behavior in Preferences > General.

> when in split view mode, Lagrange somehow managed to use 100% of a CPU core.

Hmm, haven't seen this one. There's a known issue when 100% is being used during a fetching of a streaming page (that never stops loading). Is this reproducible with any set of pages (even "about:lagrange")?

**Comment by skyjake** [comment]
Version 1.9 will have an unsplit `x` button in the toolbar when split view mode is active.
