### ISSUE TITLE
Use the same identity for Titan uploads

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#379]
I was quite confused when I tried to edit pages in the new Transjovian capsules. There's a quick introduction at gemini://transjovian.org/phoebe/page/Capsules, the capsules themselves are gemini://transjovian.org/capsule – the problem is that uploading there requires a client certificate and the Titan uploads do not default to using the same certificate as I used while browsing. This makes sense from a technical perspective, since the URL scheme is different, but from a practical perspective, I think it's highly likely that the same client certificate is going to be used. Alternatively, we could use the same solution as for text and token: keep the last one used so that we don't have to keep picking one for every edit.

(And on my side, I should make sure that the token is not checked when a client certificate is used. Right now, both are checked.)

**Comment by skyjake** [comment]
> keep the last one used so that we don't have to keep picking one for every edit.

This is probably a good idea. Currently, the upload dialog's identity selection only applies to the current upload URL in its entirety, when in practice the identity should be remembered as a site-specific setting. The infrastructure for that exists now in v1.8; it didn't before.

**Comment by skyjake** [comment]
This will be included in 1.8.3.
