### ISSUE TITLE
Incorrect line wrapping with mixed Japanese/English text

### ISSUE THREAD

**Issue by schwigri** [skyjake/lagrange#380]
When Japanese text is all on its own, it wraps as expected. However, if there are English words or phrases mixed in (as is occasionally the case as seen in the screenshot), the Japanese text following the English text is all moved to the next line, instead of filling up the rest of the line as one would expect.

<img width="696" alt="Screenshot of Lagrange displaying a Japanese paragraph with English words" src="https://user-images.githubusercontent.com/18409205/140592831-2b21d009-2447-48f5-aca7-c51a4eea3a1f.png">

You can see in this screenshot, the first paragraph wraps as expected. However, the non-Japanese phrases "S/MIME" and "PGP" cause strange wrapping with Japanese text, and it is all wrapped immediately instead of wrapping at the boundary as expected, making the paragraph look very strange.

**Comment by skyjake** [comment]
Please, could you add a link to the page if it's available somewhere? Or just paste the paragraphs as text here?

That would make fixing/testing easier...

**Comment by schwigri** [comment]
Sure, I have the page available here: gemini://weblog.gs/ja/

For reference, the paragraphs are written like this in the `.gmi`file:

    僕はグリフィン、アクセシビリティーと国際化を大切にしているデザイナー・デベロッパーとしてインターネットをもっと美しくてインクルーシブにしようと存じる。仕事以外は、外国語を勉強したり、ピアノを弾いたりする可能性が高い。

    暗号化されたメールの方を好むので、 S/MIME キーを使用して最初のメールに署名するか、PGP キーを使用して暗号化されたメールを送っていただければ幸い。

**Comment by skyjake** [comment]
Ha, I'm not alone in doing this wrong...
<img width="747" alt="Screen Shot 2021-11-07 at 6 28 09" src="https://user-images.githubusercontent.com/1225742/140632325-112d7798-1997-4ba8-a8b5-46f80b46631a.png">
(TextMate on macOS)

This does give me quite a good hunch as to where the problem is.

**Comment by skyjake** [comment]
This looks better?
<img width="648" alt="Screen Shot 2022-01-07 at 7 45 14" src="https://user-images.githubusercontent.com/1225742/148498283-f48edb42-f420-48c1-abfe-7e8ae07f9bca.png">
