### ISSUE TITLE
SEGV when entering about:command?!open URL with no url: parameter

### ISSUE THREAD

**Issue by Strahinja** [skyjake/lagrange#385]
On the latest dev branch, entering
```
about:command?!open newtab:1
```
in the URL bar results in SIGSEGV. Adding `url:`, for example `url:gemini://skyjake.fi`:
```
about:command?!open newtab:1 url:gemini://skyjake.fi
```
produces no error.

Tested on up-to-date Artix Linux and gcc 11.1.0-1.

**Comment by skyjake** [comment]
Thanks for reporting. I'm curious: are you using the `about:command`s for something like scripting?

**Comment by Strahinja** [comment]
No, I was searching for `about:` in the source because I forgot what is the URL to list all `about:` URLs (it is `about:about`) and saw the `about:command?!` URLs. When entering one without the `url:` parameter, I noticed the issue.
