### ISSUE TITLE
Using http proxy shows domain name mismatch.

### ISSUE THREAD

**Issue by karelbilek** [skyjake/lagrange#386]
I am trying to use duckling as a http proxy.

I get this error

https://github.com/LukeEmmet/duckling-proxy/issues/10

<img width="389" alt="Screen Shot 2021-11-12 at 11 50 19" src="https://user-images.githubusercontent.com/104945/141419145-704f36f7-02ae-469b-a182-5ca5f1285536.png">

I am not exactly sure where is the error; if on my side (wrong cert domain), duckling side or lagrange side.

I *think* the error is on lagrange side, because it expects the domain of the website, but gets cert domain of the proxy? But I am not sure

**Comment by karelbilek** [comment]
Oh this one was when I tried e-mail address instead of domain name

I meant to post this screenshot

<img width="395" alt="Screen Shot 2021-11-12 at 11 47 36" src="https://user-images.githubusercontent.com/104945/141419363-9e0a38a3-e82a-408d-a0bb-d826f1059739.png">

**Comment by karelbilek** [comment]
Ahhh it's because I use `localhost` for the cert but `127.0.0.1` as proxy IP.

Setting `127.0.0.1` as the cert domain name worked. Haha. OK

**Comment by skyjake** [comment]
Yep correct, the proxy server is considered a regular Gemini server when it comes to certificate checks.
