### ISSUE TITLE
Add tips on how to make a fontpack with `zip`

### ISSUE THREAD

**Issue by adiabatic** [skyjake/lagrange#387]
I just made a fontpack for [Heliotrope](https://mbtype.com/fonts/heliotrope/), a favorite font of mine.

While the documentation provided inside Lagrange was fairly complete, I had a bit of trouble figuring out how to generate the zip file with the proper directory layout. Namely, _not_ including the parent directory containing the font files.

In the end, I settled on a Makefile like this, which works wonderfully:

```make
TARGET = heliotrope.fontpack

build:
	zip --junk-paths --compression-method store --exclude \*.DS_Store -r ${TARGET} "Heliotrope OT"

clean:
	rm ${TARGET}
```

Would you consider mentioning `--junk-paths` in the Lagrange documentation in `about:help`, and possibly also `--compression-method store`? These can be shortened to `-j` and `-0`, respectively. I'm assuming that `zip` is mostly the same on all POSIXish platforms.

**Comment by skyjake** [comment]
Seems like a useful addition to the documentation.

The way I do it is run `zip` from inside the directory with the `fontpack.ini`, something like:

```
zip -0 -r ../test.fontpack *
```
