### ISSUE TITLE
Context menu only available on right-clicking feed entries, not headers

### ISSUE THREAD

**Issue by FiXato** [skyjake/lagrange#388]
I couldn't find the (context) menu to refresh feed entries because I was clicking on the feed's date headers rather than the entries (a long history of file explorers teaching me to find empty whitespace to click on rather than entries, I guess).
Maybe the feed entries context menu can trigger when right-clicking *anywhere* in the feed entries sidebar, rather than just on the entries?

**Comment by skyjake** [comment]
Perfectly reasonable, yes. Some sort of context menu should appear also when right-clicking below a short list of items. 

In other words, there should be two sidebar context menus: one that is related to an item, and one that is related to the currently active sidebar tab. The latter one can be a subset of the former.

**Comment by skyjake** [comment]
Implemented for v1.9.
