### ISSUE TITLE
Texts for singulars

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#389]
I used to see the following when translating:

* Used on %u URL
* Used on %zu URLs

But today I also saw this:

* Delete Bookmark
* Delete %u Bookmarks

I guess in English and German at least, we could always drop the %u for singulars?

**Comment by skyjake** [comment]
Yes, in strings with a single format placeholder, it is perfectly OK to leave it out when if it isn't needed. These strings basically go into `printf()`, and that will ignore unused values.

**Comment by kensanata** [comment]
Done!
