### ISSUE TITLE
Distributing Lagrange using Homebrew Cask

### ISSUE THREAD

**Issue by vladimyr** [skyjake/lagrange#39]
Hi @skyjake 👋 

Thank you for building a nice little _window_ into Geminispace. As a developer, I prefer to install things on my machine using Homebrew/Cask so my immediate reaction was to create a cask for Lagrange → https://github.com/vladimyr/homebrew-vladimyr/blob/27188d3/Casks/lagrange.rb I don't know if you are interested in maintaining your personal Homebrew tap but in case you decide so feel free to reuse my work,

cheers 🍻

**Comment by skyjake** [comment]
Nice! I'll keep this in mind if I have a suitable moment to spare.

Spotted a typo in your `lagrange.rb` though: ☺️
> `name "Lagranage"`

**Comment by vladimyr** [comment]
> Spotted a typo in your `lagrange.rb` though: ☺️
> 
> > `name "Lagranage"`

Well that's just embarrassing 🤦  Thanks 👍

**Comment by ploum** [comment]
@vladimyr : can you contribute this cask to the official homebrew tap so we can all benefit from it?

**Comment by skyjake** [comment]
An official Homebrew tap might be [a bit premature](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md) ("Rejected Casks [...] The Cask is for an app that is too obscure. Examples:
An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).")

However, I have now set up an "official" tap for Lagrange, so you can now just do this:
```bash
$ brew tap skyjake/lagrange
$ brew install lagrange
```

I'll endeavor to keep it up to date with the new releases.

**Comment by ploum** [comment]
Awesome, thanks a lot for this !


---
Ploum - Lionel Dricot

Abonnez-vous sur https://www.ploum.net 
Commandez Printeurs, thriller de science-fiction : https://www.plaisirvaleurdhistoire.com/shop/38-printeurs

**Comment by vladimyr** [comment]
> can you contribute this cask to the official homebrew tap so we can all benefit from it?

@ploum Usually, I would do that, but as @skyjake already explained, it would end up rejected because it doesn't meet the notability threshold.
