### ISSUE TITLE
Build with external FriBidi and HarfBuzz

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#390]
### Steps to reproduce
1. Clone repo:
`git clone https://github.com/skyjake/lagrange`
2. Update only `lib/the_Foundation` submodule (others not needed since system's fribidi and harfbuzz are available):
`git submodule update --init lib/the_Foundation` (`lib/fribidi` and `lib/harfbuzz` are empty)
Or just remove others:
`rm -fr lib/fribidi lib/harfbuzz`
3. Try to build with default config options:
```
option (ENABLE_FRIBIDI          "Use the GNU FriBidi library for bidirectional text" ON)
option (ENABLE_FRIBIDI_BUILD    "Build the GNU FriBidi library (if OFF, try pkg-config)" OFF)
option (ENABLE_HARFBUZZ         "Use the HarfBuzz library to shape text" ON)
option (ENABLE_HARFBUZZ_MINIMAL "Build the HarfBuzz library with minimal dependencies (if OFF, try pkg-config)" OFF)
```

### Actual behaviour
Lagrange built without FriBidi and HarfBuzz.

### Expected behaviour
System's FriBidi and HarfBuzz should be properly detected.

### RCA
Caused by:
https://github.com/skyjake/lagrange/blob/78de5577096bd81d6da152d9f819851c2f8ef260/Depends.cmake#L46
https://github.com/skyjake/lagrange/blob/78de5577096bd81d6da152d9f819851c2f8ef260/Depends.cmake#L110

**Comment by skyjake** [comment]
Yes indeed, that looks like a logic error in Depends.cmake. I'll fix it...

**Comment by skyjake** [comment]
e38df63 should fix it, let me know if there are more problems with this.

**Comment by sikmir** [comment]
It's fine now. Thanks!
