### ISSUE TITLE
Translations of languages for the UI language dropdown

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#391]
I noticed that I'm asked for translations of languages. I'm with Wikipedia, however: the language names should be in their own language, so that an unfortunate soul getting a German Lagrange can pick Suomi from the list, instead of having to find Finnisch. What do you think?

So to translate, I'd like to use the following list, but actually I'd think that these terms should be the same for all languages, i.e. no translation is required:

(Based on an old revision of [Names.php](https://phabricator.wikimedia.org/source/mediawiki/browse/master/languages/data/Names.php;f523635a605518e874442ffa4ece0f852995859f) from Wikimedia:

* Galician → galego
* Hungarian → magyar
* German → Deutsch
* etc

**Comment by skyjake** [comment]
You are right, it makes more sense to have the menu items each have their label in the target language.

The only wrinkle is that the current implementation wants all strings to come from the same translation, so I'll need to add a little preprocessing step that collects the localized names to make them available regardless of which language is currently active.

**Comment by kensanata** [comment]
I guess we could just use the same translations for all the language files and keep the code simple. Not harm done?

**Comment by skyjake** [comment]
Well, the simplest way would be to just hardcode the language labels in the source and leave them out of the .po files, since they don't require dynamic switching. 🙂

**Comment by kensanata** [comment]
Yes!

**Comment by skyjake** [comment]
From the commit:
> Note that the Translation dialog retains the localized language labels because the user may not speak the source language, so they need to see it in their own language.

@kensanata Some `lang.` strings will remain for the purpose above.
