### ISSUE TITLE
10.12.x is kinda supported, kinda not?

### ISSUE THREAD

**Issue by godDLL** [skyjake/lagrange#394]
I see you're not testing or releasing for 10.12.x, but I and many like me who don't enjoy the direction Apple has taken with their software, and may never upgrade to newer hardware or 10.13.x as such  
(still hopeful, after the lastest MacBook Pros, but not just yet).

When trying to double-click the app I get  
"**You can’t use this version of the application “Lagrange” with this version of macOS.**" and  
"_You have macOS 10.12.6. The application requires macOS 10.13 or later._" for Lagrange 1.8.2

Yet when launching it from the Terminal, using `Contents/MacOS/Lagrange` it seems to be working fine. Might be an easy fix to support 10.12.x

Can you? Will you?

Thanks.

**Comment by godDLL** [comment]
I found 1.8.2 in macports, which allows me to install and use it without any issues or warnings.

**Comment by skyjake** [comment]
macports is the recommended way to go with 10.12 and older. I will add a mention of this to the documentation.

I think SDL supports 10.9 at least, but in practice I don't have any Mac environments suitable for creating and testing such builds. The oldest environment I have is 10.13, hence that's the current limit on my prebuilt binaries.

I have no plans to distribute binaries for macOS versions older than 10.13.
