### ISSUE TITLE
Cannot create new translation language

### ISSUE THREAD

**Issue by bitigchi** [skyjake/lagrange#396]
I've registered to the weblate instance for helping translate Lagrange into Turkish, but it seems I don't have the necessary permissions to add another language. Is there anything I need to do from my side?

Thanks in advance!

**Comment by skyjake** [comment]
I've now added Turkish (tr): https://weblate.skyjake.fi/projects/lagrange/ui/tr/

Only admins (i.e., me) are able to add new languages. I've given you Translator access rights so you can submit strings. Thanks for translating!

The language selection menu items have recently been removed from Weblate and are now hardcoded (#391). Please let me know what should the menu item be for Turkish (i.e., the Turkish word for the language itself).

**Comment by bitigchi** [comment]
Thanks for adding!

For the hardcoded string, it will be Turkish -> Türkçe.

**Comment by jobukkit** [comment]
I'd like to translate Lagrange to Dutch ("Nederlands - nl"). I've created an account on Weblate with the same username.

**Comment by skyjake** [comment]
@jobukkit I've updated your account's access rights. Here you go: https://weblate.skyjake.fi/projects/lagrange/ui/nl/

**Comment by sikmir** [comment]
@skyjake Could you please add Swedish as well?

**Comment by skyjake** [comment]
@sikmir Added.
