### ISSUE TITLE
arch linux: crash when opening a popup window

### ISSUE THREAD

**Issue by primalmotion** [skyjake/lagrange#398]
Lagrange 1.8.2 starts then display the last page. As soon as I click somewhere (page or menu) it crashes

```
$ lagrange
Lagrange: A Beautiful Gemini Client
[window] renderer: opengl (accelerated)
[window] renderer: software
xdg_wm_base@9: error 4: wrong configure serial: 119632
```

**Comment by primalmotion** [comment]
actually, it's not everywhere. It's the hamburger button, the identity button. It seems it's anything that should show a popover

**Comment by skyjake** [comment]
Is this a manual build from source or some prebuilt binary?

Sounds like the build option `ENABLE_POPUP_MENUS` should be set to `NO`. At least with Wayland there are window management issues because SDL doesn't fully support that yet.

**Comment by primalmotion** [comment]
It's a build from the AUR package

**Comment by primalmotion** [comment]
I confirm adding this option seems to work. Can you confirm this is what you meant, and it's not just luck?

```
diff --git a/PKGBUILD b/PKGBUILD
index 23b9691..2036472 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -32,6 +32,7 @@ build() {
         -DCMAKE_INSTALL_PREFIX='/usr' \
         -DENABLE_KERNING=OFF \
         -DTFDN_ENABLE_WARN_ERROR=OFF \
+        -DENABLE_POPUP_MENUS=NO \
         -Wno-dev
     make -C build
 }
```

**Comment by skyjake** [comment]
Yes, that is the correct option.

**Comment by primalmotion** [comment]
Thanks, reported to the AUR maintainer
