### ISSUE TITLE
Lagrange steals focus on mouse hover events

### ISSUE THREAD

**Issue by buzzert** [skyjake/lagrange#399]
On Gnome Shell, when hovering my mouse over the Lagrange window, Lagrange will steal focus. 

Steps to reproduce:
1. Run Lagrange (1.7.3) on Gnome Shell
2. Switch to another application
3. Hover mouse over Lagrange

Expected results:
Nothing happens

Actual results:
Lagrange steals focus

**Comment by buzzert** [comment]
It looks like a line was added to `handleWindowEvent_MainWindow_` as part of this work for supporting popup windows: 2d81addf78d6a8b0fb2f2959b04a385c4adffdf2

```patch
         case SDL_WINDOWEVENT_ENTER:
             d->base.isMouseInside = iTrue;
+            SDL_SetWindowInputFocus(d->base.win);
             postCommand_App("window.mouse.entered");
             return iTrue;
```

Removing this line resolves the issue. I'm not entirely sure why that's there, if that is supposed to intentionally focus windows on hover, then maybe it should be a setting. Otherwise, maybe we should check to see if the window is a popup window first?

**Comment by skyjake** [comment]
Thanks for pinpointing what's causing it! I don't recall why exactly that was added, but it may have been related to behavior on a specific platform and shouldn't be universally applied. I've disabled that input focusing now in 1.9.0 and will see how it turns out.

**Comment by skyjake** [comment]
v1.9 is out with the fix, and it seems to work. Closing for now, please reopen if having further problems.
