### ISSUE TITLE
Weirdness in handling relative URIs containing // or just a query part

### ISSUE THREAD

**Issue by waweic** [skyjake/lagrange#40]
Trying to access [gemini://drewdevault.com/cgi-bin/hn.py](gemini://drewdevault.com/cgi-bin/hn.py), I am encountering some (in my opinion) wrong handling of the relative links on that page.
A link will typically look like this:

`=> web.sh?https%3A//github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/ YouTube-dl's repository has been restored`

Clearly, this is a relative link, containing neither a scheme nor an authority section (which would begin with //)
Despite this, when clicking this link, lagrange tries to open `gemini://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/`. It appears to me that the `//` before `github.blog` is being misinterpreted as the beginning of an authority section.

I had a look at the code and gmutil.c:init_Url seems to be the culprit in this case.

```c
if (!relativeUrlPattern_) {
    relativeUrlPattern_ = new_RegExp("([a-z]+:)?([^?]*)(\\?.*)?", 0);
}
if (matchString_RegExp(relativeUrlPattern_, text, &m)) {
    d->scheme = capturedRange_RegExpMatch(&m, 1);
    d->path   = capturedRange_RegExpMatch(&m, 2);
    d->query  = capturedRange_RegExpMatch(&m, 3);
}
```
I checked with gdb and it definitely reaches this part. This is, where I don't really grok where the new host comes from. Also, I didn't quite get why the Regex for relative links checks for a scheme, I couldn't think of a case where there is a scheme but not an authority section.
Edit: I have experimented around with the Regex from RFC 3986 Appendix B, using that in init_Url seems to solve this problem, as in the following snippet:

```c
void init_Url(iUrl *d, const iString *text) {
    static iRegExp *urlPattern_;
    if (!urlPattern_) {
        urlPattern_ = new_RegExp("^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?", caseInsensitive_RegExpOption);
    }
    iRegExpMatch m;
    init_RegExpMatch(&m);
    if (matchString_RegExp(urlPattern_, text, &m)) {
        d->scheme = capturedRange_RegExpMatch(&m, 2);
        d->host   = capturedRange_RegExpMatch(&m, 4);
	d->port   = iNullRange;
        d->path   = capturedRange_RegExpMatch(&m, 5);
        d->query  = capturedRange_RegExpMatch(&m, 6);
    }
}
```
This doesn't split the port off, should there be any, so this is not a complete solution

**Comment by waweic** [comment]
Thinking about it, it probably isn't this part that is behaving weird

**Comment by waweic** [comment]
Also interesting, when you access one of the pages manually and click one of the links there (only containing a different query part like `=> ?xyz XYZ`) lagrange apparently tries to merge those URIs in a way that ends up with `gemini://a/b/?xyz` instead of `gemini://a/b/c?xyz` (the base URI being `gemini://a/b/c?zyx`)

**Comment by skyjake** [comment]
> I have experimented around with the Regex from RFC 3986 Appendix B, using that in init_Url seems to solve this problem

Thanks for trying it out! I'll test your code and add the port parsing.

>  click one of the links there (only containing a different query part)

Hmm, I don't recall testing this case at any point. ☺️ I'll check the handling of the relative URLs here.

**Comment by skyjake** [comment]
The commit above should take care of the URL parsing. Seems to work for all the URLs I tried.

I'll still need to look at what happens to the query-only relative URLs.

**Comment by skyjake** [comment]
OK, both issues should be taken care of now. Please test and close the issue if everything seems to work in the dev branch.

**Comment by waweic** [comment]
Hi, thanks a lot for implementing this. While Testing, I stumbled upon a few things so far. I have put them in a list:

* IPv6-addresses enclosed in square brackets can't be entered so far. RFC 3986 allows this.
  - Yesterday, I had a regex that handled this Edge case, but couldn't get it to run. Sadly, I lost it. I will see if I can make one.
* I haven't tested this, but problems may arise when specifying a username in the authority section (separated with an @)
  - This probably is a non-issue because Gemini doesn't allow this anyways
* Something about relative links feels odd so far. I haven't started to pin this down yet, but the relative links at my page don't work for now (appending the relative path to the Hostname, without a /)
  - This is my page, I will see if I find something from the client stress test instead: gemini://de.activ.ism.rocks/

**Comment by skyjake** [comment]
Pushed a fix for the last item. A path that begins with `~` is effectively an absolute path, and the code made the incorrect assumption that all absolute paths have a slash in the beginning.

> username in the authority section

Lagrange allows opening HTTP links via proxy, those could have a username in the authority?

> IPv6-addresses enclosed in square brackets (...) I will see if I can make one.

That would be great. :+1:

**Comment by skyjake** [comment]
Looks good to me now.
