### ISSUE TITLE
SIGSEGV when saving bookmark in AppImage build

### ISSUE THREAD

**Issue by shellhazard** [skyjake/lagrange#402]
Attempting to bookmark any page or link while using the Lagrange AppImage build will crash the application completely. I have not tested this on any other system or with any other build but after asking around I can only assume the problem is AppImage specific.

**Steps to reproduce:**
1. Launch the Lagrange AppImage build.
2. Right click on any page (`about:help` is fine) and select "Bookmark Page".
3. Select "Save Bookmark"

OS: Debian Bullseye
```
$ cat /proc/version
Linux version 5.10.0-6-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.28-1 (2021-04-09)
```

GDB output: 
```
Lagrange: A Beautiful Gemini Client
[Detaching after vfork from child process 616763]
[window] renderer: opengl (accelerated)
[New Thread 0x7fffc30fe700 (LWP 616764)]

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00005555554a5fc7 in handleBookmarkCreationCommands_SidebarWidget_ ()
```

**Comment by skyjake** [comment]
Thanks for reporting! Looks like a simple oversight...
