### ISSUE TITLE
Positioning of the New Tab button and tab close buttons

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#403]
Version: Flatpak v. 1.9

Bug summary:
The new tab button is not in a fixed position. When opening a lot of tabs, you can see that the new tab button is not always in the same position. The same goes for the close tab position.

Idea for an improvement: it should more be handled like in firefox where these elements are in a fixed position: for example after a lot of tabs, the space of these tabs scale but the close button of the last tab and the new tab button remain always in the same location. This allows a better and more consistent user experience when opening several tabs :)

**Comment by skyjake** [comment]
Fixed the New Tab button positioning for v1.9.1.

If I understood correctly, you're talking about the behavior in Firefox and other browsers where tab buttons don't get resized until the mouse leaves the tab area, allowing one to close multiple tabs by clicking in the same position? That is a bit challenging to implement currently, but definitely should be done at some point.

**Comment by Altonss** [comment]
> If I understood correctly, you're talking about the behavior in Firefox and other browsers where tab buttons don't get resized until the mouse leaves the tab area, allowing one to close multiple tabs by clicking in the same position? That is a bit challenging to implement currently, but definitely should be done at some point.

Oh I didn't even think about that, but that would be a cool enhancement indeed ;)
What I just meant, is that the position of the new tab and therefore the position of the last tab and its close button are shifting depending on the number of tabs opened. But I will wait the 1.9.1 release to give more feedback to see if the problem has been fixed :)

**Comment by skyjake** [comment]
Ah I see what you mean. I've now fixed the tab button layout for v1.9.1 so the last one stays connected to the right edge.

**Comment by Altonss** [comment]
Yes

> Ah I see what you mean. I've now fixed the tab button layout for v1.9.1 so the last one stays connected to the right edge.

Yes that's what I meant, sorry for my bad english and my unclear explanation.

**Comment by skyjake** [comment]
No problem!
