### ISSUE TITLE
Bug: text instead of "..." in the tab preview when too much tabs are open

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#404]
Version: Flatpak v. 1.9

When opening a log of tabs, the title of the tab gets cropped, until just "..." is displayed.
When opening too much tabs, I discovered a bug that suddenly text reappears!

Here a screenshot of the bug:
![image](https://user-images.githubusercontent.com/66519591/143789207-bd0832d0-bd6c-4f99-a9bc-2d0930edaa7c.png)

**Comment by skyjake** [comment]
Fixed for v1.9.1.
