### ISSUE TITLE
Elements of flow, formating of the text

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#407]
When changing the size of the column, the way to display changes in a weird way. Is this intentional?
Narrow column:
![image](https://user-images.githubusercontent.com/66519591/143895971-1bcee085-bf93-471c-b1aa-de8adf792688.png)
Wider column:
![image](https://user-images.githubusercontent.com/66519591/143896144-0c2f020d-db5e-4987-8066-162fbc5ea56e.png)
Larg column:
![image](https://user-images.githubusercontent.com/66519591/143896258-abce7986-b6d7-4d67-b6f3-31686b3ff994.png)

EDIT: Oh nevermind, I think I understood what you did and this is brilliant. It adapts to the size available to display to most content possible in the best way. That's great :) Sorry to have opened this ^^ Nevertheless I will maybe open another issue about the "mark everything as read" button. It is very hard to read the content of the button unless the column is very large, but that's another issue and I don't know how this could be fixed...

**Comment by skyjake** [comment]
No problem.

**Comment by Altonss** [comment]
I saw that the 1.9.2 has replaced "mark everything as read" by "Read all". This string is shorter and therefor better for usability and readability. But I think the downside of this, is that "Read all" is not very clear about what it does :/

**Comment by skyjake** [comment]
Yeah, it's a compromise... Any suggestions better than "Read All", but still short? From the context inside the Feeds sidebar, plus the associated icon, its function should be sufficiently clear IMO.
