### ISSUE TITLE
Issue on weblate

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#408]
![image](https://user-images.githubusercontent.com/66519591/143904775-86a2b685-dc12-43c1-a429-4326e13fd03e.png)
https://weblate.skyjake.fi/translate/lagrange/ui/de/?q=has:check or https://weblate.skyjake.fi/translate/lagrange/ui/fr/?q=has%3Adismissed-check&offset=2*

How could this issue be resolved and what is this issue really about?

**Comment by skyjake** [comment]
I think this is just Weblate not understanding `strftime` formatting. I should just remove the c-format flag from these strings.

**Comment by Altonss** [comment]
Impossible to click save on weblate, where could the issue come from because I am logged in with an account?

**Comment by skyjake** [comment]
@Altonss It appears your account didn't yet have translator access rights, so you were only able to suggest strings. I have corrected the issue.

You may want to discuss with @MCMic about the most suitable terminology; he is responsible for most of the French translation thus far.

**Comment by skyjake** [comment]
>  I should just remove the c-format flag from these strings.

I have done this, although not sure if the changes are yet visible in Weblate.

**Comment by Altonss** [comment]
> I have done this, although not sure if the changes are yet visible in Weblate.

Last time I looked, they weren't there anymore.
