### ISSUE TITLE
One pixel is wrongly placed when selecting / hovering over a tab 

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#409]
When hovering, pixel on the top right:
![image](https://user-images.githubusercontent.com/66519591/143951007-e7a530c8-ac79-4232-a990-aaa22e7fb8b6.png)

When selecting, pixel on the bottom right:
![image](https://user-images.githubusercontent.com/66519591/143951051-d5204e28-c629-4c9f-aed6-59e069ea9500.png)

Version: 1.9.1 Flatpak

**Comment by skyjake** [comment]
This is a known issue with SDL line drawing routines. In some versions, they have this kind of one-pixel offsets.

The issue could be worked around by drawing the buttons differently, but this is a minor artifact so it hasn't been a priority.

**Comment by Altonss** [comment]
> The issue could be worked around by drawing the buttons differently, but this is a minor artifact so it hasn't been a priority.

Yes indeed, it is a very minor issue :)

**Comment by Altonss** [comment]
On this picture of a button in the Lagrange interface we see this offset issue better:
![image](https://user-images.githubusercontent.com/66519591/144143972-37c76f6d-4a5b-4fe1-a16a-e74381de04aa.png)
Wouldn't it just be a matter of starting the line one pixel lower, or to patch SDL line routines? Is it an open issue on the sdl bugtracker?

**Comment by skyjake** [comment]
> starting the line one pixel lower

In that case, sure. However, I've seen different variations of this glitch. In fact, there is currently one special offset being applied for 2.0.16 in Lagrange drawing routines:  https://git.skyjake.fi/gemini/lagrange/src/branch/dev/src/ui/paint.c#L113

I'm pretty sure the Flatpak version uses some release older than 2.0.16.

> Is it an open issue on the sdl bugtracker?

I don't know, but @icculus has mentioned line drawing glitches in the past, so it's seems like a known issue that line drawing is a bit nondeterministic.

It doesn't seem worthwhile to fight with SDL's line drawing but instead use a different way to render the UI rectangles in Lagrange.
