### ISSUE TITLE
Full-width / ideographic space

### ISSUE THREAD

**Issue by blksprt** [skyjake/lagrange#41]
The full-width space character (aka ideographic space / U+3000) is not rendered properly, but is instead rendered as a dotted box with "ID SP" written inside it. I'm guessing this is a simple issue of which font is being picked to render it - some of the included fonts should definitely be able to display it properly.

An example can be seen at gemini://higeki.jp/fanden

**Comment by skyjake** [comment]
You are correct, selecting a different font fixed the issue.
