### ISSUE TITLE
Percent-encoding input and query-string

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#410]
Two issues, actually:
* Upon input, characters [ and ] are not encoded;
* Queries entered directly into the URL bar are not encoded at all.  It would be wise to clean all user input that goes back to the server to avoid issues with reserved characters.

**Comment by skyjake** [comment]
From commit 5e31f66:

> This means that if the user enters a URL in the input field manually, its non-ASCII characters will be percent encoded as well. However, in this case the user is expected to manually escape all reserved characters because the input field can't tell the difference between what is intended to be a reserved separator and what isn't. For example, a server might expect &-separated fields, and if the user enters such fields manually in the URL field, they shouldn't be converted to %26.
>
> When forming a query URL in the input dialog, user-entered text is fully percent-encoded because in that case the input is just a generic text string.

**Comment by stacksmith** [comment]
That is sensible.  It is up to the server to make sure the input is sane, as it is always possible to make an arbitrary request using any number non-lagrange implements.
