### ISSUE TITLE
Lagrange 1.9 crashes when creating a bookmark on Xubuntu

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#411]
I seem to be cursed when it comes to bookmarks...

I compiled 1.9 and installed over older version.  Whenever I try to make a new bookmark, LaGrange immediately exits as soon as I press the 'create bookmark' button.  Otherwise it functions well. 

I am using Xubuntu 20.04, kernel 5.4.0-91-generic on x86-64, gcc 9.3.0, everything up to date.

**Comment by skyjake** [comment]
This is v1.9.0? I released v1.9.1 on Monday with a fix that should resolve that crash.

**Comment by stacksmith** [comment]
Yes.  I will upgrade.

**Comment by stacksmith** [comment]
Upgade fixed the issue.
