### ISSUE TITLE
Edit Page with Titan…	⌘E

### ISSUE THREAD

**Issue by joakim** [skyjake/lagrange#415]
What the title says. I'm sure this is already in the cards :)

Something like this?  
Opens a dialog, pre-filled with the body of the current page, with a `Save` button instead of `Upload`.

Also, what about iapetus, if adding support for that (#414)?

Maybe servers could give clients hints about its capabilities through out-of-band MIME parameters?

    text/gemini; lang=en; server=titan

**Comment by skyjake** [comment]
I've been thinking about it, although ⌘E would be pretty much just a shortcut for ⌘C, ⌘U, ⌘A, ⌘V. This would seem convenient.

It is up to the user to choose the upload protocol, perhaps via a site-specific config setting. It's extremely unlikely that this kind of MIME parameters will be included in the Gemini specification...

**Comment by joakim** [comment]
Yea, I don't expect the Gemini spec to embrace that. Chosing upload protocol per site would do the trick without bending Gemini's spec in uncomfortable positions :)

**Comment by skyjake** [comment]
Implemented for v1.10.
