### ISSUE TITLE
Make home row keypress take precedence over other shortcuts

### ISSUE THREAD

**Issue by nathan-whittington** [skyjake/lagrange#419]
I've set the shortcut 'd' to close tab.   When I 'open link via home row keys' it highlights a link with 'd' but pressing that key closes the tab instead of following the link.

I generally do this several times per session because it's muscle memory from firefox but it's more painful because there isn't an option to undo the most recently closed tab.

**Comment by skyjake** [comment]
Any chance you are on a Mac? I noticed that the native menu item shortcuts are active during home row key navigation, even though they shouldn't be.

**Comment by nathan-whittington** [comment]
Unfortunately no. I'm running ubuntu - sorry I didn't make that clear.  

I just downloaded 1.9.4 to test this again and I see the same behavior.

**Comment by skyjake** [comment]
All right, this should now be fixed in 1.9.5.

**Comment by skyjake** [comment]
Let me know if you discover further issues with this.
