### ISSUE TITLE
Should Lagrange be able to serve Gemini pages too?

### ISSUE THREAD

**Issue by johanbove** [skyjake/lagrange#423]
Was wondering if it would make sense to have Lagrange also be able to perform as a server instead of a browser of Gemini and Gopher and such. I feel it's such a mature piece of software, and building a Gemini server is not "that" hard to do, it could make it easier for people to serve some pages while they're active together. Not sure if it would make sense though. Just a thought.

**Comment by skyjake** [comment]
While on some level that makes sense, I prefer to keep Lagrange focused on being a client.

I think instead what would be useful is a friendly GUI for a server like [Agate](https://github.com/mbrubeck/agate), to make things more manageable for people who are unfamiliar with the terminal.
