### ISSUE TITLE
Lagrange 1.9.2 opening About page every time I defocus it

### ISSUE THREAD

**Issue by duncan-bayne** [skyjake/lagrange#424]
Repro steps:

1. Run Lagrange with `./Lagrange-1.9.2-x86_64.AppImage`.
2. Lagrange loads, displaying the last viewed page in a tab (in this case `gemini://localhost/`).
3. Defocus the Lagrange window (with `C-t` in StumpWM).

Expected:

1. Lagrange leaves the last viewed tab open.

Actual:

1. Lagrange displays the `about:lagrange` page in a new tab, immediately it loses focus.
![lagrange](https://user-images.githubusercontent.com/65949/146714794-083ee670-9d7a-4e14-bae5-035afca902c9.png).
2. Every time I focus and de-focus Lagrange, it opens _another_ `about:lagrange` tab.  There are two in the above screenshot for this reason.

System details:

* Ubuntu 21.04 (Hirsute Hippo) x86_64
* StumpWM 2:1.0.0-1

**Comment by skyjake** [comment]
Sounds like a keybindings conflict. Try changing the key for "New tab" in Lagrange's Preferences > Keys.

I'm not aware of anything I could do in Lagrange to prevent this from happening, so closing the issue. I'm all ears if anyone has ideas, though... (wrt. handling key events in SDL vs. system/WM keys)

**Comment by duncan-bayne** [comment]
It does sound like an SDL bug.

No other application I run treats the initial `C-t` as an actual `C-t`, because StumpWM only sends `C-t` when you do `C-t t`.

So for example Firefox running on my system under Unity creates a new tab on `C-t`. But when I run it under Stump WM on the same system it doesn't; I have to do `C-t t` to send Firefox a `C-t`.

From the [StumpWM docs](https://stumpwm.github.io/git/stumpwm-git_2.html):

> C-t t
> 
>     Sends a C-t to the frame; this is useful for applications like Firefox which make heavy use of C-t (in Firefox’s case, for opening a new tab). This is similar to how GNU screen uses C-a a.

I might see if I can find another SDL app and try to reproduce the problem.

**Comment by duncan-bayne** [comment]
I haven't been able to reproduce this bug on other SDL apps, but it appears to have worsened since installing Lagrange 1.13.6 - now on Ubuntu 22.04 with libsdl 1.2.

Previously, I'd worked around this by changing the new tab shortcut from `C-t`.

Now however all my WM shortcuts are interpreted by Lagrange as control plus the last key pressed.

An example: I do `C-t e` - that is, press Control and T together, then release them, then press E.  StumpWM switches to Emacs as I've configured it to do.  But at the same time, Lagrange seems to receive `C-e`, and opens the Titan dialog.  It's strange because at no point did I _actually_ press Control and E; I pressed Control and T, released them, and only then pressed E.

I appreciate that I'm probably your one and only user on StumpWM, so understand if this bug remains closed :)  But thought I'd report the new behaviour anyhow in case it sheds some light on the problem.

**Comment by skyjake** [comment]
My guess is that the window manager doesn't send a release event for the Control key when it intercepts Control+T for its own bindings, making the app believe it's still being held down when you press the E.

I did think of one possible workaround, though: check out the "modmap.txt" config file that is documented in section 3.5 of the Help page. If you remap Lagrange's Control modifier keys to something else (both `Rctrl` and `Lctrl`), perhaps swapping it with another modifier, your use of the Control+T combo can be then ignored by the app.
