### ISSUE TITLE
Certificates created with "not valid before" in the future

### ISSUE THREAD

**Issue by PatrickKing** [skyjake/lagrange#425]
I've just installed a fresh copy of the Windows build of Lagrange, and all of the certificates it generates come with "not valid before" set seven hours into the future. I'm at UTC-7, so I'm guessing this may be a timezone issue.

**Comment by skyjake** [comment]
Yeah, looks like the wrong OpenSSL API was used for setting the time. I changed it to use UTC and it seems to work correctly now.

Thanks for reporting!

**Comment by skyjake** [comment]
Should be fixed in v1.9.3.
