### ISSUE TITLE
Do not quit program when all windows are closed

### ISSUE THREAD

**Issue by bitigchi** [skyjake/lagrange#426]
This is for macOS.

For some macOS applications, it makes sense to keep them running even when all windows are closed. Browser are also generally in this category, they use multiple windows, and it's just accepted behaviour to keep them open on macOS even if there are no windows open.

AFAIK, all browsers conform to this on macOS.

**Comment by skyjake** [comment]
Once there is support for multiple windows (#191), changing this behavior would make sense, yes.
