### ISSUE TITLE
Line alignment issues using SDL >=2.0.16

### ISSUE THREAD

**Issue by ftphikari** [skyjake/lagrange#428]
![image](https://user-images.githubusercontent.com/92269215/147379863-f93428d9-3916-43d5-85b1-822d9b51f4d0.png)
These and more.

The line drawing routines in SDL have been broken for quite a while now, but this year's release 2.0.16 has fixed the line drawing.
I have had the same issue recently where I had to revert line drawing hacks that I made to work around the bug. Now you have to fix the line drawing coordinates too!

**Comment by skyjake** [comment]
Thanks for reporting. I've been tracking this issue myself, and have updated the work/v1.10 branch accordingly.
