### ISSUE TITLE
SDL_VIDEODRIVER=wayland burger menu does not open

### ISSUE THREAD

**Issue by ftphikari** [skyjake/lagrange#429]
![image](https://user-images.githubusercontent.com/92269215/147379916-3f6b379d-baac-4135-a806-3b80b6e4f199.png)
This menu on the right does not open when lagrange is launched with SDL_VIDEODRIVER=wayland.

Log says this:
```
[window] renderer: opengl (accelerated)
[window] renderer: software
```

So when the main window is opened the OpenGL renderer is used, but when the hamburger menu is opened, the renderer is set to software and the menu does not work.

**Comment by skyjake** [comment]
I added a note about this to known issues on gemini://skyjake.fi/lagrange/:

> The environment variable `SDL_VIDEODRIVER=wayland` can be used to force SDL to use Wayland instead of X11. However, SDL does not have full support for Wayland at the moment. You should set the Lagrange CMake build option ENABLE_POPUP_MENUS to NO. If there are issues with resizing windows, also set ENABLE_RESIZE_DRAW to NO.

So, my recommendation is upgrading to the latest version of SDL and/or giving those build options a try.

**Comment by ftphikari** [comment]
> set the Lagrange CMake build option ENABLE_POPUP_MENUS to NO

I did it, and it works. but why do popup menus set to YES in the first place, if NO is more portable? I guess it's not finished yet?

**Comment by skyjake** [comment]
>  why do popup menus set to YES in the first place, if NO is more portable? I guess it's not finished yet?

Wayland is an exception in this regard, on most platforms SDL windows are working nicely. SDL's Wayland support is actively being worked on from what I gather on their issue tracker.

Also, this issue has been reported before: #352

**Comment by KSPAtlas** [comment]
> I added a note about this to known issues on gemini://skyjake.fi/lagrange/:
> 
> > The environment variable `SDL_VIDEODRIVER=wayland` can be used to force SDL to use Wayland instead of X11. However, SDL does not have full support for Wayland at the moment. You should set the Lagrange CMake build option ENABLE_POPUP_MENUS to NO. If there are issues with resizing windows, also set ENABLE_RESIZE_DRAW to NO.
> 
> So, my recommendation is upgrading to the latest version of SDL and/or giving those build options a try.

Should those be the defaults, if it doesn't effect X11?

**Comment by skyjake** [comment]
Those options do affect X11, and I believe most people are still using X11.
