### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by asterismo** [skyjake/lagrange#430]
Any ideas? i did installed dependencies: sudo apt-get install cmake zip libsdl2-dev libssl-dev libpcre3-dev zlib1g-dev libunistring-dev libfribidi-dev

I'm running debian 10

~/lagrange/build$ cmake ../ -DCMAKE_BUILD_TYPE=Release
CMake Error at Depends.cmake:19 (find_package):
  By not providing "Findthe_Foundation.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "the_Foundation", but CMake did not find one.

  Could not find a package configuration file provided by "the_Foundation"
  (requested version 1.0.1) with any of the following names:

    the_FoundationConfig.cmake
    the_foundation-config.cmake

  Add the installation prefix of "the_Foundation" to CMAKE_PREFIX_PATH or set
  "the_Foundation_DIR" to a directory containing one of the above files.  If
  "the_Foundation" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)

-- Configuring incomplete, errors occurred!
See also "/home/santiago/lagrange/build/CMakeFiles/CMakeOutput.log".

**Comment by skyjake** [comment]
If you're compiling from a cloned Git repository, remember to do `git submodule update --init` first.

If you have a tarball, get the one with the libraries included like the release notes recommend.

**Comment by asterismo** [comment]
Oh my bad. Please close this issue.

**Comment by skyjake** [comment]
No problem 🙂
