### ISSUE TITLE
Can't navigate "back" using Left_Alt + Left, only works with Right_Alt + Left

### ISSUE THREAD

**Issue by tobykurien** [skyjake/lagrange#431]
OS: Ubuntu 21.04
Release: v1.9.4 (AppImage x86_64)

As per title, Left Alt + Left doesn't navigate back. Also, I couldn't find documentation on the keyboard shortcuts and ended up having to read the source code to see what the combination is meant to be, after trying every key combination on my keyboard. A "keyboard shortcuts" section in the help would be useful.

UPDATE: Just noticed that the key bindings are in the preferences.

**Comment by skyjake** [comment]
Every popup menu also shows the corresponding shortcuts.

The Left and Right Alt keys are supposed to be interchangeable in the app. I'll do some testing on my system...

**Comment by skyjake** [comment]
Both Alt keys work on my Ubuntu 21.04 and keyboard. What kind of keyboard do you use? It's possible that the actual scancodes are different for me as I'm using an Apple keyboard.

**Comment by tobykurien** [comment]
I'm running Ubuntu on my MacBook Air. Both the on-board MacBook keyboard and the USB-attached Raspberry Pi keyboard display the same behavior.

**Comment by tobykurien** [comment]
Perhaps a clue: If I try to set the key binding in preferences to "Left Alt + Left", then it shows up as just "Left Alt" (regardless of the combination). If I use "Right Alt + Left", it shows up as "Alt <-". This also applies to all other Alt combinations, like Alt + Up, etc.

**Comment by skyjake** [comment]
That does sound suspicious! I will check it out...

**Comment by tobykurien** [comment]
I think I found the issue. I'm using i3 window manager, which seems to change how lagrange sees key combinations. I haven't seen this issue in other apps, so something to keep note of, but I don't think it's an issue worth worrying too much about.
