### ISSUE TITLE
Fails to display Atom feed entry when <updated> tag contains linebreak

### ISSUE THREAD

**Issue by zluudg** [skyjake/lagrange#433]
As the title says, when an entry contains an `<updated>` tag that is styled something like this:
```
<updated>
    2022-01-14T09:28:00+00:00
<updated/>
```
The entry won't be shown when clicking the link to the Atom feed in lagrange. Perhaps it's not a big deal, but for my case where I used some templates to autogenerate the atom feed file, it was convenient for me to write the tag in this style. Also, I think it looks nicer.

There seems to be no problem when other tags are written like this, including the `<updated>` tag for the feed itself.

I'm using lagrange version 3.2.1 that I built from source on Ubuntu 20.04, if that's relevant. The server I use is agate.

Attaching a small capsule example where I try to highlight this issue:
[example_capsule.zip](https://github.com/skyjake/lagrange/files/7869028/example_capsule.zip)

**Comment by skyjake** [comment]
Thanks for providing the example capsule, that was quite helpful! Should be fixed for the next release.

**Comment by zluudg** [comment]
Looking forward to it! Thanks for providing this software!

**Comment by skyjake** [comment]
Included in v1.10.
