### ISSUE TITLE
Missing glyphs warning duplicated

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#435]
Using Lagrange on iOS

Steps to repro:

1. Go to a page with a missing glyphs warning that also has an input link
2. Click the input link
3. Click "cancel"
4. A second missing glyphs warning is shown below the first one
5. Repeat steps 2-4, and the warnings will keep stacking up until the page is refreshed

On a side note, it would be nice if I could dismiss this warning permanently. I don't really want to install a bunch of font packs (although it's a neat feature), and the warning is much more annoying than the missing glyphs themselves.

![IMG_2916](https://user-images.githubusercontent.com/5026795/149563428-94e74ac2-7190-4430-ac1f-29506391fb0f.PNG)

**Comment by skyjake** [comment]
Will fix.

The warnings can be disabled by toggling Settings > Fonts > Glyph Warnings.

Hmm, maybe clicking on the warning could show a menu with "Never warn about fonts" or something.

**Comment by michael-lazar** [comment]
Thanks!

> The warnings can be disabled by toggling Settings > Fonts > Glyph Warnings.

Of course they can 🤦 

> Hmm, maybe clicking on the warning could show a menu with "Never warn about fonts" or something.

This sounds like a nice idea, it certainly would have helped me to discover the above setting.

**Comment by skyjake** [comment]
The duplicate warnings are fixed in v1.10.
