### ISSUE TITLE
Mouse position not registering until mouse stops moving

### ISSUE THREAD

**Issue by wangell** [skyjake/lagrange#438]
1.10 release doesn't register mouse until motion stops, e.g:
- Grabbing the scroll bar and moving it won't scroll "smoothly", it will only snap into place when you stop moving the mouse
- Similarly, bookmarks/menu items won't highlight until the mouse stops moving

Only tested on Linux, but 1.9.5 works fine

**Comment by wangell** [comment]
I found the issue, it was this commit:

https://github.com/skyjake/lagrange/commit/88a15ca1069f079d3d584a34a4d03c1d0b22c79a#diff-134a86dbc1bcb1856730147230bcaa21a569e2d4c72c9d724485dda5d03058f3

I reverted to the old code and it works fine now after removing the wait.  I don't have any issues with menus being dismissed either.

**Comment by skyjake** [comment]
Interesting. Which version of SDL are you building with? That SDL_PollEvent problem may only apply to 2.0.18 or even 2.0.20.

**Comment by wangell** [comment]
I was using the AppImages and then built it myself, it looks like my SDL2 version is 2.0.10.

**Comment by skyjake** [comment]
To clarify: on your system, is this mouse position issue occuring both with the AppImages I've provided *and* your own build with SDL 2.0.10?

**Comment by wangell** [comment]
Hi @skyjake,

Yes - it was occurring on the 1.10 AppImage as well as my own build (on two separate Ubuntu installs - I think SDL 2.0.10 is the latest provided).

The newest update (1.10.1) has fixed this issue for me - thanks!
