### ISSUE TITLE
[Feature Request] Horizontally-Scrollable Pre-formatted Text

### ISSUE THREAD

**Issue by zovt** [skyjake/lagrange#44]
Hello! Not sure how difficult it would be to support this, but it would be nice if pre-formatted text could be scrolled horizontally if it reaches outside of the typical page bounds.

What are your thoughts on something like this?

Lagrange is really great software. It definitely got me interested in Gemini :) Thanks!

**Comment by skyjake** [comment]
Yes this is one of those smaller things that I haven't gotten around to dealing with yet. It's certainly needed since one occasionally encounters very long preformatted lines.

It shouldn't be very difficult to implement.

**Comment by emilis** [comment]
The spec (5.4.4) says:
> Graphical clients should use scrolling mechanisms to present preformatted text lines which are longer than the client viewport, in preference to wrapping.

From my own experience (I use the `-1` line width), I think the preformatted blocks could be extended first to the right edge of the page area, then maybe to the left (before turning on scaling or scrolling).

**Comment by emilis** [comment]
It seems this is not a feature, but a bug:

Open gemini://gemini.circumlunar.space/users/shufei/phlog/20200915-Reply-X9-WalkawayNet.gmi
Scroll down until you find:

> 3.5. Fault Tolerance and Tree Repair
> When a failure occurs, at least one tree branch is affected. Therefore, eager push is not enough to ensure message delivered in face of failures. The lazy push messages exchanged through the remaining nodes of the gossip overlay are used both to recover missing messages but also to provide a quick mechanisms to heal the multicast tree.

Result: I can't see second line of text past "delivered" -- it goes behind the scroll bar and beyond the screen.

Expected result: text scrolls or fits.

**Comment by skyjake** [comment]
Seems odd that the author used preformatted text instead of a quote there...
