### ISSUE TITLE
1.10.1 Crash on macOS

### ISSUE THREAD

**Issue by rcarmo** [skyjake/lagrange#442]
After an initial successful run where I was able to browse for a while, `1.10.1` now crashes on startup, apparently because it is trying to put up some kind of dialog box (from what I can see in the dump I'm attaching).

[crashlog.txt](https://github.com/skyjake/lagrange/files/7918291/crashlog.txt)

**Comment by rcarmo** [comment]
Removing `~/Library/Application Support/fi.skyjake.Lagrange` fixes it, so I am assuming this has something to do with bookmarks I set (I did nothing else during my original session).

**Comment by skyjake** [comment]
The crashlog indicates that it's for some reason crashing when Sparkle tries to open an update check dialog. Does it crash if you manually select "Check for Updates" from the menu?

If the issue persists, a possible workaround is to disable Sparkle's automatic update checks.

**Comment by rcarmo** [comment]
No, using the menu works fine. I've seen this kind of crash before when trying to launch dialogs outside the Cocoa main event loop (in PyObjC, ages ago), but don't really have a clue as to why it would happen with Sparkle (the framework is supposed to be smart enough on its own).

I'll see what happens over the next day or so.

**Comment by skyjake** [comment]
Looking over the crashlog in more detail, while everything is happening on the main thread, it is inappropriately doing an extra round of event handling while the window is being shown (under SDL_ShowWindow -> resizeWatcher). I'll prevent that from happening, so Sparkle won't trigger its events during that time.

**Comment by skyjake** [comment]
Perhaps now fixed in v1.10.2. Please reopen if it happens again.
