### ISSUE TITLE
How does Lagrange calculate site-colors?

### ISSUE THREAD

**Issue by petermllrr** [skyjake/lagrange#447]
This is more of a question than a bug report: How does Lagrange calculate the site's themes? I tested two identical sites on two different domains and both are rendered in different colors. I assume that either some random seed or a mix of domain + content is used to generate the site's color scheme?

(I love that it's kind of random and that you can't influence it btw.)

--
Peter

**Comment by skyjake** [comment]
It is entirely based on the site URL. The app extracts the "URL root" that normally is just the domain name, but if a username is detected (e.g., "~user"), that is also included. The root is then hashed with CRC-32 to get a pseudo-random set of bits, and various parts of the result are used for picking a set of theme hues and parameters. How these are applied in practice depends on the user's chosen content theme.

The theme generator can be found in src/gmdocument.c (`setThemeSeed_GmDocument`) in the source.
