### ISSUE TITLE
Refreshing twice navigates backwards

### ISSUE THREAD

**Issue by fjebaker** [skyjake/lagrange#449]
Hi! I hope this isn't a duplicate or an intended feature. I had a look through open and closed issues and couldn't find anything particularly similar :)

If you navigate to a capsule and follow a few links, then refreshing twice -- either with Cmd-R or by clicking the refresh button -- in relatively quick succession will cause the browser to go back a page, until it reaches the top of the session history.

~

Tested on two different apple machines with Lagrange v1.10.4 installed via Homebrew.

**Comment by skyjake** [comment]
Thanks for reporting! I am able to reproduce this. Doesn't seem like a very high priority problem, but I'll fix it in one of the upcoming patches.
