### ISSUE TITLE
Opening URL from selected text on page ("Paste and Go" in v1.11)

### ISSUE THREAD

**Issue by shtirlic** [skyjake/lagrange#450]
It would be nice to have this feature.
![image](https://user-images.githubusercontent.com/74080/152861566-abb753c5-b60d-4726-9d90-3bb3642c9e45.png)

**Comment by skyjake** [comment]
Would be convenient, yes. I would also add here the ability to directly open a URL that has been selected anywhere on a page via the selection context menu.

**Comment by shtirlic** [comment]
Thanks!
