### ISSUE TITLE
Spartan Protocol

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#451]
Is there any chance of lagrange supporting spartan?  As documented here:
gemini://spartan.mozz.us/

Give that it's a subset of gemini with no encryption, it should be a minimal effort...

**Comment by skyjake** [comment]
It's not too much work, however I would like to refactor some of the network request code to make it fit more nicely.

The basic queries are simple enough (cf. how Gopher is currently implemented), but Spartan uploads require changing the Upload UI as well to somehow reflect which protocol is being used, and show/hide some UI elements accordingly.

**Comment by stacksmith** [comment]
I think it would be great just to be able to read Spartan sites. 

The upload protocol can be dealt with later...

**Comment by skyjake** [comment]
Spartan support coming in v1.13, with full upload functionality (both query strings and arbitrary data like with Titan).

**Comment by stacksmith** [comment]
You rock!

**Comment by stacksmith** [comment]
Thank you!
