### ISSUE TITLE
Bug in browser history with data urls

### ISSUE THREAD

**Issue by Altonss** [skyjake/lagrange#454]
![image](https://user-images.githubusercontent.com/66519591/153767893-829988f3-1faa-48f0-bad2-45ef4219d261.png)

The data url seems to load entirely and cover the rest of the browser history

**Comment by skyjake** [comment]
Yeah, I've noticed the same problem. It will be fixed in a future update.

**Comment by Altonss** [comment]
> Yeah, I've noticed the same problem. It will be fixed in a future update.

Oh yes I just noticed! I didn't finish the gemlog that's why xD

**Comment by skyjake** [comment]
Fixed in v1.12.
