### ISSUE TITLE
Localhost does not load on 1.10.5

### ISSUE THREAD

**Issue by Melonking906** [skyjake/lagrange#455]
I recently updated from 1.9.5 to 1.10.5 and since then my localhost gemini server "gemini://localhost" does not load in lagrange anymore, downgrading to 1.9.5 fixes the issue, the localhost also loads fine in amfora 1.9.2. When trying to load on 1.10.5 the page appears to just hang as it tries to load, there is no error or warning.

The localhost server is a static file served by https://github.com/jgkaplan/gemini-server 1.6.0

**Comment by skyjake** [comment]
For what it's worth, I tested gemini-server on macOS and Lagrange 1.10.5, and it worked perfectly for me.

Which OS are you using?

**Comment by Melonking906** [comment]
This is also on macOS 12.2

Attached is an image of it attempting to load localhost, you can see the url is correct and the title has changed, but the page has not loaded.

EDIT: One extra piece of info I can provide is that the server is not even receiving the request from lagrange, I setup a log that should trigger as soon as / is requested and it does not trigger with 1.10.5

<img width="767" alt="Screenshot 2022-02-14 at 10 38 48" src="https://user-images.githubusercontent.com/1700367/153848556-e4b09a82-3409-4ccd-815b-b82f6a142bf5.png">

**Comment by skyjake** [comment]
There is a known issue in Lagrange that if the server closes the socket prematurely, e.g., before sending a valid response and closing the TLS connection, no error is shown and you'll just see "0 bytes" in Page Info and the document in the current tab is unchanged. I'm seeing this behavior when I enter an invalid path with gemini-server. Perhaps the server configuration is missing the URL that you're requesting, or can't find the file that you're trying to send?

You could make a quick test with [another server](https://github.com/mbrubeck/agate/releases/tag/v3.2.3) to check if there is some underlying network issue or if it's a problem specific to gemini-server.

**Comment by Melonking906** [comment]
Iv identified the issue; going to "gemini://localhost" has the issue, going to "gemini://localhost/" works. It seems that the server and/or lagrange is seeing "/" (or lack of it) as a distinct path.

**Comment by skyjake** [comment]
There was a small change in the Gemini specification in November 2021 saying that empty paths should be normalized to /. Clearly the server isn't doing that, and in Lagrange v1.10 the path normalization was broken due to other recent changes. I've fixed it for the next update, but of course the server would be advised to properly handle both empty path and /.

**Comment by skyjake** [comment]
I guess that takes care of this issue.
