### ISSUE TITLE
Can't bind certain actions to the key "u"

### ISSUE THREAD

**Issue by hut** [skyjake/lagrange#456]
Hi, I'm using Lagrange 1.10.5 from Flathub with Ubuntu Mate and encountered this strange bug:

When I go to the preferences and assign the key "u" to certain actions (most are related to scrolling), then pressing pressing "u" just has no effect. Those actions work just fine if I assign them to other keys, like "y". The "u" key also works just fine if I assign it to certain other actions.

Some actions that work with the key "u":

- Go back
- Add bookmark
- Find text on page
- Go to capsule root

Some actions that do NOT work with the key "u":

- Jump to top
- Jump to bottom
- Scroll up
- Scroll down
- Scroll up half a page (which I wish I could use)
- Scroll down half a page
- Open link via home row

**Comment by skyjake** [comment]
This is probably because the Feeds tab of the sidebars have an unbindable keyboard shortcut U for switching to the Unread  mode. For me, if I don't have Feeds visible in either sidebar, U works as a binding.

I should be able to fix this by making the Unread/All shortcuts bindable as well.

**Comment by skyjake** [comment]
Fix included in v1.10.6.
