### ISSUE TITLE
Text selection background disappears on scroll down

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#46]
Steps to reproduce:

- select some text
- scroll down about a screen

Result:

- text selection [blue] background is not shown any more
- the selection is still active and text can be selected until the bottom of the page

Expected result:

- text selection is shown after scroll down.

**Comment by skyjake** [comment]
Yep can produce. Looks like the case of the marked selection range starting from outside the visible range is being mishandled.

**Comment by emilis** [comment]
Also no selection is shown, but seems to work when using `Ctrl+A` to "select all".

**Comment by skyjake** [comment]
There is no Select All feature in Lagrange. However, if you Copy with no selection, the entire document source is copied to the clipboard.
