### ISSUE TITLE
Improper capitalisation for Turkish

### ISSUE THREAD

**Issue by bitigchi** [skyjake/lagrange#463]
The capital form of the letter `i` is `İ` in Turkish Latin alphabet (`I` is the capitalised form of `ı`). Lagrange currently auto-capitalises `i` to `I`. It would be nice to have localised settings for this.

<img width="403" alt="Ekran Resmi 2022-03-05 02 14 43" src="https://user-images.githubusercontent.com/2769571/156854794-dbafbb7b-6cb1-4734-9345-b32f4b97cc98.png">

Above `SAYFA BILGISI` should have been capitalised as `SAYFA BİLGİSİ`.

**Comment by skyjake** [comment]
Fix to be included in v1.12.

**Comment by bitigchi** [comment]
Awesome! Thank you!

**Comment by bitigchi** [comment]
I am afraid this is not yet fixed.

**Comment by skyjake** [comment]
> Fix to be included in v1.12.

v1.12 hasn't been released yet. 🙂

**Comment by bitigchi** [comment]
Ah, sorry! I misread 1.11.2 as 1.12! My bad!
