### ISSUE TITLE
Rendering of links starting with an emoji differs depending on the emoji

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#465]
Internal links usually get an arrow on the left, unless they start with an emoji.
But if the emoji is a flag the arrow is there. I suspect it has to do with the flag being a composed character and not a single one.

I see that on gemini://tilde.club/~adou/gemlog/index.gmi
The esperanto link gets no arrow but the english link gets one (on android)

**Comment by skyjake** [comment]
Yes indeed, the link icon detection didn't account for symbols consisting of multiple code points. The regional indicator symbol pairs that are used for flags are now detected and allowed as link icons.

This will be included in 1.11.2.

**Comment by farvardin** [comment]
@skyjake I suppose it's a similar problem for the emoji 🃏 and 🎴

The first one is not rendered as link, while the second is.

![image](https://user-images.githubusercontent.com/477243/209670269-9e95279c-e4aa-44ff-aca5-9665cd2ba7c0.png)


They seems to have a similar status though:

- https://emojipedia.org/joker/
- https://emojipedia.org/flower-playing-cards/

**Comment by skyjake** [comment]
@farvardin Not the same issue, actually, as these are single code points:

```
🃏
joker
Unicode: U+1F0CF, UTF-8: F0 9F 83 8F

🎴
flower playing cards
Unicode: U+1F3B4, UTF-8: F0 9F 8E B4
```

The 🃏 probably just isn't included in the set of valid link icons. The set currently only includes ones that "make sense"... All types of playing cards could perhaps be included as an allowed group. Come to think of it, there could be configuration file to customize the allowed ranges of link icons.
