### ISSUE TITLE
Crash when clicking a certain link

### ISSUE THREAD

**Issue by xereeto** [skyjake/lagrange#467]
Hi, there seems to be a crash-inducing bug in the latest version. Tested on Windows and MacOS.

Steps to reproduce: enable "Monospace body" for gemini, visit [gemini://rawtext.club/~sloum/geminilist/005078.gmi](gemini://rawtext.club/~sloum/geminilist/005078.gmi), and click "<- back to mailing list".

The bug does not occur when using a variable width font. I suspect this has something to do with the way the monospace font seems to render the characters <- as a ligature, but I'm not sure.

Here's the [crash log](https://termbin.com/r35g), if it helps.

**Comment by skyjake** [comment]
Thanks for reporting, seems like a pretty simple fix.

**Comment by skyjake** [comment]
Fix included in v1.12.
