### ISSUE TITLE
Android: error loading image (webp)

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#472]
![scr1](https://user-images.githubusercontent.com/688044/161129604-bd2733e1-abfb-4b68-9913-461ba68fac41.jpg)

There is no such problem with Lagrange on Linux.

**Comment by skyjake** [comment]
WebP decoding will be supported in Beta 5.

**Comment by sikmir** [comment]
Just got 1.13b5 update, webp works now, thanks!
