### ISSUE TITLE
love lagrange and a solution to fuzziness using hidpi wayland scaling

### ISSUE THREAD

**Issue by iambumblehead** [skyjake/lagrange#476]
The lagrange client is beautiful and I've just found the solution to the fuzzy interface I've had using linux/wayland/hidpi and want to share. The solution is from this comment https://github.com/onivim/oni2/issues/516#issuecomment-550048033

start lagrange this way,
```bash
$ SDL_VIDEODRIVER=wayland lagrange
```

**Comment by iambumblehead** [comment]
its a little buggy in gnome, window decorations don't appear and submenus from the toolbar render in a broken way.

**Comment by skyjake** [comment]
I've read that SDL's Wayland support is being improved for 2.0.22. Hopefully the window decoration and submenu issues will be affected.

**Comment by iambumblehead** [comment]
https://github.com/libsdl-org/SDL/milestone/3 <- the 2.0.22 milestone :)

**Comment by iambumblehead** [comment]
2.0.22 release https://github.com/libsdl-org/SDL/releases/tag/release-2.0.22

**Comment by iambumblehead** [comment]
current status using `SDL_VIDEODRIVER=wayland`: submenus work great. no window decorations appear in gnome42 and lagrange needs to be fullscreen.

**Comment by iambumblehead** [comment]
same is still true using lagrange-1.17.6-1 lagrange is blurry by default and using SDL_VIDEODRIVER=wayland prevents window decorations

**Comment by iambumblehead** [comment]
installing `libdecor` then running `SDL_VIDEODRIVER=wayland lagrange` solves the issue
