### ISSUE TITLE
ctrl+shift+T to restore accidentally closed tab

### ISSUE THREAD

**Issue by mordae** [skyjake/lagrange#477]
It would be rather nice to be able to quickly restore accidentally closed tabs with the ctrl+shift+T key binding that some of us have deep in their muscle memory.

Provided it's not an unreasonable request, please outline a reasonable approach so that one may implement it on a slower weekend.

Thank you for an awesome job, by the way.

**Comment by skyjake** [comment]
Shouldn't be too difficult to do. I suppose you're assuming it remembers multiple closed tabs, like an undo stack? That's what Safari seems to do, for example.

**Comment by mordae** [comment]
There goes my Sunday.

Thanks for the feature, though! :heart:

**Comment by skyjake** [comment]
There seems to be a duplicate: #446
