### ISSUE TITLE
Android build?

### ISSUE THREAD

**Issue by h-bag** [skyjake/lagrange#478]
Unsure if this is the right place to be asking, but I'm wondering if there are any plans for an Android build. It'd be nice to have a comfortable client for my phone.

**Comment by skyjake** [comment]
Yes there is. Check it out: https://gmi.skyjake.fi/gemlog/2022-03_android-beta1.gmi

**Comment by h-bag** [comment]
Awesome, thanks! I tried to install it via F-Droid, but even after adding the repo I couldn't find it via search,

**Comment by skyjake** [comment]
I don't know what could be the problem with F-Droid, as it seems to work for me. However, the F-Droid repo APKs can be directly accessed here: https://github.com/skyjake/skyjake.github.io/tree/master/fdroid/repo
