### ISSUE TITLE
Option to equalize split view tab widths (exclude sidebars)

### ISSUE THREAD

**Issue by viviicat** [skyjake/lagrange#480]
This is a very minor feature request, but when I have the sidebar open and am using a split, the two pages are not the same size.

I was wondering if it would be possible for the split to take the sidebar into account when calculating its center position (maybe make this a toggleable option for those who prefer it the way it is currently).

It would also be nice to be able to adjust the position of the split, but that's less of a priority for me then having equally-sized pages.
![Screenshot from 2022-04-18 14-09-44](https://user-images.githubusercontent.com/287339/163878743-ef121830-d0ec-4d37-bd33-68fdfdb2daec.png)

Platform: Gentoo Linux
Version: 1.11.2

**Comment by skyjake** [comment]
Having an option for this makes sense, I'll look into it.

The technical explanation for the current behavior is that the split mode affects the entire UI, not just the document area. Making the split draggable would also be useful, but is more complicated to implement.

**Comment by skyjake** [comment]
This will be included in v1.13.6.

Having played with this for a while, I do like the symmetry of the split tabs, but it gets a little confusing when showing and hiding the sidebars. Still, this is good to have as an option.
