### ISSUE TITLE
Identity is enabled but not used when refreshing the Gemini page.

### ISSUE THREAD

**Issue by cnngimenez** [skyjake/lagrange#482]
Hi! Lagrange is a good Gemini browser and I like it 👍🏽 . I wonder if this happen only to me, but it appears to be a Lagrange bug. Could it be fixed?

Thanks! 
Cheers.

# The problem I found
When visiting a Gemini URL which requires an identity, the first time I set the identity it opens the page correctly. However, when refreshing the page or clicking a link to the same site, it ask for the same identity again but it is already enabled on the interface.

This happens on Lagrange 1.12.1, but it didn't happen on Lagrange 1.10.6 (using AppImages).

## What I expected
When refreshing the same page, and the user didn't disable the identity, the page should show its content, and not ask the identity certificate again.

(If possible) when clicking in a link to the same site, the enabled identity should be used too.

# Steps
In Lagrange 1.12.1, I'm navigating a personal site which requires a specific identity enabled. 

1. I open the URL, for example, gemini://my-gemini.site.org/secure/my-room-temperature.gmi
2. Lagrange shows a message that the server request an identity certificate (status code 60). 
3. I enabled my identity certificate at the sidebar, which is the one expected by the server. Lagrange resend the request, apparently with the selected certificate.
4. Lagrange shows the server response with success (status code 20) and with the page contents.
5. I refresh the page or clicked to a relative link to, for instance, "./my-room-humidity.gmi".
6. Lagrange shows that the server request an identity certificate (answers status code 60) again. And the identity is still enabled. 
7. I change the identity, refresh, and use the first identity in order to see the page again.

This is what I see at step 6:
![lagrange-identity](https://user-images.githubusercontent.com/1332276/164260329-795c5d06-f612-46b7-a28a-f13e1ff43683.png)

**Comment by skyjake** [comment]
So far I've been unable to reproduce this problem. Do you perhaps have a public URL/capsule where the issue could be tested?

**Comment by cnngimenez** [comment]
Hi @skyjake!
I'm sorry to post this.
I found the bug and **it's not in Lagrange**, it's on the server software. The server has some problems retaining the certificate. I thought it was Lagrange 1.12 because I changed the version or the client and the server worked properly.

Thanks for your fast reply!
