### ISSUE TITLE
bug: overview does not update when switching tabs 

### ISSUE THREAD

**Issue by lolbinarycat** [skyjake/lagrange#483]
steps to reproduce:
1. have lagrange open with 2 tabs on different pages
2. open a sidebar
3. set sidebar to show the headings on the site (overview)
4. switch between tabs

expected behavior:
overview updates to show the headings for the new site

actual behavior:
overview does not change

version (from about:lagrange): 
Version 1.12.1

**Comment by skyjake** [comment]
Fixed in v1.13.0.
