### ISSUE TITLE
bookmarks creation dialog is not keyboard accecible in several ways

### ISSUE THREAD

**Issue by lolbinarycat** [skyjake/lagrange#486]
- you can't cancel it with the keyboard (ESC just closes the sidebar, annoyingly)
- changing the folder with the keyboard doesn't seem to be possible

**Comment by skyjake** [comment]
Hmm, the ESC problem seems to be a recent bug.

The second issue will be addressed in v1.13, where there are multiple keyboard navigation improvements.
