### ISSUE TITLE
Add standard icon for crypto links

### ISSUE THREAD

**Issue by kallisti5** [skyjake/lagrange#487]
Just like mailto uri's get a mail icon, gemini links get a blue triangle, and external links get a orange globe for http/https, cryptocurrency links should get a generic crypto icon.

bitcoin -  ```bitcoin:hash```
[etherum](https://eips.ethereum.org/EIPS/eip-831) - ```etherum:0xhash```

Unicode 6 offers 💰, and later Unicode 10 offers a bitcoin logo ₿

**Comment by kallisti5** [comment]
Example below...   Can't adjust the link icon, nor does it detect the crypto url's.   These are valid via XDG -> bitcoin / Ethereum wallets.

![terarocket](https://user-images.githubusercontent.com/100110/166252233-55bd100a-97c7-479c-9063-f616ca438610.png)

```
## Donations

If you appreciate this site, please consider donating!

=> https://liberapay.com/kallisti5 Liberapay
=> bitcoin:bc1q0fvhyml7d39a67lt2c8c66q04ad7uzd5mcjfdc 💰 Bitcoin: bc1q0fvhyml7d39a67lt2c8c66q04ad7uzd5mcjfdc
=> ethereum:0xA0Ce42789a6e0Baece7B88A6440ce514478Aa0B9 💰 Ethereum: 0xA0Ce42789a6e0Baece7B88A6440ce514478Aa0B9
```

**Comment by skyjake** [comment]
I'm not going to add code to recognize the URL schemes of a bunch of cryptocurrencies, but I can enable the use of custom link icons with all unsupported schemes, which lets you put 💰, 🪙 and ₿ in your link labels.
