### ISSUE TITLE
Ui bug: Existing content doesn't change with empty responses.

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#489]
Noticed an odd UI issue on Lagrange 1.13.2 (1.13.2)on MacOS

This gemini URL returns an empty (and invalid) response. No status code, no \r\n, nothing

gemini://shinra.pollux.casa:1965/images/avif/pexelsavif100.avif

When receiving such a response, Lagrange updates the hostname and url for the new URL but continues to show the old content. No error is displayed, and content that does not match the URL is shown, which is pretty confusing

<img width="744" alt="image" src="https://user-images.githubusercontent.com/4118560/166713979-242ccea2-c853-4f31-bda3-e74805025749.png">

To reproduce:
1. Go to gemini://git.skyjake.fi/lagrange/dev/AUTHORS.md to render some content
2. Paste this URL into the address bar: gemini://shinra.pollux.casa:1965/images/avif/pexelsavif100.avif
3. Lagrange updates the hostname display at the top fo the screen to be `shinra.pollux.casa` but continues to display the old contents from `git.skyjake.fi` as shown in the screenshot above

**Comment by skyjake** [comment]
I'm familiar with this bug. It has seemed like a rare occurrence in practice, so it hasn't been prioritized, but I think it's time to fix it.

**Comment by skyjake** [comment]
Fixed for v1.13.3.
