### ISSUE TITLE
Clarify meaning of multiple bookmarks having the special "homepage" tag

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#49]
Not sure how Lagrange then selects which one to use, but may lead to inconsistencies and unexpected behavior to users.

I had to manually remove "homepage" from the old bookmark, after adding it to the new bookmark.

I suggest at least adding visual aids to separate the "homepage" bookmarks from others.

**Comment by skyjake** [comment]
Hmm, the Help doesn't elaborate on the logic... It's actually a randomized selection if multiple homepage tags exist.

I've been meaning to add a preference to configure what the Home button does.

> I suggest at least adding visual aids to separate the "homepage" bookmarks from others.

This is coming, yes. 😃
