### ISSUE TITLE
Spartan input field: do not show session-id information in default text

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#491]
The only way to keep session information in Spartan is to pass a session-id in the query-text of the prompt-url, and hope that the client is smart enough not to strip it when appending user's data from the input field.

Lagrange already does this well, and perhaps I've convinced you to select the default text for easy replacement.

You've made a decision to use the query text as the default text.  Now I will try to convince you to provide a way to hide a session-id in the URL from the eyes of the user while passing it back to the server.

Consider a game like SpellBinding, where the user is constantly providing new words by interacting with a prompt line like this:
```
=: spartan://tilde.cafe/~spellbinding/game?sesh1234
```
As it stands, the user will see 'sesh1234` as the default, delete it (if you took my advice, the user can just type in the word).  The url at the server will be something like `...game?sesh1234?foo`.

I propose the following idea: a session-id is passed between two `?` in the query; whatever follows is the default (and could be replaced by the user response.  So, the prompt line will be 
```
=: spartan://tilde.cafe/~spellbinding/game?sesh1234?default-text-here
```
session id will not be show - only the default text, and when the user types 'foo', the query string will become `?sesh1234?foo` (replacing the default).

This follows what Lagrange currently returns to the server (two ? with the original data in between), while providing a clear way to pass session data back and forth unmolested, and unseen in the text field.

**Comment by skyjake** [comment]
>  two ? in the query

Unfortunately, this was a bug and completely unintentional. The intended behavior, now pushed to dev, is that the query string is replaced with what the user enters, and the ? from the URL is excluded from the Spartan request content, as per the table in the spec section 5.1.

>The only way to keep session information in Spartan is to pass a session-id in the query-text of the prompt-url

I suggest using CGI `PATH_INFO` for session parameters. @michael-lazar may want to weigh in on this too, but I think the query string is intended purely for user input and should not be "polluted" with server-side parameters.

**Comment by michael-lazar** [comment]
I agree that I think ``PATH_INFO`` is a great solution for server-side parameters. This is a really cool part of CGI that is vastly underutilized, I think because it's easy to misinterpret [(link)](https://github.com/michael-lazar/jetforce/issues/16).

 In this example you would have something like 

```
=: spartan://tilde.cafe/~spellbinding/game.cgi/sesh1234?default-text-here
```

which would be sent to the server like this

```
tilde.cafe /~spellbinding/game.cgi/sesh1234 17
default-text-here
```

And if I were writing a CGI implementation, I would represent it like this

```
SCRIPT_NAME=/~spellbinding/game.cgi
PATH_INFO=/sesh1234
QUERY_STRING=
CONTENT_LENGTH=17

<stdin>=default-text-here
```

This actually fits really well with the paradigm if you look at how CGI is supposed to handle HTTP POST requests. [(reference)](https://datatracker.ietf.org/doc/html/rfc3875#section-4.3.2). The spartan server/CGI handler would not see query strings, because they're only part of the URL and not part of the actual spartan request. The client should always strip the whole query string from the URL (everything after the first "?") when building the request path.

**Comment by stacksmith** [comment]
Shite.  Did I just destroy the part of Spartan that accidentally worked well?

Without this I will not be able to implement games - and no server-based applications can work...

The servers I see would, for the example above, try to hit `/~spellbinding/game.cgi/sesh1234`, not `game.cgi`, and everything would suck.   How can the server determine where the cgi is?  By noting that it is a file and not a directory?  That seems odd.

 SPSRV does not send PATH_INFO.

What have I done...

**Comment by michael-lazar** [comment]
> The servers I see would, for the example above, try to hit /~spellbinding/game.cgi/sesh1234, not game.cgi, and everything would suck. How can the server determine where the cgi is? By noting that it is a file and not a directory? That seems odd.

Yea basically, the CGI server can traverse up the path one segment at a time and look for an executable file.

-  /~spellbinding/game.cgi/sesh1234/submit
   (is executable file? No.)
-  /~spellbinding/game.cgi/sesh1234
   (is executable file? No.)
-  /~spellbinding/game.cgi
   (is executable file? Yes! Invoke the script and set ``PATH_INFO=/sesh1234/submit``

You can make it simpler to implement if you add a constraint like "no sub-directories are allowed in cgi-bin/", but that's really up to the server to decide how they want to implement it.

This is how CGI is is supposed to work. It's easy to miss, but I don't think it destroys anything? If you want to write a compliant CGI server in gemini you also need to handle this.

Edit: Here's an example on my gemini server

gemini://mozz.us/cgi-bin/debug.cgi/hello/world ([(proxy)](https://portal.mozz.us/gemini/mozz.us/cgi-bin/debug.cgi/hello/world)

**Comment by stacksmith** [comment]
_can_ is the operative word.  Will the CGI servers traverse up the path after checking for validity of every sub-path along the way? 

I can't believe I've blown Spartan SpellBinding with my big mouth and do-good ignorance.  I even wrote a cgi->Common Lisp proxy for Spartan games which will no longer work, as SPSRV will certainly not do what's described above.

I am really bummed.

I could've just quietly done it, and it would've worked, and as the only interactive Spartan application, weighed in heavily on leaving the query-string as it is...

**Comment by michael-lazar** [comment]
I'm sorry this is discouraging, it's definitely no fun to run into a roadblock right before the finish line.

> as SPSRV will certainly not do what's described above.

Maybe not now, but I don't see why we can't write a patch for it. MollyBrown has logic to handle this is like 20 lines of go, and the codebase for SPSRV looks suspiciously similar 😄

- https://tildegit.org/solderpunk/molly-brown/src/branch/master/dynamic.go#L19-L45
- https://git.sr.ht/~hedy/spsrv/tree/main/item/dynamic.go#L17

**Comment by skyjake** [comment]
Thanks for the comments @michael-lazar, I fully agree with what you're saying.

@stacksmith:
> can is the operative word. Will the CGI servers traverse up the path after checking for validity of every sub-path along the way?

They will if you write such a server or convince someone to improve their own server to behave this way. Also, CGI doesn't have to rely on actual executables in a file system. For example, in my own Gemini server I just configure the CGI URL entry points explicitly in a config file, without any mapping to the file system. This way it's trivial to know which parts of the URL become the `PATH_INFO`.

**Comment by stacksmith** [comment]
I am entering the 'acceptance' phase of my grief.  I run no servers directly and have to rely on whatever server the tilde is running.

I have not fully grokked the implications of hiding the name of the cgi script in the middle of the path.  in `spartan://someserver/blah/bleh/cgi/foo/bar`, identifying the 'cgi' component mixed in with the filesystem path, seems tricky!  Is the server supposed to try every sub-path as a file to see if a component is indeed a file, then check if it's executable?  Or would it start with the entire path, and on error, shorten it until it (hopefully) gets to a subset that works as a cgi?  Should it cache the cgi and compare all incoming URIs to that?  Kind of nuts, or perhaps I am just not clever enough.

Oh, I missed @michael-lazar describing exactly the tediousness I was suspecting.  OK, I officially think _that is nuts_.  No hard feelings, but this is just crazy!  And hitting the filesystem many times and getting errors, has got to be really slow.

I will work around the whole issue by creating per-session symbolic links linking back to the cgi directory; the path of the CGI invoked will then contain the session-id _before_ the dreaded ? or remaining path.

**Comment by skyjake** [comment]
> Oh, I missed @michael-lazar describing exactly the tediousness I was suspecting. OK, I officially think that is nuts. No hard feelings, but this is just crazy! And hitting the filesystem many times and getting errors, has got to be really slow.

A naive implementation could work that way, but why wouldn't the server at least cache this information, if it's a slow operation?

**Comment by stacksmith** [comment]
To me, cacheing less weird state seems to imply better reliability.  Once a cgi is cached, the consistency needs to be constantly checked for.  For `spartan://blah/cgi/foo`, what if I change the name of the cgi?  What if I create a folder called `cgi`?  What if some cgi script alters the filesystem and can't ask the server to verify the cache?

What is this for, anyway?

Not to mention that now we have no way to know where the filesystem ends and a virtual path begins.  And by 'we' I mean anyone who tries to parse URIs for bookmarks, crawlers, etc...  How can we identify transient parts of the URIs?  With a `?` as a barrier things were so simple...

I don't know, but things like this make me feel old and tired.
