### ISSUE TITLE
TUI doesn't work as expected

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#492]
Here is what I see:
![scr1](https://user-images.githubusercontent.com/688044/167114989-79269d34-8f8d-40a3-9698-6a2f6e0e1d03.jpg)
Screenshot from [gemlog](https://gmi.skyjake.fi/gemlog/2022-05_lagrange-1.13.gmi):
![](https://gmi.skyjake.fi/gemlog/images/clagr2.png)
What I'm doing wrong? I've used cmake flags from build-tui.sh.

**Comment by skyjake** [comment]
Which terminal are you using? Currently there is no support for basic VGA color modes. It assumes "xterm-256color" and a terminal that supports a modifiable palette. I'm working on adding reduced color modes next.

**Comment by sikmir** [comment]
I'm using [st](https://st.suckless.org/) and [kitty](https://sw.kovidgoyal.net/kitty/), the problem with both ones. But I've just tried on macOS with iTerm and clagrange works as expected! Do you know what terminal could be used on linux?

**Comment by skyjake** [comment]
I'll try those on my system(s).

xfce4-terminal has been working fine for me at least.

**Comment by skyjake** [comment]
This should be significantly better now with the latest v1.13 patches.

**Comment by sikmir** [comment]
I've tried v1.13.6 with `xfce4-terminal`, but it doesn't work as well. SInce xfce4-terminal works for you, I wonder what is missed on my system...
