### ISSUE TITLE
The special case of index.gmi with "go to parent"

### ISSUE THREAD

**Issue by lolbinarycat** [skyjake/lagrange#494]
currently, there is a special case for "go to parent" for when the url ends in "/index.gmi".  instead of going to the dir containing index.gmi, it goes up an extra level.

this often doesn't make sense (eg. in file:// urls, or anywhere else index.gmi has no special meaning), and just makes the feature feel weirdly inconsistent and unintuitive.  especially with how it only exists for index.gmi, not index.gemini or anything else.

i think this should be removed to make the feature feel more consistent, and also probably simplify the code.

**Comment by skyjake** [comment]
I'll check it out, there's probably some fine-tuning needed here.

The intent with this is for the navigation to behave as expected when navigating up from the default/index page of a directory served by a Gemini server.  If you go from "path/index.gmi" to "path/", the user will typically just get the same page back and the feature seems broken.

**Comment by lolbinarycat** [comment]
> I'll check it out, there's probably some fine-tuning needed here.
> 
> The intent with this is for the navigation to behave as expected when navigating up from the default/index page of a directory served by a Gemini server. If you go from "path/index.gmi" to "path/", the user will typically just get the same page back and the feature seems broken.

typically those two paths have the same content, yes.  however, in the case where they don't (perhaps there was a reason you were linked to index.gmi specifically), it can be quite jarring, and there is no easy fix, you have to edit the url manually.

if you somehow find yourself on path/index.gmi instead of just path/ (i guess someone just didn't link the correct page?), and you press "go to parent", you may be a bit confused for a second, but you can simply press the button again.

at the very least, an option to disable this would be appreciated.

**Comment by skyjake** [comment]
According to [Gemini best practices](https://gemini.circumlunar.space/docs/best-practices.gmi), I have amended this behavior to only apply to Gemini URLs and also check for "index.gemini".

> however, in the case where they don't (perhaps there was a reason you were linked to index.gmi specifically)

Gemini servers certainly are not required to follow best practices, but I feel that clients should by default assume they do and behave accordingly, to create an incentive for all the various servers out there to follow best practices.

I have now added the variable `parentnavskipindex` (in prefs.cfg) that you can use to disable this index skipping. Perhaps I will add an "Advanced" preferences pane at some point; for now, the option has no GUI toggle.

**Comment by skyjake** [comment]
Changes included in v1.13.5.
