### ISSUE TITLE
mailto: link structure not recognized

### ISSUE THREAD

**Issue by deltamualpha** [skyjake/lagrange#5]
Hello! Love the app.

5.4.2 of the spec doesn't make it entirely clear if `mailto:` should work in a link-line (the examples are all of the `protocol://` variety), but as a user it seems like it should. Grepping the mailing list doesn't make it clear if the intention was to support mailto or not, but https://lists.orbitalfox.eu/archives/gemini/2020/001285.html implies that some of the people working on the spec would expect it to work.

An example line would be `=> mailto:user@example.com my email address` and the expected behavior on clicking it would be to hand off to the OS for whatever application is designated for email authoring.

**Comment by skyjake** [comment]
I agree. `mailto:` should be recognized and it should be handled the same way as http links.
