### ISSUE TITLE
The cursor size and blinking speed is a bit intense

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#50]
I was trying to write an email in a smaller window on top of Lagrange and the blinking cursor in the URL field was too distracting.

At least FireFox has a line cursor and it blinks really slow.

**Comment by emilis** [comment]
I want to add that I really like the cursor style in general -- it shows that the application is using a different UI toolkit than e.g. GTK apps and has some retro feel to it. But it may be harder to make it less distracting.

**Comment by skyjake** [comment]
I could de-emphasize the text cursor appearance when the mouse cursor is outside the window. Would that help?

**Comment by emilis** [comment]
The problem is that not only the mouse cursor was outside, but another application window was focused.

I think the bugs with URL field not dropping selection+blinking when mouse clicks anywhere else (#51) would fix this annoyance.

**Comment by skyjake** [comment]
I think this can be closed now, Lagrange's input fields are unfocused when some other window gets the input focus.
