### ISSUE TITLE
Improper Link Decoding

### ISSUE THREAD

**Issue by juvtib** [skyjake/lagrange#503]
I have a link to an HTTP site which includes a URL fragment (`example.com/#url-fragment`). That should open my default Web browser and take me to a specific element on the destination page. But clicking the link in Lagrange sends me to the top of the page instead. 

Clicking the same link using a proxied version of my site in a traditional Web browser works. Showing the source in Lagrange shows the correct, encoded URL. 

Lagrange appears to decode part of my link before sending it to my default Web browser. And the decoded link does not work. 

Here is the source code. 

``` Gemtext
=> https://vimhelp.org/pattern.txt.html#%2F%5Cr    \r | Carriage Return Escape Sequence | Vim Help
```

Here is the link that seems to come out of Lagrange. 

``` text
https://vimhelp.org/pattern.txt.html#%2F\r
```

Notice the `%5Cr` has been changed to `\r`. 

## Issue 

Can Lagrange send the unmodified link to the default Web browser? 

Thanks,

**Comment by skyjake** [comment]
Are you on Windows by any chance? There are some path backslash conversions on Windows that may have an improper effect here. Also, I just tried the link on macOS and it worked fine...

**Comment by juvtib** [comment]
Sorry. I'm on Linux. 

Manjaro
5.17.6
XFCE 4.16

**Comment by juvtib** [comment]
Thanks for taking a look at this. I am able to click through and land at the right `id=` using [1.13.6](https://github.com/skyjake/lagrange/releases/tag/v1.13.6)
