### ISSUE TITLE
View as Plain Text crashes when caption visible

### ISSUE THREAD

**Issue by Alzarath** [skyjake/lagrange#506]
When a caption is displayed from hovering over preformatted text, using View as Plain Text from the drop-down menu or with the shortcut causes Lagrange to experience a segmentation fault.

Reproduce:

* Open `about:lagrange`
* Hover over the Lagrange ASCII art toward the top of the page
* Wait until a caption is displayed
* View as Plain Text (Ctrl+Y)

Reproduced from 1.13.4 and 8587c0f on Arch Linux (AUR)

**Comment by skyjake** [comment]
Fixed for 1.13.6.
