### ISSUE TITLE
No issue, just a big thank you (TUI lagrange)

### ISSUE THREAD

**Issue by m040601** [skyjake/lagrange#508]
This is not an ISSUE. Just a big THANK YOU.

I'm a proficient Linux, keyboard, command line, TUI end user fanatic.

I try to avoid all kind of GUI's on my "desktop". But even so, I had already been very impressed with the **beauty and polish of GUI Lagrange**. I definetely wanted to try some TUI from this same guy.

I'm very limited in understanding "cmake", "make", editing flags etc. And there is no prebuilt binary "clagrange" or "lagrange-tui" being released. But I desperately wanted to test this "clagrange" TUI version. I'm on Archlinux. So I just went ahead, git cloned, and just used the,

````
.... The build-tui.sh helper script is provided for building the TUI version. ....
````

It compiled OK, but wanted to install some man page in root "/", like "/lagrange/resources.lgr" and "/man/lagrange". Probably needs some adjustment.

Anyway. In the end I got an executable "clagrange".

**TUI Lagrange, WOW !!!** 

**What a nice piece of software for all the command line users lovers.** 

It works with keyboard hints, key "f", for clicking the links. Just like Qutebrowser and Firefox Tridactyl etc.  You must give more prominence and stress this in the docs, because it wasn't obvious the first time I rapidly glanced at the README. A must have for all keyboard fanatics already used to this usage pattern.

Really, really, snappy, performant and smooth experience. I think it even has some kind of acceleration. I havent seen another polished piece of terminal browser CLI software being developed lately.

So there you have it. Just praise and keep up the good work !!!
Is there a "market" and "interest" for this ? You can bet it. It definetely needs more "marketing" on your blog posts or gemini posts.

PS: Very interested in hearing feedback from other TUI users. Maybe you could open the github "Discussions". Not for "problems" or "issues", just like a "forum". And  with a special section just for the TUI. So that other proficient command line users can give you feedback and suggestions.

**Comment by skyjake** [comment]
Glad to hear you like it! This is basically the GUI app running on a text mode backend, so it gets much of the polish of the GUI version without any extra effort.

> It compiled OK, but wanted to install some man page in root "/", like "/lagrange/resources.lgr" and "/man/lagrange". Probably needs some adjustment.

Oops, let me fix that...

**Comment by m040601** [comment]
Could you also release a precompiled binary of "clagrange" ?

Very usefull to make a "clagrange-bin" PKGBUILD on Archlinux x64 and others.


Also regarding ARM.
It would also definitely be extremely usefull for use in little arm underpowered devices like the raspberry pi and chromebooks, etc. Not very powerfull or feasible to compile there. But perfectly good old hardware where I run gemini CLI browsers.
A killer use case.


Raspberry Pi 4 = arm64 (aarch64)
Raspberry Pi Zero = armv6h (arm 32 bits)
Raspberry Pi 2 = armv7h (32 bits)
Debian calls it "armhf".

I "think" only one universal lowest common denominator, arm 32 bit prebuilt binary is enough. But I'm not sure. Maybe github workfllow/automation can take care of this. Not an expert.

**Comment by m040601** [comment]
Regarding the GUI prebuilt binary for x64.

> x86_64 AppImage | Built on Ubuntu 18.04

Just for letting you know. We already have a "lagrange" build from source PKGBUILD in Archlinux. I was curious if we could also have a "lagrange-bin" PKGBUILD in Archlinux, that just pulls and packs the prebuilt x64 binary from github.

So I tested this "appimage" it anyway. 

On Archlinux it fails with "segmentation fault". I guess it fails,  because its meant to be used only on Ubuntu right ? It's not a "universal" Linux x64 binary right ?

**Comment by skyjake** [comment]
I'm planning to make a binary TUI release, too, but I want to polish it still a bit more.

> On Archlinux it fails with "segmentation fault". I guess it fails, because its meant to be used only on Ubuntu right ? It's not a "universal" Linux x64 binary right ?

It's not Ubuntu-specific, however AppImages are not fully self-contained so it's not universal either. As a rule of thumb, an AppImage built on Ubuntu 18 should at least run on Debian/Ubuntu, Fedora, and other distros related to those, released in 2018 or later.

The Flatpak version is more compatible but it comes at the cost of pulling in the entire set of dependencies down to the lowest system-level libraries.

**Comment by skyjake** [comment]
>  Maybe you could open the github "Discussions".

I don't want to become any more reliant on GitHub... What I would actually want to see is a Gemini-based discussion forum, but I suppose I'll need to build one myself. 🙂
