### ISSUE TITLE
Android, iOS: can't open file in another app

### ISSUE THREAD

**Issue by sikmir** [skyjake/lagrange#518]
### Steps to reproduce
1. Download file
2. Open in another app:
<img src="https://user-images.githubusercontent.com/688044/176261166-8960ffb0-30e2-432c-ba53-2797ddc49f8f.jpg" width="250">
3. Save error:
<img src="https://user-images.githubusercontent.com/688044/176261160-01f6df2f-3a5a-46e3-b0fc-4b838b1e4252.jpg" width="250">
4. At the same time "Save to downloads" works and I can open file from file manager

**Comment by sikmir** [comment]
The same issue on iOS, but with error "Operation not permitted" instead of "No such file or directory".

**Comment by skyjake** [comment]
The Android issue has been fixed (#535).

**Comment by sikmir** [comment]
> The Android issue has been fixed (#535).

Great, it works now.
