### ISSUE TITLE
Visual clues for links are unclear

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#52]
I consider myself somewhat experienced in UI/UX (been interested in that stuff since ~2000).

After using Lagrange for a couple of days I still don't understand what the icons beside the links mean.

One thing I figured out is that blue color is for Gemini links and brown color is for web/other URLs.

I have no idea what's the difference between the globe / arrow / circled numbers.

Maybe a help page would help?
Maybe show hints on links or the icons?

**Comment by skyjake** [comment]
This is explained in the Help document. You can get to it via the menus.

If the documentation is unclear, I can improve it. 🙂
