### ISSUE TITLE
seeing crashes opening gopher pages in Lagrange on macos

### ISSUE THREAD

**Issue by cquenelle** [skyjake/lagrange#525]
MacOS 12.4
Lagrange 1.13.7

I'm a new user and the first 3 or 4 different gopher pages I tried crashed Lagrange.
I've tried opening from other apps and pasting the url into Lagrange, same result.

Ah ha!  If Lagrange is not running, then links open okay.  But if the app is already running whenI try to open a gopher page then it crashes

**Comment by skyjake** [comment]
I haven't seen any Gopher-specific crashes myself. Do you have a URL that causes the crash every time for you?

**Comment by cquenelle** [comment]
For me, the following steps will cause a crash.

Start Lagrange
Close all windows, but leave the app running.
from the shell command line type:
% open gopher://gopher.quux.org/1/Software/Gopher/servers

If there are any windows open but iconified, then the address opens as expected.
So it's only triggered if there are no active windows.

If the app is not running, then it's started and open the page as expected.

**Comment by skyjake** [comment]
Fixed for 1.13.8. The problem was that the event handler didn't realize that a new window needed opening if there wasn't one when the user was opening a URL via an external app.

**Comment by skyjake** [comment]
Included in v1.13.8.
