### ISSUE TITLE
Question: How to connect to server on local network?

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#529]
I’ve spun up agate on a raspberry pi. I’d like to connect purely by IP address for testing. Is this possible? Or how can I use the host name of the pi? Eg mypi.local. 

I tried setting the IP of the pi as the Gemini proxy address in Lgranage settings but no use. Thanks.

**Comment by siiky** [comment]
This is unrelated to Lagrange.

(Assuming that you're asking about accessing your Pi in the same local network)

Just use your Pi's IP in the URL: `gemini://192.168.XXX.YYY/some/page.gmi`.

Alternatively, if pinging your Pi by hostname works (`ping mypi.local`) then using that should also work: `gemini://mypi.local/some/page.gmi`.
