### ISSUE TITLE
Has SNI been implemented?

### ISSUE THREAD

**Issue by marek22k** [skyjake/lagrange#531]
Has SNI been implemented?
SNI is a TLS extension which allows to store multiple pages on one server. The hostname is already transmitted unencrypted during the TLS handshake, so that the server can select the appropriate certificate.

https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by skyjake** [comment]
Yes, Lagrange uses SNI when making TLS connections.

**Comment by marek22k** [comment]
Thanks for the answer!
Is the SNI encrypted (ESNI) or the Client Hello message (ECH)? If not, are there any plans for this?
