### ISSUE TITLE
In fullscreen, Lagrange 1.13.7 minimizes itself when it looses focus. (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#534]
Lagrange 1.13.7 
Ubuntu 22.04 with Gnome
Flatpack release

Issue:
ALT + TAB (or any method of changing windows) works as expected when Lagrange is not in fullscreen (with F11).
![P4JJ0mE7Cu 08 22 19:54:34](https://user-images.githubusercontent.com/1757768/183995496-9a8df4cb-d7c5-46bf-a28d-80af46134b95.gif)

When Lagrange is fullscreen, the behaviour changes. When the user does ALT + TAB - or just chooses another window with the mouse - Lagrange minimizes and puts itself to the end of the ALT + TAB queue.
![pRgJCw395J 08 22 20:00:16](https://user-images.githubusercontent.com/1757768/183995940-b04be380-e816-488e-9460-4bc3ea5eea9b.gif)
.

Edit: this was originally reported against 1.13.6 as per the screengrab, but tests with 1.13.7 have the same results.

Edit 2: I see in the "Known Issues" that SDL does not have full support for Wayland yet.  Maybe that's the reason.

**Comment by skyjake** [comment]
This seems a window management issue in the domain of SDL and/or the desktop environment. As such, I don't see much that Lagrange can do differently here... Of course, can reopen later if we figure something out.
