### ISSUE TITLE
External App fails in Android

### ISSUE THREAD

**Issue by stacksmith** [skyjake/lagrange#535]
LAGRANGE 1.13 (B6) 2022-05-09  Android

When opening say an mp4 link, the 'Open in Another App' button fails with; Error Saving File  No such file or directory.

The desktop Linux version works fine.

Try this link:

gemini://gemini.ctrl-c.club/~stack/gemlog/2022-08-13.raylgun.gmi

Is it possible that I somehow missed a setting that specifies some temporary directory for such things?

**Comment by skyjake** [comment]
There is no setting for this. In the mobile versions, both Android and iOS, viewing in external app isn't working currently.
