### ISSUE TITLE
Command line option for an alternative runtime/profile directory 

### ISSUE THREAD

**Issue by jakobi** [skyjake/lagrange#537]
something like

- --tuiprofile (which would use .config/clagrange),
- --xprofile (which would use .config/lagrange; whichever is of --tuiprofile/--xprofile would be the default), plus a more generic 
- --profile PROFILEDIRECTORY option. 

This would enable using a proper lagrange in parallel to smaller more task-specific special purpose mini-clagranges. 

Think firefox and a few shell functions build arund lynx -dump to quickly look up a thesaurus or similar. Some options for clagrange modelled after links/lynx/w3m (like -source, -dump -w(idth)) might ease writing similar aliases or functions for gemini resources.

Even outside such shell functions, I would really like to be able to use clagrange in parallel to a running X lagrange: different work style, window switching, ..., with X lagrange being reserved for more "serious" reading and longer "drilling-down" sessions :).

(Side note shell functions and gemini: I failed to compile gurl, and somewhat distrust the moderately stale gemini-patched curl, which  I found just now.  In contrast, the go language gemget builds nicely on debian testing, and gemget -o - looks to be suitable for use with above mentioned shell functions )

**Comment by skyjake** [comment]
>  Some options for clagrange modelled after links/lynx/w3m (like -source, -dump -w(idth)) might ease writing similar aliases or functions for gemini resources.

I agree this kind of an option can be quite useful. It has been implemented for v1.14. It's just a direct dump of the response body to stdout, with metadata printed to stderr.
