### ISSUE TITLE
Patch to support more file extensions to MIME types

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#539]
This is preparatory to FTP support, where only the extension tells you what the MIME type is.

[more-extensions.diff.txt](https://github.com/skyjake/lagrange/files/9440170/more-extensions.diff.txt)

**Comment by skyjake** [comment]
Nice. Recognizing more extensions should be helpful in general.

I'll only need to check if `mediaTypeFromFileExtension_String` is being called often anywhere, which would have an implication on performance. In that case, using a binary search into an alphabetically sorted array might be preferable to a linear `for` loop.

**Comment by skyjake** [comment]
Patch merged (with minor edits) in dev branch, due v1.14.
