### ISSUE TITLE
First line is highlighted

### ISSUE THREAD

**Issue by marek22k** [skyjake/lagrange#540]
The first line is somehow highlighted in Lagrange. I do not know why. I have installed Lagrange from Flatpak.
![img](https://user-images.githubusercontent.com/46723399/187246241-5fcaf343-b7b4-4a6a-a7a7-728465c49ed1.png)
Code:
```
From: Marek Küthe (m.k@mk16.de)
Last updated: 29.08.2022
```

**Comment by skyjake** [comment]
This is a feature of the text styling engine: the detected lede paragraph of the page is rendered with a slightly larger font. You can control this with _Preferences > Style > Big 1st paragraph_.

At the moment, this doesn't take into account that some "paragraphs" can be short one-liners, which has produced this behavior that you see. The issue has been reported before (#256) so I'll close this one.

**Comment by marek22k** [comment]
I have not found the other issue unfortunately. Thanks for the answer!
