### ISSUE TITLE
ANSI background color reset bug

### ISSUE THREAD

**Issue by ro1y** [skyjake/lagrange#545]
I am having a problem with ANSI color codes where resetting the background color mid-line (using `ESC[49m`) doesn't work.

Intended (as shown in GNOME terminal):
![image](https://user-images.githubusercontent.com/76408418/192573146-7c45e528-7448-4612-9a6f-31988889f444.png)

In Lagrange:
![image](https://user-images.githubusercontent.com/76408418/192574369-a9725842-7ae8-44c2-b3fb-d3add1e84e26.png)

[ansitest.txt](https://github.com/skyjake/lagrange/files/9657702/ansitest.txt)

**Comment by skyjake** [comment]
Yep, there seems to be a bug with handling escape code 49.
