### ISSUE TITLE
Freezing most UI events in Gnome

### ISSUE THREAD

**Issue by despens** [skyjake/lagrange#547]
I'm using Lagrange via the excellent Flatpak distribution, on Gnome (Ubuntu 22.04), X11.

When Lagrange is running, sometimes most functions of the Window manager freeze. I'm able to move the mouse and some keypresses are still recognized (Ctrl+Alt+T for instance to open a terminal, and subsequent input to that terminal), but no click or drag actions are recognized anymore.

When I switch to a text terminal and `killall -9 lagrange` the UI is unfrozen.

I know this is not a great description to reproduce the bug unfortunately. If I can narrow it down more I will add more info. Is there any place that I could look to gather more useful information?

**Comment by skyjake** [comment]
Not really sure what could be causing that. Have you tried a non-Flatpak version of Lagrange (e.g., the AppImage or manual build from source)?

**Comment by despens** [comment]
I wasn't able to test with other versions than the Flatpak distribution. Is there any type of info or log I could try to capture if I observe the bug? It seems to happen very seldomly.

**Comment by despens** [comment]
I couldn't observe the behavior since a few months with new versions of Flatpak release. Closing.
