### ISSUE TITLE
Cursor text selection bug

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#550]
I'm using Lagrange v1.13.7 on MacOS Monterey 12.5.1

I was trying to highlight a URL to copy/paste the text, and I noticed that the cursor was acting strange. On certain lines, when I drag my cursor to the right while holding the left mouse button to highlight the text, it will reach a point where the highlighted text "resets" back to the beginning of the line and starts over. This is hard to describe so I took a screen recording.

This doesn't happen for me on every line of the screen, but the lines that it does effect are reproducible even after page reload.

It seems to be related to the source line in the document. I.E. if a single line of gemtext is wrapped to multiple lines on the viewport, either *all* of those lines in the viewport will have the cursor selection bug or *none* of them will.

https://user-images.githubusercontent.com/5026795/199499404-d95005fd-be85-498b-a6c2-176d8dd1e413.mov

**Comment by skyjake** [comment]
This looks very much like #515. The good news is that I'm about to release a fix for that in v1.13.8. Hopefully this issue will be resolved as well.

**Comment by michael-lazar** [comment]
Awesome! Sorry for the noise
