### ISSUE TITLE
Android: how to import user data?

### ISSUE THREAD

**Issue by skyfaller** [skyjake/lagrange#553]
I have exported user data from Lagrange on my Linux laptop, and I want to have the same bookmarks, feeds, identities etc. on my Android phone. I have the exported data on my phone. I cannot figure out how to open it in Android. How would I drag and drop the file onto Lagrange? How would I figure out the file URL to enter into Lagrange to access the file?

**Comment by skyjake** [comment]
The easiest way to access the exported ZIP is to use the "Open File..." item in the app's hamburger menu (rightmost toolbar button).

This has been supported since v1.12 (Beta 4):

gemini://git.skyjake.fi/lagrange/release/res/about/android-version.gmi

**Comment by skyfaller** [comment]
Thank you, that solves the user interface issue! Sorry for missing that obvious button.

Sadly I've discovered a new problem, I can't open the ZIP file on Android.

![Screenshot_20221110-145929.png](https://user-images.githubusercontent.com/80093/201194175-d684be19-9ea0-4856-a031-a3ccc0e2e39d.png)

I'm on 1.13 b6 2022-05-09, as installed from your FDroid repo.

**Comment by skyjake** [comment]
Are you sure the ZIP you tried to open is not corrupted somehow? And it has the file extension `.zip` in its name?

**Comment by skyjake** [comment]
At least on my devices exported user data ZIPs can be opened, so the feature is not completely broken...

For v1.14, there is now a clear place where user data can be exported and imported: Settings > User Data.

**Comment by skyjake** [comment]
I discovered what the bug is with opening the user data ZIP, and will be making a fix for the next beta build.

**Comment by skyjake** [comment]
Should now be fixed in Beta 11.

**Comment by skyfaller** [comment]
Thank you for your efforts! I can confirm importing user data on Android now works for me, using Lagrange 1.15 (B12) 2022-12-19
