### ISSUE TITLE
Windows protocol handlers

### ISSUE THREAD

**Issue by bradbrownjr** [skyjake/lagrange#555]
I recently fell into the rabbit hole of Gopher and Gemini, and found Lagrange does both the best, in my opinion. Thank you so much for putting so much work into this!

I occasionally stumble on Gopher and Gemini links on the web and have to copy/paste them into Lagrange. Figuring there had to be a way to make them open these links into Lagrange, like I can open PuTTY for telnet:// and similar, I looked into how to add URL handlers for Gopher and Gemini. Below is the results, tested successfully on my computer. 

I'd like to recommend that you include this in a .reg file in the Windows release package, or maybe check for and add these registry keys during installation and updates.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\gemini]
"URL Protocol"=""
[HKEY_CLASSES_ROOT\gemini\shell]
[HKEY_CLASSES_ROOT\gemini\shell\open]
[HKEY_CLASSES_ROOT\gemini\shell\open\command] 
@="\"C:\\Program Files\\Lagrange\\lagrange.exe" \"%1\""

[HKEY_CLASSES_ROOT\gopher]
"URL Protocol"=""
[HKEY_CLASSES_ROOT\gopher\shell]
[HKEY_CLASSES_ROOT\gopher\shell\open]
[HKEY_CLASSES_ROOT\gopher\shell\open\command] 
@="\"C:\\Program Files\\Lagrange\\lagrange.exe" \"%1\""
```

Thank you for your consideration,
Brad Brown Jr

**Comment by skyjake** [comment]
I suppose you didn't use the setup.exe installer? That sets registry keys for opening Gemini, Gopher and Spartan URLs.

A future improvement here could be (re)installing these handlers individually via the app GUI.

**Comment by bradbrownjr** [comment]
I did use the setup.exe. Perhaps I overlooked this and the links I've come across weren't 'a href' tagged. I just checked for a Spartan class and it is already there. My apologies!
