### ISSUE TITLE
Links to gemini (and gopher) fail to open on first click

### ISSUE THREAD

**Issue by jamestomasino** [skyjake/lagrange#556]
Attaching video for evidence of what happens. In short, if Lagrange is not already open and I click a link to gemini (Lagrange as the handler) the app opens and navigation fails. It looks like it takes the path portion of the URL and applies it to a file:// path instead of gemini:// with the domain. If I return and click the link again it loads properly.

v1.14b7 installed via F-Droid. Recorded on a stock Samsung A-72. Links coming from Mastodon website in this video, but same behavior happens no matter the link source.

https://user-images.githubusercontent.com/201422/202928284-92c7f8f1-6a45-4885-a91a-eaf86ebaf81e.mp4

**Comment by skyjake** [comment]
Looks like this is a bug in SDL2, where it's only passing the path component of an incoming URI when the app is being launched. Fortunately, a small tweak in the SDL2 Java code fixed it.

**Comment by skyjake** [comment]
The commit: https://git.skyjake.fi/gemini/lagrange-android/commit/3daaea6f5885c8ea665f08e8d19065e3af9aec9f
