### ISSUE TITLE
Settings menu not available

### ISSUE THREAD

**Issue by Sporiff** [skyjake/lagrange#557]
I can't open the Lagrange settings menu with the `CMD+,` shortcut. When I try to open it using the `Lagrange -> Settings` menu option in the top bar, the option is grayed out. This was working prior to the upgrade to Lagrange 1.14.0.

<img width="259" alt="Screenshot 2022-11-26 at 12 07 56" src="https://user-images.githubusercontent.com/29224057/204085639-28d9a3c6-aeb8-4fa5-8748-cdb06d01a0a7.png">

## System information

* Model: 2020 M1 MacBook Pro
* Arch: arm64
* OS version: macOS Ventura 13.0.1
* Lagrange version: 1.14.0
* Installed via: Homebrew

## Logs

These are the only error logs I could find relating to Lagrange itself. I'm not sure that any of these are relevant.

```log
Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for accessing={TCCDProcess: identifier=fi.skyjake.lagrange, pid=3730, auid=501, euid=501, binary_path=/Applications/Lagrange.app/Contents/MacOS/Lagrange}, requesting={TCCDProcess: identifier=com.apple.appleeventsd, pid=503, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd},
```

```
IMKLaunchAgent -requestIMKXPCEndpointInvalid: received notification Request for Endpoint Invalid (from pid_t: 3730) for bundleID: <private>
```

**Comment by skyjake** [comment]
Potential fix will be included in v1.14.1. This looks like a Ventura-specific change, since they renamed the menu item and the app was looking for the "Preferences" item...

**Comment by skyjake** [comment]
I don't have Ventura installed so can't test, but let me know if v1.14.1 doesn't fix this.

**Comment by Sporiff** [comment]
@skyjake I put in an update for the homebrew cask and upgraded to 1.14.1. I can confirm this is now fixed. Thanks!
