### ISSUE TITLE
file:/// URLs are not handled properly on Windows

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#56]
I was unable to open local files with Lagrange on Windows. Tried `file:///c:/` like URLs. Tried the same URL in Firefox and it worked.

**Comment by skyjake** [comment]
Does it work if you drag-and-drop a file from the Explorer?

**Comment by emilis** [comment]
It works indeed.

The URL becomes `file://C%3A/path/to/file.gmi`.

When I copy it to Firefox, it does not work there and is converted to `file:///path/to/file.gmi`.

**Comment by skyjake** [comment]
9a4032bbba8846d1f5c92b4c39743dc6884f06ec should fix this.
