### ISSUE TITLE
mobile: option to disable swipe / slide gesture

### ISSUE THREAD

**Issue by farvardin** [skyjake/lagrange#560]
Hello, I can't find a way to disable the swiping gesture on android: each time i try to slide some preformatted content, then I slide instead to another tab or back and forth, making the navigation very tedious.

There are icons to change tabs and going back btw, so gesture should be optional please 😅

**Comment by skyjake** [comment]
I agree an option for the swipes would be good. Specifically, options to enable/disable swiping from an edge, and over the page. Also, it should be considered a bug that the preformatted horizontal scrolling triggers navigation at the boundaries...

**Comment by farvardin** [comment]
@skyjake thanks a lot for the quick fix! I've upgraded to latest version and the new options for swipe are perfect now!

**Comment by farvardin** [comment]
cf. https://github.com/skyjake/lagrange/commit/b0d106e9376edbe1c82536ba0fc1be2d458f9149
