### ISSUE TITLE
Inconsistent heading spacing behavior

### ISSUE THREAD

**Issue by jrsalow** [skyjake/lagrange#564]
There is inconsistent behavior on Lagrange 1.14.1 on Windows 10 with spacing after headings.

With the first heading level putting a blank newline between the heading and content
`# Heading 1`

`Content`
 actually _decreases_ the spacing between the heading and subsequent content,  when the expected behavior would be either to increase it or do nothing.

Consequently, removing a blank new line 
 `# Heading 1`
`Content`

actually _increases_ the spacing between the heading and subsequent contents, when the expected behavior would be the decrease it or do nothing.

The next two levels of headings `## & ###` work as expected: a blank line in-between increases spacing, and removing it decreases spacing.

**Comment by skyjake** [comment]
You are right, the spacing after h1 is not right. The intended behavior in this layout is that that the spacing is exactly the same with or without one empty line after the heading.

**Comment by jrsalow** [comment]
> 

Is that only for h1, or should the other levels not increase and decrease at all (even though their change is at least logical)?
