### ISSUE TITLE
Early segfault (1.14.1, 1.14.2 and fb081a9)

### ISSUE THREAD

**Issue by omnivagant** [skyjake/lagrange#567]
Hi, I haven't run lagrange for some time so I could have bumped into this earlier than 1.14.1 if I had tried.

With 1.14.1 and 1.14.2 lagrange segfault for me when the mouse cursor is over the window: [gdb output](https://gitlab.alpinelinux.org/-/snippets/662), [valgrind output](https://gitlab.alpinelinux.org/-/snippets/663).

Built from trunk (at fb081a9) it segfault on startup: [gdb output](https://gitlab.alpinelinux.org/-/snippets/664).

I run Alpinelinux edge (the rolling release) on 64b x86,
- linux: 6.1.4
- musl: 1.2.3
- sway: 1.8
- wlroots: 0.16.1

A couple of other Alpine users say they don't experience the crasches.

**Comment by skyjake** [comment]
This is on Wayland? With the dev branch, please set `ENABLE_X11_XLIB` to `OFF`.

The first two outputs say that the crash occurs inside SDL2, which may indicate a problem with SDL_CreateSystemCursor(). That may be an SDL2 bug.

(Thanks for the debug outputs, quite informative. 👍)

**Comment by skyjake** [comment]
Closing as there is not really anything that I can fix here.
