### ISSUE TITLE
Mouse I-beam cursor overused, should only appear over selectable text

### ISSUE THREAD

**Issue by teepark** [skyjake/lagrange#568]
The light gray, thin cursor which typically only shows up when hovering directly over text is used as the default everyone on the page in Lagrange (the only exception being the hand cursor for links and pre-formatted text sections - clickable things).

The only problem I encounter with this is that it is very difficult to see over light theme backgrounds, so I'm frequently waving the cursor around in an attempt to find it on the screen.

Can Lagrange follow web browsers' lead here and use the arrow cursor by default, then the text-selection cursor when directly over text, and hand over clickable page elements? Or is it something you could support in a preference?

**Comment by skyjake** [comment]
This is somewhat OS/system theme dependent, since mouse cursors can be different or customized.

I do agree this could be improved, though. It is feasible to activate the I-beam cursor only over text and have the regular mouse cursor elsewhere.
