### ISSUE TITLE
Preferences: the selected section is "black on black"

### ISSUE THREAD

**Issue by mascaldotfr** [skyjake/lagrange#570]
The title says it all. 

This has been tried under a Debian Unstable installation with Lagrange 1.15, under GNOME, KDE and MATE (these 3 with their default configurations), and Xfce. The problem can be reproduced whether the DE and/or Lagrange is in light or dark mode.

![image](https://user-images.githubusercontent.com/116852972/213875451-7457d27f-7db9-4dbd-8905-9b01c29749b2.png)

**Comment by skyjake** [comment]
I'm unable to reproduce this...

Looks like Debian Unstable is using SDL 2.26.2. I'm using 2.24 on XUbuntu, maybe I'll try with 2.26 and see if there's a problem there. (EDIT: Still works fine with 2.26.2 built from source.)

Any difference if you launch the app with `--sw`?

What about `--prefs-sheet`? A window is not opened then any more.

**Comment by mascaldotfr** [comment]
> Looks like Debian Unstable is using SDL 2.26.2. I'm using 2.24 on XUbuntu, maybe I'll try with 2.26 and see if there's a problem there.

Yes, this is the current version used.

> Any difference if you launch the app with `--sw`?

None at all.

> What about `--prefs-sheet`? A window is not opened then any more.

It works as intended if I run `lagrange --prefs-sheet`

![Capture d’écran_2023-01-22_17-59-38](https://user-images.githubusercontent.com/116852972/213928785-92b65a6e-51a9-4d01-8870-cd8d9c9a0486.png)
