### ISSUE TITLE
Improper handling of AltGr modifier key

### ISSUE THREAD

**Issue by vFetet** [skyjake/lagrange#572]
# Description

The [`AltGr` key](https://en.wikipedia.org/wiki/AltGr_key) is used on some keyboard layouts (in my case, the standard French AZERTY layout) as a modifier to enter special characters.

During standard navigation, it is handled like the `Alt` key, allowing keyboard navigation, is not canonical but not a real issue.

However, when the input widget is open, pressing the `AltGr` key:

* doesn't allow entering characters requiring an `AltGr` key combination (e.g. `@` is mapped to `AltGr` + `2/é` on the AZERTY keyboard, and can't by typed in inputs)
* bypasses the `Alt` key being disabled from triggering keyboard navigation when the input widget is open, allowing keyboard navigation in the background of the widget
* if navigating to an input link (gemini 1x status code), it causes funky UI bugs (see screenshot: Lagrange window after opening an input link with `AltGr` + `number key` while the input widget is open).

![Lagrange window after opening an input link with `AltGr` + `number key` while the input widget is open](https://user-images.githubusercontent.com/43585698/214017961-ad0920eb-8b7b-494b-8f85-4a662e00827d.png)

# Expected behavior

The `AltGr` key should not trigger keyboard navigation when an input widget is active, and should allow the user to type special characters using `AltGr` key combos.

The `AltGr` key could either trigger or not trigger keyboard navigation when no input widget is active.

# System and version info

* Lagrange 1.14.2 on Windows 10
* Lagrange 1.15 on Windows 10

Note: default behavior of `AltGr` key is slightly different on Windows and Linux systems. This was not tested on Linux. 

On Window, pressing `Ctrl` + `Alt` acts as an alias for `AltGr`, an triggers the same bugs than pressing `Alt+Gr`.

The `AltGr` key is absent from Mac keyboards (including French Mac keyboards) and this issue shouldn't affect the MacOs version.

**Comment by skyjake** [comment]
Some of the issues here are because both left and right Alt keys (right Alt being AltGr on PC keyboards) are treated as equivalent, which is inappopriate.

When it comes to AltGr-combos, those are under SDL's responsibility to handle as part of Unicode text input events. I'm not sure if I own any physical keyboards with an AltGr key at the moment, but I can always do some testing with virtual keyboards in Windows.

**Comment by vFetet** [comment]
Thanks for looking into this. 

As far as I know, there is no hardware difference (except for keycaps) between keyboards, so for testing, you should be fine by setting your keyboard layout to one with an `AltGr` key (I would suggest [US-International](https://en.wikipedia.org/wiki/QWERTY#US-International) as it behaves mostly like a standard QWERTY keyboard, except for a couple of dead keys and the use of `AltGr`).

**Comment by alexlehm** [comment]
I noticed that as well, it affect the @ and ~ keys on the german keyboard which makes it necessary to copy and paste from a editor

**Comment by alexlehm** [comment]
thank you for fixing that, it is really helpful
