### ISSUE TITLE
Android: Crash on startup when opening the app and loading a page returning `1x`

### ISSUE THREAD

**Issue by vFetet** [skyjake/lagrange#573]
# Description

When opening the Lagrange Android app, the last visited page is loaded on startup. If that page causes the input widget to open, the application crashes.

# Reproduction

* Use the Lagrange Android app
* Navigate to a gemini link returning a `1x` status code, opening the input widget
* Exit the application while the input widget is open
* Open the app

# Workaround

Opening the app while on airplane mode (or otherwise disabling all internet access) causes an error page to be displayed instead of loading the link. From there, it is possible to enable internet and navigate normally.

# System info

Tested on versions 1.14 (beta11) and 1.15 (beta13) on Android 10

**Comment by skyjake** [comment]
I tried to reproduce this on an Android 9 phone and Android 12 in the emulator, but neither crashed (gemini://geminispace.info/search). I was using Lagrange Beta 14.

Does it crash for you on any query URL?

**Comment by skyjake** [comment]
Tagged as "needs testing" for when Android beta 16 is available.

**Comment by skyjake** [comment]
The expected behavior in Beta 16 is that the input prompt needs to be manually re-opened by reloading the page after the app has been launched.

**Comment by stacksmith** [comment]
I am getting consistent crashes playing Spellbinding (which uses input extensively) when my phone is switched to another app while an input field is active and some text entered.  Starting Lagrange pops up the input field momentarily then exits the app; the only way to recover is to stop the app and wipe all data (losing bookmarks, etc).

Lagrange 1.15 on Moto G Play  (2021) on Republic network.

Exact sequence causing such a crash (others possible)
* Go to Spellbinding and click on the 'guess' link;
* Enter 'aaa' but don't send
* Switch to task view and swipe Lagrange off the list
* Re-start Lagrange from icon.

On my device the input field will briefly show, then disappear as the app crashes.

ILet me know if I can hep in any way.

**Comment by skyjake** [comment]
@stacksmith Have you got the latest/current Android Beta 17 (v1.15b17)? There's a workaround where the page is not reloaded at launch unless it's cached locally, which should prevent the crash in this situation.

**Comment by stacksmith** [comment]
Is there an .apk I can sideload?  

I installed from F-DROID.  I don't have an android sdk set up...

**Comment by skyjake** [comment]
You can find the APKs here on GitHub: https://github.com/skyjake/skyjake.github.io/blob/master/fdroid/repo/lagrange_v1.15b17_phone.apk

**Comment by stacksmith** [comment]
Thanks... I will install that.
Here is a weird thing: my new Samsung tablet updated  Lagrange via FDroid, but my older Moto G Play is not showing any new updates... Hmm.

**Comment by skyjake** [comment]
Assuming this has been fixed.
