### ISSUE TITLE
finger urls are not parsed correctly

### ISSUE THREAD

**Issue by alexlehm** [skyjake/lagrange#576]
when I use a finger url on gemini, the url is not parsed correct, the same url is parsed correctly by Bombadillo
I use the following gmi code:
```
You can finger me as
=> finger://alexlehm@sdf.org alexlehm@sdf.org

```
and the resulting url is finger://sdf.org/

**Comment by skyjake** [comment]
Based on the (provisional, never finalized) [Finger URL RFC](https://datatracker.ietf.org/doc/html/draft-ietf-uri-url-finger), the correct format of a Finger URL is:
```
finger://host[:port][/<request>]
```

That is, this will work:
```
=> finger://sdf.org/alexlehm alexlehm@sdf.org
```
Do you have some link or other reference to a specification that says using the URL username component is also allowed?

**Comment by alexlehm** [comment]
I purely guessed the format and tried if it worked in bombadillo, i never checked the spec. if the official format is host/username, i will change my text

**Comment by alexlehm** [comment]
Thanks, changing the url fixed it (turns out the http://portal.mozz.us proxy does it in the exact same way)
