### ISSUE TITLE
"Maybe the server is from the future" error while using HTTP proxy — response to inline media request is a redirect

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#578]
I'm getting an odd error while trying to access a file with Lagrange while using an HTTP proxy.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/4118560/219880360-034f23b0-b732-4ee3-9e88-c7b6ea19a887.png">

To reproduce:
* Use the proxy `stargate.gemi.dev:1994`
* Got to the URL `https://cdn.atp.fm/rss/public?x0h3nk5k` (This is an RSS feed, but the Stargate proxy automatically converts it to gemtext and exposes the MP3 enclosures)
* Click on any of the Audio items

Result:
You get the error message above.

Expected:
Lagrange downloads the audio file, or plays it inline.

Extra info:
* The links to the auto files actually first return a redirect, before returning the actual file
* The URL of the URL to the mp3, as well as the redirect that's in the RSS feed are < 1024 characters, so should still work with the gemini protocol.
* At first I thought this might be a bug in my proxy, but both `gemget` and and `amfora` successfully download the when configured with the same proxy, download the file just fine

**Comment by skyjake** [comment]
Yeah this is definitely a bug in Lagrange. When doing an inline media request, it can only handle a `20` response. The `30` redirect causes the error popup, when the correct behavior would be to redo the request as told.

The workaround is to do the request without triggering the inline media player, e.g., opening the link in a new tab.

**Comment by acidus99** [comment]
Confirmed fixed in 1.15.3. Thanks
