### ISSUE TITLE
Translation translates Gemini links without protocol and breaks them

### ISSUE THREAD

**Issue by michaelnordmeyer** [skyjake/lagrange#580]
Example (EN=>DE): 

| English | German |
| ------- | ------ |
| `=> car.gmi Car` | `=> Auto.gmi Auto` |
| `=> car/ Car` | `=> Auto/Auto` |
| `=> car/index.gmi Car` | `=> Auto/Index.gmi Auto` |
| `=> car/car.gmi Car` | `=> Auto/Auto.gmi Auto` |
| `=> ./car/ Car` | `=> ./Auto/Auto` |
| `=> ./car/index.gmi Car` | `=> ./car/index.gmi Auto` |
| `=> ./car/car.gmi Car` | `=> ./Auto/Auto.gmi Auto` |
| `=> ../car/ Car` | `=> ../Auto/Auto` |
| `=> ../car/index.gmi Car` | `=> ../car/index.gmi Auto` |
| `=> ../car/car.gmi Car` | `=> ../Auto/Auto.gmi Auto` |
| `=> /car/ Car` | `=> /Auto/Auto` |
| `=> /car/index.gmi Car` | `=> /Auto/Index.gmi Auto` |
| `=> /car/car.gmi Car` | `=> /Auto/Auto.gmi Auto` |

Obviously this leads to broken links in terms of wording and spaces.

Everything before the second whitespace area shouldn't be translated.

**Comment by skyjake** [comment]
Yes, the pre-translation conversion step should definitely omit the link URLs from the translated content.

There are also known issues with translating preformatted blocks. There should probably be an option in the Translate dialog for selecting whether preformatted blocks should be translated or not.
