### ISSUE TITLE
The Split view pinning setting is reset

### ISSUE THREAD

**Issue by nerudopab** [skyjake/lagrange#585]
After each new start, the 'Preferences - General - Split view pinning' setting is reset to 'Left Tab'. On Linux/macOS/Windows.
Any other settings are fine.

**Comment by skyjake** [comment]
Thanks for reporting! This seems to be some kind of an oversight. The value of the setting wasn't being saved when quitting.

Will be fixed in the next patch.

**Comment by nerudopab** [comment]
It works in the version 1.15.5. Thank you!
