### ISSUE TITLE
Windows update does not start the program in the end

### ISSUE THREAD

**Issue by alexlehm** [skyjake/lagrange#586]
When running the Windows update, the program does not start for me after the update is finished.

I have noticed this with the current update to 1.15.5 on two computers and I think I also noticed it with the previous update to 1.15.4

**Comment by skyjake** [comment]
This is a known issue... I have set in the installer config to restart the app afterwards but for some reason it doesn't work. This hasn't seemed high enough on the priority list to investigate closer.

**Comment by skyjake** [comment]
I finally found a suitable moment to fix this. The installer will automatically close and restart Lagrange during updates, and there is a checkbox for launching the app if it wasn't running. As a bonus, the uninstaller executable is now signed, too.
