### ISSUE TITLE
Redraw Error in Page Outline with "Colorful Light" Light Theme

### ISSUE THREAD

**Issue by michaelnordmeyer** [skyjake/lagrange#587]
(Lagrange v1.15.5 on macOS Ventura 13.2.1 with macOS light theme enabled)

When having the page outline displayed and using `Colorful Light` as the light theme in `Settings > Page style`, the background of the page outline will have the wrong color on some UI actions depending on different theme seeds. UI actions can be:

- tab opening, switching, closing
- clicking on page outline, even when it is already displayed
- ...?

<img width="650" alt="wrong-background-color" src="https://user-images.githubusercontent.com/146761/226603395-b66b718d-4504-4f3d-b2c7-800e0db3eb11.png">

To reproduce:

1. Open outline for a page with a certain theme seed
2. The page outline will display the theme seed's background color (here a light blue)
3. Open another tab with homepage set to `about:blank`
4. The second page outline will display the accent color (here `Teal`) as the background color and the UI theme's background color for the empty page
5. Select the first tab again to be greeted with a two-colored page outline background, where to background color for the actual outline will have the theme's seed color, while the empty space will have the accent color.
6. Select the `about:blank` tab again and the page outline background from 4. will be collapsed to a tiny sliver, while the rest will display the first tab's theme seed background color.

If doing the above with not a blank page but a page with a different theme seed, the second page outline will display the second theme seed's background color instead of the accent color.

Depending on the combinations of tab switching, the wrong colors will change. The same goes for clicking the already open page outline button in the sidebar again.

IMHO, apart from the mismatching colors, for 3. Lagrange should not display the accent color as the page outline's background in the first place, but the UI theme's background color.

**Comment by skyjake** [comment]
> Lagrange should not display the accent color as the page outline's background in the first place, but the UI theme's background color.

In the next patch, the outline uses the normal UI colors like all the other sidebar tabs. The old outline colors were a stylistic choice left over from a time when the outline was a component in the document margin, so it matched the document colors. Nowadays it doesn't really make sense to theme the outline, and with some themes it may lead to unreadable text (e.g., Colorful Light's level 1 headings are white on a pastel background).

**Comment by skyjake** [comment]
This is the relevant commit: 85d6914
