### ISSUE TITLE
The Preference's "Tab" Selector Has No Contrast Between Text and Background Color

### ISSUE THREAD

**Issue by michaelnordmeyer** [skyjake/lagrange#588]
(Lagrange v1.15.5 on macOS Ventura 13.2.1 with macOS light theme enabled)

Lagrange's theme settings are displayed in the screenshot, and `Colorful Light` is used as the light theme in `Settings > Page style`.

<img width="722" alt="preferences-selection-color" src="https://user-images.githubusercontent.com/146761/226606948-bb5cf867-7ab9-4afe-977d-e3d0c7d63f6c.png">

If switching to Lagrange's black or dark theme, the background color of the tab or list selection will have the accent color and is readable, while for light or white it's black.

**Comment by skyjake** [comment]
Looks like the same issue as #570. For the record, I have never been able to reproduce this...

**Comment by skyjake** [comment]
And having said that, I did now manage to reproduce it, although not sure how. 😄

**Comment by michaelnordmeyer** [comment]
> And having said that, I did now manage to reproduce it, although not sure how. 😄

Interesting. I only open the preferences panel and click on the different UI theme buttons.

**Comment by skyjake** [comment]
Fixed for the next patch.
