### ISSUE TITLE
Ability to re-order tabs

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#59]
Usually this is done via drag-and-drop.

A temporary solution could be implemented via the tab context menu.

**Comment by skyjake** [comment]
A nice-to-have for sure.

**Comment by skyjake** [comment]
v1.15 finally adds keyboard actions for moving a tab left/right. The actions are also available in the tab context menu (right-clicking on a tab button). Drag-and-drop is not implemented yet.

**Comment by skyjake** [comment]
Drag-and-drop has also now been implemented for v1.15, although one cannot drag across UI splits or into another window.
