### ISSUE TITLE
Add euskara/Basque to Weblate

### ISSUE THREAD

**Issue by xabirequejo** [skyjake/lagrange#592]
Hi,

I'd like to localise Lagrange to Basque. I was wondering if you could enable the language on Weblate (UI).

Thanks

**Comment by skyjake** [comment]
Ok, I've added the new translation language. Let me know your user ID on https://weblate.skyjake.fi and I'll give you translator access rights.

**Comment by xabirequejo** [comment]
Hi,
My username is @xabi.

**Comment by skyjake** [comment]
Done. Thanks for translating!
