### ISSUE TITLE
Opening links in new tab places the tab at the end

### ISSUE THREAD

**Issue by albertlarsan68** [skyjake/lagrange#594]
Hello,

When using any browser/tab-able software, I get really tab-hungry: I open any link in a new tab.
However, in Lagrange, the new tab gets put at the end of the list, frequently making me lose track of where I was.
I would like new tabs (opened with <kbd>ctrl</kbd>+click or middle-click) open to the right of the current tab, instead of at the end of the window.

A bonus thing would be to have the <kbd>ctrl</kbd>(+<kbd>shift</kbd>)?+<kbd>tab</kbd> shortcuts work, but it is just because it is hard to get the <kbd>ctrl</kbd>+<kbd>PgUp</kbd>/<kbd>PgDown</kbd> with one hand on a keyboard with no right ctrl key.

A final note: Thank you so much for making this amazing piece of software!

**Comment by skyjake** [comment]
I was thinking of this same thing the other day. New tabs should indeed be opened next to the current tab.

**Comment by skyjake** [comment]
Included in v1.15.9.
