### ISSUE TITLE
Version 1.16 has lost support for the Alt-Gr characters on a German keyboard

### ISSUE THREAD

**Issue by alexlehm** [skyjake/lagrange#596]
After updating to version 1.16 I cannot type keys like @ or [] on the German keyboard that require the Alt-Gr. I think that worked in the previous version since it was introduced as a fix for #572

**Comment by skyjake** [comment]
Curious. I'll see if I can reproduce this.

EDIT: Yes I can. Will fix...

**Comment by skyjake** [comment]
Fixed in v1.16.1.

**Comment by alexlehm** [comment]
thank you
