### ISSUE TITLE
UI Blanks When Resized (Windows 10)

### ISSUE THREAD

**Issue by mattharwood** [skyjake/lagrange#6]
Firstly, definitely a beautiful client, thank you! :) 

The UI seems to go completely blank when resizing or maximising the window on Windows 10 (2004 - build 19041.508). Screenshot attached.

If I can help debug it, I'm more than happy to! 
![Screenshot 2020-09-17 130600](https://user-images.githubusercontent.com/502742/93468224-8ffb5080-f8e6-11ea-8911-a7b2441caa96.png)

**Comment by skyjake** [comment]
Hmm, in this blank state, if you change text size with Ctrl-Minus or Ctrl-Equals, does it fix the issue?

**Comment by skyjake** [comment]
I noticed this issue occurs when the Windows admin prompt/overlay happens while Lagrange is open. There is probably an event about GL context invalidation or something like that the app can observe and reload the glyph texture.

Changing text size was a workaround to get text showing again.

**Comment by skyjake** [comment]
Could be fixed now, should still test more in the dev branch.
