### ISSUE TITLE
Flatpak: Opening Preferences Causes a Crash

### ISSUE THREAD

**Issue by yigib** [skyjake/lagrange#602]
Launching the preferences window crashes Lagrange.

Ways to replicate:
* Click on File->Preferences 
* Use the keyboard shortcut

OS: Fedora 38
Windowing System: Wayland
Lagrange Version: 1.16.4
Flatpak Version: 1.15.4
Flatpak Origin: flathub

**Comment by skyjake** [comment]
There are some known issues with SDL's Wayland support. It is steadily improving, the unfortunately Flatpaks don't use the latest SDL releases.

I recommend using the `--prefs-sheet` command line option to disable the standalone Preferences window. You might also consider using the Lagrange AppImage releases or doing a manual build with the latest SDL.

**Comment by macifell** [comment]
I've also seen this happen and I'm not using Wayland. The failures are showing up when I try to open the preferences window. The behavior is exactly the same with `--prefs-sheet`, which doesn't seem to do anything different.

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/lagrange --file-forwarding fi.skyjake.Lagrange
Lagrange: A Beautiful Gemini Client
failed to find 000065e5 (日)
failed to find 0000672c (本)
failed to find 00008a9e (語)
failed to find 00007b80 (简)
failed to find 00004f53 (体)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 00007e41 (繁)
failed to find 00009ad4 (體)
failed to find 00006b63 (正)
failed to find 00009ad4 (體)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 000065e5 (日)
failed to find 0000672c (本)
failed to find 00008a9e (語)
failed to find 00007b80 (简)
failed to find 00004f53 (体)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 00007e41 (繁)
failed to find 00009ad4 (體)
failed to find 00006b63 (正)
failed to find 00009ad4 (體)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 000065e5 (日)
failed to find 0000672c (本)
failed to find 00008a9e (語)
failed to find 00007b80 (简)
failed to find 00004f53 (体)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 00007e41 (繁)
failed to find 00009ad4 (體)
failed to find 00006b63 (正)
failed to find 00009ad4 (體)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 000065e5 (日)
failed to find 0000672c (本)
failed to find 00008a9e (語)
failed to find 00007b80 (简)
failed to find 00004f53 (体)
failed to find 00004e2d (中)
failed to find 00006587 (文)
failed to find 00007e41 (繁)
failed to find 00009ad4 (體)
failed to find 00006b63 (正)
failed to find 00009ad4 (體)
failed to find 00004e2d (中)
failed to find 00006587 (文)
```

**Comment by skyjake** [comment]
I checked the Flathub build on my machine, and yes it does crash. (The non-Flatpak version works fine.)

I'll see what's up with this.

**Comment by skyjake** [comment]
Version 1.16.5, to be available soon on Flathub, should fix the crash.

**Comment by macifell** [comment]
I can confirm that the preferences window is now working on version 1.16.5.

Thank you @skyjake !
