### ISSUE TITLE
Scroll wheel does not function under Wayland hw rendering

### ISSUE THREAD

**Issue by kiefac** [skyjake/lagrange#612]
(Possibly related to #605?)
I am running the AUR package on KDE/KWin-wayland. Lagrange seems to be forced into very laggy software rendering to XWayland, so I set the `SDL_VIDEODRIVER` env var to `wayland` to see if it would smooth things out. While it does make Lagrange much smoother and more comfortable to use, it has the unfortunate side effect of making the scroll wheel do absolutely nothing, even in the preferences menu.
Arrow keys and PgUp/Dn still function to scroll the page. Ctrl-- and Ctrl-= still function to zoom. Scroll wheel still functions in every other application, of course.
I would assume this was some SDL-specific issue, but a quick google for "sdl wayland scroll wheel" doesn't appear to bring up anything relevant. Also, the scroll wheel works in Steam, which also uses SDL, when running with the same environment variable change.

**Comment by rnb42** [comment]
Same issue here on sway version 1.8.1 under Voidlinux

**Comment by jtietema** [comment]
Same issue with the flatpak version on Fedora 38 (Gnome edition on Wayland)

**Comment by tuomovee** [comment]
Are you possibly using multiple displays? Does the scrolling work if you move the Lagrange window to 0,0 on your leftmost display?
I encountered a similar issue on KWin Wayland session and this seems to be related to coord_MouseWheelEvent() and how SDL_GetGlobalMouseState() and SDL_GetWindowPosition() misbehave under Wayland. I don't know the Lagrange codebase enough to say what are the adverse effects for this but removing the check for mousewheel event coordinates in dispatchEvent_Window() seems to allow the scrollwheel event to be processed despite SDL being bonkers under Wayland.

**Comment by maxgira** [comment]
This issue still persists in Fedora 39, with a GNOME Wayland session, both with the RPM package from the Fedora repos as well as the flatpak version.
I can also confirm as mentioned by @tuomovee that scrolling does work on one of my monitors.
I would greatly appreciate this issue getting fixed, as Lagrange is an otherwise great Gemini browser.

**Comment by probablySophie** [comment]
I've made PR #669
Which I *think* solves the issue?

**Comment by skyjake** [comment]
Dev branch has a possible fix, although it requires SDL 2.26 or newer. Please give it a test...

**Comment by skyjake** [comment]
A potential fix for this is included in v1.18. I'd appreciate it if someone could test and confirm whether this fixes the issue.

**Comment by kiefac** [comment]
Please excuse my absence until now, I sort of fell off of my fixation on Gemini for a while. Can confirm it has been fixed on my end, still using the AUR package, KDE/kwin, and `SDL_VIDEODRIVER=wayland`. Also tested without the envvar and the lagginess is gone, though I have a feeling that's more because of the explicit sync fixes for Wayland/XWayland/Nvidia - I'm not sure if I was aware of that situation when I opened the issue.
P.S. I'm not super experienced with Git(hub) and don't know if I should be the one to close this or if we should wait for more reports, so I'll just leave this comment for now.

**Comment by maxgira** [comment]
Scrolling with the AppImage release works on both of my displays. I am running Fedora 40 with GNOME 46 on Wayland with the amdgpu driver.

**Comment by skyjake** [comment]
Sounds good, seems to be fixed then.
