### ISSUE TITLE
ctrl- shortcuts do not work when cap lock is on

### ISSUE THREAD

**Issue by delsuc** [skyjake/lagrange#613]
Hi, 

I just discovered gemini and Lagrange. I love both !
I got a bug on my Version 1.16.6 running on Ubuntu 22.04 :  most editing short-cuts (ctrl-C V A ...) do not work when caplock is on
ctrl-W works though... (did not test all of them !)

Marc-André

**Comment by skyjake** [comment]
This is somewhat of an oversight in the app's keybindings code. Caps Lock is treated as a regular modifier key, just like Ctrl/Alt/Shift, however this of course means that if one does bind some keys to it, it's more than likely that when text is being entered in some input field, Caps Lock will probably be engaged even if that's not the intention.

The intended use case was that binding Caps Lock would only be done when one has remapped the key at a lower level to something else, but Lagrange has no way of knowing that. Probably will need to make this disabled by default.

**Comment by delsuc** [comment]
I get it.
However, most of the time I enter the url in Lagrange with a copy-paste. The fact that nothing happens when CP is engaged is always is bit annoying.
As a workaround, can't you at least add the CapsLock + crtl/alt/shift test in the key binding?
Or is it too much work?  tbh, I haven't look to the code so far...
