### ISSUE TITLE
TUI: error with font archive

### ISSUE THREAD

**Issue by itsdeadguy** [skyjake/lagrange#615]
After the last error was fixed, I tried again. I got this error this time:

```
[  1%] Building C object CMakeFiles/app.dir/src/main.c.o
In file included from /home/corpse/prg/lagrange/src/media.h:25,
                 from /home/corpse/prg/lagrange/src/gmdocument.h:27,
                 from /home/corpse/prg/lagrange/src/prefs.h:27,
                 from /home/corpse/prg/lagrange/src/app.h:30,
                 from /home/corpse/prg/lagrange/src/main.c:23:
/home/corpse/prg/lagrange/src/fontpack.h:163:65: error: unknown type name 'iArchive'
  163 | iBool               loadArchive_FontPack    (iFontPack *, const iArchive *zip);
      |                                                                 ^~~~~~~~
make[2]: *** [CMakeFiles/app.dir/build.make:76: CMakeFiles/app.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/app.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Could i be missing something? or perhaps i'm using a wrong version of something?

Sidenote: I tried building this on a 32bit OpenBSD install. Worked just fine. Wonder what's the difference between that and the void linux box that gave me this error.

**Comment by skyjake** [comment]
My best guess is that there is a missing dependency and the `Archive` class in the_Foundation was excluded from the build. Check that you have the zlib devel files installed (pkg-config package "zlib").

**Comment by itsdeadguy** [comment]
That did the trick, thank you. I finally have it running, it looks and works great.
