### ISSUE TITLE
RSS feed not auto-translated to Gemini feed

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#616]
Found an RSS feed that Lagrange displays as raw text, instead of auto translating it to Gemini feed as it does with other RSS feeds.

gemini://thrig.me/blog/atom.xml

Content type is `text/xml` so perhaps this is due to the version or RDF stuff?

**Comment by skyjake** [comment]
You probably meant `gemini://thrig.me/blog/rss.xml`?

Lagrange only supports Atom feeds. Any older RSS formats are not translated to Gemini feeds.

**Comment by skyjake** [comment]
Related to #171.
