### ISSUE TITLE
Atom feed need auto-translated to Gemini feed for rendering

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#617]
Found an Atom feed that is not being auto-translated into a Gemini feed, as Lagrange often does automatically:

gemini://thrig.me/blog/atom.xml

Unless #616, this looks like a standard Atom feed so 🤷‍♀️

**Comment by skyjake** [comment]
I checked this in a feed validator:

> Sorry
> 
> This feed does not validate.
> line 2, column 0: This feed uses an obsolete namespace
> \<feed xmlns="http://purl.org/atom/ns#">

Lagrange requires the namespace to be `http://www.w3.org/2005/Atom`.
