### ISSUE TITLE
Preferences window is not a window

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#62]
This is very very minor.

On my OpenBox based desktop I am used to dragging windows with Alt+mouse.

I was a bit unhappy when I couldn't drag the preferences popup down, to the center of my screen.

**Comment by skyjake** [comment]
Sorry, multi-window support is not being planned due to the added complexity vs. the gained benefits. This is one of the drawbacks of using a custom light-weight UI toolkit.

Eventually I might get around to it, but closing this for now.
