### ISSUE TITLE
Images not rendering on macOS

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#622]
<img width="869" alt="image" src="https://github.com/skyjake/lagrange/assets/4118560/dfa17916-5d39-47c7-b715-ff8fcc2e0b85">

I'm running the latest version of Lagrange. Looking at server logs, I see the correct status code, MIME type, and bytes being sent.

**Comment by skyjake** [comment]
That is quite strange, because it works just fine for me. I tested the v1.16.7 arm64 build on Ventura, and the x86_64 build on Big Sur and High Sierra.

Are all image formats similarly broken for you? Relaunching the app or rebooting doesn't help? What is your OS version and Mac hardware?

**Comment by acidus99** [comment]
Can reproduce this. Not sure what it was
