### ISSUE TITLE
"?" Is rendered rotated with Roboto font

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#624]
I have the same issue both in lagrange mobile and desktop, on gemini://ploum.net , all question marks are rendered rotated 45°.
This only seems to happen with Roboto font, and if I copy/paste the text elsewhere it renders fine.

**Comment by skyjake** [comment]
Hmm, this is quite curious. The question marks are preceded by U+202F (Narrow No-Break Space). Apparently this NNBSP code point confuses the glyph selection.

I have no idea why this causes the glyph to be misselected by HarfBuzz, but I found a simple workaround for v1.17. Perhaps one day I'll have time for a more detailed debugging session.

**Comment by ploum** [comment]
Note: in French typography, question marks should always be preceded by a non-breaking space. (that’s why this character is there ;-) )

**Comment by skyjake** [comment]
@ploum Good to know!
