### ISSUE TITLE
Wrong dpi on iPad

### ISSUE THREAD

**Issue by trufae** [skyjake/lagrange#626]
Check the screenshot, everything looks so smol, and this is 200% zoom

![IMG_9D2DFDB663F7-1](https://github.com/skyjake/lagrange/assets/6431515/ec9909f0-44aa-4031-a146-b03dfba7961c)

**Comment by skyjake** [comment]
I think I've seen this once on iPadOS 17. The scaling was restored to normal when I force-quit the app and relaunched it. I'm guessing it's an SDL glitch.

**Comment by skyjake** [comment]
I'm closing this as it seems like an SDL or operating system level issue. I haven't seen this reoccurring on my iPad, but please do report if it keeps happening with some regularity.

**Comment by trufae** [comment]
The bug is not fixed yet. But happens only when the app is started as a floating window. if the app is started in fullscreen, then splitting or making it float works again.

So please reopen the ticket. if u cant repro i can record a video. but enotime for dev :_ 

Kudos for your hard work on this amazing app! thanks

**Comment by skyjake** [comment]
>  if u cant repro i can record a video

Please, that would help debug it for sure.

**Comment by trufae** [comment]
https://youtu.be/XrJhbGtk4VE

**Comment by skyjake** [comment]
Thanks for the video! The new build 1.17 (3) should fix this by querying iOS directly for the display scale factor. Apparently SDL reports the wrong value when launching in Slide Over.

**Comment by trufae** [comment]
Nice catch! Did you filled the issue in sdl? So eventually it can be fixed upstream too? I'll let u know if it works when i have time for testing thank you!
