### ISSUE TITLE
Lagrange-1.17.0-x86_64.AppImage requires libjack on system

### ISSUE THREAD

**Issue by shibotto** [skyjake/lagrange#627]
```
Lagrange-1.17.0-x86_64.AppImage: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory
```

This is probably related to the fix for https://github.com/skyjake/lagrange/issues/623

**Comment by skyjake** [comment]
Definitely related, yes. That library should've been bundled into the AppImage along with the rest... Have to check the manifest again.

**Comment by skyjake** [comment]
The v1.17.1 AppImage should fix this. The problem was that my SDL was built with support for JACK audio, however for some reason the AppImage builder has blacklisted the libjack shared library so it wasn't included in the distribution. I rebuilt my SDL without JACK.
