### ISSUE TITLE
Page Scrolls to Top after Refresh

### ISSUE THREAD

**Issue by juvtib** [skyjake/lagrange#628]
There appears to be a refresh regression that I first noticed in Lagrange v 1.17.0. Now, when I refresh a page, it reloads and my view moves to the top of the page. I edit Gemini pages and used to refresh to view changes. Now, when refreshing, I lose my place. I'm using the Lagrange openSUSE package. I'm not sure of when the bug first appeared. I don't see a preference setting relating to this effect, so, I assume this is a new bug. Thanks, Mike

**Comment by skyjake** [comment]
I think I've seen this issue myself. It is definitely a regression.

**Comment by juvtib** [comment]
FYI 

> Fixed scroll position being reset when reloading the page.

* [Release v1.17.1 · skyjake/lagrange](https://github.com/skyjake/lagrange/releases/tag/v1.17.1)
