### ISSUE TITLE
Page search disables links when match lies outside visible area 

### ISSUE THREAD

**Issue by marococo** [skyjake/lagrange#629]
When searching via find bar for an item matched outside the visible part of a page links cease to be clickable. Only after scrolling they become clickable again.

Example: I search for "voice" when at the top of [gemini://gemi.dev/cgi-bin/waffle.cgi/](url). Lagrange will correctly jump to the match at the bottom of the page but nothing will happen when I click a link.

(Lagrange-1.17.0-x86_64.AppImage, Linux)

**Comment by skyjake** [comment]
Thanks for reporting! Fixed for v1.17.1.
