### ISSUE TITLE
View as plaintext persists after page reload

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#630]
Steps to repro (on macOS, v1.17.0)

1. Right click on a gemini page, click "View as Plaintext".
2. Refresh the page or navigate to a different URL.
3. The new page loads as gemtext.
4. Right click on page, and the option still says "View as Gemtext" instead of "View as Plaintext".

<img width="889" alt="Screenshot 2023-10-18 at 1 32 02 PM" src="https://github.com/skyjake/lagrange/assets/5026795/264ec340-c05f-4405-a8b1-f3908725f312">

**Comment by skyjake** [comment]
Thanks for reporting! Fixed for v1.17.1.
