### ISSUE TITLE
"Incomplete Header" message on all sites

### ISSUE THREAD

**Issue by audiodude** [skyjake/lagrange#636]
Just upgraded to 1.17.2 via the built in macOS upgrade mechanism.

Environment:

macOS Ventura: 13.3.1
Lagrange: 1.17.2

Steps to reproduce:

Open Lagrange and navigate to any Gemini site.

Expected result:

The site loads.

Actual result:

<img width="900" alt="Screenshot 2023-10-30 at 13 21 40" src="https://github.com/skyjake/lagrange/assets/57832/fbfc11a6-2780-4f33-a4a8-2b2cfe6abaa9">

<img width="899" alt="Screenshot 2023-10-30 at 13 21 48" src="https://github.com/skyjake/lagrange/assets/57832/724399de-a681-4919-87ce-65c21aab416b">

Tested on a site I control and one I don't.

**Comment by skyjake** [comment]
Is this the arm64 or Intel build?

If you downgrade to a previous release, does that fix the problem?

If you change your network, for example by tethering to a phone, does it affect the issue?

**Comment by audiodude** [comment]
Just checked again and it's working now, though I haven't changed anything. Sorry for the false alarm!
