### ISSUE TITLE
double url-encoding of spartan links

### ISSUE THREAD

**Issue by teepark** [skyjake/lagrange#637]
I ran into this porting a git viewer to spartan, which uses `/<hash>^/` URL segments. The special character ^ in that URL segment isn't getting encoded to `%5E` properly as it does in gemini links, but rather to `%255E`, which is the _url encoding_ of `%5E`.

A minimal reproduction is to visit this text/gemini page via spartan:
```
=> ./here^.gmi Click here
```
and click the link.

The URL it attempts to load is `spartan://localhost/here%255E.gmi/`

**Comment by skyjake** [comment]
I did as instructed with Lagrange v1.17.2 on macOS, but it appears to work correctly. Mozz's reference server says:

```
2023-11-04T18:20:07.412775 "localhost /here%5E.gmi 0"
```

Could you add some details about your app version and operating system?

**Comment by teepark** [comment]
I just verified it was an issue in the server I was using, sorry about that. FWIW I did check this against bombadillo where this example appeared to work, but it turns out that client doesn't escape urls at all.
