### ISSUE TITLE
Titan Upload Size

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#640]
When I was writing my own Titan server, I noticed something about the requests that lagrange gives. The data size in bytes in the titan request (which was 1216) is different from the size listed in the bottom left corner of the Titan edit popup (which showed 1906).

**Comment by skyjake** [comment]
My guess is that the final number of bytes written is not being updated in the UI, just the intermediate values before the request has completed.

Tagging as a bug although this is more of a UI glitch than a serious issue.
