### ISSUE TITLE
Non-typical "Fingerprint" language used in Page Information

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#645]
Lagrange currently has a "Copy Fingerprint" button under a "Certificate" section of the "Page Information" model. Lagrange uses this to mean the SHA-256 hash of just the bytes of the public key, contained inside the certificate.

This is very confusing because that is not the typical definition of the term "Fingerprint", when used in the context of X.509 certificates. The overwhelming majority of software that handles or displays certificates use the "fingerprint" terminology to mean "a hash of the entire certificate." Examples of software that use this typical definition are:

* macOS (in all OS-wide certificate controls, Safari, etc.)
* OpenSSL (via the `-fingerprint` argument)
* Firefox (in it's Certificate details view)
* Windows (in all OS-wide certificate controls, Edge browser, IIS, though it uses "thumbprint" instead of "fingerprint")

Please consider changing Lagrange's terminology to avoid this confusion. A few options:
* Add a "Public Key" section to the "Page Information" Model that displays the hash function (SHA-256) and value for the public key
* Change the button text to say "Copy Public Key Fingerprint" or "Copy Public Key SHA-256 Hash"

**Comment by skyjake** [comment]
I agree this needs some clarifying.

**Comment by skyjake** [comment]
Implemented for v1.18.
