### ISSUE TITLE
Optional setting to dismiss TLS warnings

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#646]
Hope you are doing well!

When surfing through gemini, especially when visiting older capsules that are no longer updated, I run into certificate warnings fairly often. It's not the end of the world but it's annoying to be forced to go through the motions for something that I don't care about.

This is a feature request for an opt-in setting in Lagrange that will

- bypass all TLS warning screens
- hide all "Security Issue" banners

If the certificate is not trusted by Lagrange, the URL banner can still show the warning icon instead of the green lock. I think it makes sense to have that there regardless, and it doesn't disrupt anything.

**Comment by skyjake** [comment]
Seems like a reasonable option, yes. I'll add it to the v1.18 to-dos.

**Comment by skyjake** [comment]
Implemented for v1.18.
