### ISSUE TITLE
Compilation question

### ISSUE THREAD

**Issue by d47081** [skyjake/lagrange#647]
Hello 

I have compiled Lagrange from master but have this in left top corner

![image](https://github.com/skyjake/lagrange/assets/108541346/157cccbb-8b62-4950-a59b-c0889d542343)

is the debug and how to disable?

**Comment by skyjake** [comment]
That means you are running a debug build. You need to reconfigure the build with the option `-DCMAKE_BUILD_TYPE=Release`.

**Comment by d47081** [comment]
Thank for reply, just missed `-` in the command:

`cmake /lagrange  DCMAKE_BUILD_TYPE=Release`
`cmake --build .`
