### ISSUE TITLE
Search bar UX improvements

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#65]
Currently:

- search bar searches through invisible link URLs without visual clues,
- does not indicate that no results were found
- appends text instead or replacing when re-opened

I suggest just stealing the UI and UX from something well developed (e.g. Firefox text search bar).

**Comment by skyjake** [comment]
The first item is already fixed in v0.10.

The other two would be nice to have.

**Comment by skyjake** [comment]
* Should mark the whole previous input field contents selected when opening the search bar.
* Should unfocus and dismiss the search bar with one Escape keypress.
