### ISSUE TITLE
Chinesian chars?

### ISSUE THREAD

**Issue by d47081** [skyjake/lagrange#652]
![image](https://github.com/skyjake/lagrange/assets/108541346/bc122f51-af76-47bf-885c-7f220faa512b)

**Comment by d47081** [comment]
Found answer here
gemini://skyjake.fi/fonts/

but would be nice to have this support from the box

**Comment by skyjake** [comment]
This would be fixed by relying on already-installed system fonts. There is an existing issue about that: #195

Also see this comment: https://github.com/skyjake/lagrange/issues/471#issuecomment-1084601140
