### ISSUE TITLE
Trailing whitespace in domain name is URL encoded

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#656]
I noticed that if you have trailing whitespace in the domain name, it gets URL encoded

If you put this URL into the address bar: `gemini://gemi.dev ` Lagrange converts the trailing space into `%20`, creating the invalid domain name `gemi.dev%20` and displays an error:

<img width="784" alt="image" src="https://github.com/skyjake/lagrange/assets/4118560/e023a254-1ef3-4e7d-9c41-fdbfa568cd7b">

I noticed this while copy+pasting a URL, which seems like a common probably where whitespace might accidentally get copied.

Consider having Lagrange to trim trailing whitespace off the URL. If you don't want to do this (so that people could have a file reachable at `gemini://example.com/%20` then consider trimming whitespace where it would not be allowed. In this case, in the domain name.

**Comment by skyjake** [comment]
I think it wouldn't hurt to trim whitespace from text pasted into URL fields. IIRC that's already done in the mobile ports. Maybe the URL handling code could simply reject domain names with illegal characters like whitespace.

**Comment by zzo38** [comment]
I think it makes sense to trim spaces at the beginning and end of the URL. If you deliberately want a space at the beginning or end of a URL, you can type `%20` instead.
