### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by d47081** [skyjake/lagrange#657]
Is webp supported?

I found few closed issues but with version `1.17.6` this does not work

![2024-03-12_18-42](https://github.com/skyjake/lagrange/assets/108541346/cd567048-99bc-4be1-a1cd-1308770e1390)

**Comment by skyjake** [comment]
WebP is supported, however it is an optional build dependency. I have included WebP decoding in most of the binaries available here on GitHub and in the mobile builds.

Which build are you running?

**Comment by d47081** [comment]
Hm, I don't remember, suppose the build from this repo, master branch - it's correct?

Doubts maybe the app issue, but `image/png` works well there, e.g. 
`gemini://kevachat.duckdns.org/raw/NZGczWYDgewMqLm5PL5STiwbX5UJN5XD42`

Could you please check this `image/webp` one on your build:
`gemini://kevachat.duckdns.org/raw/NQdN6x4g4tEXRp3M6yfQdqqoZHUkS4bbs3`

Maybe just incorrect meta headers / MIME type..

p.s. I'm using build on Debian 12, i3wm so also maybe I forgot to install some dependency to support this format in system environment, just not sure how does it work exactly, seems it work before (on Ubuntu), but now I can't open.. maybe not browser issue

**Comment by skyjake** [comment]
The binaries are built out of the "release" branch but currently the main branch is pretty much equivalent to release.

Your linked image does work for me (in the iOS mobile build, at least):
![Screenshot 2024-03-12 at 21 16 25](https://github.com/skyjake/lagrange/assets/1225742/5e57c0c5-6f97-420f-8a80-87fd86628ba0)

**Comment by d47081** [comment]
Hm, thanks.. let me check it from release binaries, maybe that's really some system dependency that I forgot to install (because webp is ~newest format, maybe just debian want some lib to render that inline)

**Comment by d47081** [comment]
Yes, it works in `appimage`

I found that forgot to compile with [ENABLE_WEBP](https://github.com/skyjake/lagrange?tab=readme-ov-file#build-options):

```
cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_WEBP=YES
```

Just why not to enable `webp` by default?
