### ISSUE TITLE
Add "Download Linked File" in context menu for all links

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#66]
I was trying to download the mp3 files from _Konpeito_, but had to open each of them individually in a new tab, stop the playback and then press `Ctrl+S`.

Could you add another item to the link context menu?

**Comment by skyjake** [comment]
Saving inline media to Downloads is available in v0.10, although the file has to be first fully downloaded.

In the short term, I have no plans to implement file save/open dialogs because that needs platform-dependent code for accessing the native UI frameworks.

**Comment by emilis** [comment]
You could add "Save link to Downloads" to context menus.

That would not require the platform-dependent code and could work before the file is fully downloaded.

**Comment by johnwcowan** [comment]
Thumbs up.

**Comment by skyjake** [comment]
Done for v1.2.
