### ISSUE TITLE
"Incomplete header" on capsule that works with other browsers

### ISSUE THREAD

**Issue by jphastings** [skyjake/lagrange#664]
Hi folks! I've deployed a capsule to _gemini://byjp.cc_, but Lagrange shows an "Incomplete Header" error when I visit it on my mac (v1.17.6), on iPhone (v1.17 (9) 2024-04-20).

This capsule works as expected using [amfora](https://github.com/makew0rld/amfora) (`amfora gemini://byjp.cc`), and works "manually" (with `openssl s_client -crlf -connect byjp.cc:1965`, typing "gemini://byjp.cc" and hitting return).

What's _really_ weird is running the [docker container](https://github.com/by-jp/www.byjp.me/blob/main/Dockerfile) locally, instead of [with fly.io](https://github.com/by-jp/www.byjp.me/blob/main/fly.toml) which is what's serving the production capsule, seems to be fine (using the same keys, and using `/etc/hosts` to point that domain to localhost).

I'd think this is a problem with how I've set up fly.io to serve my container, but amfora and openssl working seem to imply this isn't the case. I've checked the output from the openssl command to the fly.io hosted agora container and the locally served agora container, and they seem as identical as I think they need to be.

Any ideas? Is there a debug mode for Lagrange that would let me see the request/response text to debug further? What am I missing?

<details>
<summary>A guide for building my container locally, if anyone wants to try</summary>

I don't think it'd be necessary, but you can try the build locally yourself if you like (⚠️ it's a substantial git repo of ~240MB, even shallow; and the rust builder container for amfora is ~500MB). The following assumes you have [taskfile.dev](https://taskfile.dev), [gohugo.io](https://gohugo.io), [pagefind.app](https://pagefind.app), [docker](https://docker.com) installed locally.
```bash
# Show my fly.io served capsule is broken (assumes macOS)
$ open /Applications/Lagrange.app "gemini://byjp.cc"

# Clone my repo, as little as is necessary
$ git clone --depth=1 https://github.com/by-jp/www.byjp.me.git

# Build my capsule, removing the parts meant for HTML servers
$ task build gemini-reduce

# Build the docker container
$ docker build -t byjp.cc .

# Run the docker container locally as a daemon
$ docker run -d -t -p 1965:1965 byjp-cc

# Add my domain to your /etc/hosts file, as a quick hack
$ echo "\n127.0.0.1 byjp.cc" | sudo tee -a /etc/hosts

# Check your machine is hitting localhost for my domain
$ ping byjp.cc
PING byjp.cc (127.0.0.1): 56 data bytes

# Use amfora to check the local capsule is working
$ amfora gemini://byjp.cc

# Open your locally served capsule locally (assuming macOS)
$ open /Applications/Lagrange.app "gemini://byjp.cc"
```

</details>

**Comment by skyjake** [comment]
When I try to connect to your server manually with openssl, I get this:
```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 299 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```
Something appears wrong here on your end... Have you tried connecting to your server from outside your local network, for example via a tethered phone, through a VPN, from a VPS, etc.?

**Comment by skyjake** [comment]
>  Is there a debug mode for Lagrange that would let me see the request/response text to debug further?

There is no such mode, unless you rebuild the app (and the_Foundation) with debug messages enabled. However, since the problem can be reproduced without Lagrange, this appears unnecessary.

**Comment by jphastings** [comment]
Great spot — my local network, or more likely something that affects terminal applications on my mac, is doing… _something_ that's making my fly.io server look like it works when it doesn't.

I really appreciate the quick reply! I'll investigate and post here in case there's something stupid or weird that others may benefit from. Thank you!

**Comment by jphastings** [comment]
🤦‍♂️ I should have searched the fly.io forum; it [looks like](https://community.fly.io/t/troubles-w-hosting-gemini-server-from-fly-io/14941) the shared IPv4 addresses they use prevent TCP-only apps like Agate from working correctly with in-app TLS termination.

Running `fly ips allocate-v4`, accepting the $2/mo fee, and removing the shared IP address from my app fixed the issue 😊 

Thanks again @skyjake!
