### ISSUE TITLE
Unable to open context menu while an mp3 is playing

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#67]
Steps to reproduce:

- open a Gemini mp3 link (e.g. from Konpeito).
- right-click anywhere on page.

Result:

- the context menu(s) appear and momentarily disappear.

Expected result:

- the context menus keep opened while the sound file is playing.

**Comment by skyjake** [comment]
Which version of Lagrange are you using? d81caf1798335a8e6a4608cf750f1b5f2eddd5a6 included in v0.10 should've fixed this, and it Works For Me™.

**Comment by emilis** [comment]
I upgraded to v0.10 (`release` branch) and it seems to be fixed.
