### ISSUE TITLE
Bug in Titan: sends an empty request on startup

### ISSUE THREAD

**Issue by bleonard252** [skyjake/lagrange#671]
On occasion (after crashing?), if the current tab is set to a Titan URI, on startup it may send an **empty** request to that Titan URI, with no token and no body, which causes the receiving server to delete or empty the file it was previously looking at.

**Comment by skyjake** [comment]
The correct behavior here would be that tabs with a Titan URI are never restored (reloaded) at launch, because they are upload operations.

A similar issue can occur when navigating back and forward in history.
