### ISSUE TITLE
When ENABLE_TUI=ON building clagrange links with static ncurses

### ISSUE THREAD

**Issue by etam** [skyjake/lagrange#683]
Version: 1.18.0
OS: Linux

I tried `cmake -DENABLE_TUI=YES`. I have ncurses as shared libraries provided by distro.
Building failed, because at linking stage there was:
```
[ 99%] Linking C executable clagrange
/usr/bin/cmake -E cmake_link_script CMakeFiles/tuiapp.dir/link.txt --verbose=1
/var/lib/build/ccache/bin/cc [...] -Wl,-Bstatic -lncursesw -ltinfo -Wl,-Bdynamic
/usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: cannot find -lncursesw: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/14/../../../../x86_64-suse-linux/bin/ld: cannot find -ltinfo: No such file or directory
```

It's probably because sealcurses is build as a static library. The build system thinks its dependencies also needs to be statically linked.

**Comment by skyjake** [comment]
I'm changing the build so that ncurses is only linked statically if the ENABLE_STATIC setting is ON.

**Comment by skyjake** [comment]
v1.18.1 includes the fix mentioned above.
