### ISSUE TITLE
tui is unreadable

### ISSUE THREAD

**Issue by talmage** [skyjake/lagrange#684]
I built the TUI from source (commit 551969d1154579e03d5f42a12d28e29d084ab110) on Pop! OS 22.04 according to the instructions in README.md  The resulting TUI runs but isn't readable.  

For example, the screenshot shows the main window with the right panel open.

![Screenshot_20240927_173509](https://github.com/user-attachments/assets/99cc19bc-3b21-4f74-ad95-960443330b95)

You can see that the skyjake.fi content isn't rendered correctly.  It is shifted to the left and cut off vertically.   The content of the right panel is unreadable.

This behavior is consistent no matter which lagrange theme I choose or which terminal emulator I use.

I also compiled the TUI for PostmarketOS (with SwayWM) on my PinePhone.  It, too, behaves this way in foot, the terminal emulator.

**Comment by skyjake** [comment]
This looks very much like the issue that was fixed by https://git.skyjake.fi/skyjake/sealcurses/commit/d5de692cd6df0c389e5705a9f2323a97162eb266

That fix will be included in the upcoming v1.18.1. If you want, you can test it by compiling from the dev branch.

**Comment by talmage** [comment]
That definitely fixes the problem.   Thanks!
