### ISSUE TITLE
Shadow/border around flatpak Lagrange

### ISSUE THREAD

**Issue by KrisZane** [skyjake/lagrange#685]
Hey skyjake,

absolutely love the product you have made, it is no small feat.

I stumbled on what I assume might be a bug of sorts, the edge around Lagrange on Fedora, from flatpak has a quite wide shadow border of what I estimate to be 25-50 pixels, that is a part of the window.

That makes window resizing hard, as the edge is actually beyond the visible edge, but it also sometimes makes it hard to quick click a program behind it.

The problem may also be exacerbate on my pc, as I am only running 1080p resolution, so if it is a set pixel size, my gap would be 2-4x larger than what most people see.

![image](https://github.com/user-attachments/assets/fd5c097c-cda6-4b51-8191-21bf9a6a1d84)

**Comment by skyjake** [comment]
I'm not sure if the border around the window, on the outside, is something that applications can control. Seems like a window compositor feature? Which desktop environment and compositor are you using?

**Comment by KrisZane** [comment]
@skyjake I am using gnome on Wayland. I don't have shadows/drop borders on any other windows. :)

**Comment by KrisZane** [comment]
Sorry, misclick.

**Comment by KrisZane** [comment]
@skyjake You are most likely right, I just tested this on some other windows and it seems a lot of windows that are foregoing the built in menu's, has this to some extent.

Firefox:
![image](https://github.com/user-attachments/assets/a72e0ba2-fdbd-4fdb-bdee-37ac009acee4)
 
 I'll go report it with Gnome, as I think that may be the perpetrator here.
