### ISSUE TITLE
clagrange now is always light background and black text

### ISSUE THREAD

**Issue by roughnecks** [skyjake/lagrange#688]
Hello,
just installed clagrange on my shell, but UI is like this, doesn't matter what theme I choose:

https://i.imgur.com/3qaCeif.jpeg

```
echo $TERM
screen-256color
```
Am I doing something wrong? Thanks

**Comment by roughnecks** [comment]
This is with 1.18.0

https://i.imgur.com/PlnAJdk.jpeg

**Comment by skyjake** [comment]
Looks like the fix for the cursor color on empty backgrounds broke the background coloring for the whole screen in some TERM environments. I'll investigate what exactly went wrong with it...

**Comment by skyjake** [comment]
a840ab69 should fix this. It was simply using the wrong color for background clearing in reduced (<256) color modes. I'll do another build.

**Comment by skyjake** [comment]
Version 1.18.3 is available and should fix this.

**Comment by roughnecks** [comment]
yes, thanks!
