### ISSUE TITLE
XMPP PubSub

### ISSUE THREAD

**Issue by sjehuda** [skyjake/lagrange#692]
Please add support for XMPP.

By adding support for XMPP, I namely mean to [Atom Over XMPP](https://blasta.woodpeckersnest.eu/help/about/xmpp/atomsub) (XEP-0277 and XEP-0472) which is utilizing XEP-0060: Publish-Subscribe (PubSub) which allows to host "rich" content on XMPP.

This is a visual demonstration to prove that subject matter https://video.xmpp-it.net/w/vNqcMooy3pqRAZ8Yb8grr1

[Rivista XJP](https://git.xmpp-it.net/sch/Rivista) is an HTTP gateway to deliver posts from the XMPP network.

See also:
- https://xmpp.org/extensions/xep-0060.html
- https://xmpp.org/extensions/xep-0277.html
- https://xmpp.org/extensions/xep-0472.html
- https://blasta.woodpeckersnest.eu/help/about/xmpp/pubsub
- https://join.movim.eu/

For example, the journal at https://mov.im/blog/edhelas is not hosted at mov.im; rather, it is hosted inside an account at XMPP server movim.eu which is conveyed by the Movim instance at mov.im.

Please join to JDev group chat if you want more help or information https://search.jabber.network/search?q=jdev

**Comment by skyjake** [comment]
This does not seem to be within the scope of the project.

**Comment by sjehuda** [comment]
> This does not seem to be within the scope of the project.
> 

I would argue, and state that:

XMPP PubSub has a structural form. Each node contains items and each
item is represented by an ID (i.e. Item ID).

The standard by which Atom Over XMPP is designed is Atom Syndication
Format, which is parsable by Lagrange.

I have made a plugin for Dillo to handle XMPP PubSub.

https://lists.mailman3.com/hyperkitty/list/dillo-dev@mailman3.com/thread/JF6NB5UXXYB6D7GYCAD5FDZ6WTLFQJBO/

This is indeed a start of observation, and I am waiting for
feedbacks from the people of the Dillo community.

In what circumstances may I raise this subject matter again?

**Comment by sjehuda** [comment]
The link is

https://lists.mailman3.com/hyperkitty/list/dillo-dev___mailman3.com/thread/JF6NB5UXXYB6D7GYCAD5FDZ6WTLFQJBO/

Replace ___ by @
