### ISSUE TITLE
Segfault when popen errors due to missing error handling

### ISSUE THREAD

**Issue by sertonix** [skyjake/lagrange#694]
When the `popen` call in [`lib/sealcurses/src/video.c#L45`](https://git.skyjake.fi/skyjake/sealcurses/src/commit/700f9b10b84a86e95f9981a5618202c29446c967/src/video.c#L45) errors it returns `NULL`. Since there is no error checking the `NULL` is passed to `fgetc` and can cause a segfault (at least on musl libc).

(Hope this is enough information to fix the issue.)

**Comment by skyjake** [comment]
Seems easy enough to fix. I'll include this in the next patch.
