### ISSUE TITLE
Android: edge swipes conflict with gesture navigation

### ISSUE THREAD

**Issue by vzsg** [skyjake/lagrange#696]
Hi. First of all, thank you for this amazing app. It's a blast to use on all kinds of screens.

I found some weird behavior on Android when gesture navigation is enabled with the app's default settings.

Swiping on the edge of the screen starts the built-in navigation, but when the system's back gesture kicks in, it gets canceled _and_ the app falls into an inconsistent state. 

The old page is still on top of the screen (albeit a bit translated to the side), but the address bar is showing the underlying page, and that page reacts to scroll and other events.

For example, here's a screenshot:

![Screenshot_20241123-181420](https://github.com/user-attachments/assets/654f2393-ecb3-45b0-8b08-1bb0b6d2b1df)

This was pretty confusing until I found in another issue that "Swiping from edge" can be disabled in the UI settings, a place I wouldn't have otherwise visited. Or that swiping in the middle of the screen can dismiss the stuck panel.

---

I believe that to avoid this, the app should either:
- Disable the from edge gestures automatically if gesture navigation is enabled. In theory, it [should be possible](https://stackoverflow.com/a/76872801/3952680) to detect this, starting with Android API level 30.
- Handle the touch cancellation when the system gesture kicks in, and revert the halfway done navigation.
- Start with edge gestures disabled on Android. That would align the app with Chrome's behavior: back gesture or back button to go back, depending on the system setting.

What do you think?

**Comment by skyjake** [comment]
I opted to change the Android defaults to disable edge swipes, which then should fall back to the system Back action being issued and handled.

I have no idea how widely edge swipes are supported on Android devices, though.

Thanks for reporting!

**Comment by vzsg** [comment]
Thank you!

I don't know how popular gesture navigation is among all Android users either. But since it was introduced in Android 10, most phones out in the wild at least support it. Android 9 and below marketshare seems to be around 10-15% on various stats sites.
