### ISSUE TITLE
(UX improvement request) Make all UI buttons rounded

### ISSUE THREAD

**Issue by hardBSDk** [skyjake/lagrange#697]
Like web browsers.

![image](https://github.com/user-attachments/assets/844be9b8-42c9-4f2c-8eea-58adfc0e0ec2)

**Comment by skyjake** [comment]
The UI appearance is as intended. The point is not to emulate any existing platform or application.

**Comment by hardBSDk** [comment]
@skyjake Keep in mind that existing softwares or platforms have good UI/UX design.
