### ISSUE TITLE
(UX improvement request) Move the top menu items to a list in a 3-dot button

### ISSUE THREAD

**Issue by hardBSDk** [skyjake/lagrange#698]
Like web browsers.

![image](https://github.com/user-attachments/assets/61686fda-3b8c-48b8-b96c-6871eff6cebe)

![image](https://github.com/user-attachments/assets/d40db02b-869c-41bf-be4c-72cf9aeecead)

**Comment by skyjake** [comment]
Go to Preferences > Appearance and disable the "Menu Bar" toggle. This hides the menu bar and gives you a single button instead.
