### ISSUE TITLE
Lagrange segfaults continuously in Linux

### ISSUE THREAD

**Issue by jcromero** [skyjake/lagrange#70]
Recently built dev branch and I get:
 
```
lagrange: ../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
```

when navigating through a lot of pages. Not always, but yes with a high frequency.

**Comment by skyjake** [comment]
Which git commit did you build?

Did you remember to also update git submodules?

**Comment by jcromero** [comment]
commit 8df6eb8425651b72a4940ba18ddd1ee206158eab

Yes, I did `git pull --recurse-submodules`

**Comment by skyjake** [comment]
Thanks. I've been off Linux for the week, so something may have broken. Let me take a look...

**Comment by jcromero** [comment]
If you need me to test something, tell me.

**Comment by skyjake** [comment]
I am able to reproduce this under Ubuntu 18.04. Looks a like a bug in the recent changes to the_Foundation's address.c.

**Comment by skyjake** [comment]
Please test now with a0ebb6485cf81468c41ccc68f91dbe8018e1c0a7.

Quite surprised this worked just fine on macOS and Windows... It was basically trying to lock/unlock a random memory location as a mutex.

**Comment by jcromero** [comment]
Working fine, now. Thanks.
