### ISSUE TITLE
Numbered links stay on after switching apps

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#71]
Steps to reproduce:

- Switch from Lagrange to another app via `Alt+Tab`.
- Switch back to Lagrange.

Result:

The links are now numbered.
They stay numbered, no matter how you switch back (both `Alt+Tab` and via other methods).
They stay numbered between page reloads and navigating to pages in the same tab.
They disappear on scroll or switching tabs.
They disappear on pressing and releasing `Alt`.

Expected result:

- Numbered links do not stay on after switching out of the app.
- Numbered links do not stay on after navigating to a different URL.
- Numbered links do not stay on after reloading the page.

**Comment by emilis** [comment]
I think this bug is one of the reasons I was so confused by the variety of the link icons -- they were unexpectedly changed for me when returning to the app :laughing:

**Comment by jcromero** [comment]
Fixed in dev branch

**Comment by skyjake** [comment]
3b0e44c should take care of all three of the expected cases.
