### ISSUE TITLE
Server certificate problems should be communicated prominently

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#72]
Steps to reproduce:

- Open a page on a new domain.
- Re-generate the certificate used by the domain (on the Gemini server).
- Open another page / reload the page on the same domain.

Result:

- Lock icon (left of the URL input) becomes orange.
- Certificate status is shown as matching and not expired, but "Not trusted".
- No further information is available.

Expected result:

- A very obvious and visible indication that there may be a security issue.
- More detailed information about the certificate mismatch (comparison of two certificates?).
- Instructions for non-advanced users on what to do.

Note: popular web browsers replace the whole page with a warning view in similar cases.

**Comment by emilis** [comment]
One more thing: the orange color of the lock icon somewhat matches the orange color used by the light theme:

![naujenai-cert-in-lagrange](https://user-images.githubusercontent.com/41564/100522233-e96ae000-31b1-11eb-944c-f3f9a56f6d50.png)

So it just seems like a normal-state-and-not-a-warning UI.

**Comment by emilis** [comment]
One more option would be to invert the colors of both the lock icon and the URL input (e.g. white on red). This could work for the color-blind users too.

Although replacing the whole page with a warning may still be the least problematic option.

**Comment by skyjake** [comment]
> One more thing: the orange color of the lock icon somewhat matches the orange color used by the light theme:

Good point. I prefer to use dark mode myself so have missed this detail. This needs to be prominently displayed in all UI themes.

**Comment by emilis** [comment]
Gemini spec says the following on this matter (4.2):

> On all subsequent connections to that hostname, the received certificate's fingerprint is computed and compared to the one in the database. If the certificate is not the one previously received, but the previous certificate's expiry date has not passed, the user is shown a warning, analogous to the one web browser users are shown when receiving a certificate without a signature chain leading to a trusted CA.

https://gemini.circumlunar.space/docs/specification.html

**Comment by skyjake** [comment]
Here's a preview of what I'm working on:

- The new warning banner appears at the top of the page if there is a certificate trust issue.
- The orange-on-white lock icon has been replaced with a warning symbol.

When it comes to certificate fingerprints, would it be useful to easily copy them to the clipboard for example?

<img width="1048" alt="Screen Shot 2020-12-02 at 16 01 15" src="https://user-images.githubusercontent.com/1225742/100882315-b5e0cc00-34b7-11eb-9866-e3ea9867d0bc.png">

**Comment by emilis** [comment]
This is much much better than just the color of the icon. I think the banner placement is good, even if it may get confused with page content -- it will not get ignored.

The contrast for the warning text seems a bit lower than for the page text and the color scheme doesn't exactly say "Warning!" :smile: .

Also this looks like it could be expanded in the future with more functionality (review both certificates, check with some observatory, accept the new one, etc. ).

I think it would be really useful to be able to get the problematic certificate details somehow. Maybe add them to the Certificate Status dialog?

**Comment by skyjake** [comment]
Thanks for the improvement ideas! I'll close this issue but keep working along those lines. I'm thinking the Certificate Status should be expanded into a more general-purpose Page Information dialog. Then it would be natural to put more info/tools in there.
