### ISSUE TITLE
Showing decoded URLs in address bar

### ISSUE THREAD

**Issue by blksprt** [skyjake/lagrange#73]
This might be a contentious issue, but how do you feel about showing the decoded versions of URL encoded URLs in the address bar, and possibly even automatically encoding URLs with characters outside the valid range of characters?

As an example, a URL with the path `/%e5%a5%a5%e4%bb%98` currently shows up exactly like that in the interface - with this change it would be displayed as `/奥付` but the encoded version would still be used internally, sent to the server etc.

(A number of web browser seem to use this pattern, at least for most characters outside of the set of valid URL characters - spaces mostly still show up as `%20`)

**Comment by skyjake** [comment]
I can see the UX benefits of this, but allowing any Unicode characters to display in decoded form seems a little iffy. Might be doable if only certain subsets are allowed, like the CJK glyphs.

**Comment by blksprt** [comment]
Confining it to subsets like CJK glyphs definitely sounds like a good idea (although I'd love to to see emoji included as well, just for fun 😂)

I suppose a related issue is how internationalized domain names are handled. I've got a gemini server running on `蛸.jp`, aka `xn--td2a.jp` but I'm not sure if any gemini browsers currently allow the first form...

**Comment by alyssarosenzweig** [comment]
See also https://en.wikipedia.org/wiki/IDN_homograph_attack

**Comment by skyjake** [comment]
Working on IDN support...

<img width="537" src="https://user-images.githubusercontent.com/1225742/101940636-7456cc00-3bef-11eb-935a-4aa253ba62fd.png">

**Comment by skyjake** [comment]
...and Unicode in the rest of the URL.

<img width="727" src="https://user-images.githubusercontent.com/1225742/101981101-24b9e400-3c73-11eb-97c6-6b1e5758d15f.png">

Having thought about this for a while, I'm on the side of just allowing all of Unicode to show up. The Gemini spec supports UTF-8 URLs with no limitations. Homographs notwithstanding, I think this is the right way to go for both i18n and simplicity, in the sense of not having special exceptions and hidden rules.

I will add a preference for disabling the URL decoding, if someone wants to enjoy their percent-soup. 🙃
