### ISSUE TITLE
Window stops responding when doing some actions while attempting to connect to a server that doesn't respond

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#74]
Type: Bug

Summary: Lagrange stops responding when doing some actions while attempting to connect to a server that doesn't respond to TCP SYNs.

Build environment: Debian Buster, x86_64

Build date: 2020-11-29 19:30 UTC

Source: From that git repository. Used build instructions on https://github.com/skyjake/lagrange#how-to-compile

Reproduction scenario:
1. Open tab (press Ctrl-T)
2. Visit gemini://auriga.luthienstar.net/ .
    Browser starts attempting connection, without timing out.
3. Perform one of the following actions while still on the loading tab:
    * Click on the "Previous page" button on the main window.
    * Click on the "Home page" button on the main window.
    * Click on the "World Globe" button on the main window.

Expected behaviors:
* Lagrange sets a quick timer (e.g. 5 seconds), then aborts the connection attempt and displays "Connection timed out" if the server hasn't acknowledged the TCP connection once that timer expires.
* When performing the actions listed in the 3rd point of the reproduction scenario, Lagrange immediately aborts the connection attempt, and performed the requested action. This valid behavior is observed when having completed step 2, then typing either a valid gemini URL or an about page URL.

**Comment by skyjake** [comment]
Socket connections now have a timeout. Please test with 135ae99, and remember to update the git submodule, too.

**Comment by ghost** [comment]
I've built from the dev branch, and I can confirm this issue is now fixed. Thanks for your quick fix :+1:
