### ISSUE TITLE
Add keybindings to switch tabs

### ISSUE THREAD

**Issue by russsharek** [skyjake/lagrange#75]
It's entirely possible that I missed it in the documentation, but is there a way to switch tabs via keyboard commands?

**Comment by skyjake** [comment]
I don't think it's mentioned, but generally I used the same keybindings as Firefox. So Ctrl+PageUp/Down should work on Linux, and Cmd+Shift+[ and Cmd+Shift+] on the Mac.

I should add these to the keybindings in Preferences.

**Comment by russsharek** [comment]
No idea how I missed something so obvious.

Adding it to the docs/prefs would be terrific. 

On November 30, 2020 5:16:57 AM UTC, "Jaakko Keränen" <notifications@github.com> wrote:
>I don't think it's mentioned, but generally I used the same keybindings
>as Firefox. So Ctrl+PageUp/Down should work on Linux, and Cmd+Shift+[
>and Cmd+Shift+] on the Mac.
>
>I should add these to the keybindings in Preferences.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/skyjake/lagrange/issues/75#issuecomment-735550809

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
