### ISSUE TITLE
Windows - Nvidia GeForce Experience displays FPS counter

### ISSUE THREAD

**Issue by ArthurHoaro** [skyjake/lagrange#76]
I use Nvidia GeForce Experience to display an FPS counter in video games on Windows, and for some reason it is displayed in lagrange.

![2020-11-30_14-27](https://user-images.githubusercontent.com/1962678/100615698-408ac500-3318-11eb-99a2-4b83acfd79ec.png)

Maybe it's due to how the binary is built? 

Note that it can easily be disabled.

**Comment by skyjake** [comment]
I suspect this is because Lagrange uses Direct3D to draw its UI by default on Windows. That would mean that launching with the `--sw` command line option would not show an FPS counter.

> Note that it can easily be disabled.

By the user? Or by Lagrange itself?

**Comment by ArthurHoaro** [comment]
> I suspect this is because Lagrange uses Direct3D to draw its UI by default on Windows. That would mean that launching with the --sw command line option would not show an FPS counter.

You are right, launching it with `--sw` does not show the counter. What's this parameter?

> By the user? Or by Lagrange itself?

By the user. I meant that it's a pretty low priority issue.

**Comment by skyjake** [comment]
`--sw` forces the use of a software rendering mode.

Not sure if there is anything that I can do about this, as I do want to keep GPU rendering as the default.

**Comment by ArthurHoaro** [comment]
That's fine with me, there are 2 workarounds available, either disabling the counter or using software rendering.

Thanks for your time!
