### ISSUE TITLE
Add Atom feed support

### ISSUE THREAD

**Issue by charabaruk** [skyjake/lagrange#78]
Even though there is a companion spec for subscribing to Gemini pages, many Gemini sites still use Atom for feeds. Atom and RSS also provide more information that would be useful for feeds. It would be helpful if Lagrange would support Atom and RSS feeds, either directly or by transcoding to Gemini text.

**Comment by johanbove** [comment]
Isn't it the point of the "subscribing to Gemini pages" that Gemini capsule owners do not need to offer an atom.xml file for clients to be able to create a feed in favor of gemini/txt files? I'm personally okay with Lagrange not doing atom.xml.

**Comment by skyjake** [comment]
> by transcoding to Gemini text

I'm intrigued by this idea. In fact, I'm working on a way for Lagrange to call out to external programs to convert incoming requests into a supported format. Then one would be able to parse and process the RSS/Atom XML for example in a Python script and generate a corresponding Gemini index page.

> Isn't it the point of the "subscribing to Gemini pages" that Gemini capsule owners do not need to offer an atom.xml file for clients to be able to create a feed in favor of gemini/txt files?

Indeed. IMO it is healthier for the future development of the Geminisphere to use formats that are native to it, meaning they are a match on a conceptual and philosophical level. RSS and Atom certainly "work" and are pragmatic choices, but an XML-based format is an odd pairing with the line-based _text/gemini_ and the Gemini protocol itself.

**Comment by charabaruk** [comment]
Unfortunately, the Gemini format doesn't leave much opportunity to provide additional, useful metadata. If it at least had comments, that would be an option for parsing by sufficiently advanced clients, but barring that there's no real ability to pack in such info in the format.

I was considering writing up a C# program that would convert RSS and Atom into Gemini pages, as I'm more comfortable with that than with Python. Especially with .NET being open-source these days, a helper program interface in Lagrange would make either option good. However, even that would need a defined protocol -- perhaps something as simple as response data into the helper program stdin, with text/gemini in stdout, each lead by a double CRLF to provide the opportunity for future expansion if needed?

**Comment by skyjake** [comment]
Stay tuned for v0.12. It'll have a system to pipe request responses to external programs, allowing rewriting the whole response including the MIME type. So, for example, you can load up an Atom XML feed in Lagrange and have it show up as text/gemini, or maybe render MIDI files using timidity to WAV for playback. I've already tested both of these and they seem to work nicely.

**Comment by charabaruk** [comment]
Nice! Guess I should start working on my feed converter then!

**Comment by skyjake** [comment]
The interface is pretty simple and I'll document it in `about:help`. The external command gets the MIME type as command line argument(s), and response body via stdin. The output (via stdout) is expected to be a valid `20` Gemini response (so header line, `\r\n`, and the body).

**Comment by skyjake** [comment]
Closing for now as the functionality is covered by MIME hooks.

May reopen in the future if built-in Atom feed support becomes relevant. The big catch there is that either it needs to use a new dependency for XML parsing (a minimal C library preferably) or an XML parser implementation needs to added to the_Foundation.

**Comment by skyjake** [comment]
Reopening for visibility.

**Comment by makew0rld** [comment]
I still think having this subscription feature built-in is important. I have friends who aren't super tech-savvy and use Lagrange. MIME hook scripts are not really an option for them.

**Comment by skyjake** [comment]
You are right, they are not user-friendly at all.

I'll see how much work it would be to add equivalent built-in support for translating Atom XML feeds to Gemini pages. I still prefer that the subscription backend deals only with Gemini feeds.

**Comment by makew0rld** [comment]
I think if it had an internal format that it processed all feeds into, but you know your application better than I do. Let me know if I can be of any help logic-wise, as I got to do some fun things with Amfora. For example: Choosing gemini links, then falling back to HTTP(S) links, then whatever the first link was - for when an Atom feed has multiple links.

Good luck!

**Comment by Br0000k** [comment]
> Even though there is a companion spec for subscribing to Gemini pages, many Gemini sites still use Atom for feeds.

On the web, subscribing to a feed seems weird. Welcome to the Gemini world! :)

I think Gemini browsers should be kept simple. But if Atom/RSS support is necessary (and it is - remember CAPCOM), then I think it should be added. RFC 4287 (the Atom syndication format) seems quite a bit to implement though, especially when it's built on XML - but then anything is possible :)

**Comment by skyjake** [comment]
Progress: the dev branch now has a new simple XML parser and it can successfully read most of the Atom feeds listed on CAPCOM. This is implemented as a built-in MIME hook that gets run last after the user-defined hooks.

Atom seems pretty reasonable to deal with, but RSS 2.0 less so. It also seems quite rare on CAPCOM, so I'm likely calling it a day for now and working on other more fun stuff. (More fun than XML?! :slightly_smiling_face:)

**Comment by skyjake** [comment]
Calling it done for v1.2.
