### ISSUE TITLE
Browser is not responding trying to close a loading tab

### ISSUE THREAD

**Issue by ArthurHoaro** [skyjake/lagrange#79]
I was able to reproduce the issue multiple times:

## Steps 

  1. Open gemini://antonmcclure.com/ (probably defunct or something)
  2. Try to close the tab seeing it's not loading

## Observed

Lagrange is not responding - even after a few minutes - and I have to kill it manually.

## Expected

Tab is closed

## Info

Client version: 0.11.0
OS: Ubuntu 20.04 (with KDE)

**Comment by skyjake** [comment]
This sounds similar to #74 that has been fixed in the dev branch.

Tried connecting to antonmcclure.com using a dev build and indeed it doesn't hang.

**Comment by ArthurHoaro** [comment]
Awesome, I'll wait for the next release. I only looked at the open issues.
