### ISSUE TITLE
"Identities" tab, "Reveal Files" does not do anything

### ISSUE THREAD

**Issue by johanbove** [skyjake/lagrange#80]
OS: Windows 10
Version: Lagrange v0.11

## Situation
I created an identity using Lagrange, which I can see and use in the "identities" tab. I would like to back up these cert and key files. When I choose the option on right-click "Reveal files", then nothing happens.

## Expectation
When I choose "Reveal files" I expected an Explorer window to open showing me the location of the cert files.

## Additional
Where on the Windows machine are these certs and keys stored? How can I add my own keys so that Lagrange recognizes them?

**Comment by johanbove** [comment]
Found where the files are stored on Windows: `AppData\Roaming\fi.skyjake.Lagrange`

**Comment by skyjake** [comment]
I think "Reveal files" is also broken on macOS at the moment...

**Comment by skyjake** [comment]
Removed the menu item for now, maybe I'll add it back later after figuring out why it isn't working.
