### ISSUE TITLE
Changing window DPI at runtime based on which monitor the window is moved on

### ISSUE THREAD

**Issue by skyjake** [skyjake/lagrange#83]
Lagrange should observe if the monitor DPI changes after the window has been moved and change the window pixel ratio accordingly. Otherwise the UI ends up being scaled incorrectly if moved between monitors with different DPIs.

**Comment by raspbeguy** [comment]
Also the window has incorrect DPI when using on my HiDPI laptop on Linux (only using laptop screen).

**Comment by skyjake** [comment]
Currently on Linux you'll need to manually set Lagrange's UI scaling factor. Last I checked, I couldn't find a reliable way to query for the correct UI scaling factor. It seems rather desktop environment specific, and since Lagrange is UI framework agnostic, not sure where to get that info.

When I'm running Linux, I have Lagrange's UI scaling set to 2.2 on my 27" 5K display.

**Comment by skyjake** [comment]
Tested on Windows 10 and macOS, seems to work pretty well.
