### ISSUE TITLE
debian rules complains about missing /build when cross compiling in pbuilder

### ISSUE THREAD

**Issue by SolidEva** [skyjake/lagrange#85]
While packaging lagrange for PrawnOS (armhf/arm64) I found the included debian/rules complains about a missing /build directory when cross compiling in pbuilder. 

I ended up settling on the following https://github.com/SolidHal/PrawnOS/blob/master/filesystem/packages/lagrange-gemini-browser/src/debian/rules

which worked quite well! I can submit a PR for this if you'd like. I think there is some logic available in debian/rules to change flags depending on arch, so I would include that as well to enforce sw rendering on arm* platforms. 

Thanks for your work on lagrange, it makes for a great ship in geminispace! :D

**Comment by skyjake** [comment]
Sounds good! A PR would be nice.
