### ISSUE TITLE
Remapping key modifiers (Lagrange doesn't respect remapped keys)

### ISSUE THREAD

**Issue by natpen** [skyjake/lagrange#87]
The issue I'm experiencing is that I have my caps lock key remapped to function as control, but within Lagrange the remapping doesn't work. This is abnormal, as once I do the remapping at the OS level, it typically "just works" in all applications from then on.

I'm not an expert in keyboard mapping, nor the implementation language of Lagrange, but if I could offer one potential theory, I believe there are two ways to map to keys - by symbols, and by physical keys. The behavior I'm experiencing makes me think perhaps Lagrange is mapping to physical keys in this case. And if so, I think mapping to symbols would be a better experience, so users can retain control over which modifier keys do what.

**Comment by skyjake** [comment]
Which OS are you using? At least on macOS my remapping of Escape to Caps Lock is not causing problems.

I think this behavior comes straight from [SDL](https://libsdl.org) and Lagrange does indeed use physical keys, although not actual scancodes. On the bright side, it is possible to implement a custom modifier mapping in Lagrange where you could configure what Caps Lock does.

**Comment by natpen** [comment]
I'm using Linux (Arch) with Sway as a window manager. In my sway config there is a keyboard block where it sets some xkb options, like `xkb_options caps:ctrl_modifier`.

Thank you for the tip about custom modifier mappings! That's amazing, and I will definitely just try using that for now.

**Comment by skyjake** [comment]
To clarify, this needs some (pretty easy) work to implement such a mapping, I don't think SDL comes with a mapping mechanism of its own. There's a few keybindings configurable in Lagrange's Preferences dialog, but not all of them are yet.

**Comment by skyjake** [comment]
A new file was added to Lagrange's config directory: `modmap.txt`. It is automatically created when you run the app and explains the usage:

```
# This is a translation table for keyboard modifiers. The syntax is:
#
# (hardware key) -> (effective modifier)
#
# A modifier can be mapped to "none" to disable it. For example:
#
# Lalt -> none
#
# When using CapsLock as a modifier key, its toggled state will still affect
# text entry. You may need to remap or disable CapsLock in your window system.
#
# You may delete this file and it will be recreated with the default mapping.

Lshift -> Lshift
Lctrl -> Lctrl
Lalt -> Lalt
Lgui -> Lgui
Rshift -> Rshift
Rctrl -> Rctrl
Ralt -> Ralt
Rgui -> Rgui
caps -> caps
```
