### ISSUE TITLE
«Unsupported Content Type» for text/x-php files

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#88]
I updated my server to send the actual mimetypes for files instead of just plain text for gemini://code.lanterne.chilliet.eu

As a result, opening PHP files in lagrange does not work anymore and show:
```
👽 Unsupported Content Type
The received content cannot be viewed with this application.
text/x-php
You can save it as a file to your Downloads folder, though. Press Ctrl+S or select "Save to Downloads" from the menu.
```

Shouldn’t lagrange just show the content for any text/* mimetype?

The specification seems to agree:

> Response handling by clients should be informed by the provided MIME type information. Gemini defines one MIME type of its own (text/gemini) whose handling is discussed below in section 5. In all other cases, clients should do "something sensible" based on the MIME type. Minimalistic clients might adopt a strategy of printing all other text/* responses to the screen without formatting and saving all non-text responses to the disk. Clients for unix systems may consult /etc/mailcap to find installed programs for handling non-text types.

**Comment by skyjake** [comment]
Yeah, I should make all text/* types default to plain text mode.
