### ISSUE TITLE
Lagrange exits when MIME hook program not found

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#89]
Steps to reproduce:

- Create a MIME hook with a command that does not exist
- Open/reload a page that should use the hook.

Result:

- Lagrange exits.
- No errors in output.

Expected result:

- Lagrange does not exit.
- Some warning shown in GUI.
- Error in output.

**Comment by skyjake** [comment]
Can't reproduce this on macOS, maybe Linux-specific behavior?

10d5a1ea2ded21623d1abcb6a955f5098faad334 alerts the user of bad paths in mimehooks.txt and directs to open "about:debug" for more information.

**Comment by skyjake** [comment]
The reason for the sudden exit was that Lagrange didn't check if the hook program actually was started and got a SIGPIPE when it wasn't.
