### ISSUE TITLE
Cannot open from the command line unless typing the full path to the executable

### ISSUE THREAD

**Issue by Admicos** [skyjake/lagrange#9]
```
% lagrange
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: en_US.utf8
Lagrange: A Beautiful Gemini Client
failed to load resources: No such file or directory
```

```
% /usr/bin/lagrange
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: en_US.utf8
Lagrange: A Beautiful Gemini Client
[window] renderer: opengl (accelerated)
[window] max texture size: 16384 x 16384
...
```

---

The most likely cause for this (that I could find) is [app.c line 421](https://github.com/skyjake/lagrange/blob/release/src/app.c#L421), where `executablePath_CommandLine` probably expects the command line program name to be a full path.

Relevant strace output:
```
% pwd
/home/admicos
% strace lagrange
...
stat("/home/share/lagrange/resources.binary", 0x7ffc96b175b0) = -1 ENOENT (No such file or directory)
stat("/home/share/lagrange/resources.binary", 0x7ffc96b17580) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/share/lagrange/resources.binary", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/admicos/resources.binary", 0x7ffc96b175b0) = -1 ENOENT (No such file or directory)
stat("/home/admicos/resources.binary", 0x7ffc96b17580) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/admicos/resources.binary", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "failed to load resources: No suc"..., 52failed to load resources: No such file or directory
```

**Comment by skyjake** [comment]
I can reproduce this on Ubuntu 18.04. Specifically, the problem is that if the binary is found via PATH, its absolute path is not determined correctly.

**Comment by skyjake** [comment]
Note to self: This is a very platform-dependent topic ([a relevant StackOverflow answer](https://stackoverflow.com/a/1024937)). It would be better to change the init behavior to not rely on the executable location at all, for example by installing the resource file to a predetermined location.

**Comment by skyjake** [comment]
Since 04b626c12cf9fcecabdf6662bd602a81aa498290 it first tries loading resources.binary from  ${CMAKE_INSTALL_PREFIX}/share/lagrange/.
