### ISSUE TITLE
Please supply request URL to MIME hooks

### ISSUE THREAD

**Issue by emilis** [skyjake/lagrange#90]
I suggest that MIME hook commands would be given request URL as an argument like this:

```
hook-command mime/type URL lang=en
```

This would be a change that would break backwards-compatibility for some users, but the project is quite new and I think it can still do that.

This would open a possibility to make useful HTML converters, because usually it is easier to write a special parser for a site one visits frequently, than to write a universal HTML to gemini converter.

**Alternatively**, please create "URL hooks" that would match on the URL _before_ the request is made and would either rewrite the URL (e.g. with a gemini redirect) or would supply the response.

The browser could show some hints for the user if the link on a page will be rewritten by an URL hook.

**Comment by skyjake** [comment]
URL hooks could be useful, I'll think about how those would work.

For MIME hooks, how about I supply the URL via an environment variable, like REQUEST_URL? Then it can be easily ignored by hooks who don't need it.

**Comment by emilis** [comment]
`REQUEST_URL` would work too.

**Comment by skyjake** [comment]
All right, please test 90472c8.

**Comment by skyjake** [comment]
Actually, that will race if multiple requests happen to finish processing at the exact same time. Pretty unlikely, but I should still address that issue.

**Comment by emilis** [comment]
Tested `90472c8` and `REQUEST_URL` seems to be working as expected.
