### ISSUE TITLE
Check for SSE instruction support — compiles but crashes (x86 with Debian)

### ISSUE THREAD

**Issue by bortzmeyer** [skyjake/lagrange#91]
Compilation works fine, following the instructions. But, then:

```
% ./lagrange 
Lagrange: A Beautiful Gemini Client
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: fr_FR.utf8
[window] renderer: opengl (accelerated)
zsh: illegal hardware instruction  ./lagrange
```
```
% gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% uname -a
Linux XXX 4.19.0-12-686-pae #1 SMP Debian 4.19.152-1 (2020-10-18) i686 GNU/Linux

% cat /etc/debian_version 
10.7
```

**Comment by skyjake** [comment]
Sounds similar to #38.

I have not been able to reproduce/solve that one yet. We could try this, though: in the build config, disable `TFDN_ENABLE_SSE41` and rebuild.

**Comment by skyjake** [comment]
Maybe it's a locale-related thing? Do you happen to have the "en_US.utf8" locale installed? (E.g., try `locale -a`)

**Comment by bortzmeyer** [comment]
> Maybe it's a locale-related thing? Do you happen to have the "en_US.utf8" locale installed? (E.g., try `locale -a`)

Unsetting LC_CTYPE changes nothing:

```
% ./lagrange    
Lagrange: A Beautiful Gemini Client
[the_Foundation] version: 1.0.0 cstd:201112
[the_Foundation] locale: en_US.utf8
[window] renderer: opengl (accelerated)
zsh: illegal hardware instruction  ./lagrange
```

**Comment by skyjake** [comment]
Any luck with setting the CMake variable `TFDN_ENABLE_SSE41=NO`?

**Comment by bortzmeyer** [comment]
> `TFDN_ENABLE_SSE41`

I edited `CMakeCache.txt` to replace ON by OFF, ran `cmake --build .` and now everything works. Thanks. (Nice program, by the way.)

**Comment by skyjake** [comment]
Great! Thank you for testing.

Sounds like I need to add a more robust test for SSE4.1 support in the CMake config...

**Comment by bortzmeyer** [comment]
Now that it works, I can set the old locale again (fr_FR) and it works fine so it was not a locale issue.

**Comment by skyjake** [comment]
>  it was not a locale issue

Good to know.

**Comment by bortzmeyer** [comment]
I may add that it was an "old" PC (8 years old) which may explain the lack of some hardware features.
