### ISSUE TITLE
Lagrange exits if mime hook doesn't "consume" entire input

### ISSUE THREAD

**Issue by blksprt** [skyjake/lagrange#92]
If a mime hook script doesn't finish reading `stdin`, Lagrange gets a SIGPIPE and exits.

I set up the following script to play videos, and while it works fine if I play through to the end, Lagrange exits if I stop mpv halfway through the video. Similarly, if I just remove the mpv line completely, Lagrange still just exits.

```
#!/bin/bash

/usr/local/bin/mpv --fs - >/dev/null 2>/dev/null

echo -e "20 text/gemini\r"
echo "done~"
```

Just for completeness' sake - this is on macOS 11.0.1, Lagrange 0.12.1.

Probably similar to #89

**Comment by skyjake** [comment]
I'll add a handler for SIGPIPE so this use case works, too.

**Comment by skyjake** [comment]
Running macOS, I couldn't get mpv to read the video from stdin:

```
[file] Reading from stdin...
 (+) Video --vid=1 (*) (h264 320x240 15.000fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
[file] Cannot seek backward in linear streams!
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 1, offset 0x30: partial file
[lavf] error reading packet: Invalid data found when processing input.
```

However, if I dump the video to a file it plays fine with this:

```
cat > /tmp/vidfile
/usr/local/bin/mpv --fs /tmp/vidfile >/dev/null 2>/dev/null

echo "20 text/gemini\r"
echo "done playing!"
```

Hook definition:

```
Show video via mpv
video/mp4
/bin/sh;/Users/jaakko/mpv.sh
```

**Comment by skyjake** [comment]
Of course, the current MIME hooks were not intended for handing the file to an external viewer. A separate mechanism for external viewer programs could/should be added.

**Comment by skyjake** [comment]
Closing as SIGPIPE is now dealt with.
