### ISSUE TITLE
Certificate warning in banner is clickable

### ISSUE THREAD

**Issue by karthanistyr** [skyjake/lagrange#93]
Following implementation of #29 and #72, the certificate warning in the banner is part of the clickable region that takes you to the gemsite's root.

Is this intended? It's a nitpick, but it feels a bit weird that clicking the warning (which may not be intended to be clickable at all) takes an unrelated action (navigation).

For your kind consideration!

![Capture_2020-12-08_10-52-23 092059089](https://user-images.githubusercontent.com/7722196/101468736-181c4f80-3944-11eb-8fc9-baedcf02b596.png)

**Comment by skyjake** [comment]
Yeah that should be changed. Maybe the best option is to open the Certificate Status dialog when clicking on the warning.

(gmi.skyjake.fi meant for HTTP requests only, but [agate](https://github.com/mbrubeck/agate) apparently doesn't refuse requests for it. Need to upgrade...)
