### ISSUE TITLE
Feeds

### ISSUE THREAD

**Issue by raspbeguy** [skyjake/lagrange#94]
Hello,

There is a menu option "Show Feed Entries" leading to a page that is supposed to list feed subscription. Sadly I didn't fing any option to subscribe to a feed.

Is that feature still WIP or am I too stupid to find the way to subscribe to feeds?

EDIT: well, my bad, there is a subscribe option, but I can't make it work.

To do that, I go to a atom feed, for instance gemini://hashtagueule.fr/atom.xml, I ignore the warning that Lagrange cannot open XML content, and then I click on subscribe in the menu. But when I go to the subscription side bar and click refresh, nothing happens.

**Comment by skyjake** [comment]
Sorry, Lagrange only supports Gemini style feeds at the moment. From the Help:

> Lagrange does _not_ support RSS or Atom, only Gemini feeds. A Gemini feed is simply a regular 'text/gemini' page that contains one or more links whose labels are formatted in a particular way.

Also, note that bookmarks and subscriptions are closely tied, so any bookmark can be turned into a subscription via the context menu in the Bookmarks list.

The latest version also supports subscribing to new headings that appear on a Gemini page.

There is an issue about [support for Atom feeds](https://github.com/skyjake/lagrange/issues/78). I suggest further discussion about RSS/Atom should continue there.

**Comment by raspbeguy** [comment]
Oh ok, sorry, I didn't know about that. This is interresting.
