### ISSUE TITLE
Provide a way to see the header line

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#97]
Hello,

I sometimes want to check the header line, often to see if capsules are returning a lang= tag or not, but it could be useful for other purposes too.
It’s nice to have the copy the source option, but it does not include the header line. Maybe just add the header line to what is copied?

**Comment by skyjake** [comment]
I've been planning to expand the "Certificate Status" dialog into a more general-purpose "Page Information". I think that would be a good place to put the response header.
