### ISSUE TITLE
Can't the build process be done using Make?

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#99]

**Comment by skyjake** [comment]
I suppose you mean there could be a Makefile provided with the source. In principle, sure, that would be possible but the CMake configuration does a number of checks to adapt to the system you are compiling on. So in fact you'd need something like autoconf/automake. Also, CMake works with other build tools like ninja that I frequently use myself.

**Comment by ghost** [comment]
A program for a minimal protocol should have a minimal build system.

**Comment by skyjake** [comment]
Sorry, I have no plans to change the build system. CMake is not minimal, but it is flexible, widely-used, and available on all platforms. Maybe in the future when Lagrange is more stable there can be a set of platform-specific Makefiles provided, but things are evolving too rapidly to make that feasible.
